// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: approval.sql

package db

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const approvalDocVisible = `-- name: ApprovalDocVisible :one
SELECT (
  ($1::text = 'purchase_order' AND EXISTS (SELECT 1 FROM purchase_orders x WHERE x.id = $2 AND x.company_id = $3))
  OR ($1::text = 'goods_receipt' AND EXISTS (SELECT 1 FROM goods_receipts x WHERE x.id = $2 AND x.company_id = $3))
  OR ($1::text = 'work_order' AND EXISTS (SELECT 1 FROM work_orders x WHERE x.id = $2 AND x.company_id = $3))
  OR ($1::text = 'payment' AND EXISTS (SELECT 1 FROM settlements x WHERE x.id = $2 AND x.company_id = $3 AND x.side = 'payment'))
  OR ($1::text = 'sales_order' AND EXISTS (
        SELECT 1 FROM sales_orders x LEFT JOIN users su ON su.id = x.sales_user_id
        WHERE x.id = $2 AND x.company_id = $3
          AND ($4::bigint IS NULL OR x.sales_user_id = $4)
          AND ($5::bigint IS NULL OR su.department_id = $5)))
  OR ($1::text = 'delivery' AND EXISTS (
        SELECT 1 FROM deliveries x LEFT JOIN users su ON su.id = x.sales_user_id
        WHERE x.id = $2 AND x.company_id = $3
          AND ($4::bigint IS NULL OR x.sales_user_id = $4)
          AND ($5::bigint IS NULL OR su.department_id = $5)))
  OR ($1::text = 'collection' AND EXISTS (
        SELECT 1 FROM settlements x LEFT JOIN users su ON su.id = x.sales_user_id
        WHERE x.id = $2 AND x.company_id = $3 AND x.side = 'receipt'
          AND ($4::bigint IS NULL OR x.sales_user_id = $4)
          AND ($5::bigint IS NULL OR su.department_id = $5)))
)::boolean AS visible
`

type ApprovalDocVisibleParams struct {
	DocType     string
	DocID       int64
	CompanyID   int64
	ScopeUserID *int64
	ScopeDeptID *int64
}

// 單據是否存在於本公司,且在使用者的資料範圍內(業務類單據依負責業務快照,與各單據頁相同的規則)
func (q *Queries) ApprovalDocVisible(ctx context.Context, arg ApprovalDocVisibleParams) (bool, error) {
	row := q.db.QueryRow(ctx, approvalDocVisible,
		arg.DocType,
		arg.DocID,
		arg.CompanyID,
		arg.ScopeUserID,
		arg.ScopeDeptID,
	)
	var visible bool
	err := row.Scan(&visible)
	return visible, err
}

const companyRolesByIDs = `-- name: CompanyRolesByIDs :many
SELECT id, name FROM roles WHERE company_id = $1 AND id = ANY($2::bigint[]) AND is_active
`

type CompanyRolesByIDsParams struct {
	CompanyID int64
	Ids       []int64
}

type CompanyRolesByIDsRow struct {
	ID   int64
	Name string
}

func (q *Queries) CompanyRolesByIDs(ctx context.Context, arg CompanyRolesByIDsParams) ([]CompanyRolesByIDsRow, error) {
	rows, err := q.db.Query(ctx, companyRolesByIDs, arg.CompanyID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompanyRolesByIDsRow{}
	for rows.Next() {
		var i CompanyRolesByIDsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeDocumentApproval = `-- name: CompleteDocumentApproval :execrows
UPDATE document_approvals SET approver_id = $1, approved_at = now()
WHERE doc_type = $2 AND doc_id = $3 AND step_no = $4 AND approver_id IS NULL
`

type CompleteDocumentApprovalParams struct {
	ApproverID *int64
	DocType    string
	DocID      int64
	StepNo     int32
}

func (q *Queries) CompleteDocumentApproval(ctx context.Context, arg CompleteDocumentApprovalParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeDocumentApproval,
		arg.ApproverID,
		arg.DocType,
		arg.DocID,
		arg.StepNo,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createApprovalRule = `-- name: CreateApprovalRule :one
INSERT INTO approval_rules (company_id, doc_type, min_amount, created_by, updated_by)
VALUES ($1, $2, $3, $4, $4) RETURNING id, company_id, doc_type, min_amount, created_by, updated_by, version, created_at, updated_at
`

type CreateApprovalRuleParams struct {
	CompanyID int64
	DocType   string
	MinAmount decimal.Decimal
	ActorID   *int64
}

func (q *Queries) CreateApprovalRule(ctx context.Context, arg CreateApprovalRuleParams) (ApprovalRule, error) {
	row := q.db.QueryRow(ctx, createApprovalRule,
		arg.CompanyID,
		arg.DocType,
		arg.MinAmount,
		arg.ActorID,
	)
	var i ApprovalRule
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocType,
		&i.MinAmount,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApprovalRule = `-- name: DeleteApprovalRule :execrows
DELETE FROM approval_rules WHERE id = $1 AND company_id = $2
`

type DeleteApprovalRuleParams struct {
	ID        int64
	CompanyID int64
}

func (q *Queries) DeleteApprovalRule(ctx context.Context, arg DeleteApprovalRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteApprovalRule, arg.ID, arg.CompanyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteApprovalRuleSteps = `-- name: DeleteApprovalRuleSteps :exec
DELETE FROM approval_rule_steps WHERE rule_id = $1
`

func (q *Queries) DeleteApprovalRuleSteps(ctx context.Context, ruleID int64) error {
	_, err := q.db.Exec(ctx, deleteApprovalRuleSteps, ruleID)
	return err
}

const deleteDocumentApprovals = `-- name: DeleteDocumentApprovals :exec
DELETE FROM document_approvals WHERE doc_type = $1 AND doc_id = $2 AND company_id = $3
`

type DeleteDocumentApprovalsParams struct {
	DocType   string
	DocID     int64
	CompanyID int64
}

func (q *Queries) DeleteDocumentApprovals(ctx context.Context, arg DeleteDocumentApprovalsParams) error {
	_, err := q.db.Exec(ctx, deleteDocumentApprovals, arg.DocType, arg.DocID, arg.CompanyID)
	return err
}

const getApprovalRule = `-- name: GetApprovalRule :one
SELECT id, company_id, doc_type, min_amount, created_by, updated_by, version, created_at, updated_at FROM approval_rules WHERE id = $1 AND company_id = $2
`

type GetApprovalRuleParams struct {
	ID        int64
	CompanyID int64
}

func (q *Queries) GetApprovalRule(ctx context.Context, arg GetApprovalRuleParams) (ApprovalRule, error) {
	row := q.db.QueryRow(ctx, getApprovalRule, arg.ID, arg.CompanyID)
	var i ApprovalRule
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocType,
		&i.MinAmount,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertApprovalRuleStep = `-- name: InsertApprovalRuleStep :exec
INSERT INTO approval_rule_steps (rule_id, step_no, role_id) VALUES ($1, $2, $3)
`

type InsertApprovalRuleStepParams struct {
	RuleID int64
	StepNo int32
	RoleID int64
}

func (q *Queries) InsertApprovalRuleStep(ctx context.Context, arg InsertApprovalRuleStepParams) error {
	_, err := q.db.Exec(ctx, insertApprovalRuleStep, arg.RuleID, arg.StepNo, arg.RoleID)
	return err
}

const insertDocumentApproval = `-- name: InsertDocumentApproval :exec
INSERT INTO document_approvals (company_id, doc_type, doc_id, step_no, role_id, role_name)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertDocumentApprovalParams struct {
	CompanyID int64
	DocType   string
	DocID     int64
	StepNo    int32
	RoleID    *int64
	RoleName  string
}

func (q *Queries) InsertDocumentApproval(ctx context.Context, arg InsertDocumentApprovalParams) error {
	_, err := q.db.Exec(ctx, insertDocumentApproval,
		arg.CompanyID,
		arg.DocType,
		arg.DocID,
		arg.StepNo,
		arg.RoleID,
		arg.RoleName,
	)
	return err
}

const listApprovalRuleSteps = `-- name: ListApprovalRuleSteps :many
SELECT s.rule_id, s.step_no, s.role_id, r.name AS role_name
FROM approval_rule_steps s JOIN roles r ON r.id = s.role_id
JOIN approval_rules ar ON ar.id = s.rule_id
WHERE ar.company_id = $1 ORDER BY s.rule_id, s.step_no
`

type ListApprovalRuleStepsRow struct {
	RuleID   int64
	StepNo   int32
	RoleID   int64
	RoleName string
}

func (q *Queries) ListApprovalRuleSteps(ctx context.Context, companyID int64) ([]ListApprovalRuleStepsRow, error) {
	rows, err := q.db.Query(ctx, listApprovalRuleSteps, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApprovalRuleStepsRow{}
	for rows.Next() {
		var i ListApprovalRuleStepsRow
		if err := rows.Scan(
			&i.RuleID,
			&i.StepNo,
			&i.RoleID,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovalRules = `-- name: ListApprovalRules :many

SELECT id, company_id, doc_type, min_amount, created_by, updated_by, version, created_at, updated_at FROM approval_rules WHERE company_id = $1 ORDER BY doc_type, min_amount
`

// ======== 多層簽核(D61) ========
func (q *Queries) ListApprovalRules(ctx context.Context, companyID int64) ([]ApprovalRule, error) {
	rows, err := q.db.Query(ctx, listApprovalRules, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalRule{}
	for rows.Next() {
		var i ApprovalRule
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.DocType,
			&i.MinAmount,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentApprovals = `-- name: ListDocumentApprovals :many
SELECT d.step_no, d.role_id, d.role_name, d.approver_id, d.approved_at, COALESCE(u.name, '')::text AS approver_name
FROM document_approvals d LEFT JOIN users u ON u.id = d.approver_id
WHERE d.company_id = $1 AND d.doc_type = $2 AND d.doc_id = $3
ORDER BY d.step_no
`

type ListDocumentApprovalsParams struct {
	CompanyID int64
	DocType   string
	DocID     int64
}

type ListDocumentApprovalsRow struct {
	StepNo       int32
	RoleID       *int64
	RoleName     string
	ApproverID   *int64
	ApprovedAt   *time.Time
	ApproverName string
}

func (q *Queries) ListDocumentApprovals(ctx context.Context, arg ListDocumentApprovalsParams) ([]ListDocumentApprovalsRow, error) {
	rows, err := q.db.Query(ctx, listDocumentApprovals, arg.CompanyID, arg.DocType, arg.DocID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentApprovalsRow{}
	for rows.Next() {
		var i ListDocumentApprovalsRow
		if err := rows.Scan(
			&i.StepNo,
			&i.RoleID,
			&i.RoleName,
			&i.ApproverID,
			&i.ApprovedAt,
			&i.ApproverName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const matchApprovalRule = `-- name: MatchApprovalRule :one
SELECT id FROM approval_rules
WHERE company_id = $1 AND doc_type = $2 AND min_amount <= $3::numeric
ORDER BY min_amount DESC LIMIT 1
`

type MatchApprovalRuleParams struct {
	CompanyID int64
	DocType   string
	Amount    decimal.Decimal
}

// 同類型中 min_amount 最大且不超過單據金額的規則
func (q *Queries) MatchApprovalRule(ctx context.Context, arg MatchApprovalRuleParams) (int64, error) {
	row := q.db.QueryRow(ctx, matchApprovalRule, arg.CompanyID, arg.DocType, arg.Amount)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const roleCountInApprovalRules = `-- name: RoleCountInApprovalRules :one
SELECT count(*) FROM approval_rule_steps WHERE role_id = $1
`

func (q *Queries) RoleCountInApprovalRules(ctx context.Context, roleID int64) (int64, error) {
	row := q.db.QueryRow(ctx, roleCountInApprovalRules, roleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateApprovalRule = `-- name: UpdateApprovalRule :one
UPDATE approval_rules SET doc_type = $1, min_amount = $2, updated_by = $3, version = version + 1
WHERE id = $4 AND company_id = $5 AND version = $6 RETURNING id, company_id, doc_type, min_amount, created_by, updated_by, version, created_at, updated_at
`

type UpdateApprovalRuleParams struct {
	DocType   string
	MinAmount decimal.Decimal
	ActorID   *int64
	ID        int64
	CompanyID int64
	Version   int32
}

func (q *Queries) UpdateApprovalRule(ctx context.Context, arg UpdateApprovalRuleParams) (ApprovalRule, error) {
	row := q.db.QueryRow(ctx, updateApprovalRule,
		arg.DocType,
		arg.MinAmount,
		arg.ActorID,
		arg.ID,
		arg.CompanyID,
		arg.Version,
	)
	var i ApprovalRule
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocType,
		&i.MinAmount,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userHasRole = `-- name: UserHasRole :one
SELECT EXISTS (SELECT 1 FROM user_roles WHERE user_id = $1 AND role_id = $2)
`

type UserHasRoleParams struct {
	UserID int64
	RoleID int64
}

func (q *Queries) UserHasRole(ctx context.Context, arg UserHasRoleParams) (bool, error) {
	row := q.db.QueryRow(ctx, userHasRole, arg.UserID, arg.RoleID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
