// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package db

import (
	"context"
	"time"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT count(*)
FROM audit_logs a
WHERE a.company_id = $1
  AND ($2::text IS NULL OR a.entity_type = $2)
  AND ($3::bigint IS NULL OR a.entity_id = $3)
  AND ($4::bigint IS NULL OR a.user_id = $4)
  AND ($5::text IS NULL OR a.action = $5)
  AND ($6::timestamptz IS NULL OR a.created_at >= $6)
  AND ($7::timestamptz IS NULL OR a.created_at < $7)
`

type CountAuditLogsParams struct {
	CompanyID  int64
	EntityType *string
	EntityID   *int64
	UserID     *int64
	Action     *string
	FromTime   *time.Time
	ToTime     *time.Time
}

func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs,
		arg.CompanyID,
		arg.EntityType,
		arg.EntityID,
		arg.UserID,
		arg.Action,
		arg.FromTime,
		arg.ToTime,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (company_id, user_id, action, entity_type, entity_id, summary,
                        before_data, after_data, ip, user_agent, request_id)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, $10, $11)
`

type InsertAuditLogParams struct {
	CompanyID  int64
	UserID     *int64
	Action     string
	EntityType string
	EntityID   *int64
	Summary    string
	BeforeData []byte
	AfterData  []byte
	Ip         string
	UserAgent  string
	RequestID  string
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.CompanyID,
		arg.UserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Summary,
		arg.BeforeData,
		arg.AfterData,
		arg.Ip,
		arg.UserAgent,
		arg.RequestID,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT a.id, a.user_id, u.username, u.name AS user_name, a.action, a.entity_type, a.entity_id,
       a.summary, a.before_data, a.after_data, a.ip, a.user_agent, a.request_id, a.created_at
FROM audit_logs a
LEFT JOIN users u ON u.id = a.user_id
WHERE a.company_id = $1
  AND ($2::text IS NULL OR a.entity_type = $2)
  AND ($3::bigint IS NULL OR a.entity_id = $3)
  AND ($4::bigint IS NULL OR a.user_id = $4)
  AND ($5::text IS NULL OR a.action = $5)
  AND ($6::timestamptz IS NULL OR a.created_at >= $6)
  AND ($7::timestamptz IS NULL OR a.created_at < $7)
ORDER BY a.id DESC
LIMIT $9 OFFSET $8
`

type ListAuditLogsParams struct {
	CompanyID  int64
	EntityType *string
	EntityID   *int64
	UserID     *int64
	Action     *string
	FromTime   *time.Time
	ToTime     *time.Time
	Off        int32
	Lim        int32
}

type ListAuditLogsRow struct {
	ID         int64
	UserID     *int64
	Username   *string
	UserName   *string
	Action     string
	EntityType string
	EntityID   *int64
	Summary    string
	BeforeData []byte
	AfterData  []byte
	Ip         string
	UserAgent  string
	RequestID  string
	CreatedAt  time.Time
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.CompanyID,
		arg.EntityType,
		arg.EntityID,
		arg.UserID,
		arg.Action,
		arg.FromTime,
		arg.ToTime,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsRow{}
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.UserName,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Summary,
			&i.BeforeData,
			&i.AfterData,
			&i.Ip,
			&i.UserAgent,
			&i.RequestID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
