// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bins.sql

package db

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const binBalanceMismatches = `-- name: BinBalanceMismatches :one
SELECT (
    (SELECT count(*) FROM (
        SELECT b.bin_id, b.item_id FROM inventory_bin_balances b
        LEFT JOIN (SELECT t.bin_id, t.item_id, SUM(t.qty) AS q FROM inventory_transactions t
                   WHERE t.company_id = $1 AND t.bin_id IS NOT NULL GROUP BY t.bin_id, t.item_id) x
               ON x.bin_id = b.bin_id AND x.item_id = b.item_id
        WHERE b.company_id = $1 AND b.qty <> COALESCE(x.q, 0)
    ) a)
    +
    (SELECT count(*) FROM (
        SELECT ib.item_id, ib.warehouse_id FROM inventory_balances ib JOIN warehouses w ON w.id = ib.warehouse_id
        LEFT JOIN (SELECT bb.item_id, bb.warehouse_id, SUM(bb.qty) AS q FROM inventory_bin_balances bb
                   WHERE bb.company_id = $1 GROUP BY bb.item_id, bb.warehouse_id) y
               ON y.item_id = ib.item_id AND y.warehouse_id = ib.warehouse_id
        WHERE ib.company_id = $1 AND w.use_bins AND ib.qty <> COALESCE(y.q, 0)
    ) c)
)::bigint AS mismatches
`

// 完整性:①儲位現有量 = 流水帳該儲位的合計;②啟用儲位的倉庫,各儲位合計 = 料品現有量。筆數應為 0
func (q *Queries) BinBalanceMismatches(ctx context.Context, companyID int64) (int64, error) {
	row := q.db.QueryRow(ctx, binBalanceMismatches, companyID)
	var mismatches int64
	err := row.Scan(&mismatches)
	return mismatches, err
}

const binHasStock = `-- name: BinHasStock :one
SELECT EXISTS (SELECT 1 FROM inventory_bin_balances WHERE bin_id = $1 AND qty <> 0)
`

func (q *Queries) BinHasStock(ctx context.Context, binID int64) (bool, error) {
	row := q.db.QueryRow(ctx, binHasStock, binID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const binHasTransactions = `-- name: BinHasTransactions :one
SELECT EXISTS (SELECT 1 FROM inventory_transactions WHERE bin_id = $1)
`

func (q *Queries) BinHasTransactions(ctx context.Context, binID *int64) (bool, error) {
	row := q.db.QueryRow(ctx, binHasTransactions, binID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countBinStock = `-- name: CountBinStock :one
SELECT count(*) FROM inventory_bin_balances b
JOIN bins bn ON bn.id = b.bin_id JOIN items i ON i.id = b.item_id
WHERE b.company_id = $1
  AND ($2::bigint IS NULL OR b.warehouse_id = $2)
  AND ($3::bigint IS NULL OR b.bin_id = $3)
  AND ($4::text IS NULL OR i.code ILIKE '%' || $4 || '%' OR i.name ILIKE '%' || $4 || '%'
       OR bn.code ILIKE '%' || $4 || '%')
  AND ($5::boolean OR b.qty > 0)
`

type CountBinStockParams struct {
	CompanyID   int64
	WarehouseID *int64
	BinID       *int64
	Keyword     *string
	IncludeZero bool
}

func (q *Queries) CountBinStock(ctx context.Context, arg CountBinStockParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBinStock,
		arg.CompanyID,
		arg.WarehouseID,
		arg.BinID,
		arg.Keyword,
		arg.IncludeZero,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBin = `-- name: CreateBin :one
INSERT INTO bins (company_id, warehouse_id, code, name, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $5) RETURNING id, company_id, warehouse_id, code, name, is_active, created_by, updated_by, version, created_at, updated_at
`

type CreateBinParams struct {
	CompanyID   int64
	WarehouseID int64
	Code        string
	Name        string
	ActorID     *int64
}

func (q *Queries) CreateBin(ctx context.Context, arg CreateBinParams) (Bin, error) {
	row := q.db.QueryRow(ctx, createBin,
		arg.CompanyID,
		arg.WarehouseID,
		arg.Code,
		arg.Name,
		arg.ActorID,
	)
	var i Bin
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.WarehouseID,
		&i.Code,
		&i.Name,
		&i.IsActive,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBin = `-- name: DeleteBin :execrows
DELETE FROM bins WHERE id = $1 AND company_id = $2
`

type DeleteBinParams struct {
	ID        int64
	CompanyID int64
}

func (q *Queries) DeleteBin(ctx context.Context, arg DeleteBinParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBin, arg.ID, arg.CompanyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureBinBalance = `-- name: EnsureBinBalance :exec
INSERT INTO inventory_bin_balances (company_id, item_id, warehouse_id, bin_id, qty)
VALUES ($1, $2, $3, $4, 0) ON CONFLICT (bin_id, item_id) DO NOTHING
`

type EnsureBinBalanceParams struct {
	CompanyID   int64
	ItemID      int64
	WarehouseID int64
	BinID       int64
}

func (q *Queries) EnsureBinBalance(ctx context.Context, arg EnsureBinBalanceParams) error {
	_, err := q.db.Exec(ctx, ensureBinBalance,
		arg.CompanyID,
		arg.ItemID,
		arg.WarehouseID,
		arg.BinID,
	)
	return err
}

const getBin = `-- name: GetBin :one
SELECT id, company_id, warehouse_id, code, name, is_active, created_by, updated_by, version, created_at, updated_at FROM bins WHERE id = $1 AND company_id = $2
`

type GetBinParams struct {
	ID        int64
	CompanyID int64
}

func (q *Queries) GetBin(ctx context.Context, arg GetBinParams) (Bin, error) {
	row := q.db.QueryRow(ctx, getBin, arg.ID, arg.CompanyID)
	var i Bin
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.WarehouseID,
		&i.Code,
		&i.Name,
		&i.IsActive,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBinByCode = `-- name: GetBinByCode :one
SELECT id, company_id, warehouse_id, code, name, is_active, created_by, updated_by, version, created_at, updated_at FROM bins WHERE company_id = $1 AND warehouse_id = $2 AND code = $3
`

type GetBinByCodeParams struct {
	CompanyID   int64
	WarehouseID int64
	Code        string
}

func (q *Queries) GetBinByCode(ctx context.Context, arg GetBinByCodeParams) (Bin, error) {
	row := q.db.QueryRow(ctx, getBinByCode, arg.CompanyID, arg.WarehouseID, arg.Code)
	var i Bin
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.WarehouseID,
		&i.Code,
		&i.Name,
		&i.IsActive,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBinBalancesForAllocation = `-- name: ListBinBalancesForAllocation :many
SELECT b.bin_id, b.qty, bn.code
FROM inventory_bin_balances b JOIN bins bn ON bn.id = b.bin_id
WHERE b.item_id = $1 AND b.warehouse_id = $2 AND b.qty > 0 AND bn.is_active
ORDER BY b.qty DESC, bn.code
FOR UPDATE OF b
`

type ListBinBalancesForAllocationParams struct {
	ItemID      int64
	WarehouseID int64
}

type ListBinBalancesForAllocationRow struct {
	BinID int64
	Qty   decimal.Decimal
	Code  string
}

// 出庫自動分配:庫存多的儲位先出(同量依儲位代號);鎖定這些列
func (q *Queries) ListBinBalancesForAllocation(ctx context.Context, arg ListBinBalancesForAllocationParams) ([]ListBinBalancesForAllocationRow, error) {
	rows, err := q.db.Query(ctx, listBinBalancesForAllocation, arg.ItemID, arg.WarehouseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBinBalancesForAllocationRow{}
	for rows.Next() {
		var i ListBinBalancesForAllocationRow
		if err := rows.Scan(&i.BinID, &i.Qty, &i.Code); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBinStock = `-- name: ListBinStock :many
SELECT b.bin_id, bn.code AS bin_code, bn.name AS bin_name, b.warehouse_id, w.code AS warehouse_code, w.name AS warehouse_name,
       b.item_id, i.code AS item_code, i.name AS item_name, u.name AS unit_name, b.qty
FROM inventory_bin_balances b
JOIN bins bn ON bn.id = b.bin_id JOIN warehouses w ON w.id = b.warehouse_id
JOIN items i ON i.id = b.item_id JOIN units u ON u.id = i.base_unit_id
WHERE b.company_id = $1
  AND ($2::bigint IS NULL OR b.warehouse_id = $2)
  AND ($3::bigint IS NULL OR b.bin_id = $3)
  AND ($4::text IS NULL OR i.code ILIKE '%' || $4 || '%' OR i.name ILIKE '%' || $4 || '%'
       OR bn.code ILIKE '%' || $4 || '%')
  AND ($5::boolean OR b.qty > 0)
ORDER BY w.code, bn.code, i.code
LIMIT $7 OFFSET $6
`

type ListBinStockParams struct {
	CompanyID   int64
	WarehouseID *int64
	BinID       *int64
	Keyword     *string
	IncludeZero bool
	Off         int32
	Lim         int32
}

type ListBinStockRow struct {
	BinID         int64
	BinCode       string
	BinName       string
	WarehouseID   int64
	WarehouseCode string
	WarehouseName string
	ItemID        int64
	ItemCode      string
	ItemName      string
	UnitName      string
	Qty           decimal.Decimal
}

// 儲位庫存報表
func (q *Queries) ListBinStock(ctx context.Context, arg ListBinStockParams) ([]ListBinStockRow, error) {
	rows, err := q.db.Query(ctx, listBinStock,
		arg.CompanyID,
		arg.WarehouseID,
		arg.BinID,
		arg.Keyword,
		arg.IncludeZero,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBinStockRow{}
	for rows.Next() {
		var i ListBinStockRow
		if err := rows.Scan(
			&i.BinID,
			&i.BinCode,
			&i.BinName,
			&i.WarehouseID,
			&i.WarehouseCode,
			&i.WarehouseName,
			&i.ItemID,
			&i.ItemCode,
			&i.ItemName,
			&i.UnitName,
			&i.Qty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBins = `-- name: ListBins :many

SELECT b.id, b.company_id, b.warehouse_id, b.code, b.name, b.is_active, b.created_by, b.updated_by, b.version, b.created_at, b.updated_at, (SELECT COALESCE(SUM(x.qty), 0) FROM inventory_bin_balances x WHERE x.bin_id = b.id)::numeric AS stock_qty
FROM bins b
WHERE b.company_id = $1 AND ($2::bigint IS NULL OR b.warehouse_id = $2)
ORDER BY b.warehouse_id, b.code
`

type ListBinsParams struct {
	CompanyID   int64
	WarehouseID *int64
}

type ListBinsRow struct {
	ID          int64
	CompanyID   int64
	WarehouseID int64
	Code        string
	Name        string
	IsActive    bool
	CreatedBy   *int64
	UpdatedBy   *int64
	Version     int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	StockQty    decimal.Decimal
}

// ======== 儲位(D65) ========
func (q *Queries) ListBins(ctx context.Context, arg ListBinsParams) ([]ListBinsRow, error) {
	rows, err := q.db.Query(ctx, listBins, arg.CompanyID, arg.WarehouseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBinsRow{}
	for rows.Next() {
		var i ListBinsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.WarehouseID,
			&i.Code,
			&i.Name,
			&i.IsActive,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StockQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBinsByIDs = `-- name: ListBinsByIDs :many
SELECT id, company_id, warehouse_id, code, name, is_active, created_by, updated_by, version, created_at, updated_at FROM bins WHERE id = ANY($1::bigint[])
`

func (q *Queries) ListBinsByIDs(ctx context.Context, ids []int64) ([]Bin, error) {
	rows, err := q.db.Query(ctx, listBinsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bin{}
	for rows.Next() {
		var i Bin
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.WarehouseID,
			&i.Code,
			&i.Name,
			&i.IsActive,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBinBalance = `-- name: LockBinBalance :one
SELECT qty FROM inventory_bin_balances WHERE bin_id = $1 AND item_id = $2 FOR UPDATE
`

type LockBinBalanceParams struct {
	BinID  int64
	ItemID int64
}

func (q *Queries) LockBinBalance(ctx context.Context, arg LockBinBalanceParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, lockBinBalance, arg.BinID, arg.ItemID)
	var qty decimal.Decimal
	err := row.Scan(&qty)
	return qty, err
}

const setBinBalance = `-- name: SetBinBalance :exec
UPDATE inventory_bin_balances SET qty = $1, updated_at = now() WHERE bin_id = $2 AND item_id = $3
`

type SetBinBalanceParams struct {
	Qty    decimal.Decimal
	BinID  int64
	ItemID int64
}

func (q *Queries) SetBinBalance(ctx context.Context, arg SetBinBalanceParams) error {
	_, err := q.db.Exec(ctx, setBinBalance, arg.Qty, arg.BinID, arg.ItemID)
	return err
}

const setWarehouseUseBins = `-- name: SetWarehouseUseBins :exec
UPDATE warehouses SET use_bins = $1 WHERE id = $2 AND company_id = $3
`

type SetWarehouseUseBinsParams struct {
	UseBins   bool
	ID        int64
	CompanyID int64
}

func (q *Queries) SetWarehouseUseBins(ctx context.Context, arg SetWarehouseUseBinsParams) error {
	_, err := q.db.Exec(ctx, setWarehouseUseBins, arg.UseBins, arg.ID, arg.CompanyID)
	return err
}

const updateBin = `-- name: UpdateBin :one
UPDATE bins SET name = $1, is_active = $2, version = version + 1, updated_by = $3
WHERE id = $4 AND company_id = $5 AND version = $6 RETURNING id, company_id, warehouse_id, code, name, is_active, created_by, updated_by, version, created_at, updated_at
`

type UpdateBinParams struct {
	Name      string
	IsActive  bool
	ActorID   *int64
	ID        int64
	CompanyID int64
	Version   int32
}

func (q *Queries) UpdateBin(ctx context.Context, arg UpdateBinParams) (Bin, error) {
	row := q.db.QueryRow(ctx, updateBin,
		arg.Name,
		arg.IsActive,
		arg.ActorID,
		arg.ID,
		arg.CompanyID,
		arg.Version,
	)
	var i Bin
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.WarehouseID,
		&i.Code,
		&i.Name,
		&i.IsActive,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const warehouseHasBinStock = `-- name: WarehouseHasBinStock :one
SELECT EXISTS (SELECT 1 FROM inventory_bin_balances WHERE warehouse_id = $1 AND qty <> 0)
`

func (q *Queries) WarehouseHasBinStock(ctx context.Context, warehouseID int64) (bool, error) {
	row := q.db.QueryRow(ctx, warehouseHasBinStock, warehouseID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const warehouseHasStock = `-- name: WarehouseHasStock :one
SELECT EXISTS (SELECT 1 FROM inventory_balances WHERE warehouse_id = $1 AND qty <> 0)
`

func (q *Queries) WarehouseHasStock(ctx context.Context, warehouseID int64) (bool, error) {
	row := q.db.QueryRow(ctx, warehouseHasStock, warehouseID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
