// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: companies.sql

package db

import (
	"context"
)

const getCompany = `-- name: GetCompany :one
SELECT id, code, name, tax_id, currency, is_active, version, created_at, updated_at FROM companies WHERE id = $1
`

func (q *Queries) GetCompany(ctx context.Context, id int64) (Company, error) {
	row := q.db.QueryRow(ctx, getCompany, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.TaxID,
		&i.Currency,
		&i.IsActive,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompanyByCode = `-- name: GetCompanyByCode :one
SELECT id, code, name, tax_id, currency, is_active, version, created_at, updated_at FROM companies WHERE code = $1
`

func (q *Queries) GetCompanyByCode(ctx context.Context, code string) (Company, error) {
	row := q.db.QueryRow(ctx, getCompanyByCode, code)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.TaxID,
		&i.Currency,
		&i.IsActive,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
