// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: costing.sql

package db

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const costClosingExists = `-- name: CostClosingExists :one
SELECT EXISTS (SELECT 1 FROM cost_closings WHERE company_id = $1 AND period = $2::char(7))
`

type CostClosingExistsParams struct {
	CompanyID int64
	Period    string
}

// 該日期所屬月份是否已月結成本(已月結的月份不可再異動庫存)
func (q *Queries) CostClosingExists(ctx context.Context, arg CostClosingExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, costClosingExists, arg.CompanyID, arg.Period)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const costPeriodAggregates = `-- name: CostPeriodAggregates :many
SELECT t.item_id,
       COALESCE(SUM(t.qty) FILTER (WHERE t.source_type IN ('goods_receipt', 'purchase_return', 'opening_stock')), 0)::numeric AS purchase_qty,
       COALESCE(SUM(t.qty * COALESCE(t.unit_cost, 0)) FILTER (WHERE t.source_type IN ('goods_receipt', 'purchase_return', 'opening_stock')), 0)::numeric AS purchase_value,
       COALESCE(SUM(t.qty) FILTER (WHERE t.source_type IN ('delivery', 'sales_return')), 0)::numeric AS sales_qty,
       COALESCE(SUM(t.qty) FILTER (WHERE t.source_type IN ('stock_adjustment', 'stock_count')), 0)::numeric AS adjust_qty,
       COALESCE(SUM(t.qty) FILTER (WHERE t.source_type = 'work_order_issue'), 0)::numeric AS consume_qty,
       COALESCE(SUM(t.qty) FILTER (WHERE t.source_type = 'work_order_receipt'), 0)::numeric AS produce_qty,
       COALESCE(SUM(t.qty) FILTER (WHERE t.source_type NOT IN ('goods_receipt', 'purchase_return', 'delivery',
                                   'sales_return', 'stock_adjustment', 'stock_count', 'stock_transfer', 'opening_stock',
                                   'work_order_issue', 'work_order_receipt')), 0)::numeric AS other_qty
FROM inventory_transactions t
WHERE t.company_id = $1 AND t.doc_date BETWEEN $2::date AND $3::date
GROUP BY t.item_id
ORDER BY t.item_id
`

type CostPeriodAggregatesParams struct {
	CompanyID int64
	StartDate time.Time
	EndDate   time.Time
}

type CostPeriodAggregatesRow struct {
	ItemID        int64
	PurchaseQty   decimal.Decimal
	PurchaseValue decimal.Decimal
	SalesQty      decimal.Decimal
	AdjustQty     decimal.Decimal
	ConsumeQty    decimal.Decimal
	ProduceQty    decimal.Decimal
	OtherQty      decimal.Decimal
}

// 期間內各料品的異動彙總(基本單位);其他來源(未知類型)併入 other_qty,以平均成本計價
func (q *Queries) CostPeriodAggregates(ctx context.Context, arg CostPeriodAggregatesParams) ([]CostPeriodAggregatesRow, error) {
	rows, err := q.db.Query(ctx, costPeriodAggregates, arg.CompanyID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CostPeriodAggregatesRow{}
	for rows.Next() {
		var i CostPeriodAggregatesRow
		if err := rows.Scan(
			&i.ItemID,
			&i.PurchaseQty,
			&i.PurchaseValue,
			&i.SalesQty,
			&i.AdjustQty,
			&i.ConsumeQty,
			&i.ProduceQty,
			&i.OtherQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countItemCostsForClosing = `-- name: CountItemCostsForClosing :one
SELECT count(*) FROM item_costs ic JOIN items i ON i.id = ic.item_id
WHERE ic.closing_id = $1
  AND ($2::text IS NULL OR i.code ILIKE '%' || $2 || '%' OR i.name ILIKE '%' || $2 || '%')
`

type CountItemCostsForClosingParams struct {
	ClosingID int64
	Keyword   *string
}

func (q *Queries) CountItemCostsForClosing(ctx context.Context, arg CountItemCostsForClosingParams) (int64, error) {
	row := q.db.QueryRow(ctx, countItemCostsForClosing, arg.ClosingID, arg.Keyword)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCostClosing = `-- name: DeleteCostClosing :exec
DELETE FROM cost_closings WHERE id = $1
`

func (q *Queries) DeleteCostClosing(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCostClosing, id)
	return err
}

const gLBalanceAsOf = `-- name: GLBalanceAsOf :one

SELECT COALESCE(SUM(l.debit - l.credit), 0)::numeric AS balance
FROM voucher_lines l JOIN vouchers v ON v.id = l.voucher_id
WHERE v.company_id = $1 AND v.status = 'posted' AND l.account_id = $2
  AND v.voucher_date <= $3::date
`

type GLBalanceAsOfParams struct {
	CompanyID int64
	AccountID int64
	AsOf      time.Time
}

// ======== 對帳檢查 ========
// 科目截至某日(含)已過帳傳票的借方 − 貸方
func (q *Queries) GLBalanceAsOf(ctx context.Context, arg GLBalanceAsOfParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, gLBalanceAsOf, arg.CompanyID, arg.AccountID, arg.AsOf)
	var balance decimal.Decimal
	err := row.Scan(&balance)
	return balance, err
}

const getCostClosing = `-- name: GetCostClosing :one
SELECT id, company_id, period, item_count, cogs_amount, adjust_amount, inventory_value, closed_by, closed_at FROM cost_closings WHERE company_id = $1 AND period = $2::char(7)
`

type GetCostClosingParams struct {
	CompanyID int64
	Period    string
}

func (q *Queries) GetCostClosing(ctx context.Context, arg GetCostClosingParams) (CostClosing, error) {
	row := q.db.QueryRow(ctx, getCostClosing, arg.CompanyID, arg.Period)
	var i CostClosing
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Period,
		&i.ItemCount,
		&i.CogsAmount,
		&i.AdjustAmount,
		&i.InventoryValue,
		&i.ClosedBy,
		&i.ClosedAt,
	)
	return i, err
}

const insertCostClosing = `-- name: InsertCostClosing :one
INSERT INTO cost_closings (company_id, period, item_count, cogs_amount, adjust_amount, inventory_value, closed_by)
VALUES ($1, $2::char(7), $3, $4, $5, $6, $7)
RETURNING id, company_id, period, item_count, cogs_amount, adjust_amount, inventory_value, closed_by, closed_at
`

type InsertCostClosingParams struct {
	CompanyID      int64
	Period         string
	ItemCount      int32
	CogsAmount     decimal.Decimal
	AdjustAmount   decimal.Decimal
	InventoryValue decimal.Decimal
	ClosedBy       *int64
}

func (q *Queries) InsertCostClosing(ctx context.Context, arg InsertCostClosingParams) (CostClosing, error) {
	row := q.db.QueryRow(ctx, insertCostClosing,
		arg.CompanyID,
		arg.Period,
		arg.ItemCount,
		arg.CogsAmount,
		arg.AdjustAmount,
		arg.InventoryValue,
		arg.ClosedBy,
	)
	var i CostClosing
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Period,
		&i.ItemCount,
		&i.CogsAmount,
		&i.AdjustAmount,
		&i.InventoryValue,
		&i.ClosedBy,
		&i.ClosedAt,
	)
	return i, err
}

const insertItemCost = `-- name: InsertItemCost :exec
INSERT INTO item_costs (closing_id, item_id, opening_qty, opening_value, purchase_qty, purchase_value, sales_qty,
                        adjust_qty, avg_cost, cogs_amount, adjust_amount, closing_qty, closing_value,
                        consume_qty, consume_value)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11, $12, $13,
        $14, $15)
`

type InsertItemCostParams struct {
	ClosingID     int64
	ItemID        int64
	OpeningQty    decimal.Decimal
	OpeningValue  decimal.Decimal
	PurchaseQty   decimal.Decimal
	PurchaseValue decimal.Decimal
	SalesQty      decimal.Decimal
	AdjustQty     decimal.Decimal
	AvgCost       decimal.Decimal
	CogsAmount    decimal.Decimal
	AdjustAmount  decimal.Decimal
	ClosingQty    decimal.Decimal
	ClosingValue  decimal.Decimal
	ConsumeQty    decimal.Decimal
	ConsumeValue  decimal.Decimal
}

func (q *Queries) InsertItemCost(ctx context.Context, arg InsertItemCostParams) error {
	_, err := q.db.Exec(ctx, insertItemCost,
		arg.ClosingID,
		arg.ItemID,
		arg.OpeningQty,
		arg.OpeningValue,
		arg.PurchaseQty,
		arg.PurchaseValue,
		arg.SalesQty,
		arg.AdjustQty,
		arg.AvgCost,
		arg.CogsAmount,
		arg.AdjustAmount,
		arg.ClosingQty,
		arg.ClosingValue,
		arg.ConsumeQty,
		arg.ConsumeValue,
	)
	return err
}

const inventoryBalanceMismatches = `-- name: InventoryBalanceMismatches :one
SELECT count(*) FROM (
    SELECT b.item_id, b.warehouse_id FROM inventory_balances b
    LEFT JOIN (SELECT it.item_id, it.warehouse_id, SUM(it.qty) AS q FROM inventory_transactions it
               WHERE it.company_id = $1 GROUP BY it.item_id, it.warehouse_id) t
           ON t.item_id = b.item_id AND t.warehouse_id = b.warehouse_id
    WHERE b.company_id = $1 AND b.qty <> COALESCE(t.q, 0)
) x
`

// 現有量與流水帳合計不一致的(料品, 倉庫)筆數,應為 0
func (q *Queries) InventoryBalanceMismatches(ctx context.Context, companyID int64) (int64, error) {
	row := q.db.QueryRow(ctx, inventoryBalanceMismatches, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const latestCostClosing = `-- name: LatestCostClosing :one
SELECT id, company_id, period, item_count, cogs_amount, adjust_amount, inventory_value, closed_by, closed_at FROM cost_closings WHERE company_id = $1 ORDER BY period DESC LIMIT 1
`

func (q *Queries) LatestCostClosing(ctx context.Context, companyID int64) (CostClosing, error) {
	row := q.db.QueryRow(ctx, latestCostClosing, companyID)
	var i CostClosing
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Period,
		&i.ItemCount,
		&i.CogsAmount,
		&i.AdjustAmount,
		&i.InventoryValue,
		&i.ClosedBy,
		&i.ClosedAt,
	)
	return i, err
}

const latestCostClosingBefore = `-- name: LatestCostClosingBefore :one
SELECT id, company_id, period, item_count, cogs_amount, adjust_amount, inventory_value, closed_by, closed_at FROM cost_closings WHERE company_id = $1 AND period < $2::char(7)
ORDER BY period DESC LIMIT 1
`

type LatestCostClosingBeforeParams struct {
	CompanyID int64
	Period    string
}

func (q *Queries) LatestCostClosingBefore(ctx context.Context, arg LatestCostClosingBeforeParams) (CostClosing, error) {
	row := q.db.QueryRow(ctx, latestCostClosingBefore, arg.CompanyID, arg.Period)
	var i CostClosing
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Period,
		&i.ItemCount,
		&i.CogsAmount,
		&i.AdjustAmount,
		&i.InventoryValue,
		&i.ClosedBy,
		&i.ClosedAt,
	)
	return i, err
}

const listCostClosings = `-- name: ListCostClosings :many

SELECT c.id, c.company_id, c.period, c.item_count, c.cogs_amount, c.adjust_amount, c.inventory_value, c.closed_by, c.closed_at, u.name AS closed_by_name FROM cost_closings c LEFT JOIN users u ON u.id = c.closed_by
WHERE c.company_id = $1 ORDER BY c.period DESC
`

type ListCostClosingsRow struct {
	ID             int64
	CompanyID      int64
	Period         string
	ItemCount      int32
	CogsAmount     decimal.Decimal
	AdjustAmount   decimal.Decimal
	InventoryValue decimal.Decimal
	ClosedBy       *int64
	ClosedAt       time.Time
	ClosedByName   *string
}

// ======== 月結成本 ========
func (q *Queries) ListCostClosings(ctx context.Context, companyID int64) ([]ListCostClosingsRow, error) {
	rows, err := q.db.Query(ctx, listCostClosings, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCostClosingsRow{}
	for rows.Next() {
		var i ListCostClosingsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Period,
			&i.ItemCount,
			&i.CogsAmount,
			&i.AdjustAmount,
			&i.InventoryValue,
			&i.ClosedBy,
			&i.ClosedAt,
			&i.ClosedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemCostsForClosing = `-- name: ListItemCostsForClosing :many
SELECT ic.closing_id, ic.item_id, ic.opening_qty, ic.opening_value, ic.purchase_qty, ic.purchase_value, ic.sales_qty, ic.adjust_qty, ic.avg_cost, ic.cogs_amount, ic.adjust_amount, ic.closing_qty, ic.closing_value, ic.consume_qty, ic.consume_value, i.code AS item_code, i.name AS item_name, u.name AS unit_name
FROM item_costs ic JOIN items i ON i.id = ic.item_id JOIN units u ON u.id = i.base_unit_id
WHERE ic.closing_id = $1
  AND ($2::text IS NULL OR i.code ILIKE '%' || $2 || '%' OR i.name ILIKE '%' || $2 || '%')
ORDER BY i.code
LIMIT $4 OFFSET $3
`

type ListItemCostsForClosingParams struct {
	ClosingID int64
	Keyword   *string
	Off       int32
	Lim       int32
}

type ListItemCostsForClosingRow struct {
	ClosingID     int64
	ItemID        int64
	OpeningQty    decimal.Decimal
	OpeningValue  decimal.Decimal
	PurchaseQty   decimal.Decimal
	PurchaseValue decimal.Decimal
	SalesQty      decimal.Decimal
	AdjustQty     decimal.Decimal
	AvgCost       decimal.Decimal
	CogsAmount    decimal.Decimal
	AdjustAmount  decimal.Decimal
	ClosingQty    decimal.Decimal
	ClosingValue  decimal.Decimal
	ConsumeQty    decimal.Decimal
	ConsumeValue  decimal.Decimal
	ItemCode      string
	ItemName      string
	UnitName      string
}

func (q *Queries) ListItemCostsForClosing(ctx context.Context, arg ListItemCostsForClosingParams) ([]ListItemCostsForClosingRow, error) {
	rows, err := q.db.Query(ctx, listItemCostsForClosing,
		arg.ClosingID,
		arg.Keyword,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemCostsForClosingRow{}
	for rows.Next() {
		var i ListItemCostsForClosingRow
		if err := rows.Scan(
			&i.ClosingID,
			&i.ItemID,
			&i.OpeningQty,
			&i.OpeningValue,
			&i.PurchaseQty,
			&i.PurchaseValue,
			&i.SalesQty,
			&i.AdjustQty,
			&i.AvgCost,
			&i.CogsAmount,
			&i.AdjustAmount,
			&i.ClosingQty,
			&i.ClosingValue,
			&i.ConsumeQty,
			&i.ConsumeValue,
			&i.ItemCode,
			&i.ItemName,
			&i.UnitName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemCostsRaw = `-- name: ListItemCostsRaw :many
SELECT closing_id, item_id, opening_qty, opening_value, purchase_qty, purchase_value, sales_qty, adjust_qty, avg_cost, cogs_amount, adjust_amount, closing_qty, closing_value, consume_qty, consume_value FROM item_costs WHERE closing_id = $1
`

func (q *Queries) ListItemCostsRaw(ctx context.Context, closingID int64) ([]ItemCost, error) {
	rows, err := q.db.Query(ctx, listItemCostsRaw, closingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemCost{}
	for rows.Next() {
		var i ItemCost
		if err := rows.Scan(
			&i.ClosingID,
			&i.ItemID,
			&i.OpeningQty,
			&i.OpeningValue,
			&i.PurchaseQty,
			&i.PurchaseValue,
			&i.SalesQty,
			&i.AdjustQty,
			&i.AvgCost,
			&i.CogsAmount,
			&i.AdjustAmount,
			&i.ClosingQty,
			&i.ClosingValue,
			&i.ConsumeQty,
			&i.ConsumeValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lotBalanceMismatches = `-- name: LotBalanceMismatches :one
SELECT (
    (SELECT count(*) FROM (
        SELECT b.lot_id, b.warehouse_id FROM inventory_lot_balances b
        LEFT JOIN (SELECT t.lot_id, t.warehouse_id, SUM(t.qty) AS q FROM inventory_transactions t
                   WHERE t.company_id = $1 AND t.lot_id IS NOT NULL GROUP BY t.lot_id, t.warehouse_id) x
               ON x.lot_id = b.lot_id AND x.warehouse_id = b.warehouse_id
        WHERE b.company_id = $1 AND b.qty <> COALESCE(x.q, 0)
    ) a)
    +
    (SELECT count(*) FROM (
        SELECT ib.item_id, ib.warehouse_id FROM inventory_balances ib JOIN items i ON i.id = ib.item_id
        LEFT JOIN (SELECT lb.item_id, lb.warehouse_id, SUM(lb.qty) AS q FROM inventory_lot_balances lb
                   WHERE lb.company_id = $1 GROUP BY lb.item_id, lb.warehouse_id) y
               ON y.item_id = ib.item_id AND y.warehouse_id = ib.warehouse_id
        WHERE ib.company_id = $1 AND i.lot_control <> 'none' AND ib.qty <> COALESCE(y.q, 0)
    ) c)
)::bigint AS mismatches
`

// 批號現有量的完整性:①各批號現有量 = 流水帳該批號的合計;②批號管理料品各批號合計 = 料品現有量。筆數應為 0
func (q *Queries) LotBalanceMismatches(ctx context.Context, companyID int64) (int64, error) {
	row := q.db.QueryRow(ctx, lotBalanceMismatches, companyID)
	var mismatches int64
	err := row.Scan(&mismatches)
	return mismatches, err
}

const payableBaseBalance = `-- name: PayableBaseBalance :one
SELECT COALESCE(SUM(CASE WHEN amount = 0 THEN 0 ELSE base_amount * (amount - paid_amount) / amount END), 0)::numeric AS balance
FROM accounts_payable WHERE company_id = $1
`

func (q *Queries) PayableBaseBalance(ctx context.Context, companyID int64) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, payableBaseBalance, companyID)
	var balance decimal.Decimal
	err := row.Scan(&balance)
	return balance, err
}

const receivableBaseBalance = `-- name: ReceivableBaseBalance :one
SELECT COALESCE(SUM(CASE WHEN amount = 0 THEN 0 ELSE base_amount * (amount - paid_amount) / amount END), 0)::numeric AS balance
FROM accounts_receivable WHERE company_id = $1
`

func (q *Queries) ReceivableBaseBalance(ctx context.Context, companyID int64) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, receivableBaseBalance, companyID)
	var balance decimal.Decimal
	err := row.Scan(&balance)
	return balance, err
}

const unbalancedVouchers = `-- name: UnbalancedVouchers :one
SELECT count(*) FROM (
    SELECT v.id FROM vouchers v JOIN voucher_lines l ON l.voucher_id = v.id
    WHERE v.company_id = $1 AND v.status = 'posted'
    GROUP BY v.id HAVING SUM(l.debit) <> SUM(l.credit)
) x
`

func (q *Queries) UnbalancedVouchers(ctx context.Context, companyID int64) (int64, error) {
	row := q.db.QueryRow(ctx, unbalancedVouchers, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const uncostedEarlierMonth = `-- name: UncostedEarlierMonth :one
SELECT x.m::text AS month FROM (
    SELECT DISTINCT to_char(it.doc_date, 'YYYY-MM') AS m FROM inventory_transactions it
    WHERE it.company_id = $1 AND it.doc_date < $2::date
) x
WHERE NOT EXISTS (SELECT 1 FROM cost_closings c WHERE c.company_id = $1 AND c.period = x.m)
ORDER BY x.m LIMIT 1
`

type UncostedEarlierMonthParams struct {
	CompanyID int64
	StartDate time.Time
}

// 在指定月份之前、有庫存異動卻尚未月結的最早月份(月結須依序進行)
func (q *Queries) UncostedEarlierMonth(ctx context.Context, arg UncostedEarlierMonthParams) (string, error) {
	row := q.db.QueryRow(ctx, uncostedEarlierMonth, arg.CompanyID, arg.StartDate)
	var month string
	err := row.Scan(&month)
	return month, err
}

const uncostedStockMonths = `-- name: UncostedStockMonths :one
SELECT count(*) FROM (
    SELECT DISTINCT to_char(it.doc_date, 'YYYY-MM') AS m FROM inventory_transactions it
    WHERE it.company_id = $1 AND it.doc_date < $2::date
) x WHERE NOT EXISTS (SELECT 1 FROM cost_closings c WHERE c.company_id = $1 AND c.period = x.m)
`

type UncostedStockMonthsParams struct {
	CompanyID  int64
	MonthStart time.Time
}

// 已有庫存異動、但尚未月結成本的月份數(不含本月)
func (q *Queries) UncostedStockMonths(ctx context.Context, arg UncostedStockMonthsParams) (int64, error) {
	row := q.db.QueryRow(ctx, uncostedStockMonths, arg.CompanyID, arg.MonthStart)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const writebackUnitCost = `-- name: WritebackUnitCost :exec
UPDATE inventory_transactions SET unit_cost = $1
WHERE company_id = $2 AND item_id = $3
  AND doc_date BETWEEN $4::date AND $5::date
  AND source_type NOT IN ('goods_receipt', 'purchase_return', 'opening_stock', 'work_order_receipt')
`

type WritebackUnitCostParams struct {
	AvgCost   *decimal.Decimal
	CompanyID int64
	ItemID    int64
	StartDate time.Time
	EndDate   time.Time
}

// 把平均成本回寫到沒有成本的流水帳(出貨、銷貨退回、調整、盤點、調撥);進貨的單位成本保留原值
func (q *Queries) WritebackUnitCost(ctx context.Context, arg WritebackUnitCostParams) error {
	_, err := q.db.Exec(ctx, writebackUnitCost,
		arg.AvgCost,
		arg.CompanyID,
		arg.ItemID,
		arg.StartDate,
		arg.EndDate,
	)
	return err
}
