// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package db

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const dashboardExpiryCounts = `-- name: DashboardExpiryCounts :one
SELECT
  count(*) FILTER (WHERE l.expiry_date < $1::date)::bigint AS expired,
  count(*) FILTER (WHERE l.expiry_date >= $1::date AND l.expiry_date <= $2::date)::bigint AS expiring,
  EXISTS (SELECT 1 FROM items x WHERE x.company_id = $3 AND x.lot_control = 'lot_expiry') AS controlled
FROM (SELECT DISTINCT b.lot_id FROM inventory_lot_balances b WHERE b.company_id = $3 AND b.qty > 0) s
JOIN item_lots l ON l.id = s.lot_id
`

type DashboardExpiryCountsParams struct {
	Today     time.Time
	Until     time.Time
	CompanyID int64
}

type DashboardExpiryCountsRow struct {
	Expired    int64
	Expiring   int64
	Controlled bool
}

// 有庫存的批號中,已過期與即將到期(today 到 until)的批號數;controlled 表示公司有效期管理的料品
func (q *Queries) DashboardExpiryCounts(ctx context.Context, arg DashboardExpiryCountsParams) (DashboardExpiryCountsRow, error) {
	row := q.db.QueryRow(ctx, dashboardExpiryCounts, arg.Today, arg.Until, arg.CompanyID)
	var i DashboardExpiryCountsRow
	err := row.Scan(&i.Expired, &i.Expiring, &i.Controlled)
	return i, err
}

const dashboardExpiryTop = `-- name: DashboardExpiryTop :many
SELECT l.id AS lot_id, l.lot_no, l.expiry_date, i.code, i.name, SUM(b.qty)::numeric AS qty
FROM inventory_lot_balances b
JOIN item_lots l ON l.id = b.lot_id
JOIN items i ON i.id = b.item_id
WHERE b.company_id = $1 AND b.qty > 0 AND l.expiry_date IS NOT NULL AND l.expiry_date <= $2::date
GROUP BY l.id, i.code, i.name
ORDER BY l.expiry_date, i.code
LIMIT 5
`

type DashboardExpiryTopParams struct {
	CompanyID int64
	Until     time.Time
}

type DashboardExpiryTopRow struct {
	LotID      int64
	LotNo      string
	ExpiryDate *time.Time
	Code       string
	Name       string
	Qty        decimal.Decimal
}

// 最早到期的前 5 個有庫存的批號(含已過期)
func (q *Queries) DashboardExpiryTop(ctx context.Context, arg DashboardExpiryTopParams) ([]DashboardExpiryTopRow, error) {
	rows, err := q.db.Query(ctx, dashboardExpiryTop, arg.CompanyID, arg.Until)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardExpiryTopRow{}
	for rows.Next() {
		var i DashboardExpiryTopRow
		if err := rows.Scan(
			&i.LotID,
			&i.LotNo,
			&i.ExpiryDate,
			&i.Code,
			&i.Name,
			&i.Qty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardLatestClosing = `-- name: DashboardLatestClosing :one
SELECT c.period FROM cost_closings c WHERE c.company_id = $1 ORDER BY c.period DESC LIMIT 1
`

func (q *Queries) DashboardLatestClosing(ctx context.Context, companyID int64) (string, error) {
	row := q.db.QueryRow(ctx, dashboardLatestClosing, companyID)
	var period string
	err := row.Scan(&period)
	return period, err
}

const dashboardLowStock = `-- name: DashboardLowStock :many
SELECT i.id, i.code, i.name, i.safety_stock, u.name AS unit_name, t.total
FROM items i
JOIN units u ON u.id = i.base_unit_id
JOIN LATERAL (SELECT COALESCE(SUM(b.qty), 0)::numeric AS total FROM inventory_balances b WHERE b.item_id = i.id) t ON TRUE
WHERE i.company_id = $1 AND i.is_active AND i.item_type = 'goods' AND i.safety_stock > 0 AND t.total < i.safety_stock
ORDER BY (i.safety_stock - t.total) DESC, i.code
LIMIT 5
`

type DashboardLowStockRow struct {
	ID          int64
	Code        string
	Name        string
	SafetyStock decimal.Decimal
	UnitName    string
	Total       decimal.Decimal
}

// 低於安全庫存的商品(以所有倉庫合計判斷),缺口大的在前
func (q *Queries) DashboardLowStock(ctx context.Context, companyID int64) ([]DashboardLowStockRow, error) {
	rows, err := q.db.Query(ctx, dashboardLowStock, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardLowStockRow{}
	for rows.Next() {
		var i DashboardLowStockRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.SafetyStock,
			&i.UnitName,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardLowStockCount = `-- name: DashboardLowStockCount :one
SELECT count(*) FROM items i
WHERE i.company_id = $1 AND i.is_active AND i.item_type = 'goods' AND i.safety_stock > 0
  AND COALESCE((SELECT SUM(b.qty) FROM inventory_balances b WHERE b.item_id = i.id), 0) < i.safety_stock
`

func (q *Queries) DashboardLowStockCount(ctx context.Context, companyID int64) (int64, error) {
	row := q.db.QueryRow(ctx, dashboardLowStockCount, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dashboardPayables = `-- name: DashboardPayables :one
SELECT
  COALESCE(SUM(b.bal), 0)::numeric AS open_amount,
  COALESCE(SUM(b.bal) FILTER (WHERE p.due_date < $1::date), 0)::numeric AS overdue_amount,
  count(*) FILTER (WHERE p.due_date < $1::date) AS overdue_count,
  COALESCE(SUM(b.bal) FILTER (WHERE p.due_date BETWEEN $1::date AND $2::date), 0)::numeric AS due_soon_amount
FROM accounts_payable p
CROSS JOIN LATERAL (SELECT (CASE WHEN p.amount = 0 THEN 0 ELSE p.base_amount * (p.amount - p.paid_amount) / p.amount END)::numeric AS bal) b
WHERE p.company_id = $3 AND p.amount <> p.paid_amount
`

type DashboardPayablesParams struct {
	Today     time.Time
	Soon      time.Time
	CompanyID int64
}

type DashboardPayablesRow struct {
	OpenAmount    decimal.Decimal
	OverdueAmount decimal.Decimal
	OverdueCount  int64
	DueSoonAmount decimal.Decimal
}

// 未沖應付、已逾期、7 日內到期
func (q *Queries) DashboardPayables(ctx context.Context, arg DashboardPayablesParams) (DashboardPayablesRow, error) {
	row := q.db.QueryRow(ctx, dashboardPayables, arg.Today, arg.Soon, arg.CompanyID)
	var i DashboardPayablesRow
	err := row.Scan(
		&i.OpenAmount,
		&i.OverdueAmount,
		&i.OverdueCount,
		&i.DueSoonAmount,
	)
	return i, err
}

const dashboardPendingOthers = `-- name: DashboardPendingOthers :one
SELECT
  (SELECT count(*) FROM purchase_orders x WHERE x.company_id = $1 AND x.status = 'pending') AS purchase_orders,
  (SELECT count(*) FROM goods_receipts x WHERE x.company_id = $1 AND x.status = 'pending') AS receipts,
  (SELECT count(*) FROM settlements x WHERE x.company_id = $1 AND x.status = 'pending' AND x.side = 'payment') AS payments,
  (SELECT count(*) FROM stock_documents x WHERE x.company_id = $1 AND x.status = 'pending') AS stock_documents,
  (SELECT count(*) FROM vouchers x WHERE x.company_id = $1 AND x.status = 'draft') AS draft_vouchers
`

type DashboardPendingOthersRow struct {
	PurchaseOrders int64
	Receipts       int64
	Payments       int64
	StockDocuments int64
	DraftVouchers  int64
}

func (q *Queries) DashboardPendingOthers(ctx context.Context, companyID int64) (DashboardPendingOthersRow, error) {
	row := q.db.QueryRow(ctx, dashboardPendingOthers, companyID)
	var i DashboardPendingOthersRow
	err := row.Scan(
		&i.PurchaseOrders,
		&i.Receipts,
		&i.Payments,
		&i.StockDocuments,
		&i.DraftVouchers,
	)
	return i, err
}

const dashboardPendingSales = `-- name: DashboardPendingSales :one
SELECT
  (SELECT count(*) FROM sales_orders x LEFT JOIN users u ON u.id = x.sales_user_id
    WHERE x.company_id = $1 AND x.status = 'pending'
      AND ($2::bigint IS NULL OR x.sales_user_id = $2)
      AND ($3::bigint IS NULL OR u.department_id = $3)) AS sales_orders,
  (SELECT count(*) FROM deliveries x LEFT JOIN users u ON u.id = x.sales_user_id
    WHERE x.company_id = $1 AND x.status = 'pending'
      AND ($2::bigint IS NULL OR x.sales_user_id = $2)
      AND ($3::bigint IS NULL OR u.department_id = $3)) AS deliveries,
  (SELECT count(*) FROM settlements x LEFT JOIN users u ON u.id = x.sales_user_id
    WHERE x.company_id = $1 AND x.status = 'pending' AND x.side = 'receipt'
      AND ($2::bigint IS NULL OR x.sales_user_id = $2)
      AND ($3::bigint IS NULL OR u.department_id = $3)) AS collections
`

type DashboardPendingSalesParams struct {
	CompanyID   int64
	ScopeUserID *int64
	ScopeDeptID *int64
}

type DashboardPendingSalesRow struct {
	SalesOrders int64
	Deliveries  int64
	Collections int64
}

// 待審的報價 / 訂單、出貨 / 退回、收款單(依資料範圍)
func (q *Queries) DashboardPendingSales(ctx context.Context, arg DashboardPendingSalesParams) (DashboardPendingSalesRow, error) {
	row := q.db.QueryRow(ctx, dashboardPendingSales, arg.CompanyID, arg.ScopeUserID, arg.ScopeDeptID)
	var i DashboardPendingSalesRow
	err := row.Scan(&i.SalesOrders, &i.Deliveries, &i.Collections)
	return i, err
}

const dashboardReceivables = `-- name: DashboardReceivables :one
SELECT
  COALESCE(SUM(b.bal), 0)::numeric AS open_amount,
  COALESCE(SUM(b.bal) FILTER (WHERE r.due_date < $1::date), 0)::numeric AS overdue_amount,
  count(*) FILTER (WHERE r.due_date < $1::date) AS overdue_count
FROM accounts_receivable r
JOIN customers c ON c.id = r.customer_id
LEFT JOIN users su ON su.id = c.sales_user_id
CROSS JOIN LATERAL (SELECT (CASE WHEN r.amount = 0 THEN 0 ELSE r.base_amount * (r.amount - r.paid_amount) / r.amount END)::numeric AS bal) b
WHERE r.company_id = $2 AND r.amount <> r.paid_amount
  AND ($3::bigint IS NULL OR c.sales_user_id = $3)
  AND ($4::bigint IS NULL OR su.department_id = $4)
`

type DashboardReceivablesParams struct {
	Today       time.Time
	CompanyID   int64
	ScopeUserID *int64
	ScopeDeptID *int64
}

type DashboardReceivablesRow struct {
	OpenAmount    decimal.Decimal
	OverdueAmount decimal.Decimal
	OverdueCount  int64
}

// 未沖應收(本位幣,依餘額比例;退回的負數帳款一併計入,與應收帳款頁、帳齡一致)與逾期部分;依客戶負責業務的資料範圍
func (q *Queries) DashboardReceivables(ctx context.Context, arg DashboardReceivablesParams) (DashboardReceivablesRow, error) {
	row := q.db.QueryRow(ctx, dashboardReceivables,
		arg.Today,
		arg.CompanyID,
		arg.ScopeUserID,
		arg.ScopeDeptID,
	)
	var i DashboardReceivablesRow
	err := row.Scan(&i.OpenAmount, &i.OverdueAmount, &i.OverdueCount)
	return i, err
}

const dashboardSales = `-- name: DashboardSales :one

SELECT COALESCE(SUM(CASE WHEN d.doc_type = 'delivery' THEN d.base_untaxed ELSE -d.base_untaxed END), 0)::numeric AS amount,
       count(*) FILTER (WHERE d.doc_type = 'delivery') AS delivery_count
FROM deliveries d
LEFT JOIN users su ON su.id = d.sales_user_id
WHERE d.company_id = $1 AND d.status = 'posted'
  AND d.doc_date BETWEEN $2::date AND $3::date
  AND ($4::bigint IS NULL OR d.sales_user_id = $4)
  AND ($5::bigint IS NULL OR su.department_id = $5)
`

type DashboardSalesParams struct {
	CompanyID   int64
	FromDate    time.Time
	ToDate      time.Time
	ScopeUserID *int64
	ScopeDeptID *int64
}

type DashboardSalesRow struct {
	Amount        decimal.Decimal
	DeliveryCount int64
}

// 首頁儀表板:各卡片只在使用者有對應權限時才會被呼叫;銷售相關依資料範圍(D38)
// 期間內已過帳出貨 − 銷貨退回的未稅本位幣金額與出貨單張數
func (q *Queries) DashboardSales(ctx context.Context, arg DashboardSalesParams) (DashboardSalesRow, error) {
	row := q.db.QueryRow(ctx, dashboardSales,
		arg.CompanyID,
		arg.FromDate,
		arg.ToDate,
		arg.ScopeUserID,
		arg.ScopeDeptID,
	)
	var i DashboardSalesRow
	err := row.Scan(&i.Amount, &i.DeliveryCount)
	return i, err
}

const dashboardSalesDaily = `-- name: DashboardSalesDaily :many
SELECT d.doc_date AS day,
       COALESCE(SUM(CASE WHEN d.doc_type = 'delivery' THEN d.base_untaxed ELSE -d.base_untaxed END), 0)::numeric AS amount
FROM deliveries d
LEFT JOIN users su ON su.id = d.sales_user_id
WHERE d.company_id = $1 AND d.status = 'posted'
  AND d.doc_date BETWEEN $2::date AND $3::date
  AND ($4::bigint IS NULL OR d.sales_user_id = $4)
  AND ($5::bigint IS NULL OR su.department_id = $5)
GROUP BY d.doc_date
ORDER BY d.doc_date
`

type DashboardSalesDailyParams struct {
	CompanyID   int64
	FromDate    time.Time
	ToDate      time.Time
	ScopeUserID *int64
	ScopeDeptID *int64
}

type DashboardSalesDailyRow struct {
	Day    time.Time
	Amount decimal.Decimal
}

// 近幾天每日銷售額(用於趨勢)
func (q *Queries) DashboardSalesDaily(ctx context.Context, arg DashboardSalesDailyParams) ([]DashboardSalesDailyRow, error) {
	rows, err := q.db.Query(ctx, dashboardSalesDaily,
		arg.CompanyID,
		arg.FromDate,
		arg.ToDate,
		arg.ScopeUserID,
		arg.ScopeDeptID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardSalesDailyRow{}
	for rows.Next() {
		var i DashboardSalesDailyRow
		if err := rows.Scan(&i.Day, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
