// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: doc_numbers.sql

package db

import (
	"context"
)

const getDocNumberRule = `-- name: GetDocNumberRule :one
SELECT company_id, doc_type, name, prefix, date_format, seq_length, version, updated_by, created_at, updated_at FROM doc_number_rules WHERE company_id = $1 AND doc_type = $2
`

type GetDocNumberRuleParams struct {
	CompanyID int64
	DocType   string
}

func (q *Queries) GetDocNumberRule(ctx context.Context, arg GetDocNumberRuleParams) (DocNumberRule, error) {
	row := q.db.QueryRow(ctx, getDocNumberRule, arg.CompanyID, arg.DocType)
	var i DocNumberRule
	err := row.Scan(
		&i.CompanyID,
		&i.DocType,
		&i.Name,
		&i.Prefix,
		&i.DateFormat,
		&i.SeqLength,
		&i.Version,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocNumberRules = `-- name: ListDocNumberRules :many
SELECT company_id, doc_type, name, prefix, date_format, seq_length, version, updated_by, created_at, updated_at FROM doc_number_rules WHERE company_id = $1 ORDER BY doc_type
`

func (q *Queries) ListDocNumberRules(ctx context.Context, companyID int64) ([]DocNumberRule, error) {
	rows, err := q.db.Query(ctx, listDocNumberRules, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocNumberRule{}
	for rows.Next() {
		var i DocNumberRule
		if err := rows.Scan(
			&i.CompanyID,
			&i.DocType,
			&i.Name,
			&i.Prefix,
			&i.DateFormat,
			&i.SeqLength,
			&i.Version,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextDocNumber = `-- name: NextDocNumber :one
INSERT INTO doc_number_counters (company_id, doc_type, period_key, last_value)
VALUES ($1, $2, $3, 1)
ON CONFLICT (company_id, doc_type, period_key)
DO UPDATE SET last_value = doc_number_counters.last_value + 1
RETURNING last_value
`

type NextDocNumberParams struct {
	CompanyID int64
	DocType   string
	PeriodKey string
}

// 原子地取下一號:同一期間的計數列會被鎖到交易結束,確保不重號、交易回滾時不跳號
func (q *Queries) NextDocNumber(ctx context.Context, arg NextDocNumberParams) (int64, error) {
	row := q.db.QueryRow(ctx, nextDocNumber, arg.CompanyID, arg.DocType, arg.PeriodKey)
	var last_value int64
	err := row.Scan(&last_value)
	return last_value, err
}

const updateDocNumberRule = `-- name: UpdateDocNumberRule :one
UPDATE doc_number_rules
SET name        = $1,
    prefix      = $2,
    date_format = $3,
    seq_length  = $4,
    version     = version + 1,
    updated_by  = $5
WHERE company_id = $6 AND doc_type = $7 AND version = $8
RETURNING company_id, doc_type, name, prefix, date_format, seq_length, version, updated_by, created_at, updated_at
`

type UpdateDocNumberRuleParams struct {
	Name       string
	Prefix     string
	DateFormat string
	SeqLength  int32
	UpdatedBy  *int64
	CompanyID  int64
	DocType    string
	Version    int32
}

func (q *Queries) UpdateDocNumberRule(ctx context.Context, arg UpdateDocNumberRuleParams) (DocNumberRule, error) {
	row := q.db.QueryRow(ctx, updateDocNumberRule,
		arg.Name,
		arg.Prefix,
		arg.DateFormat,
		arg.SeqLength,
		arg.UpdatedBy,
		arg.CompanyID,
		arg.DocType,
		arg.Version,
	)
	var i DocNumberRule
	err := row.Scan(
		&i.CompanyID,
		&i.DocType,
		&i.Name,
		&i.Prefix,
		&i.DateFormat,
		&i.SeqLength,
		&i.Version,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
