// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: finance_settings.sql

package db

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const countExchangeRates = `-- name: CountExchangeRates :one
SELECT count(*) FROM exchange_rates
WHERE company_id = $1
  AND ($2::text IS NULL OR currency = $2)
  AND ($3::date IS NULL OR rate_date >= $3)
  AND ($4::date IS NULL OR rate_date <= $4)
`

type CountExchangeRatesParams struct {
	CompanyID int64
	Currency  *string
	FromDate  *time.Time
	ToDate    *time.Time
}

func (q *Queries) CountExchangeRates(ctx context.Context, arg CountExchangeRatesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countExchangeRates,
		arg.CompanyID,
		arg.Currency,
		arg.FromDate,
		arg.ToDate,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExchangeRate = `-- name: CreateExchangeRate :one
INSERT INTO exchange_rates (company_id, currency, rate_date, rate, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $5)
RETURNING id, company_id, currency, rate_date, rate, created_by, updated_by, version, created_at, updated_at
`

type CreateExchangeRateParams struct {
	CompanyID int64
	Currency  string
	RateDate  time.Time
	Rate      decimal.Decimal
	CreatedBy *int64
}

func (q *Queries) CreateExchangeRate(ctx context.Context, arg CreateExchangeRateParams) (ExchangeRate, error) {
	row := q.db.QueryRow(ctx, createExchangeRate,
		arg.CompanyID,
		arg.Currency,
		arg.RateDate,
		arg.Rate,
		arg.CreatedBy,
	)
	var i ExchangeRate
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Currency,
		&i.RateDate,
		&i.Rate,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPaymentTerm = `-- name: CreatePaymentTerm :one
INSERT INTO payment_terms (company_id, code, name, is_month_end, net_days, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $6)
RETURNING id, company_id, code, name, is_month_end, net_days, is_active, created_by, updated_by, version, created_at, updated_at
`

type CreatePaymentTermParams struct {
	CompanyID  int64
	Code       string
	Name       string
	IsMonthEnd bool
	NetDays    int32
	CreatedBy  *int64
}

func (q *Queries) CreatePaymentTerm(ctx context.Context, arg CreatePaymentTermParams) (PaymentTerm, error) {
	row := q.db.QueryRow(ctx, createPaymentTerm,
		arg.CompanyID,
		arg.Code,
		arg.Name,
		arg.IsMonthEnd,
		arg.NetDays,
		arg.CreatedBy,
	)
	var i PaymentTerm
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.Name,
		&i.IsMonthEnd,
		&i.NetDays,
		&i.IsActive,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTaxType = `-- name: CreateTaxType :one
INSERT INTO tax_types (company_id, code, name, kind, rate, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $6)
RETURNING id, company_id, code, name, kind, rate, is_active, created_by, updated_by, version, created_at, updated_at
`

type CreateTaxTypeParams struct {
	CompanyID int64
	Code      string
	Name      string
	Kind      string
	Rate      decimal.Decimal
	CreatedBy *int64
}

func (q *Queries) CreateTaxType(ctx context.Context, arg CreateTaxTypeParams) (TaxType, error) {
	row := q.db.QueryRow(ctx, createTaxType,
		arg.CompanyID,
		arg.Code,
		arg.Name,
		arg.Kind,
		arg.Rate,
		arg.CreatedBy,
	)
	var i TaxType
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.Name,
		&i.Kind,
		&i.Rate,
		&i.IsActive,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExchangeRate = `-- name: DeleteExchangeRate :execrows
DELETE FROM exchange_rates WHERE id = $1 AND company_id = $2
`

type DeleteExchangeRateParams struct {
	ID        int64
	CompanyID int64
}

func (q *Queries) DeleteExchangeRate(ctx context.Context, arg DeleteExchangeRateParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExchangeRate, arg.ID, arg.CompanyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCurrency = `-- name: GetCurrency :one
SELECT code, name, symbol, decimals, is_active, sort_order FROM currencies WHERE code = $1
`

func (q *Queries) GetCurrency(ctx context.Context, code string) (Currency, error) {
	row := q.db.QueryRow(ctx, getCurrency, code)
	var i Currency
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.Decimals,
		&i.IsActive,
		&i.SortOrder,
	)
	return i, err
}

const getExchangeRate = `-- name: GetExchangeRate :one
SELECT id, company_id, currency, rate_date, rate, created_by, updated_by, version, created_at, updated_at FROM exchange_rates WHERE id = $1 AND company_id = $2
`

type GetExchangeRateParams struct {
	ID        int64
	CompanyID int64
}

func (q *Queries) GetExchangeRate(ctx context.Context, arg GetExchangeRateParams) (ExchangeRate, error) {
	row := q.db.QueryRow(ctx, getExchangeRate, arg.ID, arg.CompanyID)
	var i ExchangeRate
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Currency,
		&i.RateDate,
		&i.Rate,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentTerm = `-- name: GetPaymentTerm :one
SELECT id, company_id, code, name, is_month_end, net_days, is_active, created_by, updated_by, version, created_at, updated_at FROM payment_terms WHERE id = $1 AND company_id = $2
`

type GetPaymentTermParams struct {
	ID        int64
	CompanyID int64
}

func (q *Queries) GetPaymentTerm(ctx context.Context, arg GetPaymentTermParams) (PaymentTerm, error) {
	row := q.db.QueryRow(ctx, getPaymentTerm, arg.ID, arg.CompanyID)
	var i PaymentTerm
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.Name,
		&i.IsMonthEnd,
		&i.NetDays,
		&i.IsActive,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaxType = `-- name: GetTaxType :one
SELECT id, company_id, code, name, kind, rate, is_active, created_by, updated_by, version, created_at, updated_at FROM tax_types WHERE id = $1 AND company_id = $2
`

type GetTaxTypeParams struct {
	ID        int64
	CompanyID int64
}

func (q *Queries) GetTaxType(ctx context.Context, arg GetTaxTypeParams) (TaxType, error) {
	row := q.db.QueryRow(ctx, getTaxType, arg.ID, arg.CompanyID)
	var i TaxType
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.Name,
		&i.Kind,
		&i.Rate,
		&i.IsActive,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCurrencies = `-- name: ListCurrencies :many
SELECT code, name, symbol, decimals, is_active, sort_order FROM currencies ORDER BY sort_order, code
`

func (q *Queries) ListCurrencies(ctx context.Context) ([]Currency, error) {
	rows, err := q.db.Query(ctx, listCurrencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Currency{}
	for rows.Next() {
		var i Currency
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Symbol,
			&i.Decimals,
			&i.IsActive,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExchangeRates = `-- name: ListExchangeRates :many
SELECT id, company_id, currency, rate_date, rate, created_by, updated_by, version, created_at, updated_at FROM exchange_rates
WHERE company_id = $1
  AND ($2::text IS NULL OR currency = $2)
  AND ($3::date IS NULL OR rate_date >= $3)
  AND ($4::date IS NULL OR rate_date <= $4)
ORDER BY rate_date DESC, currency
LIMIT $6 OFFSET $5
`

type ListExchangeRatesParams struct {
	CompanyID int64
	Currency  *string
	FromDate  *time.Time
	ToDate    *time.Time
	Off       int32
	Lim       int32
}

func (q *Queries) ListExchangeRates(ctx context.Context, arg ListExchangeRatesParams) ([]ExchangeRate, error) {
	rows, err := q.db.Query(ctx, listExchangeRates,
		arg.CompanyID,
		arg.Currency,
		arg.FromDate,
		arg.ToDate,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExchangeRate{}
	for rows.Next() {
		var i ExchangeRate
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Currency,
			&i.RateDate,
			&i.Rate,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentTerms = `-- name: ListPaymentTerms :many
SELECT id, company_id, code, name, is_month_end, net_days, is_active, created_by, updated_by, version, created_at, updated_at FROM payment_terms WHERE company_id = $1 ORDER BY code
`

func (q *Queries) ListPaymentTerms(ctx context.Context, companyID int64) ([]PaymentTerm, error) {
	rows, err := q.db.Query(ctx, listPaymentTerms, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentTerm{}
	for rows.Next() {
		var i PaymentTerm
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Code,
			&i.Name,
			&i.IsMonthEnd,
			&i.NetDays,
			&i.IsActive,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaxTypes = `-- name: ListTaxTypes :many
SELECT id, company_id, code, name, kind, rate, is_active, created_by, updated_by, version, created_at, updated_at FROM tax_types WHERE company_id = $1 ORDER BY code
`

func (q *Queries) ListTaxTypes(ctx context.Context, companyID int64) ([]TaxType, error) {
	rows, err := q.db.Query(ctx, listTaxTypes, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaxType{}
	for rows.Next() {
		var i TaxType
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Code,
			&i.Name,
			&i.Kind,
			&i.Rate,
			&i.IsActive,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rateOn = `-- name: RateOn :one
SELECT id, company_id, currency, rate_date, rate, created_by, updated_by, version, created_at, updated_at FROM exchange_rates
WHERE company_id = $1 AND currency = $2 AND rate_date <= $3
ORDER BY rate_date DESC
LIMIT 1
`

type RateOnParams struct {
	CompanyID int64
	Currency  string
	OnDate    time.Time
}

// 取該日或之前最近一筆匯率
func (q *Queries) RateOn(ctx context.Context, arg RateOnParams) (ExchangeRate, error) {
	row := q.db.QueryRow(ctx, rateOn, arg.CompanyID, arg.Currency, arg.OnDate)
	var i ExchangeRate
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Currency,
		&i.RateDate,
		&i.Rate,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCurrencyActive = `-- name: SetCurrencyActive :one
UPDATE currencies SET is_active = $1 WHERE code = $2 RETURNING code, name, symbol, decimals, is_active, sort_order
`

type SetCurrencyActiveParams struct {
	IsActive bool
	Code     string
}

func (q *Queries) SetCurrencyActive(ctx context.Context, arg SetCurrencyActiveParams) (Currency, error) {
	row := q.db.QueryRow(ctx, setCurrencyActive, arg.IsActive, arg.Code)
	var i Currency
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.Decimals,
		&i.IsActive,
		&i.SortOrder,
	)
	return i, err
}

const updateExchangeRate = `-- name: UpdateExchangeRate :one
UPDATE exchange_rates
SET rate = $1, version = version + 1, updated_by = $2
WHERE id = $3 AND company_id = $4 AND version = $5
RETURNING id, company_id, currency, rate_date, rate, created_by, updated_by, version, created_at, updated_at
`

type UpdateExchangeRateParams struct {
	Rate      decimal.Decimal
	UpdatedBy *int64
	ID        int64
	CompanyID int64
	Version   int32
}

func (q *Queries) UpdateExchangeRate(ctx context.Context, arg UpdateExchangeRateParams) (ExchangeRate, error) {
	row := q.db.QueryRow(ctx, updateExchangeRate,
		arg.Rate,
		arg.UpdatedBy,
		arg.ID,
		arg.CompanyID,
		arg.Version,
	)
	var i ExchangeRate
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Currency,
		&i.RateDate,
		&i.Rate,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentTerm = `-- name: UpdatePaymentTerm :one
UPDATE payment_terms
SET code = $1, name = $2, is_month_end = $3, net_days = $4,
    is_active = $5, version = version + 1, updated_by = $6
WHERE id = $7 AND company_id = $8 AND version = $9
RETURNING id, company_id, code, name, is_month_end, net_days, is_active, created_by, updated_by, version, created_at, updated_at
`

type UpdatePaymentTermParams struct {
	Code       string
	Name       string
	IsMonthEnd bool
	NetDays    int32
	IsActive   bool
	UpdatedBy  *int64
	ID         int64
	CompanyID  int64
	Version    int32
}

func (q *Queries) UpdatePaymentTerm(ctx context.Context, arg UpdatePaymentTermParams) (PaymentTerm, error) {
	row := q.db.QueryRow(ctx, updatePaymentTerm,
		arg.Code,
		arg.Name,
		arg.IsMonthEnd,
		arg.NetDays,
		arg.IsActive,
		arg.UpdatedBy,
		arg.ID,
		arg.CompanyID,
		arg.Version,
	)
	var i PaymentTerm
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.Name,
		&i.IsMonthEnd,
		&i.NetDays,
		&i.IsActive,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaxType = `-- name: UpdateTaxType :one
UPDATE tax_types
SET code = $1, name = $2, kind = $3, rate = $4, is_active = $5,
    version = version + 1, updated_by = $6
WHERE id = $7 AND company_id = $8 AND version = $9
RETURNING id, company_id, code, name, kind, rate, is_active, created_by, updated_by, version, created_at, updated_at
`

type UpdateTaxTypeParams struct {
	Code      string
	Name      string
	Kind      string
	Rate      decimal.Decimal
	IsActive  bool
	UpdatedBy *int64
	ID        int64
	CompanyID int64
	Version   int32
}

func (q *Queries) UpdateTaxType(ctx context.Context, arg UpdateTaxTypeParams) (TaxType, error) {
	row := q.db.QueryRow(ctx, updateTaxType,
		arg.Code,
		arg.Name,
		arg.Kind,
		arg.Rate,
		arg.IsActive,
		arg.UpdatedBy,
		arg.ID,
		arg.CompanyID,
		arg.Version,
	)
	var i TaxType
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.Name,
		&i.Kind,
		&i.Rate,
		&i.IsActive,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
