// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gl.sql

package db

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const accountParentCycle = `-- name: AccountParentCycle :one
WITH RECURSIVE chain (cid) AS (
    SELECT $2::bigint
    UNION ALL
    SELECT accounts.parent_id FROM accounts, chain WHERE accounts.id = chain.cid AND accounts.parent_id IS NOT NULL
)
SELECT EXISTS (SELECT 1 FROM chain WHERE chain.cid = $1::bigint)
`

type AccountParentCycleParams struct {
	SelfID   int64
	ParentID int64
}

// 設定 parent 後是否會形成循環(parent 的祖先鏈中包含自己)
func (q *Queries) AccountParentCycle(ctx context.Context, arg AccountParentCycleParams) (bool, error) {
	row := q.db.QueryRow(ctx, accountParentCycle, arg.SelfID, arg.ParentID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const accountsForPosting = `-- name: AccountsForPosting :many
SELECT id, code, name, is_active, is_postable FROM accounts
WHERE company_id = $1 AND id = ANY($2::bigint[])
`

type AccountsForPostingParams struct {
	CompanyID int64
	Ids       []int64
}

type AccountsForPostingRow struct {
	ID         int64
	Code       string
	Name       string
	IsActive   bool
	IsPostable bool
}

// 記帳驗證:科目須屬同公司、啟用且為明細科目
func (q *Queries) AccountsForPosting(ctx context.Context, arg AccountsForPostingParams) ([]AccountsForPostingRow, error) {
	rows, err := q.db.Query(ctx, accountsForPosting, arg.CompanyID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountsForPostingRow{}
	for rows.Next() {
		var i AccountsForPostingRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.IsActive,
			&i.IsPostable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const addVoucherLine = `-- name: AddVoucherLine :exec
INSERT INTO voucher_lines (voucher_id, line_no, account_id, debit, credit, description, customer_id, supplier_id, department_id)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9)
`

type AddVoucherLineParams struct {
	VoucherID    int64
	LineNo       int32
	AccountID    int64
	Debit        decimal.Decimal
	Credit       decimal.Decimal
	Description  string
	CustomerID   *int64
	SupplierID   *int64
	DepartmentID *int64
}

func (q *Queries) AddVoucherLine(ctx context.Context, arg AddVoucherLineParams) error {
	_, err := q.db.Exec(ctx, addVoucherLine,
		arg.VoucherID,
		arg.LineNo,
		arg.AccountID,
		arg.Debit,
		arg.Credit,
		arg.Description,
		arg.CustomerID,
		arg.SupplierID,
		arg.DepartmentID,
	)
	return err
}

const countDraftVouchersInPeriod = `-- name: CountDraftVouchersInPeriod :one
SELECT count(*) FROM vouchers
WHERE company_id = $1 AND status = 'draft' AND to_char(voucher_date, 'YYYY-MM') = $2::text
`

type CountDraftVouchersInPeriodParams struct {
	CompanyID int64
	Period    string
}

func (q *Queries) CountDraftVouchersInPeriod(ctx context.Context, arg CountDraftVouchersInPeriodParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDraftVouchersInPeriod, arg.CompanyID, arg.Period)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countJournal = `-- name: CountJournal :one
SELECT count(*) FROM vouchers v JOIN voucher_lines l ON l.voucher_id = v.id
WHERE v.company_id = $1 AND v.status = 'posted'
  AND v.voucher_date BETWEEN $2::date AND $3::date
`

type CountJournalParams struct {
	CompanyID int64
	FromDate  time.Time
	ToDate    time.Time
}

func (q *Queries) CountJournal(ctx context.Context, arg CountJournalParams) (int64, error) {
	row := q.db.QueryRow(ctx, countJournal, arg.CompanyID, arg.FromDate, arg.ToDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVouchers = `-- name: CountVouchers :one
SELECT count(*) FROM vouchers v
WHERE v.company_id = $1
  AND ($2::text IS NULL OR v.status = $2)
  AND ($3::text IS NULL OR ($3 = 'manual' AND v.source_type = 'manual')
       OR ($3 = 'auto' AND v.source_type <> 'manual'))
  AND ($4::text IS NULL OR v.doc_no ILIKE '%' || $4 || '%'
       OR v.source_no ILIKE '%' || $4 || '%' OR v.description ILIKE '%' || $4 || '%')
  AND ($5::date IS NULL OR v.voucher_date >= $5)
  AND ($6::date IS NULL OR v.voucher_date <= $6)
  AND ($7::bigint IS NULL OR EXISTS (
        SELECT 1 FROM voucher_lines l WHERE l.voucher_id = v.id AND l.account_id = $7))
`

type CountVouchersParams struct {
	CompanyID int64
	Status    *string
	Source    *string
	Keyword   *string
	FromDate  *time.Time
	ToDate    *time.Time
	AccountID *int64
}

func (q *Queries) CountVouchers(ctx context.Context, arg CountVouchersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVouchers,
		arg.CompanyID,
		arg.Status,
		arg.Source,
		arg.Keyword,
		arg.FromDate,
		arg.ToDate,
		arg.AccountID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (company_id, code, name, acct_type, parent_id, is_postable, note, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $8)
RETURNING id, company_id, code, name, acct_type, parent_id, is_postable, is_active, note, created_by, updated_by, version, created_at, updated_at
`

type CreateAccountParams struct {
	CompanyID  int64
	Code       string
	Name       string
	AcctType   string
	ParentID   *int64
	IsPostable bool
	Note       string
	CreatedBy  *int64
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.CompanyID,
		arg.Code,
		arg.Name,
		arg.AcctType,
		arg.ParentID,
		arg.IsPostable,
		arg.Note,
		arg.CreatedBy,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.Name,
		&i.AcctType,
		&i.ParentID,
		&i.IsPostable,
		&i.IsActive,
		&i.Note,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVoucher = `-- name: CreateVoucher :one
INSERT INTO vouchers (company_id, doc_no, voucher_date, source_type, source_id, source_no, description, status,
                      reversal_of, total_amount, posted_by, posted_at, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8::text,
        $9, $10, $11,
        CASE WHEN $8::text = 'posted' THEN now() END, $12, $12)
RETURNING id, company_id, doc_no, voucher_date, source_type, source_id, source_no, description, status, reversal_of, total_amount, posted_by, posted_at, created_by, updated_by, version, created_at, updated_at
`

type CreateVoucherParams struct {
	CompanyID   int64
	DocNo       string
	VoucherDate time.Time
	SourceType  string
	SourceID    *int64
	SourceNo    string
	Description string
	Status      string
	ReversalOf  *int64
	TotalAmount decimal.Decimal
	PostedBy    *int64
	CreatedBy   *int64
}

func (q *Queries) CreateVoucher(ctx context.Context, arg CreateVoucherParams) (Voucher, error) {
	row := q.db.QueryRow(ctx, createVoucher,
		arg.CompanyID,
		arg.DocNo,
		arg.VoucherDate,
		arg.SourceType,
		arg.SourceID,
		arg.SourceNo,
		arg.Description,
		arg.Status,
		arg.ReversalOf,
		arg.TotalAmount,
		arg.PostedBy,
		arg.CreatedBy,
	)
	var i Voucher
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocNo,
		&i.VoucherDate,
		&i.SourceType,
		&i.SourceID,
		&i.SourceNo,
		&i.Description,
		&i.Status,
		&i.ReversalOf,
		&i.TotalAmount,
		&i.PostedBy,
		&i.PostedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const customerSupplierDeptExist = `-- name: CustomerSupplierDeptExist :one
SELECT
    COALESCE($1::bigint IS NULL OR EXISTS (
        SELECT 1 FROM customers WHERE id = $1::bigint AND company_id = $2::bigint), FALSE)::boolean AS customer_ok,
    COALESCE($3::bigint IS NULL OR EXISTS (
        SELECT 1 FROM suppliers WHERE id = $3::bigint AND company_id = $2::bigint), FALSE)::boolean AS supplier_ok,
    COALESCE($4::bigint IS NULL OR EXISTS (
        SELECT 1 FROM departments WHERE id = $4::bigint AND company_id = $2::bigint), FALSE)::boolean AS department_ok
`

type CustomerSupplierDeptExistParams struct {
	CustomerID   *int64
	CompanyID    int64
	SupplierID   *int64
	DepartmentID *int64
}

type CustomerSupplierDeptExistRow struct {
	CustomerOk   bool
	SupplierOk   bool
	DepartmentOk bool
}

func (q *Queries) CustomerSupplierDeptExist(ctx context.Context, arg CustomerSupplierDeptExistParams) (CustomerSupplierDeptExistRow, error) {
	row := q.db.QueryRow(ctx, customerSupplierDeptExist,
		arg.CustomerID,
		arg.CompanyID,
		arg.SupplierID,
		arg.DepartmentID,
	)
	var i CustomerSupplierDeptExistRow
	err := row.Scan(&i.CustomerOk, &i.SupplierOk, &i.DepartmentOk)
	return i, err
}

const deleteVoucherLines = `-- name: DeleteVoucherLines :exec
DELETE FROM voucher_lines WHERE voucher_id = $1
`

func (q *Queries) DeleteVoucherLines(ctx context.Context, voucherID int64) error {
	_, err := q.db.Exec(ctx, deleteVoucherLines, voucherID)
	return err
}

const generalLedger = `-- name: GeneralLedger :many
SELECT v.id AS voucher_id, v.doc_no, v.voucher_date, v.source_type, v.source_no,
       COALESCE(NULLIF(l.description, ''), v.description) AS description, l.debit, l.credit
FROM voucher_lines l JOIN vouchers v ON v.id = l.voucher_id
WHERE v.company_id = $1 AND v.status = 'posted' AND l.account_id = $2
  AND v.voucher_date BETWEEN $3::date AND $4::date
ORDER BY v.voucher_date, v.id, l.line_no
`

type GeneralLedgerParams struct {
	CompanyID int64
	AccountID int64
	FromDate  time.Time
	ToDate    time.Time
}

type GeneralLedgerRow struct {
	VoucherID   int64
	DocNo       string
	VoucherDate time.Time
	SourceType  string
	SourceNo    string
	Description string
	Debit       decimal.Decimal
	Credit      decimal.Decimal
}

func (q *Queries) GeneralLedger(ctx context.Context, arg GeneralLedgerParams) ([]GeneralLedgerRow, error) {
	rows, err := q.db.Query(ctx, generalLedger,
		arg.CompanyID,
		arg.AccountID,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GeneralLedgerRow{}
	for rows.Next() {
		var i GeneralLedgerRow
		if err := rows.Scan(
			&i.VoucherID,
			&i.DocNo,
			&i.VoucherDate,
			&i.SourceType,
			&i.SourceNo,
			&i.Description,
			&i.Debit,
			&i.Credit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const generalLedgerOpening = `-- name: GeneralLedgerOpening :one
SELECT COALESCE(SUM(l.debit - l.credit), 0)::numeric AS opening
FROM voucher_lines l JOIN vouchers v ON v.id = l.voucher_id
WHERE v.company_id = $1 AND v.status = 'posted' AND l.account_id = $2
  AND v.voucher_date < $3::date
`

type GeneralLedgerOpeningParams struct {
	CompanyID int64
	AccountID int64
	FromDate  time.Time
}

func (q *Queries) GeneralLedgerOpening(ctx context.Context, arg GeneralLedgerOpeningParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, generalLedgerOpening, arg.CompanyID, arg.AccountID, arg.FromDate)
	var opening decimal.Decimal
	err := row.Scan(&opening)
	return opening, err
}

const getAccount = `-- name: GetAccount :one
SELECT a.id, a.company_id, a.code, a.name, a.acct_type, a.parent_id, a.is_postable, a.is_active, a.note, a.created_by, a.updated_by, a.version, a.created_at, a.updated_at, p.code AS parent_code,
       EXISTS (SELECT 1 FROM voucher_lines l WHERE l.account_id = a.id) AS has_entries
FROM accounts a
LEFT JOIN accounts p ON p.id = a.parent_id
WHERE a.id = $1 AND a.company_id = $2
`

type GetAccountParams struct {
	ID        int64
	CompanyID int64
}

type GetAccountRow struct {
	ID         int64
	CompanyID  int64
	Code       string
	Name       string
	AcctType   string
	ParentID   *int64
	IsPostable bool
	IsActive   bool
	Note       string
	CreatedBy  *int64
	UpdatedBy  *int64
	Version    int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
	ParentCode *string
	HasEntries bool
}

func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (GetAccountRow, error) {
	row := q.db.QueryRow(ctx, getAccount, arg.ID, arg.CompanyID)
	var i GetAccountRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.Name,
		&i.AcctType,
		&i.ParentID,
		&i.IsPostable,
		&i.IsActive,
		&i.Note,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentCode,
		&i.HasEntries,
	)
	return i, err
}

const getPeriod = `-- name: GetPeriod :one

SELECT company_id, period, status, closed_by, closed_at, updated_at FROM accounting_periods WHERE company_id = $1 AND period = $2::char(7)
`

type GetPeriodParams struct {
	CompanyID int64
	Period    string
}

// ======== 會計期間 ========
func (q *Queries) GetPeriod(ctx context.Context, arg GetPeriodParams) (AccountingPeriod, error) {
	row := q.db.QueryRow(ctx, getPeriod, arg.CompanyID, arg.Period)
	var i AccountingPeriod
	err := row.Scan(
		&i.CompanyID,
		&i.Period,
		&i.Status,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVoucher = `-- name: GetVoucher :one
SELECT v.id, v.company_id, v.doc_no, v.voucher_date, v.source_type, v.source_id, v.source_no, v.description, v.status, v.reversal_of, v.total_amount, v.posted_by, v.posted_at, v.created_by, v.updated_by, v.version, v.created_at, v.updated_at, cu.name AS created_by_name, pu.name AS posted_by_name, r.doc_no AS reversal_of_no,
       rv.doc_no AS reversed_by_no
FROM vouchers v
LEFT JOIN users cu ON cu.id = v.created_by
LEFT JOIN users pu ON pu.id = v.posted_by
LEFT JOIN vouchers r ON r.id = v.reversal_of
LEFT JOIN vouchers rv ON rv.reversal_of = v.id
WHERE v.id = $1 AND v.company_id = $2
`

type GetVoucherParams struct {
	ID        int64
	CompanyID int64
}

type GetVoucherRow struct {
	ID            int64
	CompanyID     int64
	DocNo         string
	VoucherDate   time.Time
	SourceType    string
	SourceID      *int64
	SourceNo      string
	Description   string
	Status        string
	ReversalOf    *int64
	TotalAmount   decimal.Decimal
	PostedBy      *int64
	PostedAt      *time.Time
	CreatedBy     *int64
	UpdatedBy     *int64
	Version       int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
	CreatedByName *string
	PostedByName  *string
	ReversalOfNo  *string
	ReversedByNo  *string
}

func (q *Queries) GetVoucher(ctx context.Context, arg GetVoucherParams) (GetVoucherRow, error) {
	row := q.db.QueryRow(ctx, getVoucher, arg.ID, arg.CompanyID)
	var i GetVoucherRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocNo,
		&i.VoucherDate,
		&i.SourceType,
		&i.SourceID,
		&i.SourceNo,
		&i.Description,
		&i.Status,
		&i.ReversalOf,
		&i.TotalAmount,
		&i.PostedBy,
		&i.PostedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByName,
		&i.PostedByName,
		&i.ReversalOfNo,
		&i.ReversedByNo,
	)
	return i, err
}

const journal = `-- name: Journal :many
SELECT v.id AS voucher_id, v.doc_no, v.voucher_date, v.source_type, v.source_no, v.description AS voucher_description,
       l.line_no, a.code AS account_code, a.name AS account_name, l.debit, l.credit, l.description
FROM vouchers v
JOIN voucher_lines l ON l.voucher_id = v.id
JOIN accounts a ON a.id = l.account_id
WHERE v.company_id = $1 AND v.status = 'posted'
  AND v.voucher_date BETWEEN $2::date AND $3::date
ORDER BY v.voucher_date, v.id, l.line_no
LIMIT $5 OFFSET $4
`

type JournalParams struct {
	CompanyID int64
	FromDate  time.Time
	ToDate    time.Time
	Off       int32
	Lim       int32
}

type JournalRow struct {
	VoucherID          int64
	DocNo              string
	VoucherDate        time.Time
	SourceType         string
	SourceNo           string
	VoucherDescription string
	LineNo             int32
	AccountCode        string
	AccountName        string
	Debit              decimal.Decimal
	Credit             decimal.Decimal
	Description        string
}

func (q *Queries) Journal(ctx context.Context, arg JournalParams) ([]JournalRow, error) {
	rows, err := q.db.Query(ctx, journal,
		arg.CompanyID,
		arg.FromDate,
		arg.ToDate,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JournalRow{}
	for rows.Next() {
		var i JournalRow
		if err := rows.Scan(
			&i.VoucherID,
			&i.DocNo,
			&i.VoucherDate,
			&i.SourceType,
			&i.SourceNo,
			&i.VoucherDescription,
			&i.LineNo,
			&i.AccountCode,
			&i.AccountName,
			&i.Debit,
			&i.Credit,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountMappings = `-- name: ListAccountMappings :many

SELECT m.map_key, m.account_id, a.code AS account_code, a.name AS account_name, a.is_active, a.is_postable, m.updated_at
FROM account_mappings m JOIN accounts a ON a.id = m.account_id
WHERE m.company_id = $1
ORDER BY m.map_key
`

type ListAccountMappingsRow struct {
	MapKey      string
	AccountID   int64
	AccountCode string
	AccountName string
	IsActive    bool
	IsPostable  bool
	UpdatedAt   time.Time
}

// ======== 拋轉規則 ========
func (q *Queries) ListAccountMappings(ctx context.Context, companyID int64) ([]ListAccountMappingsRow, error) {
	rows, err := q.db.Query(ctx, listAccountMappings, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountMappingsRow{}
	for rows.Next() {
		var i ListAccountMappingsRow
		if err := rows.Scan(
			&i.MapKey,
			&i.AccountID,
			&i.AccountCode,
			&i.AccountName,
			&i.IsActive,
			&i.IsPostable,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccounts = `-- name: ListAccounts :many

SELECT a.id, a.company_id, a.code, a.name, a.acct_type, a.parent_id, a.is_postable, a.is_active, a.note, a.created_by, a.updated_by, a.version, a.created_at, a.updated_at, p.code AS parent_code,
       EXISTS (SELECT 1 FROM voucher_lines l WHERE l.account_id = a.id) AS has_entries
FROM accounts a
LEFT JOIN accounts p ON p.id = a.parent_id
WHERE a.company_id = $1
  AND ($2::text IS NULL OR a.code ILIKE $2 || '%' OR a.name ILIKE '%' || $2 || '%')
  AND ($3::boolean IS NULL OR a.is_active = $3)
  AND ($4::boolean IS NULL OR NOT $4::boolean OR a.is_postable)
ORDER BY a.code
`

type ListAccountsParams struct {
	CompanyID    int64
	Keyword      *string
	IsActive     *bool
	PostableOnly *bool
}

type ListAccountsRow struct {
	ID         int64
	CompanyID  int64
	Code       string
	Name       string
	AcctType   string
	ParentID   *int64
	IsPostable bool
	IsActive   bool
	Note       string
	CreatedBy  *int64
	UpdatedBy  *int64
	Version    int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
	ParentCode *string
	HasEntries bool
}

// ======== 會計科目 ========
func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]ListAccountsRow, error) {
	rows, err := q.db.Query(ctx, listAccounts,
		arg.CompanyID,
		arg.Keyword,
		arg.IsActive,
		arg.PostableOnly,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsRow{}
	for rows.Next() {
		var i ListAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Code,
			&i.Name,
			&i.AcctType,
			&i.ParentID,
			&i.IsPostable,
			&i.IsActive,
			&i.Note,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentCode,
			&i.HasEntries,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeriods = `-- name: ListPeriods :many
SELECT p.period, p.status, p.closed_at, u.name AS closed_by_name,
       (SELECT count(*) FROM vouchers v WHERE v.company_id = p.company_id AND v.status = 'draft'
          AND to_char(v.voucher_date, 'YYYY-MM') = p.period) AS draft_vouchers
FROM accounting_periods p LEFT JOIN users u ON u.id = p.closed_by
WHERE p.company_id = $1
ORDER BY p.period DESC
`

type ListPeriodsRow struct {
	Period        string
	Status        string
	ClosedAt      *time.Time
	ClosedByName  *string
	DraftVouchers int64
}

func (q *Queries) ListPeriods(ctx context.Context, companyID int64) ([]ListPeriodsRow, error) {
	rows, err := q.db.Query(ctx, listPeriods, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPeriodsRow{}
	for rows.Next() {
		var i ListPeriodsRow
		if err := rows.Scan(
			&i.Period,
			&i.Status,
			&i.ClosedAt,
			&i.ClosedByName,
			&i.DraftVouchers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVoucherLines = `-- name: ListVoucherLines :many
SELECT l.id, l.voucher_id, l.line_no, l.account_id, l.debit, l.credit, l.description, l.customer_id, l.supplier_id, l.department_id, a.code AS account_code, a.name AS account_name, c.name AS customer_name, s.name AS supplier_name,
       d.name AS department_name
FROM voucher_lines l
JOIN accounts a ON a.id = l.account_id
LEFT JOIN customers c ON c.id = l.customer_id
LEFT JOIN suppliers s ON s.id = l.supplier_id
LEFT JOIN departments d ON d.id = l.department_id
WHERE l.voucher_id = $1
ORDER BY l.line_no
`

type ListVoucherLinesRow struct {
	ID             int64
	VoucherID      int64
	LineNo         int32
	AccountID      int64
	Debit          decimal.Decimal
	Credit         decimal.Decimal
	Description    string
	CustomerID     *int64
	SupplierID     *int64
	DepartmentID   *int64
	AccountCode    string
	AccountName    string
	CustomerName   *string
	SupplierName   *string
	DepartmentName *string
}

func (q *Queries) ListVoucherLines(ctx context.Context, voucherID int64) ([]ListVoucherLinesRow, error) {
	rows, err := q.db.Query(ctx, listVoucherLines, voucherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVoucherLinesRow{}
	for rows.Next() {
		var i ListVoucherLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.VoucherID,
			&i.LineNo,
			&i.AccountID,
			&i.Debit,
			&i.Credit,
			&i.Description,
			&i.CustomerID,
			&i.SupplierID,
			&i.DepartmentID,
			&i.AccountCode,
			&i.AccountName,
			&i.CustomerName,
			&i.SupplierName,
			&i.DepartmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVouchers = `-- name: ListVouchers :many

SELECT v.id, v.doc_no, v.voucher_date, v.source_type, v.source_id, v.source_no, v.description, v.status,
       v.reversal_of, v.total_amount, v.version, v.updated_at, cu.name AS created_by_name,
       EXISTS (SELECT 1 FROM vouchers r WHERE r.reversal_of = v.id) AS reversed
FROM vouchers v LEFT JOIN users cu ON cu.id = v.created_by
WHERE v.company_id = $1
  AND ($2::text IS NULL OR v.status = $2)
  AND ($3::text IS NULL OR ($3 = 'manual' AND v.source_type = 'manual')
       OR ($3 = 'auto' AND v.source_type <> 'manual'))
  AND ($4::text IS NULL OR v.doc_no ILIKE '%' || $4 || '%'
       OR v.source_no ILIKE '%' || $4 || '%' OR v.description ILIKE '%' || $4 || '%')
  AND ($5::date IS NULL OR v.voucher_date >= $5)
  AND ($6::date IS NULL OR v.voucher_date <= $6)
  AND ($7::bigint IS NULL OR EXISTS (
        SELECT 1 FROM voucher_lines l WHERE l.voucher_id = v.id AND l.account_id = $7))
ORDER BY v.voucher_date DESC, v.id DESC
LIMIT $9 OFFSET $8
`

type ListVouchersParams struct {
	CompanyID int64
	Status    *string
	Source    *string
	Keyword   *string
	FromDate  *time.Time
	ToDate    *time.Time
	AccountID *int64
	Off       int32
	Lim       int32
}

type ListVouchersRow struct {
	ID            int64
	DocNo         string
	VoucherDate   time.Time
	SourceType    string
	SourceID      *int64
	SourceNo      string
	Description   string
	Status        string
	ReversalOf    *int64
	TotalAmount   decimal.Decimal
	Version       int32
	UpdatedAt     time.Time
	CreatedByName *string
	Reversed      bool
}

// ======== 傳票 ========
func (q *Queries) ListVouchers(ctx context.Context, arg ListVouchersParams) ([]ListVouchersRow, error) {
	rows, err := q.db.Query(ctx, listVouchers,
		arg.CompanyID,
		arg.Status,
		arg.Source,
		arg.Keyword,
		arg.FromDate,
		arg.ToDate,
		arg.AccountID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVouchersRow{}
	for rows.Next() {
		var i ListVouchersRow
		if err := rows.Scan(
			&i.ID,
			&i.DocNo,
			&i.VoucherDate,
			&i.SourceType,
			&i.SourceID,
			&i.SourceNo,
			&i.Description,
			&i.Status,
			&i.ReversalOf,
			&i.TotalAmount,
			&i.Version,
			&i.UpdatedAt,
			&i.CreatedByName,
			&i.Reversed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCompanyForPeriod = `-- name: LockCompanyForPeriod :exec
SELECT id FROM companies WHERE id = $1 FOR SHARE
`

// 關帳 / 重開 / 過帳檢查期間時序列化(避免檢查與關帳交錯)
func (q *Queries) LockCompanyForPeriod(ctx context.Context, companyID int64) error {
	_, err := q.db.Exec(ctx, lockCompanyForPeriod, companyID)
	return err
}

const lockCompanyForPeriodChange = `-- name: LockCompanyForPeriodChange :exec
SELECT id FROM companies WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockCompanyForPeriodChange(ctx context.Context, companyID int64) error {
	_, err := q.db.Exec(ctx, lockCompanyForPeriodChange, companyID)
	return err
}

const lockVoucher = `-- name: LockVoucher :one
SELECT id, company_id, doc_no, voucher_date, source_type, source_id, source_no, description, status, reversal_of, total_amount, posted_by, posted_at, created_by, updated_by, version, created_at, updated_at FROM vouchers WHERE id = $1 AND company_id = $2 FOR UPDATE
`

type LockVoucherParams struct {
	ID        int64
	CompanyID int64
}

func (q *Queries) LockVoucher(ctx context.Context, arg LockVoucherParams) (Voucher, error) {
	row := q.db.QueryRow(ctx, lockVoucher, arg.ID, arg.CompanyID)
	var i Voucher
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocNo,
		&i.VoucherDate,
		&i.SourceType,
		&i.SourceID,
		&i.SourceNo,
		&i.Description,
		&i.Status,
		&i.ReversalOf,
		&i.TotalAmount,
		&i.PostedBy,
		&i.PostedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const openVouchersBySource = `-- name: OpenVouchersBySource :many
SELECT v.id, v.company_id, v.doc_no, v.voucher_date, v.source_type, v.source_id, v.source_no, v.description, v.status, v.reversal_of, v.total_amount, v.posted_by, v.posted_at, v.created_by, v.updated_by, v.version, v.created_at, v.updated_at FROM vouchers v
WHERE v.company_id = $1 AND v.source_type = $2 AND v.source_id = $3
  AND v.status = 'posted' AND v.reversal_of IS NULL
  AND NOT EXISTS (SELECT 1 FROM vouchers r WHERE r.reversal_of = v.id)
ORDER BY v.id
`

type OpenVouchersBySourceParams struct {
	CompanyID  int64
	SourceType string
	SourceID   *int64
}

// 某張業務單據尚未被沖銷的已過帳傳票(反過帳時沖銷)
func (q *Queries) OpenVouchersBySource(ctx context.Context, arg OpenVouchersBySourceParams) ([]Voucher, error) {
	rows, err := q.db.Query(ctx, openVouchersBySource, arg.CompanyID, arg.SourceType, arg.SourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Voucher{}
	for rows.Next() {
		var i Voucher
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.DocNo,
			&i.VoucherDate,
			&i.SourceType,
			&i.SourceID,
			&i.SourceNo,
			&i.Description,
			&i.Status,
			&i.ReversalOf,
			&i.TotalAmount,
			&i.PostedBy,
			&i.PostedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAccountMapping = `-- name: SetAccountMapping :exec
INSERT INTO account_mappings (company_id, map_key, account_id, updated_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (company_id, map_key) DO UPDATE SET account_id = EXCLUDED.account_id,
    updated_by = EXCLUDED.updated_by, updated_at = now()
`

type SetAccountMappingParams struct {
	CompanyID int64
	MapKey    string
	AccountID int64
	UpdatedBy *int64
}

func (q *Queries) SetAccountMapping(ctx context.Context, arg SetAccountMappingParams) error {
	_, err := q.db.Exec(ctx, setAccountMapping,
		arg.CompanyID,
		arg.MapKey,
		arg.AccountID,
		arg.UpdatedBy,
	)
	return err
}

const setPeriodStatus = `-- name: SetPeriodStatus :exec
INSERT INTO accounting_periods (company_id, period, status, closed_by, closed_at)
VALUES ($1, $2::char(7), $3::text, $4, CASE WHEN $3::text = 'closed' THEN now() END)
ON CONFLICT (company_id, period) DO UPDATE
SET status = EXCLUDED.status, closed_by = EXCLUDED.closed_by, closed_at = EXCLUDED.closed_at, updated_at = now()
`

type SetPeriodStatusParams struct {
	CompanyID int64
	Period    string
	Status    string
	ActorID   *int64
}

func (q *Queries) SetPeriodStatus(ctx context.Context, arg SetPeriodStatusParams) error {
	_, err := q.db.Exec(ctx, setPeriodStatus,
		arg.CompanyID,
		arg.Period,
		arg.Status,
		arg.ActorID,
	)
	return err
}

const setVoucherStatus = `-- name: SetVoucherStatus :one
UPDATE vouchers
SET status = $1::text,
    posted_by = CASE WHEN $1::text = 'posted' THEN $2::bigint ELSE posted_by END,
    posted_at = CASE WHEN $1::text = 'posted' THEN now() ELSE posted_at END,
    version = version + 1, updated_by = $2::bigint
WHERE id = $3 AND company_id = $4 AND version = $5 AND status = 'draft'
RETURNING id, company_id, doc_no, voucher_date, source_type, source_id, source_no, description, status, reversal_of, total_amount, posted_by, posted_at, created_by, updated_by, version, created_at, updated_at
`

type SetVoucherStatusParams struct {
	Status    string
	ActorID   int64
	ID        int64
	CompanyID int64
	Version   int32
}

func (q *Queries) SetVoucherStatus(ctx context.Context, arg SetVoucherStatusParams) (Voucher, error) {
	row := q.db.QueryRow(ctx, setVoucherStatus,
		arg.Status,
		arg.ActorID,
		arg.ID,
		arg.CompanyID,
		arg.Version,
	)
	var i Voucher
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocNo,
		&i.VoucherDate,
		&i.SourceType,
		&i.SourceID,
		&i.SourceNo,
		&i.Description,
		&i.Status,
		&i.ReversalOf,
		&i.TotalAmount,
		&i.PostedBy,
		&i.PostedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const trialBalance = `-- name: TrialBalance :many

SELECT a.id AS account_id, a.code, a.name, a.acct_type,
       COALESCE(SUM(l.debit - l.credit) FILTER (WHERE v.voucher_date < $1::date), 0)::numeric AS opening,
       COALESCE(SUM(l.debit) FILTER (WHERE v.voucher_date BETWEEN $1::date AND $2::date), 0)::numeric AS period_debit,
       COALESCE(SUM(l.credit) FILTER (WHERE v.voucher_date BETWEEN $1::date AND $2::date), 0)::numeric AS period_credit
FROM accounts a
JOIN voucher_lines l ON l.account_id = a.id
JOIN vouchers v ON v.id = l.voucher_id AND v.status = 'posted' AND v.voucher_date <= $2::date
WHERE a.company_id = $3
GROUP BY a.id
ORDER BY a.code
`

type TrialBalanceParams struct {
	FromDate  time.Time
	ToDate    time.Time
	CompanyID int64
}

type TrialBalanceRow struct {
	AccountID    int64
	Code         string
	Name         string
	AcctType     string
	Opening      decimal.Decimal
	PeriodDebit  decimal.Decimal
	PeriodCredit decimal.Decimal
}

// ======== 報表(只計已過帳傳票) ========
func (q *Queries) TrialBalance(ctx context.Context, arg TrialBalanceParams) ([]TrialBalanceRow, error) {
	rows, err := q.db.Query(ctx, trialBalance, arg.FromDate, arg.ToDate, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrialBalanceRow{}
	for rows.Next() {
		var i TrialBalanceRow
		if err := rows.Scan(
			&i.AccountID,
			&i.Code,
			&i.Name,
			&i.AcctType,
			&i.Opening,
			&i.PeriodDebit,
			&i.PeriodCredit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name = $1, acct_type = $2, parent_id = $3, is_postable = $4,
    is_active = $5, note = $6, version = version + 1, updated_by = $7
WHERE id = $8 AND company_id = $9 AND version = $10
RETURNING id, company_id, code, name, acct_type, parent_id, is_postable, is_active, note, created_by, updated_by, version, created_at, updated_at
`

type UpdateAccountParams struct {
	Name       string
	AcctType   string
	ParentID   *int64
	IsPostable bool
	IsActive   bool
	Note       string
	UpdatedBy  *int64
	ID         int64
	CompanyID  int64
	Version    int32
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.Name,
		arg.AcctType,
		arg.ParentID,
		arg.IsPostable,
		arg.IsActive,
		arg.Note,
		arg.UpdatedBy,
		arg.ID,
		arg.CompanyID,
		arg.Version,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.Name,
		&i.AcctType,
		&i.ParentID,
		&i.IsPostable,
		&i.IsActive,
		&i.Note,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVoucherHeader = `-- name: UpdateVoucherHeader :one
UPDATE vouchers
SET voucher_date = $1, description = $2, total_amount = $3,
    version = version + 1, updated_by = $4
WHERE id = $5 AND company_id = $6 AND version = $7 AND status = 'draft'
RETURNING id, company_id, doc_no, voucher_date, source_type, source_id, source_no, description, status, reversal_of, total_amount, posted_by, posted_at, created_by, updated_by, version, created_at, updated_at
`

type UpdateVoucherHeaderParams struct {
	VoucherDate time.Time
	Description string
	TotalAmount decimal.Decimal
	UpdatedBy   *int64
	ID          int64
	CompanyID   int64
	Version     int32
}

func (q *Queries) UpdateVoucherHeader(ctx context.Context, arg UpdateVoucherHeaderParams) (Voucher, error) {
	row := q.db.QueryRow(ctx, updateVoucherHeader,
		arg.VoucherDate,
		arg.Description,
		arg.TotalAmount,
		arg.UpdatedBy,
		arg.ID,
		arg.CompanyID,
		arg.Version,
	)
	var i Voucher
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocNo,
		&i.VoucherDate,
		&i.SourceType,
		&i.SourceID,
		&i.SourceNo,
		&i.Description,
		&i.Status,
		&i.ReversalOf,
		&i.TotalAmount,
		&i.PostedBy,
		&i.PostedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
