// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package db

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const countBalances = `-- name: CountBalances :one
WITH RECURSIVE cats (cat_id) AS (
    SELECT item_categories.id FROM item_categories WHERE item_categories.id = $4::bigint
    UNION ALL
    SELECT item_categories.id FROM item_categories, cats WHERE item_categories.parent_id = cats.cat_id
)
SELECT count(*)
FROM inventory_balances b
JOIN items i ON i.id = b.item_id
WHERE b.company_id = $1
  AND ($2::bigint IS NULL OR b.warehouse_id = $2)
  AND ($3::text IS NULL
       OR i.code ILIKE '%' || $3 || '%'
       OR i.name ILIKE '%' || $3 || '%')
  AND ($4::bigint IS NULL OR i.category_id IN (SELECT cat_id FROM cats))
  AND (NOT $5::boolean OR b.qty <> 0)
  AND (NOT $6::boolean OR (i.safety_stock > 0 AND
       (SELECT COALESCE(SUM(b3.qty), 0) FROM inventory_balances b3 WHERE b3.item_id = b.item_id) < i.safety_stock))
`

type CountBalancesParams struct {
	CompanyID   int64
	WarehouseID *int64
	Keyword     *string
	CategoryID  *int64
	Nonzero     bool
	BelowSafety bool
}

func (q *Queries) CountBalances(ctx context.Context, arg CountBalancesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBalances,
		arg.CompanyID,
		arg.WarehouseID,
		arg.Keyword,
		arg.CategoryID,
		arg.Nonzero,
		arg.BelowSafety,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStockMovementSummary = `-- name: CountStockMovementSummary :one
SELECT count(DISTINCT t.item_id)
FROM inventory_transactions t
JOIN items i ON i.id = t.item_id
WHERE t.company_id = $1
  AND t.doc_date <= $2
  AND ($3::bigint IS NULL OR t.warehouse_id = $3)
  AND ($4::text IS NULL
       OR i.code ILIKE '%' || $4 || '%'
       OR i.name ILIKE '%' || $4 || '%')
`

type CountStockMovementSummaryParams struct {
	CompanyID   int64
	ToDate      time.Time
	WarehouseID *int64
	Keyword     *string
}

func (q *Queries) CountStockMovementSummary(ctx context.Context, arg CountStockMovementSummaryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStockMovementSummary,
		arg.CompanyID,
		arg.ToDate,
		arg.WarehouseID,
		arg.Keyword,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const ensureBalance = `-- name: EnsureBalance :exec
INSERT INTO inventory_balances (company_id, item_id, warehouse_id, qty)
VALUES ($1, $2, $3, 0)
ON CONFLICT (item_id, warehouse_id) DO NOTHING
`

type EnsureBalanceParams struct {
	CompanyID   int64
	ItemID      int64
	WarehouseID int64
}

func (q *Queries) EnsureBalance(ctx context.Context, arg EnsureBalanceParams) error {
	_, err := q.db.Exec(ctx, ensureBalance, arg.CompanyID, arg.ItemID, arg.WarehouseID)
	return err
}

const insertInventoryTransaction = `-- name: InsertInventoryTransaction :one
INSERT INTO inventory_transactions (company_id, item_id, warehouse_id, doc_date, qty, unit_cost, source_type,
                                    source_id, source_line_id, source_no, reversal_of, created_by, lot_id, bin_id)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11, $12,
        $13, $14)
RETURNING id
`

type InsertInventoryTransactionParams struct {
	CompanyID    int64
	ItemID       int64
	WarehouseID  int64
	DocDate      time.Time
	Qty          decimal.Decimal
	UnitCost     *decimal.Decimal
	SourceType   string
	SourceID     int64
	SourceLineID *int64
	SourceNo     string
	ReversalOf   *int64
	CreatedBy    *int64
	LotID        *int64
	BinID        *int64
}

func (q *Queries) InsertInventoryTransaction(ctx context.Context, arg InsertInventoryTransactionParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertInventoryTransaction,
		arg.CompanyID,
		arg.ItemID,
		arg.WarehouseID,
		arg.DocDate,
		arg.Qty,
		arg.UnitCost,
		arg.SourceType,
		arg.SourceID,
		arg.SourceLineID,
		arg.SourceNo,
		arg.ReversalOf,
		arg.CreatedBy,
		arg.LotID,
		arg.BinID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const itemHasTransactions = `-- name: ItemHasTransactions :one
SELECT EXISTS (SELECT 1 FROM inventory_transactions WHERE item_id = $1)
`

func (q *Queries) ItemHasTransactions(ctx context.Context, itemID int64) (bool, error) {
	row := q.db.QueryRow(ctx, itemHasTransactions, itemID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const itemLedger = `-- name: ItemLedger :many
SELECT t.id, t.doc_date, t.qty, t.source_type, t.source_id, t.source_no, t.reversal_of, t.created_at,
       w.code AS warehouse_code, w.name AS warehouse_name,
       (SUM(t.qty) OVER (ORDER BY t.doc_date, t.id))::numeric AS running_qty
FROM inventory_transactions t
JOIN warehouses w ON w.id = t.warehouse_id
WHERE t.company_id = $1 AND t.item_id = $2
  AND t.doc_date >= $3 AND t.doc_date <= $4
  AND ($5::bigint IS NULL OR t.warehouse_id = $5)
ORDER BY t.doc_date, t.id
LIMIT 1000
`

type ItemLedgerParams struct {
	CompanyID   int64
	ItemID      int64
	FromDate    time.Time
	ToDate      time.Time
	WarehouseID *int64
}

type ItemLedgerRow struct {
	ID            int64
	DocDate       time.Time
	Qty           decimal.Decimal
	SourceType    string
	SourceID      int64
	SourceNo      string
	ReversalOf    *int64
	CreatedAt     time.Time
	WarehouseCode string
	WarehouseName string
	RunningQty    decimal.Decimal
}

// 料品異動明細與結存(結存 = 期初 + 依日期、序號累計)
func (q *Queries) ItemLedger(ctx context.Context, arg ItemLedgerParams) ([]ItemLedgerRow, error) {
	rows, err := q.db.Query(ctx, itemLedger,
		arg.CompanyID,
		arg.ItemID,
		arg.FromDate,
		arg.ToDate,
		arg.WarehouseID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemLedgerRow{}
	for rows.Next() {
		var i ItemLedgerRow
		if err := rows.Scan(
			&i.ID,
			&i.DocDate,
			&i.Qty,
			&i.SourceType,
			&i.SourceID,
			&i.SourceNo,
			&i.ReversalOf,
			&i.CreatedAt,
			&i.WarehouseCode,
			&i.WarehouseName,
			&i.RunningQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const itemLedgerOpening = `-- name: ItemLedgerOpening :one
SELECT COALESCE(SUM(qty), 0)::numeric FROM inventory_transactions
WHERE company_id = $1 AND item_id = $2 AND doc_date < $3
  AND ($4::bigint IS NULL OR warehouse_id = $4)
`

type ItemLedgerOpeningParams struct {
	CompanyID   int64
	ItemID      int64
	FromDate    time.Time
	WarehouseID *int64
}

func (q *Queries) ItemLedgerOpening(ctx context.Context, arg ItemLedgerOpeningParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, itemLedgerOpening,
		arg.CompanyID,
		arg.ItemID,
		arg.FromDate,
		arg.WarehouseID,
	)
	var column_1 decimal.Decimal
	err := row.Scan(&column_1)
	return column_1, err
}

const listBalances = `-- name: ListBalances :many
WITH RECURSIVE cats (cat_id) AS (
    SELECT item_categories.id FROM item_categories WHERE item_categories.id = $4::bigint
    UNION ALL
    SELECT item_categories.id FROM item_categories, cats WHERE item_categories.parent_id = cats.cat_id
)
SELECT b.item_id, b.warehouse_id, b.qty, b.updated_at,
       i.code AS item_code, i.name AS item_name, i.spec AS item_spec, i.safety_stock,
       u.name AS unit_name, w.code AS warehouse_code, w.name AS warehouse_name,
       (SELECT COALESCE(SUM(b2.qty), 0) FROM inventory_balances b2 WHERE b2.item_id = b.item_id)::numeric AS item_total
FROM inventory_balances b
JOIN items i ON i.id = b.item_id
JOIN units u ON u.id = i.base_unit_id
JOIN warehouses w ON w.id = b.warehouse_id
WHERE b.company_id = $1
  AND ($2::bigint IS NULL OR b.warehouse_id = $2)
  AND ($3::text IS NULL
       OR i.code ILIKE '%' || $3 || '%'
       OR i.name ILIKE '%' || $3 || '%')
  AND ($4::bigint IS NULL OR i.category_id IN (SELECT cat_id FROM cats))
  AND (NOT $5::boolean OR b.qty <> 0)
  -- 低於安全庫存:以料品在所有倉庫的合計判斷
  AND (NOT $6::boolean OR (i.safety_stock > 0 AND
       (SELECT COALESCE(SUM(b3.qty), 0) FROM inventory_balances b3 WHERE b3.item_id = b.item_id) < i.safety_stock))
ORDER BY i.code, w.code
LIMIT $8 OFFSET $7
`

type ListBalancesParams struct {
	CompanyID   int64
	WarehouseID *int64
	Keyword     *string
	CategoryID  *int64
	Nonzero     bool
	BelowSafety bool
	Off         int32
	Lim         int32
}

type ListBalancesRow struct {
	ItemID        int64
	WarehouseID   int64
	Qty           decimal.Decimal
	UpdatedAt     time.Time
	ItemCode      string
	ItemName      string
	ItemSpec      string
	SafetyStock   decimal.Decimal
	UnitName      string
	WarehouseCode string
	WarehouseName string
	ItemTotal     decimal.Decimal
}

func (q *Queries) ListBalances(ctx context.Context, arg ListBalancesParams) ([]ListBalancesRow, error) {
	rows, err := q.db.Query(ctx, listBalances,
		arg.CompanyID,
		arg.WarehouseID,
		arg.Keyword,
		arg.CategoryID,
		arg.Nonzero,
		arg.BelowSafety,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBalancesRow{}
	for rows.Next() {
		var i ListBalancesRow
		if err := rows.Scan(
			&i.ItemID,
			&i.WarehouseID,
			&i.Qty,
			&i.UpdatedAt,
			&i.ItemCode,
			&i.ItemName,
			&i.ItemSpec,
			&i.SafetyStock,
			&i.UnitName,
			&i.WarehouseCode,
			&i.WarehouseName,
			&i.ItemTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemUnitFactors = `-- name: ListItemUnitFactors :many
SELECT i.id AS item_id, i.base_unit_id AS unit_id, 1::numeric AS factor
FROM items i WHERE i.id = ANY($1::bigint[])
UNION ALL
SELECT iu.item_id, iu.unit_id, iu.factor FROM item_units iu WHERE iu.item_id = ANY($1::bigint[])
`

type ListItemUnitFactorsRow struct {
	ItemID int64
	UnitID int64
	Factor decimal.Decimal
}

// 料品可用的單位與換算倍數(基本單位倍數為 1)
func (q *Queries) ListItemUnitFactors(ctx context.Context, itemIds []int64) ([]ListItemUnitFactorsRow, error) {
	rows, err := q.db.Query(ctx, listItemUnitFactors, itemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemUnitFactorsRow{}
	for rows.Next() {
		var i ListItemUnitFactorsRow
		if err := rows.Scan(&i.ItemID, &i.UnitID, &i.Factor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenTransactionsBySource = `-- name: ListOpenTransactionsBySource :many
SELECT t.id, t.company_id, t.item_id, t.warehouse_id, t.doc_date, t.qty, t.unit_cost, t.source_type, t.source_id, t.source_line_id, t.source_no, t.reversal_of, t.created_by, t.created_at, t.lot_id, t.bin_id FROM inventory_transactions t
WHERE t.source_type = $1 AND t.source_id = $2 AND t.reversal_of IS NULL
  AND NOT EXISTS (SELECT 1 FROM inventory_transactions r WHERE r.reversal_of = t.id)
ORDER BY t.id
`

type ListOpenTransactionsBySourceParams struct {
	SourceType string
	SourceID   int64
}

// 某張單據尚未被沖銷的分錄(反過帳用)
func (q *Queries) ListOpenTransactionsBySource(ctx context.Context, arg ListOpenTransactionsBySourceParams) ([]InventoryTransaction, error) {
	rows, err := q.db.Query(ctx, listOpenTransactionsBySource, arg.SourceType, arg.SourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryTransaction{}
	for rows.Next() {
		var i InventoryTransaction
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.ItemID,
			&i.WarehouseID,
			&i.DocDate,
			&i.Qty,
			&i.UnitCost,
			&i.SourceType,
			&i.SourceID,
			&i.SourceLineID,
			&i.SourceNo,
			&i.ReversalOf,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LotID,
			&i.BinID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockItems = `-- name: ListStockItems :many
SELECT i.id, i.code, i.name, i.item_type, i.base_unit_id, i.is_active, i.lot_control
FROM items i
WHERE i.company_id = $1 AND i.id = ANY($2::bigint[])
`

type ListStockItemsParams struct {
	CompanyID int64
	Ids       []int64
}

type ListStockItemsRow struct {
	ID         int64
	Code       string
	Name       string
	ItemType   string
	BaseUnitID int64
	IsActive   bool
	LotControl string
}

// 過帳 / 開單時驗證料品:須屬同公司
func (q *Queries) ListStockItems(ctx context.Context, arg ListStockItemsParams) ([]ListStockItemsRow, error) {
	rows, err := q.db.Query(ctx, listStockItems, arg.CompanyID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStockItemsRow{}
	for rows.Next() {
		var i ListStockItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.ItemType,
			&i.BaseUnitID,
			&i.IsActive,
			&i.LotControl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWarehouseFlags = `-- name: ListWarehouseFlags :many
SELECT w.id, w.code, w.name, w.allow_negative, w.is_active, w.use_bins
FROM warehouses w
WHERE w.company_id = $1 AND w.id = ANY($2::bigint[])
`

type ListWarehouseFlagsParams struct {
	CompanyID int64
	Ids       []int64
}

type ListWarehouseFlagsRow struct {
	ID            int64
	Code          string
	Name          string
	AllowNegative bool
	IsActive      bool
	UseBins       bool
}

func (q *Queries) ListWarehouseFlags(ctx context.Context, arg ListWarehouseFlagsParams) ([]ListWarehouseFlagsRow, error) {
	rows, err := q.db.Query(ctx, listWarehouseFlags, arg.CompanyID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWarehouseFlagsRow{}
	for rows.Next() {
		var i ListWarehouseFlagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.AllowNegative,
			&i.IsActive,
			&i.UseBins,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBalance = `-- name: LockBalance :one
SELECT qty FROM inventory_balances WHERE item_id = $1 AND warehouse_id = $2 FOR UPDATE
`

type LockBalanceParams struct {
	ItemID      int64
	WarehouseID int64
}

func (q *Queries) LockBalance(ctx context.Context, arg LockBalanceParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, lockBalance, arg.ItemID, arg.WarehouseID)
	var qty decimal.Decimal
	err := row.Scan(&qty)
	return qty, err
}

const openCountDocNo = `-- name: OpenCountDocNo :one
SELECT sd.doc_no FROM stock_documents sd
WHERE sd.company_id = $1 AND sd.doc_type = 'count'
  AND sd.status IN ('draft', 'pending', 'approved')
  AND sd.warehouse_id = ANY($2::bigint[])
  AND sd.id <> $3::bigint
LIMIT 1
`

type OpenCountDocNoParams struct {
	CompanyID    int64
	WarehouseIds []int64
	ExcludeID    int64
}

// 指定倉庫是否有進行中的盤點單(盤點凍結)
func (q *Queries) OpenCountDocNo(ctx context.Context, arg OpenCountDocNoParams) (string, error) {
	row := q.db.QueryRow(ctx, openCountDocNo, arg.CompanyID, arg.WarehouseIds, arg.ExcludeID)
	var doc_no string
	err := row.Scan(&doc_no)
	return doc_no, err
}

const setBalance = `-- name: SetBalance :exec
UPDATE inventory_balances SET qty = $1, updated_at = now()
WHERE item_id = $2 AND warehouse_id = $3
`

type SetBalanceParams struct {
	Qty         decimal.Decimal
	ItemID      int64
	WarehouseID int64
}

func (q *Queries) SetBalance(ctx context.Context, arg SetBalanceParams) error {
	_, err := q.db.Exec(ctx, setBalance, arg.Qty, arg.ItemID, arg.WarehouseID)
	return err
}

const stockMovementSummary = `-- name: StockMovementSummary :many
SELECT t.item_id, i.code AS item_code, i.name AS item_name, u.name AS unit_name,
       COALESCE(SUM(t.qty) FILTER (WHERE t.doc_date < $1), 0)::numeric AS opening_qty,
       COALESCE(SUM(t.qty) FILTER (WHERE t.doc_date >= $1 AND (
           (t.reversal_of IS NULL AND t.qty > 0) OR (t.reversal_of IS NOT NULL AND t.qty < 0))), 0)::numeric AS in_qty,
       COALESCE(-SUM(t.qty) FILTER (WHERE t.doc_date >= $1 AND (
           (t.reversal_of IS NULL AND t.qty < 0) OR (t.reversal_of IS NOT NULL AND t.qty > 0))), 0)::numeric AS out_qty,
       COALESCE(SUM(t.qty), 0)::numeric AS closing_qty
FROM inventory_transactions t
JOIN items i ON i.id = t.item_id
JOIN units u ON u.id = i.base_unit_id
WHERE t.company_id = $2
  AND t.doc_date <= $3
  AND ($4::bigint IS NULL OR t.warehouse_id = $4)
  AND ($5::text IS NULL
       OR i.code ILIKE '%' || $5 || '%'
       OR i.name ILIKE '%' || $5 || '%')
GROUP BY t.item_id, i.code, i.name, u.name
ORDER BY i.code
LIMIT $7 OFFSET $6
`

type StockMovementSummaryParams struct {
	FromDate    time.Time
	CompanyID   int64
	ToDate      time.Time
	WarehouseID *int64
	Keyword     *string
	Off         int32
	Lim         int32
}

type StockMovementSummaryRow struct {
	ItemID     int64
	ItemCode   string
	ItemName   string
	UnitName   string
	OpeningQty decimal.Decimal
	InQty      decimal.Decimal
	OutQty     decimal.Decimal
	ClosingQty decimal.Decimal
}

// 收發存:期初、本期收、本期發、期末(依單據日期)。
// 反向分錄依「原始分錄方向」歸類,沖銷後收發相互抵銷,不會同時多出一筆收與一筆發。
func (q *Queries) StockMovementSummary(ctx context.Context, arg StockMovementSummaryParams) ([]StockMovementSummaryRow, error) {
	rows, err := q.db.Query(ctx, stockMovementSummary,
		arg.FromDate,
		arg.CompanyID,
		arg.ToDate,
		arg.WarehouseID,
		arg.Keyword,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StockMovementSummaryRow{}
	for rows.Next() {
		var i StockMovementSummaryRow
		if err := rows.Scan(
			&i.ItemID,
			&i.ItemCode,
			&i.ItemName,
			&i.UnitName,
			&i.OpeningQty,
			&i.InQty,
			&i.OutQty,
			&i.ClosingQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
