// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package db

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const addItemUnit = `-- name: AddItemUnit :exec
INSERT INTO item_units (item_id, unit_id, factor, barcode)
VALUES ($1, $2, $3, $4)
`

type AddItemUnitParams struct {
	ItemID  int64
	UnitID  int64
	Factor  decimal.Decimal
	Barcode *string
}

func (q *Queries) AddItemUnit(ctx context.Context, arg AddItemUnitParams) error {
	_, err := q.db.Exec(ctx, addItemUnit,
		arg.ItemID,
		arg.UnitID,
		arg.Factor,
		arg.Barcode,
	)
	return err
}

const checkItemRefs = `-- name: CheckItemRefs :one
SELECT
    COALESCE($1::bigint IS NULL OR EXISTS (
        SELECT 1 FROM item_categories ic
        WHERE ic.id = $1::bigint AND ic.company_id = $2::bigint), FALSE)::boolean AS category_ok,
    EXISTS (
        SELECT 1 FROM units un
        WHERE un.id = $3::bigint AND un.company_id = $2::bigint) AS base_unit_ok,
    COALESCE($4::bigint IS NULL OR EXISTS (
        SELECT 1 FROM tax_types tt
        WHERE tt.id = $4::bigint AND tt.company_id = $2::bigint), FALSE)::boolean AS tax_type_ok,
    COALESCE($5::bigint IS NULL OR EXISTS (
        SELECT 1 FROM warehouses wh
        WHERE wh.id = $5::bigint AND wh.company_id = $2::bigint), FALSE)::boolean AS warehouse_ok
`

type CheckItemRefsParams struct {
	CategoryID  *int64
	CompanyID   int64
	BaseUnitID  int64
	TaxTypeID   *int64
	WarehouseID *int64
}

type CheckItemRefsRow struct {
	CategoryOk  bool
	BaseUnitOk  bool
	TaxTypeOk   bool
	WarehouseOk bool
}

// 參照的資料須存在且屬於同公司;未指定(NULL)視為通過
func (q *Queries) CheckItemRefs(ctx context.Context, arg CheckItemRefsParams) (CheckItemRefsRow, error) {
	row := q.db.QueryRow(ctx, checkItemRefs,
		arg.CategoryID,
		arg.CompanyID,
		arg.BaseUnitID,
		arg.TaxTypeID,
		arg.WarehouseID,
	)
	var i CheckItemRefsRow
	err := row.Scan(
		&i.CategoryOk,
		&i.BaseUnitOk,
		&i.TaxTypeOk,
		&i.WarehouseOk,
	)
	return i, err
}

const countItems = `-- name: CountItems :one
WITH RECURSIVE cats (cat_id) AS (
    SELECT item_categories.id FROM item_categories WHERE item_categories.id = $3::bigint
    UNION ALL
    SELECT item_categories.id FROM item_categories, cats WHERE item_categories.parent_id = cats.cat_id
)
SELECT count(*)
FROM items i
WHERE i.company_id = $1
  AND ($2::text IS NULL
       OR i.code ILIKE '%' || $2 || '%'
       OR i.name ILIKE '%' || $2 || '%'
       OR i.spec ILIKE '%' || $2 || '%'
       OR i.barcode = $2)
  AND ($3::bigint IS NULL OR i.category_id IN (SELECT cat_id FROM cats))
  AND ($4::text IS NULL OR i.item_type = $4)
  AND ($5::boolean IS NULL OR i.is_active = $5)
`

type CountItemsParams struct {
	CompanyID  int64
	Keyword    *string
	CategoryID *int64
	ItemType   *string
	IsActive   *bool
}

func (q *Queries) CountItems(ctx context.Context, arg CountItemsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countItems,
		arg.CompanyID,
		arg.Keyword,
		arg.CategoryID,
		arg.ItemType,
		arg.IsActive,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createItem = `-- name: CreateItem :one
INSERT INTO items (company_id, code, name, spec, category_id, item_type, base_unit_id, barcode,
                   tax_type_id, default_warehouse_id, safety_stock, list_price, note, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        $9, $10, $11, $12, $13,
        $14, $14)
RETURNING id, company_id, code, name, spec, category_id, item_type, base_unit_id, barcode, tax_type_id, default_warehouse_id, safety_stock, list_price, note, is_active, created_by, updated_by, version, created_at, updated_at
`

type CreateItemParams struct {
	CompanyID          int64
	Code               string
	Name               string
	Spec               string
	CategoryID         *int64
	ItemType           string
	BaseUnitID         int64
	Barcode            *string
	TaxTypeID          *int64
	DefaultWarehouseID *int64
	SafetyStock        decimal.Decimal
	ListPrice          decimal.Decimal
	Note               string
	CreatedBy          *int64
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.CompanyID,
		arg.Code,
		arg.Name,
		arg.Spec,
		arg.CategoryID,
		arg.ItemType,
		arg.BaseUnitID,
		arg.Barcode,
		arg.TaxTypeID,
		arg.DefaultWarehouseID,
		arg.SafetyStock,
		arg.ListPrice,
		arg.Note,
		arg.CreatedBy,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.Name,
		&i.Spec,
		&i.CategoryID,
		&i.ItemType,
		&i.BaseUnitID,
		&i.Barcode,
		&i.TaxTypeID,
		&i.DefaultWarehouseID,
		&i.SafetyStock,
		&i.ListPrice,
		&i.Note,
		&i.IsActive,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteItemUnits = `-- name: DeleteItemUnits :exec
DELETE FROM item_units WHERE item_id = $1
`

func (q *Queries) DeleteItemUnits(ctx context.Context, itemID int64) error {
	_, err := q.db.Exec(ctx, deleteItemUnits, itemID)
	return err
}

const getItem = `-- name: GetItem :one
SELECT id, company_id, code, name, spec, category_id, item_type, base_unit_id, barcode, tax_type_id, default_warehouse_id, safety_stock, list_price, note, is_active, created_by, updated_by, version, created_at, updated_at FROM items WHERE id = $1 AND company_id = $2
`

type GetItemParams struct {
	ID        int64
	CompanyID int64
}

func (q *Queries) GetItem(ctx context.Context, arg GetItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, getItem, arg.ID, arg.CompanyID)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.Name,
		&i.Spec,
		&i.CategoryID,
		&i.ItemType,
		&i.BaseUnitID,
		&i.Barcode,
		&i.TaxTypeID,
		&i.DefaultWarehouseID,
		&i.SafetyStock,
		&i.ListPrice,
		&i.Note,
		&i.IsActive,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listItemUnits = `-- name: ListItemUnits :many
SELECT iu.item_id, iu.unit_id, iu.factor, iu.barcode, u.code AS unit_code, u.name AS unit_name
FROM item_units iu
JOIN units u ON u.id = iu.unit_id
WHERE iu.item_id = ANY($1::bigint[])
ORDER BY iu.item_id, iu.factor
`

type ListItemUnitsRow struct {
	ItemID   int64
	UnitID   int64
	Factor   decimal.Decimal
	Barcode  *string
	UnitCode string
	UnitName string
}

func (q *Queries) ListItemUnits(ctx context.Context, itemIds []int64) ([]ListItemUnitsRow, error) {
	rows, err := q.db.Query(ctx, listItemUnits, itemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemUnitsRow{}
	for rows.Next() {
		var i ListItemUnitsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.UnitID,
			&i.Factor,
			&i.Barcode,
			&i.UnitCode,
			&i.UnitName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
WITH RECURSIVE cats (cat_id) AS (
    SELECT item_categories.id FROM item_categories WHERE item_categories.id = $3::bigint
    UNION ALL
    SELECT item_categories.id FROM item_categories, cats WHERE item_categories.parent_id = cats.cat_id
)
SELECT i.id, i.company_id, i.code, i.name, i.spec, i.category_id, i.item_type, i.base_unit_id, i.barcode, i.tax_type_id, i.default_warehouse_id, i.safety_stock, i.list_price, i.note, i.is_active, i.created_by, i.updated_by, i.version, i.created_at, i.updated_at, c.name AS category_name, u.name AS base_unit_name
FROM items i
LEFT JOIN item_categories c ON c.id = i.category_id
JOIN units u ON u.id = i.base_unit_id
WHERE i.company_id = $1
  AND ($2::text IS NULL
       OR i.code ILIKE '%' || $2 || '%'
       OR i.name ILIKE '%' || $2 || '%'
       OR i.spec ILIKE '%' || $2 || '%'
       OR i.barcode = $2)
  AND ($3::bigint IS NULL OR i.category_id IN (SELECT cat_id FROM cats))
  AND ($4::text IS NULL OR i.item_type = $4)
  AND ($5::boolean IS NULL OR i.is_active = $5)
ORDER BY i.code
LIMIT $7 OFFSET $6
`

type ListItemsParams struct {
	CompanyID  int64
	Keyword    *string
	CategoryID *int64
	ItemType   *string
	IsActive   *bool
	Off        int32
	Lim        int32
}

type ListItemsRow struct {
	ID                 int64
	CompanyID          int64
	Code               string
	Name               string
	Spec               string
	CategoryID         *int64
	ItemType           string
	BaseUnitID         int64
	Barcode            *string
	TaxTypeID          *int64
	DefaultWarehouseID *int64
	SafetyStock        decimal.Decimal
	ListPrice          decimal.Decimal
	Note               string
	IsActive           bool
	CreatedBy          *int64
	UpdatedBy          *int64
	Version            int32
	CreatedAt          time.Time
	UpdatedAt          time.Time
	CategoryName       *string
	BaseUnitName       string
}

// category_id 篩選包含所有下層分類
func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]ListItemsRow, error) {
	rows, err := q.db.Query(ctx, listItems,
		arg.CompanyID,
		arg.Keyword,
		arg.CategoryID,
		arg.ItemType,
		arg.IsActive,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemsRow{}
	for rows.Next() {
		var i ListItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Code,
			&i.Name,
			&i.Spec,
			&i.CategoryID,
			&i.ItemType,
			&i.BaseUnitID,
			&i.Barcode,
			&i.TaxTypeID,
			&i.DefaultWarehouseID,
			&i.SafetyStock,
			&i.ListPrice,
			&i.Note,
			&i.IsActive,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.BaseUnitName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItem = `-- name: UpdateItem :one
UPDATE items
SET code = $1, name = $2, spec = $3, category_id = $4, item_type = $5,
    base_unit_id = $6, barcode = $7, tax_type_id = $8,
    default_warehouse_id = $9, safety_stock = $10,
    list_price = $11, note = $12, is_active = $13,
    version = version + 1, updated_by = $14
WHERE id = $15 AND company_id = $16 AND version = $17
RETURNING id, company_id, code, name, spec, category_id, item_type, base_unit_id, barcode, tax_type_id, default_warehouse_id, safety_stock, list_price, note, is_active, created_by, updated_by, version, created_at, updated_at
`

type UpdateItemParams struct {
	Code               string
	Name               string
	Spec               string
	CategoryID         *int64
	ItemType           string
	BaseUnitID         int64
	Barcode            *string
	TaxTypeID          *int64
	DefaultWarehouseID *int64
	SafetyStock        decimal.Decimal
	ListPrice          decimal.Decimal
	Note               string
	IsActive           bool
	UpdatedBy          *int64
	ID                 int64
	CompanyID          int64
	Version            int32
}

// 基本單位不在此修改:已有異動後改基本單位會讓歷史數量失真(M2 起由庫存模組把關)
func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItem,
		arg.Code,
		arg.Name,
		arg.Spec,
		arg.CategoryID,
		arg.ItemType,
		arg.BaseUnitID,
		arg.Barcode,
		arg.TaxTypeID,
		arg.DefaultWarehouseID,
		arg.SafetyStock,
		arg.ListPrice,
		arg.Note,
		arg.IsActive,
		arg.UpdatedBy,
		arg.ID,
		arg.CompanyID,
		arg.Version,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.Name,
		&i.Spec,
		&i.CategoryID,
		&i.ItemType,
		&i.BaseUnitID,
		&i.Barcode,
		&i.TaxTypeID,
		&i.DefaultWarehouseID,
		&i.SafetyStock,
		&i.ListPrice,
		&i.Note,
		&i.IsActive,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
