// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lots.sql

package db

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const countLotBalances = `-- name: CountLotBalances :one
SELECT count(*) FROM inventory_lot_balances b
JOIN item_lots l ON l.id = b.lot_id
JOIN items i ON i.id = b.item_id
WHERE b.company_id = $1
  AND ($2::bigint IS NULL OR b.item_id = $2)
  AND ($3::bigint IS NULL OR b.warehouse_id = $3)
  AND ($4::text IS NULL OR l.lot_no ILIKE '%' || $4 || '%'
       OR i.code ILIKE '%' || $4 || '%' OR i.name ILIKE '%' || $4 || '%')
  AND ($5::boolean OR b.qty > 0)
  AND ($6::text = ''
       OR ($6::text = 'expired' AND l.expiry_date < $7::date)
       OR ($6::text = 'expiring' AND l.expiry_date >= $7::date AND l.expiry_date <= $8::date))
`

type CountLotBalancesParams struct {
	CompanyID   int64
	ItemID      *int64
	WarehouseID *int64
	Keyword     *string
	IncludeZero bool
	ExpiryMode  string
	Today       time.Time
	Until       time.Time
}

func (q *Queries) CountLotBalances(ctx context.Context, arg CountLotBalancesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLotBalances,
		arg.CompanyID,
		arg.ItemID,
		arg.WarehouseID,
		arg.Keyword,
		arg.IncludeZero,
		arg.ExpiryMode,
		arg.Today,
		arg.Until,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLotBinSnapshot = `-- name: CountLotBinSnapshot :many
SELECT b.item_id, l.lot_no, l.expiry_date, bn.code AS bin_code, b.qty
FROM inventory_lot_bin_balances b
JOIN item_lots l ON l.id = b.lot_id
JOIN bins bn ON bn.id = b.bin_id
WHERE b.company_id = $1 AND b.warehouse_id = $2 AND b.item_id = ANY($3::bigint[]) AND b.qty > 0
ORDER BY b.item_id, l.expiry_date NULLS LAST, l.id, bn.code
`

type CountLotBinSnapshotParams struct {
	CompanyID   int64
	WarehouseID int64
	ItemIds     []int64
}

type CountLotBinSnapshotRow struct {
	ItemID     int64
	LotNo      string
	ExpiryDate *time.Time
	BinCode    string
	Qty        decimal.Decimal
}

// 啟用儲位的倉庫:批號管理料品的盤點快照,依(批號, 儲位)逐筆
func (q *Queries) CountLotBinSnapshot(ctx context.Context, arg CountLotBinSnapshotParams) ([]CountLotBinSnapshotRow, error) {
	rows, err := q.db.Query(ctx, countLotBinSnapshot, arg.CompanyID, arg.WarehouseID, arg.ItemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountLotBinSnapshotRow{}
	for rows.Next() {
		var i CountLotBinSnapshotRow
		if err := rows.Scan(
			&i.ItemID,
			&i.LotNo,
			&i.ExpiryDate,
			&i.BinCode,
			&i.Qty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ensureLotBalance = `-- name: EnsureLotBalance :exec
INSERT INTO inventory_lot_balances (company_id, item_id, warehouse_id, lot_id, qty)
VALUES ($1, $2, $3, $4, 0)
ON CONFLICT (lot_id, warehouse_id) DO NOTHING
`

type EnsureLotBalanceParams struct {
	CompanyID   int64
	ItemID      int64
	WarehouseID int64
	LotID       int64
}

func (q *Queries) EnsureLotBalance(ctx context.Context, arg EnsureLotBalanceParams) error {
	_, err := q.db.Exec(ctx, ensureLotBalance,
		arg.CompanyID,
		arg.ItemID,
		arg.WarehouseID,
		arg.LotID,
	)
	return err
}

const ensureLotBinBalance = `-- name: EnsureLotBinBalance :exec
INSERT INTO inventory_lot_bin_balances (company_id, item_id, warehouse_id, lot_id, bin_id, qty)
VALUES ($1, $2, $3, $4, $5, 0)
ON CONFLICT (lot_id, bin_id) DO NOTHING
`

type EnsureLotBinBalanceParams struct {
	CompanyID   int64
	ItemID      int64
	WarehouseID int64
	LotID       int64
	BinID       int64
}

func (q *Queries) EnsureLotBinBalance(ctx context.Context, arg EnsureLotBinBalanceParams) error {
	_, err := q.db.Exec(ctx, ensureLotBinBalance,
		arg.CompanyID,
		arg.ItemID,
		arg.WarehouseID,
		arg.LotID,
		arg.BinID,
	)
	return err
}

const findOrCreateLot = `-- name: FindOrCreateLot :one

INSERT INTO item_lots (company_id, item_id, lot_no, expiry_date)
VALUES ($1, $2, $3, $4)
ON CONFLICT (company_id, item_id, lot_no) DO UPDATE SET lot_no = item_lots.lot_no
RETURNING id, company_id, item_id, lot_no, expiry_date, created_at
`

type FindOrCreateLotParams struct {
	CompanyID  int64
	ItemID     int64
	LotNo      string
	ExpiryDate *time.Time
}

// ======== 批號與效期(D63) ========
func (q *Queries) FindOrCreateLot(ctx context.Context, arg FindOrCreateLotParams) (ItemLot, error) {
	row := q.db.QueryRow(ctx, findOrCreateLot,
		arg.CompanyID,
		arg.ItemID,
		arg.LotNo,
		arg.ExpiryDate,
	)
	var i ItemLot
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ItemID,
		&i.LotNo,
		&i.ExpiryDate,
		&i.CreatedAt,
	)
	return i, err
}

const getLot = `-- name: GetLot :one
SELECT id, company_id, item_id, lot_no, expiry_date, created_at FROM item_lots WHERE id = $1 AND company_id = $2
`

type GetLotParams struct {
	ID        int64
	CompanyID int64
}

func (q *Queries) GetLot(ctx context.Context, arg GetLotParams) (ItemLot, error) {
	row := q.db.QueryRow(ctx, getLot, arg.ID, arg.CompanyID)
	var i ItemLot
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ItemID,
		&i.LotNo,
		&i.ExpiryDate,
		&i.CreatedAt,
	)
	return i, err
}

const getLotBinBalanceQtyByNo = `-- name: GetLotBinBalanceQtyByNo :one
SELECT COALESCE((SELECT b.qty FROM inventory_lot_bin_balances b
                 JOIN item_lots l ON l.id = b.lot_id JOIN bins bn ON bn.id = b.bin_id
                 WHERE l.company_id = $1 AND l.item_id = $2 AND l.lot_no = $3
                   AND bn.warehouse_id = $4 AND bn.code = $5), 0)::numeric
`

type GetLotBinBalanceQtyByNoParams struct {
	CompanyID   int64
	ItemID      int64
	LotNo       string
	WarehouseID int64
	Code        string
}

// 某批號在某儲位的現有量(不存在為 0)
func (q *Queries) GetLotBinBalanceQtyByNo(ctx context.Context, arg GetLotBinBalanceQtyByNoParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, getLotBinBalanceQtyByNo,
		arg.CompanyID,
		arg.ItemID,
		arg.LotNo,
		arg.WarehouseID,
		arg.Code,
	)
	var column_1 decimal.Decimal
	err := row.Scan(&column_1)
	return column_1, err
}

const getLotByNo = `-- name: GetLotByNo :one
SELECT id, company_id, item_id, lot_no, expiry_date, created_at FROM item_lots WHERE company_id = $1 AND item_id = $2 AND lot_no = $3
`

type GetLotByNoParams struct {
	CompanyID int64
	ItemID    int64
	LotNo     string
}

func (q *Queries) GetLotByNo(ctx context.Context, arg GetLotByNoParams) (ItemLot, error) {
	row := q.db.QueryRow(ctx, getLotByNo, arg.CompanyID, arg.ItemID, arg.LotNo)
	var i ItemLot
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ItemID,
		&i.LotNo,
		&i.ExpiryDate,
		&i.CreatedAt,
	)
	return i, err
}

const getLotDetail = `-- name: GetLotDetail :one
SELECT l.id, l.company_id, l.item_id, l.lot_no, l.expiry_date, l.created_at, i.code AS item_code, i.name AS item_name, i.spec AS item_spec, i.lot_control
FROM item_lots l JOIN items i ON i.id = l.item_id
WHERE l.id = $1 AND l.company_id = $2
`

type GetLotDetailParams struct {
	ID        int64
	CompanyID int64
}

type GetLotDetailRow struct {
	ID         int64
	CompanyID  int64
	ItemID     int64
	LotNo      string
	ExpiryDate *time.Time
	CreatedAt  time.Time
	ItemCode   string
	ItemName   string
	ItemSpec   string
	LotControl string
}

func (q *Queries) GetLotDetail(ctx context.Context, arg GetLotDetailParams) (GetLotDetailRow, error) {
	row := q.db.QueryRow(ctx, getLotDetail, arg.ID, arg.CompanyID)
	var i GetLotDetailRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ItemID,
		&i.LotNo,
		&i.ExpiryDate,
		&i.CreatedAt,
		&i.ItemCode,
		&i.ItemName,
		&i.ItemSpec,
		&i.LotControl,
	)
	return i, err
}

const listItemLots = `-- name: ListItemLots :many
SELECT l.id, l.lot_no, l.expiry_date FROM item_lots l
WHERE l.company_id = $1 AND l.item_id = $2
ORDER BY l.expiry_date NULLS LAST, l.id DESC LIMIT 50
`

type ListItemLotsParams struct {
	CompanyID int64
	ItemID    int64
}

type ListItemLotsRow struct {
	ID         int64
	LotNo      string
	ExpiryDate *time.Time
}

// 料品所有已建立的批號(不論有無庫存),供輸入批號時參考
func (q *Queries) ListItemLots(ctx context.Context, arg ListItemLotsParams) ([]ListItemLotsRow, error) {
	rows, err := q.db.Query(ctx, listItemLots, arg.CompanyID, arg.ItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemLotsRow{}
	for rows.Next() {
		var i ListItemLotsRow
		if err := rows.Scan(&i.ID, &i.LotNo, &i.ExpiryDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLotBalances = `-- name: ListLotBalances :many
SELECT b.lot_id, l.lot_no, l.expiry_date, b.item_id, i.code AS item_code, i.name AS item_name, i.spec AS item_spec,
       bu.name AS unit_name, b.warehouse_id, w.code AS warehouse_code, w.name AS warehouse_name, b.qty
FROM inventory_lot_balances b
JOIN item_lots l ON l.id = b.lot_id
JOIN items i ON i.id = b.item_id
JOIN units bu ON bu.id = i.base_unit_id
JOIN warehouses w ON w.id = b.warehouse_id
WHERE b.company_id = $1
  AND ($2::bigint IS NULL OR b.item_id = $2)
  AND ($3::bigint IS NULL OR b.warehouse_id = $3)
  AND ($4::text IS NULL OR l.lot_no ILIKE '%' || $4 || '%'
       OR i.code ILIKE '%' || $4 || '%' OR i.name ILIKE '%' || $4 || '%')
  AND ($5::boolean OR b.qty > 0)
  AND ($6::text = ''
       OR ($6::text = 'expired' AND l.expiry_date < $7::date)
       OR ($6::text = 'expiring' AND l.expiry_date >= $7::date AND l.expiry_date <= $8::date))
ORDER BY l.expiry_date NULLS LAST, i.code, l.lot_no, w.code
LIMIT $10 OFFSET $9
`

type ListLotBalancesParams struct {
	CompanyID   int64
	ItemID      *int64
	WarehouseID *int64
	Keyword     *string
	IncludeZero bool
	ExpiryMode  string
	Today       time.Time
	Until       time.Time
	Off         int32
	Lim         int32
}

type ListLotBalancesRow struct {
	LotID         int64
	LotNo         string
	ExpiryDate    *time.Time
	ItemID        int64
	ItemCode      string
	ItemName      string
	ItemSpec      string
	UnitName      string
	WarehouseID   int64
	WarehouseCode string
	WarehouseName string
	Qty           decimal.Decimal
}

// 批號庫存:依效期排序;expiry_mode 為 expired(已過期)、expiring(today 到 until 內到期)或空白(全部)
func (q *Queries) ListLotBalances(ctx context.Context, arg ListLotBalancesParams) ([]ListLotBalancesRow, error) {
	rows, err := q.db.Query(ctx, listLotBalances,
		arg.CompanyID,
		arg.ItemID,
		arg.WarehouseID,
		arg.Keyword,
		arg.IncludeZero,
		arg.ExpiryMode,
		arg.Today,
		arg.Until,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLotBalancesRow{}
	for rows.Next() {
		var i ListLotBalancesRow
		if err := rows.Scan(
			&i.LotID,
			&i.LotNo,
			&i.ExpiryDate,
			&i.ItemID,
			&i.ItemCode,
			&i.ItemName,
			&i.ItemSpec,
			&i.UnitName,
			&i.WarehouseID,
			&i.WarehouseCode,
			&i.WarehouseName,
			&i.Qty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLotBalancesForAllocation = `-- name: ListLotBalancesForAllocation :many
SELECT b.lot_id, b.qty, l.lot_no, l.expiry_date
FROM inventory_lot_balances b JOIN item_lots l ON l.id = b.lot_id
WHERE b.item_id = $1 AND b.warehouse_id = $2 AND b.qty > 0
ORDER BY l.expiry_date NULLS LAST, l.id
FOR UPDATE OF b
`

type ListLotBalancesForAllocationParams struct {
	ItemID      int64
	WarehouseID int64
}

type ListLotBalancesForAllocationRow struct {
	LotID      int64
	Qty        decimal.Decimal
	LotNo      string
	ExpiryDate *time.Time
}

// 先到期先出:有庫存的批號依效期由近到遠(沒有效期的排最後),同效期依批號建立順序;鎖定這些列
func (q *Queries) ListLotBalancesForAllocation(ctx context.Context, arg ListLotBalancesForAllocationParams) ([]ListLotBalancesForAllocationRow, error) {
	rows, err := q.db.Query(ctx, listLotBalancesForAllocation, arg.ItemID, arg.WarehouseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLotBalancesForAllocationRow{}
	for rows.Next() {
		var i ListLotBalancesForAllocationRow
		if err := rows.Scan(
			&i.LotID,
			&i.Qty,
			&i.LotNo,
			&i.ExpiryDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLotBinBalancesForAllocation = `-- name: ListLotBinBalancesForAllocation :many
SELECT b.lot_id, b.bin_id, b.qty, l.lot_no, l.expiry_date, bn.code AS bin_code
FROM inventory_lot_bin_balances b
JOIN item_lots l ON l.id = b.lot_id
JOIN bins bn ON bn.id = b.bin_id
WHERE b.item_id = $1 AND b.warehouse_id = $2 AND b.qty > 0
ORDER BY l.expiry_date NULLS LAST, l.id, b.qty DESC, bn.code
FOR UPDATE OF b
`

type ListLotBinBalancesForAllocationParams struct {
	ItemID      int64
	WarehouseID int64
}

type ListLotBinBalancesForAllocationRow struct {
	LotID      int64
	BinID      int64
	Qty        decimal.Decimal
	LotNo      string
	ExpiryDate *time.Time
	BinCode    string
}

// 啟用儲位的倉庫出庫:先到期先出(批號依效期,沒有效期的排最後);同一批號內庫存多的儲位先出。鎖定這些列
func (q *Queries) ListLotBinBalancesForAllocation(ctx context.Context, arg ListLotBinBalancesForAllocationParams) ([]ListLotBinBalancesForAllocationRow, error) {
	rows, err := q.db.Query(ctx, listLotBinBalancesForAllocation, arg.ItemID, arg.WarehouseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLotBinBalancesForAllocationRow{}
	for rows.Next() {
		var i ListLotBinBalancesForAllocationRow
		if err := rows.Scan(
			&i.LotID,
			&i.BinID,
			&i.Qty,
			&i.LotNo,
			&i.ExpiryDate,
			&i.BinCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLotBinStock = `-- name: ListLotBinStock :many
SELECT bn.code AS bin_code, bn.name AS bin_name, b.warehouse_id, b.qty
FROM inventory_lot_bin_balances b JOIN bins bn ON bn.id = b.bin_id
WHERE b.company_id = $1 AND b.lot_id = $2 AND b.qty > 0
ORDER BY b.warehouse_id, bn.code
`

type ListLotBinStockParams struct {
	CompanyID int64
	LotID     int64
}

type ListLotBinStockRow struct {
	BinCode     string
	BinName     string
	WarehouseID int64
	Qty         decimal.Decimal
}

// 某批號在各儲位的現有量
func (q *Queries) ListLotBinStock(ctx context.Context, arg ListLotBinStockParams) ([]ListLotBinStockRow, error) {
	rows, err := q.db.Query(ctx, listLotBinStock, arg.CompanyID, arg.LotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLotBinStockRow{}
	for rows.Next() {
		var i ListLotBinStockRow
		if err := rows.Scan(
			&i.BinCode,
			&i.BinName,
			&i.WarehouseID,
			&i.Qty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLotOptions = `-- name: ListLotOptions :many
SELECT b.lot_id, l.lot_no, l.expiry_date, b.qty
FROM inventory_lot_balances b JOIN item_lots l ON l.id = b.lot_id
WHERE b.company_id = $1 AND b.item_id = $2 AND b.warehouse_id = $3 AND b.qty > 0
ORDER BY l.expiry_date NULLS LAST, l.id
`

type ListLotOptionsParams struct {
	CompanyID   int64
	ItemID      int64
	WarehouseID int64
}

type ListLotOptionsRow struct {
	LotID      int64
	LotNo      string
	ExpiryDate *time.Time
	Qty        decimal.Decimal
}

// 開單挑選批號:某倉庫有庫存的批號(先到期先出的順序)
func (q *Queries) ListLotOptions(ctx context.Context, arg ListLotOptionsParams) ([]ListLotOptionsRow, error) {
	rows, err := q.db.Query(ctx, listLotOptions, arg.CompanyID, arg.ItemID, arg.WarehouseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLotOptionsRow{}
	for rows.Next() {
		var i ListLotOptionsRow
		if err := rows.Scan(
			&i.LotID,
			&i.LotNo,
			&i.ExpiryDate,
			&i.Qty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLotsByIDs = `-- name: ListLotsByIDs :many
SELECT id, company_id, item_id, lot_no, expiry_date, created_at FROM item_lots WHERE id = ANY($1::bigint[])
`

func (q *Queries) ListLotsByIDs(ctx context.Context, ids []int64) ([]ItemLot, error) {
	rows, err := q.db.Query(ctx, listLotsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemLot{}
	for rows.Next() {
		var i ItemLot
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.ItemID,
			&i.LotNo,
			&i.ExpiryDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenLotTransactionsBySource = `-- name: ListOpenLotTransactionsBySource :many
SELECT t.source_line_id, t.qty, l.lot_no, l.expiry_date
FROM inventory_transactions t JOIN item_lots l ON l.id = t.lot_id
WHERE t.source_type = $1 AND t.source_id = $2 AND t.reversal_of IS NULL
  AND NOT EXISTS (SELECT 1 FROM inventory_transactions r WHERE r.reversal_of = t.id)
ORDER BY t.id
`

type ListOpenLotTransactionsBySourceParams struct {
	SourceType string
	SourceID   int64
}

type ListOpenLotTransactionsBySourceRow struct {
	SourceLineID *int64
	Qty          decimal.Decimal
	LotNo        string
	ExpiryDate   *time.Time
}

// 某張單據尚未被沖銷的批號分錄(單據上顯示實際出了哪些批號)
func (q *Queries) ListOpenLotTransactionsBySource(ctx context.Context, arg ListOpenLotTransactionsBySourceParams) ([]ListOpenLotTransactionsBySourceRow, error) {
	rows, err := q.db.Query(ctx, listOpenLotTransactionsBySource, arg.SourceType, arg.SourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenLotTransactionsBySourceRow{}
	for rows.Next() {
		var i ListOpenLotTransactionsBySourceRow
		if err := rows.Scan(
			&i.SourceLineID,
			&i.Qty,
			&i.LotNo,
			&i.ExpiryDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLotBalance = `-- name: LockLotBalance :one
SELECT qty FROM inventory_lot_balances WHERE lot_id = $1 AND warehouse_id = $2 FOR UPDATE
`

type LockLotBalanceParams struct {
	LotID       int64
	WarehouseID int64
}

func (q *Queries) LockLotBalance(ctx context.Context, arg LockLotBalanceParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, lockLotBalance, arg.LotID, arg.WarehouseID)
	var qty decimal.Decimal
	err := row.Scan(&qty)
	return qty, err
}

const lockLotBinBalance = `-- name: LockLotBinBalance :one
SELECT qty FROM inventory_lot_bin_balances WHERE lot_id = $1 AND bin_id = $2 FOR UPDATE
`

type LockLotBinBalanceParams struct {
	LotID int64
	BinID int64
}

func (q *Queries) LockLotBinBalance(ctx context.Context, arg LockLotBinBalanceParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, lockLotBinBalance, arg.LotID, arg.BinID)
	var qty decimal.Decimal
	err := row.Scan(&qty)
	return qty, err
}

const lotBinBalanceMismatches = `-- name: LotBinBalanceMismatches :one
SELECT (
    (SELECT count(*) FROM (
        SELECT b.lot_id, b.warehouse_id FROM inventory_lot_balances b JOIN warehouses w ON w.id = b.warehouse_id
        LEFT JOIN (SELECT lb.lot_id, lb.warehouse_id, SUM(lb.qty) AS q FROM inventory_lot_bin_balances lb
                   WHERE lb.company_id = $1 GROUP BY lb.lot_id, lb.warehouse_id) x
               ON x.lot_id = b.lot_id AND x.warehouse_id = b.warehouse_id
        WHERE b.company_id = $1 AND w.use_bins AND b.qty <> COALESCE(x.q, 0)
    ) a)
    +
    (SELECT count(*) FROM (
        SELECT bb.bin_id, bb.item_id FROM inventory_bin_balances bb JOIN items i ON i.id = bb.item_id
        LEFT JOIN (SELECT lb.bin_id, lb.item_id, SUM(lb.qty) AS q FROM inventory_lot_bin_balances lb
                   WHERE lb.company_id = $1 GROUP BY lb.bin_id, lb.item_id) y
               ON y.bin_id = bb.bin_id AND y.item_id = bb.item_id
        WHERE bb.company_id = $1 AND i.lot_control <> 'none' AND bb.qty <> COALESCE(y.q, 0)
    ) c)
)::bigint AS mismatches
`

// 完整性:①各(批號, 倉庫)的儲位合計 = 批號現有量(啟用儲位的倉庫);②各(料品, 儲位)的批號合計 = 儲位現有量(批號管理料品)。筆數應為 0
func (q *Queries) LotBinBalanceMismatches(ctx context.Context, companyID int64) (int64, error) {
	row := q.db.QueryRow(ctx, lotBinBalanceMismatches, companyID)
	var mismatches int64
	err := row.Scan(&mismatches)
	return mismatches, err
}

const lotLedger = `-- name: LotLedger :many
SELECT t.id, t.doc_date, t.qty, t.source_type, t.source_id, t.source_no, t.warehouse_id, w.name AS warehouse_name,
       t.reversal_of, COALESCE(s.name, '')::text AS supplier_name, COALESCE(c.name, '')::text AS customer_name,
       d.sales_user_id AS sales_user_id,
       (SELECT u.department_id FROM users u WHERE u.id = d.sales_user_id) AS sales_department_id
FROM inventory_transactions t
JOIN warehouses w ON w.id = t.warehouse_id
LEFT JOIN goods_receipts gr ON t.source_type IN ('goods_receipt', 'purchase_return') AND gr.id = t.source_id
LEFT JOIN suppliers s ON s.id = gr.supplier_id
LEFT JOIN deliveries d ON t.source_type IN ('delivery', 'sales_return') AND d.id = t.source_id
LEFT JOIN customers c ON c.id = d.customer_id
WHERE t.lot_id = $1 AND t.company_id = $2
ORDER BY t.doc_date, t.id
`

type LotLedgerParams struct {
	LotID     *int64
	CompanyID int64
}

type LotLedgerRow struct {
	ID                int64
	DocDate           time.Time
	Qty               decimal.Decimal
	SourceType        string
	SourceID          int64
	SourceNo          string
	WarehouseID       int64
	WarehouseName     string
	ReversalOf        *int64
	SupplierName      string
	CustomerName      string
	SalesUserID       *int64
	SalesDepartmentID *int64
}

// 批號追溯:這個批號所有的異動(含沖銷),附上進貨的供應商與出貨的客戶
func (q *Queries) LotLedger(ctx context.Context, arg LotLedgerParams) ([]LotLedgerRow, error) {
	rows, err := q.db.Query(ctx, lotLedger, arg.LotID, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LotLedgerRow{}
	for rows.Next() {
		var i LotLedgerRow
		if err := rows.Scan(
			&i.ID,
			&i.DocDate,
			&i.Qty,
			&i.SourceType,
			&i.SourceID,
			&i.SourceNo,
			&i.WarehouseID,
			&i.WarehouseName,
			&i.ReversalOf,
			&i.SupplierName,
			&i.CustomerName,
			&i.SalesUserID,
			&i.SalesDepartmentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLotBalance = `-- name: SetLotBalance :exec
UPDATE inventory_lot_balances SET qty = $1, updated_at = now() WHERE lot_id = $2 AND warehouse_id = $3
`

type SetLotBalanceParams struct {
	Qty         decimal.Decimal
	LotID       int64
	WarehouseID int64
}

func (q *Queries) SetLotBalance(ctx context.Context, arg SetLotBalanceParams) error {
	_, err := q.db.Exec(ctx, setLotBalance, arg.Qty, arg.LotID, arg.WarehouseID)
	return err
}

const setLotBinBalance = `-- name: SetLotBinBalance :exec
UPDATE inventory_lot_bin_balances SET qty = $1, updated_at = now() WHERE lot_id = $2 AND bin_id = $3
`

type SetLotBinBalanceParams struct {
	Qty   decimal.Decimal
	LotID int64
	BinID int64
}

func (q *Queries) SetLotBinBalance(ctx context.Context, arg SetLotBinBalanceParams) error {
	_, err := q.db.Exec(ctx, setLotBinBalance, arg.Qty, arg.LotID, arg.BinID)
	return err
}
