// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type AuditLog struct {
	ID         int64
	CompanyID  int64
	UserID     *int64
	Action     string
	EntityType string
	EntityID   *int64
	Summary    string
	BeforeData []byte
	AfterData  []byte
	Ip         string
	UserAgent  string
	RequestID  string
	CreatedAt  time.Time
}

type Company struct {
	ID        int64
	Code      string
	Name      string
	TaxID     *string
	Currency  string
	IsActive  bool
	Version   int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Currency struct {
	Code      string
	Name      string
	Symbol    string
	Decimals  int16
	IsActive  bool
	SortOrder int32
}

type Customer struct {
	ID            int64
	CompanyID     int64
	Code          string
	Name          string
	ShortName     string
	TaxID         *string
	InvoiceTitle  string
	Phone         string
	Email         string
	Contacts      []byte
	Addresses     []byte
	Currency      string
	TaxTypeID     *int64
	PaymentTermID *int64
	CreditLimit   decimal.Decimal
	SalesUserID   *int64
	Note          string
	IsActive      bool
	CreatedBy     *int64
	UpdatedBy     *int64
	Version       int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Department struct {
	ID        int64
	CompanyID int64
	ParentID  *int64
	Code      string
	Name      string
	SortOrder int32
	IsActive  bool
	Version   int32
	CreatedBy *int64
	UpdatedBy *int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type DocNumberCounter struct {
	CompanyID int64
	DocType   string
	PeriodKey string
	LastValue int64
}

type DocNumberRule struct {
	CompanyID  int64
	DocType    string
	Name       string
	Prefix     string
	DateFormat string
	SeqLength  int32
	Version    int32
	UpdatedBy  *int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type ExchangeRate struct {
	ID        int64
	CompanyID int64
	Currency  string
	RateDate  time.Time
	Rate      decimal.Decimal
	CreatedBy *int64
	UpdatedBy *int64
	Version   int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type InventoryBalance struct {
	CompanyID   int64
	ItemID      int64
	WarehouseID int64
	Qty         decimal.Decimal
	UpdatedAt   time.Time
}

type InventoryTransaction struct {
	ID           int64
	CompanyID    int64
	ItemID       int64
	WarehouseID  int64
	DocDate      time.Time
	Qty          decimal.Decimal
	UnitCost     *decimal.Decimal
	SourceType   string
	SourceID     int64
	SourceLineID *int64
	SourceNo     string
	ReversalOf   *int64
	CreatedBy    *int64
	CreatedAt    time.Time
}

type Item struct {
	ID                 int64
	CompanyID          int64
	Code               string
	Name               string
	Spec               string
	CategoryID         *int64
	ItemType           string
	BaseUnitID         int64
	Barcode            *string
	TaxTypeID          *int64
	DefaultWarehouseID *int64
	SafetyStock        decimal.Decimal
	ListPrice          decimal.Decimal
	Note               string
	IsActive           bool
	CreatedBy          *int64
	UpdatedBy          *int64
	Version            int32
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type ItemCategory struct {
	ID        int64
	CompanyID int64
	ParentID  *int64
	Code      string
	Name      string
	SortOrder int32
	IsActive  bool
	CreatedBy *int64
	UpdatedBy *int64
	Version   int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ItemUnit struct {
	ItemID  int64
	UnitID  int64
	Factor  decimal.Decimal
	Barcode *string
}

type PaymentTerm struct {
	ID         int64
	CompanyID  int64
	Code       string
	Name       string
	IsMonthEnd bool
	NetDays    int32
	IsActive   bool
	CreatedBy  *int64
	UpdatedBy  *int64
	Version    int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type RefreshToken struct {
	ID        int64
	UserID    int64
	FamilyID  uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
	RevokedAt *time.Time
	Ip        string
	UserAgent string
	CreatedAt time.Time
}

type Role struct {
	ID          int64
	CompanyID   int64
	Code        string
	Name        string
	Description string
	DataScope   string
	IsActive    bool
	Version     int32
	CreatedBy   *int64
	UpdatedBy   *int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type RolePermission struct {
	RoleID     int64
	Permission string
}

type StockDocument struct {
	ID            int64
	CompanyID     int64
	DocType       string
	DocNo         string
	DocDate       time.Time
	WarehouseID   int64
	ToWarehouseID *int64
	CategoryID    *int64
	Status        string
	Note          string
	SubmittedBy   *int64
	SubmittedAt   *time.Time
	ApprovedBy    *int64
	ApprovedAt    *time.Time
	PostedBy      *int64
	PostedAt      *time.Time
	CreatedBy     *int64
	UpdatedBy     *int64
	Version       int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type StockDocumentLine struct {
	ID         int64
	DocumentID int64
	LineNo     int32
	ItemID     int64
	UnitID     int64
	Qty        *decimal.Decimal
	Factor     decimal.Decimal
	BaseQty    *decimal.Decimal
	SystemQty  *decimal.Decimal
	Note       string
}

type Supplier struct {
	ID            int64
	CompanyID     int64
	Code          string
	Name          string
	ShortName     string
	TaxID         *string
	Phone         string
	Email         string
	Contacts      []byte
	Addresses     []byte
	Currency      string
	TaxTypeID     *int64
	PaymentTermID *int64
	BankName      string
	BankAccount   string
	Note          string
	IsActive      bool
	CreatedBy     *int64
	UpdatedBy     *int64
	Version       int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type TaxType struct {
	ID        int64
	CompanyID int64
	Code      string
	Name      string
	Kind      string
	Rate      decimal.Decimal
	IsActive  bool
	CreatedBy *int64
	UpdatedBy *int64
	Version   int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Unit struct {
	ID        int64
	CompanyID int64
	Code      string
	Name      string
	IsActive  bool
	CreatedBy *int64
	UpdatedBy *int64
	Version   int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID                 int64
	CompanyID          int64
	DepartmentID       *int64
	Username           string
	Name               string
	Email              *string
	PasswordHash       string
	IsSuperadmin       bool
	IsActive           bool
	MustChangePassword bool
	FailedLoginCount   int32
	LockedUntil        *time.Time
	LastLoginAt        *time.Time
	PasswordChangedAt  time.Time
	TokenVersion       int32
	Version            int32
	CreatedBy          *int64
	UpdatedBy          *int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type UserRole struct {
	UserID int64
	RoleID int64
}

type Warehouse struct {
	ID            int64
	CompanyID     int64
	Code          string
	Name          string
	Address       string
	AllowNegative bool
	IsActive      bool
	CreatedBy     *int64
	UpdatedBy     *int64
	Version       int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
