// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type AuditLog struct {
	ID         int64
	CompanyID  int64
	UserID     *int64
	Action     string
	EntityType string
	EntityID   *int64
	Summary    string
	BeforeData []byte
	AfterData  []byte
	Ip         string
	UserAgent  string
	RequestID  string
	CreatedAt  time.Time
}

type Company struct {
	ID        int64
	Code      string
	Name      string
	TaxID     *string
	Currency  string
	IsActive  bool
	Version   int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Department struct {
	ID        int64
	CompanyID int64
	ParentID  *int64
	Code      string
	Name      string
	SortOrder int32
	IsActive  bool
	Version   int32
	CreatedBy *int64
	UpdatedBy *int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type DocNumberCounter struct {
	CompanyID int64
	DocType   string
	PeriodKey string
	LastValue int64
}

type DocNumberRule struct {
	CompanyID  int64
	DocType    string
	Name       string
	Prefix     string
	DateFormat string
	SeqLength  int32
	Version    int32
	UpdatedBy  *int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type RefreshToken struct {
	ID        int64
	UserID    int64
	FamilyID  uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
	RevokedAt *time.Time
	Ip        string
	UserAgent string
	CreatedAt time.Time
}

type Role struct {
	ID          int64
	CompanyID   int64
	Code        string
	Name        string
	Description string
	DataScope   string
	IsActive    bool
	Version     int32
	CreatedBy   *int64
	UpdatedBy   *int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type RolePermission struct {
	RoleID     int64
	Permission string
}

type User struct {
	ID                 int64
	CompanyID          int64
	DepartmentID       *int64
	Username           string
	Name               string
	Email              *string
	PasswordHash       string
	IsSuperadmin       bool
	IsActive           bool
	MustChangePassword bool
	FailedLoginCount   int32
	LockedUntil        *time.Time
	LastLoginAt        *time.Time
	PasswordChangedAt  time.Time
	TokenVersion       int32
	Version            int32
	CreatedBy          *int64
	UpdatedBy          *int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type UserRole struct {
	UserID int64
	RoleID int64
}
