// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: partners.sql

package db

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const checkPartnerRefs = `-- name: CheckPartnerRefs :one
SELECT
    EXISTS (SELECT 1 FROM currencies cu WHERE cu.code = $1::text AND cu.is_active) AS currency_ok,
    COALESCE($2::bigint IS NULL OR EXISTS (
        SELECT 1 FROM tax_types tt
        WHERE tt.id = $2::bigint AND tt.company_id = $3::bigint), FALSE)::boolean AS tax_type_ok,
    COALESCE($4::bigint IS NULL OR EXISTS (
        SELECT 1 FROM payment_terms pt
        WHERE pt.id = $4::bigint AND pt.company_id = $3::bigint), FALSE)::boolean AS payment_term_ok,
    COALESCE($5::bigint IS NULL OR EXISTS (
        SELECT 1 FROM users us
        WHERE us.id = $5::bigint AND us.company_id = $3::bigint), FALSE)::boolean AS sales_user_ok
`

type CheckPartnerRefsParams struct {
	Currency      string
	TaxTypeID     *int64
	CompanyID     int64
	PaymentTermID *int64
	SalesUserID   *int64
}

type CheckPartnerRefsRow struct {
	CurrencyOk    bool
	TaxTypeOk     bool
	PaymentTermOk bool
	SalesUserOk   bool
}

func (q *Queries) CheckPartnerRefs(ctx context.Context, arg CheckPartnerRefsParams) (CheckPartnerRefsRow, error) {
	row := q.db.QueryRow(ctx, checkPartnerRefs,
		arg.Currency,
		arg.TaxTypeID,
		arg.CompanyID,
		arg.PaymentTermID,
		arg.SalesUserID,
	)
	var i CheckPartnerRefsRow
	err := row.Scan(
		&i.CurrencyOk,
		&i.TaxTypeOk,
		&i.PaymentTermOk,
		&i.SalesUserOk,
	)
	return i, err
}

const countCustomers = `-- name: CountCustomers :one
SELECT count(*)
FROM customers c
LEFT JOIN users s ON s.id = c.sales_user_id
WHERE c.company_id = $1
  AND ($2::text IS NULL
       OR c.code ILIKE '%' || $2 || '%'
       OR c.name ILIKE '%' || $2 || '%'
       OR c.short_name ILIKE '%' || $2 || '%'
       OR c.tax_id = $2)
  AND ($3::boolean IS NULL OR c.is_active = $3)
  AND ($4::bigint IS NULL OR c.sales_user_id = $4)
  AND ($5::bigint IS NULL OR s.department_id = $5)
`

type CountCustomersParams struct {
	CompanyID   int64
	Keyword     *string
	IsActive    *bool
	ScopeUserID *int64
	ScopeDeptID *int64
}

func (q *Queries) CountCustomers(ctx context.Context, arg CountCustomersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomers,
		arg.CompanyID,
		arg.Keyword,
		arg.IsActive,
		arg.ScopeUserID,
		arg.ScopeDeptID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSuppliers = `-- name: CountSuppliers :one
SELECT count(*) FROM suppliers
WHERE company_id = $1
  AND ($2::text IS NULL
       OR code ILIKE '%' || $2 || '%'
       OR name ILIKE '%' || $2 || '%'
       OR short_name ILIKE '%' || $2 || '%'
       OR tax_id = $2)
  AND ($3::boolean IS NULL OR is_active = $3)
`

type CountSuppliersParams struct {
	CompanyID int64
	Keyword   *string
	IsActive  *bool
}

func (q *Queries) CountSuppliers(ctx context.Context, arg CountSuppliersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSuppliers, arg.CompanyID, arg.Keyword, arg.IsActive)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (company_id, code, name, short_name, tax_id, invoice_title, phone, email, contacts,
                       addresses, currency, tax_type_id, payment_term_id, credit_limit, sales_user_id, note,
                       created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9,
        $10, $11, $12, $13, $14,
        $15, $16, $17, $17)
RETURNING id, company_id, code, name, short_name, tax_id, invoice_title, phone, email, contacts, addresses, currency, tax_type_id, payment_term_id, credit_limit, sales_user_id, note, is_active, created_by, updated_by, version, created_at, updated_at
`

type CreateCustomerParams struct {
	CompanyID     int64
	Code          string
	Name          string
	ShortName     string
	TaxID         *string
	InvoiceTitle  string
	Phone         string
	Email         string
	Contacts      []byte
	Addresses     []byte
	Currency      string
	TaxTypeID     *int64
	PaymentTermID *int64
	CreditLimit   decimal.Decimal
	SalesUserID   *int64
	Note          string
	CreatedBy     *int64
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.CompanyID,
		arg.Code,
		arg.Name,
		arg.ShortName,
		arg.TaxID,
		arg.InvoiceTitle,
		arg.Phone,
		arg.Email,
		arg.Contacts,
		arg.Addresses,
		arg.Currency,
		arg.TaxTypeID,
		arg.PaymentTermID,
		arg.CreditLimit,
		arg.SalesUserID,
		arg.Note,
		arg.CreatedBy,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.Name,
		&i.ShortName,
		&i.TaxID,
		&i.InvoiceTitle,
		&i.Phone,
		&i.Email,
		&i.Contacts,
		&i.Addresses,
		&i.Currency,
		&i.TaxTypeID,
		&i.PaymentTermID,
		&i.CreditLimit,
		&i.SalesUserID,
		&i.Note,
		&i.IsActive,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSupplier = `-- name: CreateSupplier :one
INSERT INTO suppliers (company_id, code, name, short_name, tax_id, phone, email, contacts, addresses, currency,
                       tax_type_id, payment_term_id, bank_name, bank_account, note, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
        $11, $12, $13, $14, $15,
        $16, $16)
RETURNING id, company_id, code, name, short_name, tax_id, phone, email, contacts, addresses, currency, tax_type_id, payment_term_id, bank_name, bank_account, note, is_active, created_by, updated_by, version, created_at, updated_at
`

type CreateSupplierParams struct {
	CompanyID     int64
	Code          string
	Name          string
	ShortName     string
	TaxID         *string
	Phone         string
	Email         string
	Contacts      []byte
	Addresses     []byte
	Currency      string
	TaxTypeID     *int64
	PaymentTermID *int64
	BankName      string
	BankAccount   string
	Note          string
	CreatedBy     *int64
}

func (q *Queries) CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, createSupplier,
		arg.CompanyID,
		arg.Code,
		arg.Name,
		arg.ShortName,
		arg.TaxID,
		arg.Phone,
		arg.Email,
		arg.Contacts,
		arg.Addresses,
		arg.Currency,
		arg.TaxTypeID,
		arg.PaymentTermID,
		arg.BankName,
		arg.BankAccount,
		arg.Note,
		arg.CreatedBy,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.Name,
		&i.ShortName,
		&i.TaxID,
		&i.Phone,
		&i.Email,
		&i.Contacts,
		&i.Addresses,
		&i.Currency,
		&i.TaxTypeID,
		&i.PaymentTermID,
		&i.BankName,
		&i.BankAccount,
		&i.Note,
		&i.IsActive,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomer = `-- name: GetCustomer :one
SELECT c.id, c.company_id, c.code, c.name, c.short_name, c.tax_id, c.invoice_title, c.phone, c.email, c.contacts, c.addresses, c.currency, c.tax_type_id, c.payment_term_id, c.credit_limit, c.sales_user_id, c.note, c.is_active, c.created_by, c.updated_by, c.version, c.created_at, c.updated_at, s.name AS sales_user_name, s.department_id AS sales_department_id
FROM customers c
LEFT JOIN users s ON s.id = c.sales_user_id
WHERE c.id = $1 AND c.company_id = $2
`

type GetCustomerParams struct {
	ID        int64
	CompanyID int64
}

type GetCustomerRow struct {
	ID                int64
	CompanyID         int64
	Code              string
	Name              string
	ShortName         string
	TaxID             *string
	InvoiceTitle      string
	Phone             string
	Email             string
	Contacts          []byte
	Addresses         []byte
	Currency          string
	TaxTypeID         *int64
	PaymentTermID     *int64
	CreditLimit       decimal.Decimal
	SalesUserID       *int64
	Note              string
	IsActive          bool
	CreatedBy         *int64
	UpdatedBy         *int64
	Version           int32
	CreatedAt         time.Time
	UpdatedAt         time.Time
	SalesUserName     *string
	SalesDepartmentID *int64
}

func (q *Queries) GetCustomer(ctx context.Context, arg GetCustomerParams) (GetCustomerRow, error) {
	row := q.db.QueryRow(ctx, getCustomer, arg.ID, arg.CompanyID)
	var i GetCustomerRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.Name,
		&i.ShortName,
		&i.TaxID,
		&i.InvoiceTitle,
		&i.Phone,
		&i.Email,
		&i.Contacts,
		&i.Addresses,
		&i.Currency,
		&i.TaxTypeID,
		&i.PaymentTermID,
		&i.CreditLimit,
		&i.SalesUserID,
		&i.Note,
		&i.IsActive,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SalesUserName,
		&i.SalesDepartmentID,
	)
	return i, err
}

const getSupplier = `-- name: GetSupplier :one
SELECT id, company_id, code, name, short_name, tax_id, phone, email, contacts, addresses, currency, tax_type_id, payment_term_id, bank_name, bank_account, note, is_active, created_by, updated_by, version, created_at, updated_at FROM suppliers WHERE id = $1 AND company_id = $2
`

type GetSupplierParams struct {
	ID        int64
	CompanyID int64
}

func (q *Queries) GetSupplier(ctx context.Context, arg GetSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, getSupplier, arg.ID, arg.CompanyID)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.Name,
		&i.ShortName,
		&i.TaxID,
		&i.Phone,
		&i.Email,
		&i.Contacts,
		&i.Addresses,
		&i.Currency,
		&i.TaxTypeID,
		&i.PaymentTermID,
		&i.BankName,
		&i.BankAccount,
		&i.Note,
		&i.IsActive,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserDepartment = `-- name: GetUserDepartment :one
SELECT department_id FROM users WHERE id = $1 AND company_id = $2
`

type GetUserDepartmentParams struct {
	ID        int64
	CompanyID int64
}

func (q *Queries) GetUserDepartment(ctx context.Context, arg GetUserDepartmentParams) (*int64, error) {
	row := q.db.QueryRow(ctx, getUserDepartment, arg.ID, arg.CompanyID)
	var department_id *int64
	err := row.Scan(&department_id)
	return department_id, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT c.id, c.company_id, c.code, c.name, c.short_name, c.tax_id, c.invoice_title, c.phone, c.email, c.contacts, c.addresses, c.currency, c.tax_type_id, c.payment_term_id, c.credit_limit, c.sales_user_id, c.note, c.is_active, c.created_by, c.updated_by, c.version, c.created_at, c.updated_at, s.name AS sales_user_name
FROM customers c
LEFT JOIN users s ON s.id = c.sales_user_id
WHERE c.company_id = $1
  AND ($2::text IS NULL
       OR c.code ILIKE '%' || $2 || '%'
       OR c.name ILIKE '%' || $2 || '%'
       OR c.short_name ILIKE '%' || $2 || '%'
       OR c.tax_id = $2)
  AND ($3::boolean IS NULL OR c.is_active = $3)
  AND ($4::bigint IS NULL OR c.sales_user_id = $4)
  AND ($5::bigint IS NULL OR s.department_id = $5)
ORDER BY c.code
LIMIT $7 OFFSET $6
`

type ListCustomersParams struct {
	CompanyID   int64
	Keyword     *string
	IsActive    *bool
	ScopeUserID *int64
	ScopeDeptID *int64
	Off         int32
	Lim         int32
}

type ListCustomersRow struct {
	ID            int64
	CompanyID     int64
	Code          string
	Name          string
	ShortName     string
	TaxID         *string
	InvoiceTitle  string
	Phone         string
	Email         string
	Contacts      []byte
	Addresses     []byte
	Currency      string
	TaxTypeID     *int64
	PaymentTermID *int64
	CreditLimit   decimal.Decimal
	SalesUserID   *int64
	Note          string
	IsActive      bool
	CreatedBy     *int64
	UpdatedBy     *int64
	Version       int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
	SalesUserName *string
}

// scope_* 為資料範圍:依負責業務員(本人 / 同部門)過濾;未指定負責業務的客戶只有「全部」範圍看得到
func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]ListCustomersRow, error) {
	rows, err := q.db.Query(ctx, listCustomers,
		arg.CompanyID,
		arg.Keyword,
		arg.IsActive,
		arg.ScopeUserID,
		arg.ScopeDeptID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustomersRow{}
	for rows.Next() {
		var i ListCustomersRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Code,
			&i.Name,
			&i.ShortName,
			&i.TaxID,
			&i.InvoiceTitle,
			&i.Phone,
			&i.Email,
			&i.Contacts,
			&i.Addresses,
			&i.Currency,
			&i.TaxTypeID,
			&i.PaymentTermID,
			&i.CreditLimit,
			&i.SalesUserID,
			&i.Note,
			&i.IsActive,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SalesUserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuppliers = `-- name: ListSuppliers :many
SELECT id, company_id, code, name, short_name, tax_id, phone, email, contacts, addresses, currency, tax_type_id, payment_term_id, bank_name, bank_account, note, is_active, created_by, updated_by, version, created_at, updated_at FROM suppliers
WHERE company_id = $1
  AND ($2::text IS NULL
       OR code ILIKE '%' || $2 || '%'
       OR name ILIKE '%' || $2 || '%'
       OR short_name ILIKE '%' || $2 || '%'
       OR tax_id = $2)
  AND ($3::boolean IS NULL OR is_active = $3)
ORDER BY code
LIMIT $5 OFFSET $4
`

type ListSuppliersParams struct {
	CompanyID int64
	Keyword   *string
	IsActive  *bool
	Off       int32
	Lim       int32
}

func (q *Queries) ListSuppliers(ctx context.Context, arg ListSuppliersParams) ([]Supplier, error) {
	rows, err := q.db.Query(ctx, listSuppliers,
		arg.CompanyID,
		arg.Keyword,
		arg.IsActive,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Supplier{}
	for rows.Next() {
		var i Supplier
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Code,
			&i.Name,
			&i.ShortName,
			&i.TaxID,
			&i.Phone,
			&i.Email,
			&i.Contacts,
			&i.Addresses,
			&i.Currency,
			&i.TaxTypeID,
			&i.PaymentTermID,
			&i.BankName,
			&i.BankAccount,
			&i.Note,
			&i.IsActive,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers
SET code = $1, name = $2, short_name = $3, tax_id = $4,
    invoice_title = $5, phone = $6, email = $7, contacts = $8,
    addresses = $9, currency = $10, tax_type_id = $11,
    payment_term_id = $12, credit_limit = $13,
    sales_user_id = $14, note = $15, is_active = $16,
    version = version + 1, updated_by = $17
WHERE id = $18 AND company_id = $19 AND version = $20
RETURNING id, company_id, code, name, short_name, tax_id, invoice_title, phone, email, contacts, addresses, currency, tax_type_id, payment_term_id, credit_limit, sales_user_id, note, is_active, created_by, updated_by, version, created_at, updated_at
`

type UpdateCustomerParams struct {
	Code          string
	Name          string
	ShortName     string
	TaxID         *string
	InvoiceTitle  string
	Phone         string
	Email         string
	Contacts      []byte
	Addresses     []byte
	Currency      string
	TaxTypeID     *int64
	PaymentTermID *int64
	CreditLimit   decimal.Decimal
	SalesUserID   *int64
	Note          string
	IsActive      bool
	UpdatedBy     *int64
	ID            int64
	CompanyID     int64
	Version       int32
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.Code,
		arg.Name,
		arg.ShortName,
		arg.TaxID,
		arg.InvoiceTitle,
		arg.Phone,
		arg.Email,
		arg.Contacts,
		arg.Addresses,
		arg.Currency,
		arg.TaxTypeID,
		arg.PaymentTermID,
		arg.CreditLimit,
		arg.SalesUserID,
		arg.Note,
		arg.IsActive,
		arg.UpdatedBy,
		arg.ID,
		arg.CompanyID,
		arg.Version,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.Name,
		&i.ShortName,
		&i.TaxID,
		&i.InvoiceTitle,
		&i.Phone,
		&i.Email,
		&i.Contacts,
		&i.Addresses,
		&i.Currency,
		&i.TaxTypeID,
		&i.PaymentTermID,
		&i.CreditLimit,
		&i.SalesUserID,
		&i.Note,
		&i.IsActive,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSupplier = `-- name: UpdateSupplier :one
UPDATE suppliers
SET code = $1, name = $2, short_name = $3, tax_id = $4, phone = $5,
    email = $6, contacts = $7, addresses = $8, currency = $9,
    tax_type_id = $10, payment_term_id = $11,
    bank_name = $12, bank_account = $13, note = $14, is_active = $15,
    version = version + 1, updated_by = $16
WHERE id = $17 AND company_id = $18 AND version = $19
RETURNING id, company_id, code, name, short_name, tax_id, phone, email, contacts, addresses, currency, tax_type_id, payment_term_id, bank_name, bank_account, note, is_active, created_by, updated_by, version, created_at, updated_at
`

type UpdateSupplierParams struct {
	Code          string
	Name          string
	ShortName     string
	TaxID         *string
	Phone         string
	Email         string
	Contacts      []byte
	Addresses     []byte
	Currency      string
	TaxTypeID     *int64
	PaymentTermID *int64
	BankName      string
	BankAccount   string
	Note          string
	IsActive      bool
	UpdatedBy     *int64
	ID            int64
	CompanyID     int64
	Version       int32
}

func (q *Queries) UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, updateSupplier,
		arg.Code,
		arg.Name,
		arg.ShortName,
		arg.TaxID,
		arg.Phone,
		arg.Email,
		arg.Contacts,
		arg.Addresses,
		arg.Currency,
		arg.TaxTypeID,
		arg.PaymentTermID,
		arg.BankName,
		arg.BankAccount,
		arg.Note,
		arg.IsActive,
		arg.UpdatedBy,
		arg.ID,
		arg.CompanyID,
		arg.Version,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.Name,
		&i.ShortName,
		&i.TaxID,
		&i.Phone,
		&i.Email,
		&i.Contacts,
		&i.Addresses,
		&i.Currency,
		&i.TaxTypeID,
		&i.PaymentTermID,
		&i.BankName,
		&i.BankAccount,
		&i.Note,
		&i.IsActive,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
