// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: purchase.sql

package db

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const addGoodsReceiptLine = `-- name: AddGoodsReceiptLine :exec
INSERT INTO goods_receipt_lines (receipt_id, line_no, item_id, unit_id, qty, factor, base_qty, unit_price, amount,
                                 base_amount, po_line_id, receipt_line_id, note, lot_no, expiry_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
        $11, $12, $13, $14, $15)
`

type AddGoodsReceiptLineParams struct {
	ReceiptID     int64
	LineNo        int32
	ItemID        int64
	UnitID        int64
	Qty           decimal.Decimal
	Factor        decimal.Decimal
	BaseQty       decimal.Decimal
	UnitPrice     decimal.Decimal
	Amount        decimal.Decimal
	BaseAmount    decimal.Decimal
	PoLineID      *int64
	ReceiptLineID *int64
	Note          string
	LotNo         string
	ExpiryDate    *time.Time
}

func (q *Queries) AddGoodsReceiptLine(ctx context.Context, arg AddGoodsReceiptLineParams) error {
	_, err := q.db.Exec(ctx, addGoodsReceiptLine,
		arg.ReceiptID,
		arg.LineNo,
		arg.ItemID,
		arg.UnitID,
		arg.Qty,
		arg.Factor,
		arg.BaseQty,
		arg.UnitPrice,
		arg.Amount,
		arg.BaseAmount,
		arg.PoLineID,
		arg.ReceiptLineID,
		arg.Note,
		arg.LotNo,
		arg.ExpiryDate,
	)
	return err
}

const addPurchaseOrderLine = `-- name: AddPurchaseOrderLine :exec
INSERT INTO purchase_order_lines (order_id, line_no, item_id, unit_id, qty, factor, base_qty, unit_price, amount, note)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type AddPurchaseOrderLineParams struct {
	OrderID   int64
	LineNo    int32
	ItemID    int64
	UnitID    int64
	Qty       decimal.Decimal
	Factor    decimal.Decimal
	BaseQty   decimal.Decimal
	UnitPrice decimal.Decimal
	Amount    decimal.Decimal
	Note      string
}

func (q *Queries) AddPurchaseOrderLine(ctx context.Context, arg AddPurchaseOrderLineParams) error {
	_, err := q.db.Exec(ctx, addPurchaseOrderLine,
		arg.OrderID,
		arg.LineNo,
		arg.ItemID,
		arg.UnitID,
		arg.Qty,
		arg.Factor,
		arg.BaseQty,
		arg.UnitPrice,
		arg.Amount,
		arg.Note,
	)
	return err
}

const countGoodsReceipts = `-- name: CountGoodsReceipts :one
SELECT count(*) FROM goods_receipts r
WHERE r.company_id = $1
  AND ($2::text IS NULL OR r.doc_type = $2)
  AND ($3::text IS NULL OR r.status = $3)
  AND ($4::bigint IS NULL OR r.supplier_id = $4)
  AND ($5::text IS NULL OR r.doc_no ILIKE '%' || $5 || '%'
       OR r.invoice_no ILIKE '%' || $5 || '%')
  AND ($6::date IS NULL OR r.doc_date >= $6)
  AND ($7::date IS NULL OR r.doc_date <= $7)
`

type CountGoodsReceiptsParams struct {
	CompanyID  int64
	DocType    *string
	Status     *string
	SupplierID *int64
	Keyword    *string
	FromDate   *time.Time
	ToDate     *time.Time
}

func (q *Queries) CountGoodsReceipts(ctx context.Context, arg CountGoodsReceiptsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGoodsReceipts,
		arg.CompanyID,
		arg.DocType,
		arg.Status,
		arg.SupplierID,
		arg.Keyword,
		arg.FromDate,
		arg.ToDate,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOutstandingPurchaseLines = `-- name: CountOutstandingPurchaseLines :one
SELECT count(*)
FROM purchase_order_lines l
JOIN purchase_orders o ON o.id = l.order_id
JOIN items i ON i.id = l.item_id
WHERE o.company_id = $1 AND o.status = 'approved'
  AND l.qty > (SELECT COALESCE(SUM(rl.qty), 0) FROM goods_receipt_lines rl
               JOIN goods_receipts r ON r.id = rl.receipt_id
               WHERE rl.po_line_id = l.id AND r.status = 'posted')
  AND ($2::bigint IS NULL OR o.supplier_id = $2)
  AND ($3::text IS NULL OR o.currency = $3)
  AND ($4::text IS NULL
       OR o.doc_no ILIKE '%' || $4 || '%'
       OR i.code ILIKE '%' || $4 || '%'
       OR i.name ILIKE '%' || $4 || '%')
  AND ($5::date IS NULL OR o.expected_date <= $5)
`

type CountOutstandingPurchaseLinesParams struct {
	CompanyID  int64
	SupplierID *int64
	Currency   *string
	Keyword    *string
	DueBefore  *time.Time
}

func (q *Queries) CountOutstandingPurchaseLines(ctx context.Context, arg CountOutstandingPurchaseLinesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOutstandingPurchaseLines,
		arg.CompanyID,
		arg.SupplierID,
		arg.Currency,
		arg.Keyword,
		arg.DueBefore,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPayables = `-- name: CountPayables :one
SELECT count(*) AS total,
       COALESCE(SUM(CASE WHEN p.amount = 0 THEN 0 ELSE p.base_amount * (p.amount - p.paid_amount) / p.amount END), 0)::numeric AS base_amount_sum
FROM accounts_payable p
WHERE p.company_id = $1
  AND ($2::bigint IS NULL OR p.supplier_id = $2)
  AND ($3::text IS NULL OR p.source_no ILIKE '%' || $3 || '%')
  AND ($4::date IS NULL OR p.doc_date >= $4)
  AND ($5::date IS NULL OR p.doc_date <= $5)
  AND (NOT $6::boolean OR p.amount <> p.paid_amount)
`

type CountPayablesParams struct {
	CompanyID  int64
	SupplierID *int64
	Keyword    *string
	FromDate   *time.Time
	ToDate     *time.Time
	OpenOnly   bool
}

type CountPayablesRow struct {
	Total         int64
	BaseAmountSum decimal.Decimal
}

// base_amount_sum:未沖餘額的本位幣合計(依原幣餘額比例換算)
func (q *Queries) CountPayables(ctx context.Context, arg CountPayablesParams) (CountPayablesRow, error) {
	row := q.db.QueryRow(ctx, countPayables,
		arg.CompanyID,
		arg.SupplierID,
		arg.Keyword,
		arg.FromDate,
		arg.ToDate,
		arg.OpenOnly,
	)
	var i CountPayablesRow
	err := row.Scan(&i.Total, &i.BaseAmountSum)
	return i, err
}

const countPurchaseOrders = `-- name: CountPurchaseOrders :one
SELECT count(*) FROM purchase_orders o
WHERE o.company_id = $1
  AND ($2::text IS NULL OR o.status = $2)
  AND ($3::bigint IS NULL OR o.supplier_id = $3)
  AND ($4::text IS NULL OR o.doc_no ILIKE '%' || $4 || '%')
  AND ($5::date IS NULL OR o.doc_date >= $5)
  AND ($6::date IS NULL OR o.doc_date <= $6)
`

type CountPurchaseOrdersParams struct {
	CompanyID  int64
	Status     *string
	SupplierID *int64
	Keyword    *string
	FromDate   *time.Time
	ToDate     *time.Time
}

func (q *Queries) CountPurchaseOrders(ctx context.Context, arg CountPurchaseOrdersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPurchaseOrders,
		arg.CompanyID,
		arg.Status,
		arg.SupplierID,
		arg.Keyword,
		arg.FromDate,
		arg.ToDate,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGoodsReceipt = `-- name: CreateGoodsReceipt :one
INSERT INTO goods_receipts (company_id, doc_type, doc_no, doc_date, supplier_id, warehouse_id, currency,
                            exchange_rate, tax_type_id, tax_rate, payment_term_id, invoice_no, invoice_date,
                            invoice_kind, untaxed_amount,
                            tax_amount, total_amount, base_untaxed, base_tax, base_total, note, created_by,
                            updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        $9, $10, $11, $12, $13, $14, $15, $16,
        $17, $18, $19, $20, $21, $22, $22)
RETURNING id, company_id, doc_type, doc_no, doc_date, supplier_id, warehouse_id, currency, exchange_rate, tax_type_id, tax_rate, payment_term_id, invoice_no, untaxed_amount, tax_amount, total_amount, base_untaxed, base_tax, base_total, status, note, submitted_by, submitted_at, approved_by, approved_at, posted_by, posted_at, created_by, updated_by, version, created_at, updated_at, invoice_date, invoice_kind
`

type CreateGoodsReceiptParams struct {
	CompanyID     int64
	DocType       string
	DocNo         string
	DocDate       time.Time
	SupplierID    int64
	WarehouseID   int64
	Currency      string
	ExchangeRate  decimal.Decimal
	TaxTypeID     int64
	TaxRate       decimal.Decimal
	PaymentTermID *int64
	InvoiceNo     string
	InvoiceDate   *time.Time
	InvoiceKind   string
	UntaxedAmount decimal.Decimal
	TaxAmount     decimal.Decimal
	TotalAmount   decimal.Decimal
	BaseUntaxed   decimal.Decimal
	BaseTax       decimal.Decimal
	BaseTotal     decimal.Decimal
	Note          string
	CreatedBy     *int64
}

func (q *Queries) CreateGoodsReceipt(ctx context.Context, arg CreateGoodsReceiptParams) (GoodsReceipt, error) {
	row := q.db.QueryRow(ctx, createGoodsReceipt,
		arg.CompanyID,
		arg.DocType,
		arg.DocNo,
		arg.DocDate,
		arg.SupplierID,
		arg.WarehouseID,
		arg.Currency,
		arg.ExchangeRate,
		arg.TaxTypeID,
		arg.TaxRate,
		arg.PaymentTermID,
		arg.InvoiceNo,
		arg.InvoiceDate,
		arg.InvoiceKind,
		arg.UntaxedAmount,
		arg.TaxAmount,
		arg.TotalAmount,
		arg.BaseUntaxed,
		arg.BaseTax,
		arg.BaseTotal,
		arg.Note,
		arg.CreatedBy,
	)
	var i GoodsReceipt
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocType,
		&i.DocNo,
		&i.DocDate,
		&i.SupplierID,
		&i.WarehouseID,
		&i.Currency,
		&i.ExchangeRate,
		&i.TaxTypeID,
		&i.TaxRate,
		&i.PaymentTermID,
		&i.InvoiceNo,
		&i.UntaxedAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.BaseUntaxed,
		&i.BaseTax,
		&i.BaseTotal,
		&i.Status,
		&i.Note,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.PostedBy,
		&i.PostedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InvoiceDate,
		&i.InvoiceKind,
	)
	return i, err
}

const createPurchaseOrder = `-- name: CreatePurchaseOrder :one
INSERT INTO purchase_orders (company_id, doc_no, doc_date, supplier_id, warehouse_id, expected_date, currency,
                             exchange_rate, tax_type_id, tax_rate, payment_term_id, untaxed_amount, tax_amount,
                             total_amount, note, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11, $12, $13,
        $14, $15, $16, $16)
RETURNING id, company_id, doc_no, doc_date, supplier_id, warehouse_id, expected_date, currency, exchange_rate, tax_type_id, tax_rate, payment_term_id, untaxed_amount, tax_amount, total_amount, status, note, submitted_by, submitted_at, approved_by, approved_at, closed_by, closed_at, created_by, updated_by, version, created_at, updated_at
`

type CreatePurchaseOrderParams struct {
	CompanyID     int64
	DocNo         string
	DocDate       time.Time
	SupplierID    int64
	WarehouseID   int64
	ExpectedDate  *time.Time
	Currency      string
	ExchangeRate  decimal.Decimal
	TaxTypeID     int64
	TaxRate       decimal.Decimal
	PaymentTermID *int64
	UntaxedAmount decimal.Decimal
	TaxAmount     decimal.Decimal
	TotalAmount   decimal.Decimal
	Note          string
	CreatedBy     *int64
}

func (q *Queries) CreatePurchaseOrder(ctx context.Context, arg CreatePurchaseOrderParams) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, createPurchaseOrder,
		arg.CompanyID,
		arg.DocNo,
		arg.DocDate,
		arg.SupplierID,
		arg.WarehouseID,
		arg.ExpectedDate,
		arg.Currency,
		arg.ExchangeRate,
		arg.TaxTypeID,
		arg.TaxRate,
		arg.PaymentTermID,
		arg.UntaxedAmount,
		arg.TaxAmount,
		arg.TotalAmount,
		arg.Note,
		arg.CreatedBy,
	)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocNo,
		&i.DocDate,
		&i.SupplierID,
		&i.WarehouseID,
		&i.ExpectedDate,
		&i.Currency,
		&i.ExchangeRate,
		&i.TaxTypeID,
		&i.TaxRate,
		&i.PaymentTermID,
		&i.UntaxedAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.Status,
		&i.Note,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGoodsReceiptLines = `-- name: DeleteGoodsReceiptLines :exec
DELETE FROM goods_receipt_lines WHERE receipt_id = $1
`

func (q *Queries) DeleteGoodsReceiptLines(ctx context.Context, receiptID int64) error {
	_, err := q.db.Exec(ctx, deleteGoodsReceiptLines, receiptID)
	return err
}

const deletePayable = `-- name: DeletePayable :exec
DELETE FROM accounts_payable WHERE id = $1
`

func (q *Queries) DeletePayable(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePayable, id)
	return err
}

const deletePurchaseOrderLines = `-- name: DeletePurchaseOrderLines :exec
DELETE FROM purchase_order_lines WHERE order_id = $1
`

func (q *Queries) DeletePurchaseOrderLines(ctx context.Context, orderID int64) error {
	_, err := q.db.Exec(ctx, deletePurchaseOrderLines, orderID)
	return err
}

const getGoodsReceipt = `-- name: GetGoodsReceipt :one
SELECT r.id, r.company_id, r.doc_type, r.doc_no, r.doc_date, r.supplier_id, r.warehouse_id, r.currency, r.exchange_rate, r.tax_type_id, r.tax_rate, r.payment_term_id, r.invoice_no, r.untaxed_amount, r.tax_amount, r.total_amount, r.base_untaxed, r.base_tax, r.base_total, r.status, r.note, r.submitted_by, r.submitted_at, r.approved_by, r.approved_at, r.posted_by, r.posted_at, r.created_by, r.updated_by, r.version, r.created_at, r.updated_at, r.invoice_date, r.invoice_kind, s.code AS supplier_code, s.name AS supplier_name, w.name AS warehouse_name,
       t.name AS tax_type_name, pt.name AS payment_term_name,
       cu.name AS created_by_name, su.name AS submitted_by_name, au.name AS approved_by_name,
       pu.name AS posted_by_name
FROM goods_receipts r
JOIN suppliers s ON s.id = r.supplier_id
JOIN warehouses w ON w.id = r.warehouse_id
JOIN tax_types t ON t.id = r.tax_type_id
LEFT JOIN payment_terms pt ON pt.id = r.payment_term_id
LEFT JOIN users cu ON cu.id = r.created_by
LEFT JOIN users su ON su.id = r.submitted_by
LEFT JOIN users au ON au.id = r.approved_by
LEFT JOIN users pu ON pu.id = r.posted_by
WHERE r.id = $1 AND r.company_id = $2
`

type GetGoodsReceiptParams struct {
	ID        int64
	CompanyID int64
}

type GetGoodsReceiptRow struct {
	ID              int64
	CompanyID       int64
	DocType         string
	DocNo           string
	DocDate         time.Time
	SupplierID      int64
	WarehouseID     int64
	Currency        string
	ExchangeRate    decimal.Decimal
	TaxTypeID       int64
	TaxRate         decimal.Decimal
	PaymentTermID   *int64
	InvoiceNo       string
	UntaxedAmount   decimal.Decimal
	TaxAmount       decimal.Decimal
	TotalAmount     decimal.Decimal
	BaseUntaxed     decimal.Decimal
	BaseTax         decimal.Decimal
	BaseTotal       decimal.Decimal
	Status          string
	Note            string
	SubmittedBy     *int64
	SubmittedAt     *time.Time
	ApprovedBy      *int64
	ApprovedAt      *time.Time
	PostedBy        *int64
	PostedAt        *time.Time
	CreatedBy       *int64
	UpdatedBy       *int64
	Version         int32
	CreatedAt       time.Time
	UpdatedAt       time.Time
	InvoiceDate     *time.Time
	InvoiceKind     string
	SupplierCode    string
	SupplierName    string
	WarehouseName   string
	TaxTypeName     string
	PaymentTermName *string
	CreatedByName   *string
	SubmittedByName *string
	ApprovedByName  *string
	PostedByName    *string
}

func (q *Queries) GetGoodsReceipt(ctx context.Context, arg GetGoodsReceiptParams) (GetGoodsReceiptRow, error) {
	row := q.db.QueryRow(ctx, getGoodsReceipt, arg.ID, arg.CompanyID)
	var i GetGoodsReceiptRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocType,
		&i.DocNo,
		&i.DocDate,
		&i.SupplierID,
		&i.WarehouseID,
		&i.Currency,
		&i.ExchangeRate,
		&i.TaxTypeID,
		&i.TaxRate,
		&i.PaymentTermID,
		&i.InvoiceNo,
		&i.UntaxedAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.BaseUntaxed,
		&i.BaseTax,
		&i.BaseTotal,
		&i.Status,
		&i.Note,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.PostedBy,
		&i.PostedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InvoiceDate,
		&i.InvoiceKind,
		&i.SupplierCode,
		&i.SupplierName,
		&i.WarehouseName,
		&i.TaxTypeName,
		&i.PaymentTermName,
		&i.CreatedByName,
		&i.SubmittedByName,
		&i.ApprovedByName,
		&i.PostedByName,
	)
	return i, err
}

const getPurchaseOrder = `-- name: GetPurchaseOrder :one
SELECT o.id, o.company_id, o.doc_no, o.doc_date, o.supplier_id, o.warehouse_id, o.expected_date, o.currency, o.exchange_rate, o.tax_type_id, o.tax_rate, o.payment_term_id, o.untaxed_amount, o.tax_amount, o.total_amount, o.status, o.note, o.submitted_by, o.submitted_at, o.approved_by, o.approved_at, o.closed_by, o.closed_at, o.created_by, o.updated_by, o.version, o.created_at, o.updated_at, s.code AS supplier_code, s.name AS supplier_name, w.name AS warehouse_name,
       t.name AS tax_type_name, pt.name AS payment_term_name,
       cu.name AS created_by_name, su.name AS submitted_by_name, au.name AS approved_by_name,
       clu.name AS closed_by_name
FROM purchase_orders o
JOIN suppliers s ON s.id = o.supplier_id
JOIN warehouses w ON w.id = o.warehouse_id
JOIN tax_types t ON t.id = o.tax_type_id
LEFT JOIN payment_terms pt ON pt.id = o.payment_term_id
LEFT JOIN users cu ON cu.id = o.created_by
LEFT JOIN users su ON su.id = o.submitted_by
LEFT JOIN users au ON au.id = o.approved_by
LEFT JOIN users clu ON clu.id = o.closed_by
WHERE o.id = $1 AND o.company_id = $2
`

type GetPurchaseOrderParams struct {
	ID        int64
	CompanyID int64
}

type GetPurchaseOrderRow struct {
	ID              int64
	CompanyID       int64
	DocNo           string
	DocDate         time.Time
	SupplierID      int64
	WarehouseID     int64
	ExpectedDate    *time.Time
	Currency        string
	ExchangeRate    decimal.Decimal
	TaxTypeID       int64
	TaxRate         decimal.Decimal
	PaymentTermID   *int64
	UntaxedAmount   decimal.Decimal
	TaxAmount       decimal.Decimal
	TotalAmount     decimal.Decimal
	Status          string
	Note            string
	SubmittedBy     *int64
	SubmittedAt     *time.Time
	ApprovedBy      *int64
	ApprovedAt      *time.Time
	ClosedBy        *int64
	ClosedAt        *time.Time
	CreatedBy       *int64
	UpdatedBy       *int64
	Version         int32
	CreatedAt       time.Time
	UpdatedAt       time.Time
	SupplierCode    string
	SupplierName    string
	WarehouseName   string
	TaxTypeName     string
	PaymentTermName *string
	CreatedByName   *string
	SubmittedByName *string
	ApprovedByName  *string
	ClosedByName    *string
}

func (q *Queries) GetPurchaseOrder(ctx context.Context, arg GetPurchaseOrderParams) (GetPurchaseOrderRow, error) {
	row := q.db.QueryRow(ctx, getPurchaseOrder, arg.ID, arg.CompanyID)
	var i GetPurchaseOrderRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocNo,
		&i.DocDate,
		&i.SupplierID,
		&i.WarehouseID,
		&i.ExpectedDate,
		&i.Currency,
		&i.ExchangeRate,
		&i.TaxTypeID,
		&i.TaxRate,
		&i.PaymentTermID,
		&i.UntaxedAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.Status,
		&i.Note,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SupplierCode,
		&i.SupplierName,
		&i.WarehouseName,
		&i.TaxTypeName,
		&i.PaymentTermName,
		&i.CreatedByName,
		&i.SubmittedByName,
		&i.ApprovedByName,
		&i.ClosedByName,
	)
	return i, err
}

const insertPayable = `-- name: InsertPayable :exec

INSERT INTO accounts_payable (company_id, supplier_id, source_type, source_id, source_no, doc_date, due_date,
                              currency, exchange_rate, amount, base_amount, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        $9, $10, $11, $12)
`

type InsertPayableParams struct {
	CompanyID    int64
	SupplierID   int64
	SourceType   string
	SourceID     int64
	SourceNo     string
	DocDate      time.Time
	DueDate      time.Time
	Currency     string
	ExchangeRate decimal.Decimal
	Amount       decimal.Decimal
	BaseAmount   decimal.Decimal
	CreatedBy    *int64
}

// ======== 應付帳款 ========
func (q *Queries) InsertPayable(ctx context.Context, arg InsertPayableParams) error {
	_, err := q.db.Exec(ctx, insertPayable,
		arg.CompanyID,
		arg.SupplierID,
		arg.SourceType,
		arg.SourceID,
		arg.SourceNo,
		arg.DocDate,
		arg.DueDate,
		arg.Currency,
		arg.ExchangeRate,
		arg.Amount,
		arg.BaseAmount,
		arg.CreatedBy,
	)
	return err
}

const listGoodsReceiptLines = `-- name: ListGoodsReceiptLines :many
SELECT l.id, l.receipt_id, l.line_no, l.item_id, l.unit_id, l.qty, l.factor, l.base_qty, l.unit_price, l.amount, l.base_amount, l.po_line_id, l.receipt_line_id, l.note, l.lot_no, l.expiry_date, i.code AS item_code, i.name AS item_name, i.spec AS item_spec, i.item_type, i.lot_control AS item_lot_control,
       u.name AS unit_name, bu.name AS base_unit_name,
       po.doc_no AS po_no, src.doc_no AS source_receipt_no
FROM goods_receipt_lines l
JOIN items i ON i.id = l.item_id
JOIN units u ON u.id = l.unit_id
JOIN units bu ON bu.id = i.base_unit_id
LEFT JOIN purchase_order_lines pol ON pol.id = l.po_line_id
LEFT JOIN purchase_orders po ON po.id = pol.order_id
LEFT JOIN goods_receipt_lines srl ON srl.id = l.receipt_line_id
LEFT JOIN goods_receipts src ON src.id = srl.receipt_id
WHERE l.receipt_id = $1
ORDER BY l.line_no
`

type ListGoodsReceiptLinesRow struct {
	ID              int64
	ReceiptID       int64
	LineNo          int32
	ItemID          int64
	UnitID          int64
	Qty             decimal.Decimal
	Factor          decimal.Decimal
	BaseQty         decimal.Decimal
	UnitPrice       decimal.Decimal
	Amount          decimal.Decimal
	BaseAmount      decimal.Decimal
	PoLineID        *int64
	ReceiptLineID   *int64
	Note            string
	LotNo           string
	ExpiryDate      *time.Time
	ItemCode        string
	ItemName        string
	ItemSpec        string
	ItemType        string
	ItemLotControl  string
	UnitName        string
	BaseUnitName    string
	PoNo            *string
	SourceReceiptNo *string
}

func (q *Queries) ListGoodsReceiptLines(ctx context.Context, receiptID int64) ([]ListGoodsReceiptLinesRow, error) {
	rows, err := q.db.Query(ctx, listGoodsReceiptLines, receiptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGoodsReceiptLinesRow{}
	for rows.Next() {
		var i ListGoodsReceiptLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.ReceiptID,
			&i.LineNo,
			&i.ItemID,
			&i.UnitID,
			&i.Qty,
			&i.Factor,
			&i.BaseQty,
			&i.UnitPrice,
			&i.Amount,
			&i.BaseAmount,
			&i.PoLineID,
			&i.ReceiptLineID,
			&i.Note,
			&i.LotNo,
			&i.ExpiryDate,
			&i.ItemCode,
			&i.ItemName,
			&i.ItemSpec,
			&i.ItemType,
			&i.ItemLotControl,
			&i.UnitName,
			&i.BaseUnitName,
			&i.PoNo,
			&i.SourceReceiptNo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoodsReceipts = `-- name: ListGoodsReceipts :many

SELECT r.id, r.doc_type, r.doc_no, r.doc_date, r.status, r.currency, r.total_amount, r.invoice_no, r.note,
       r.version, r.updated_at, s.code AS supplier_code, s.name AS supplier_name, w.name AS warehouse_name,
       cu.name AS created_by_name
FROM goods_receipts r
JOIN suppliers s ON s.id = r.supplier_id
JOIN warehouses w ON w.id = r.warehouse_id
LEFT JOIN users cu ON cu.id = r.created_by
WHERE r.company_id = $1
  AND ($2::text IS NULL OR r.doc_type = $2)
  AND ($3::text IS NULL OR r.status = $3)
  AND ($4::bigint IS NULL OR r.supplier_id = $4)
  AND ($5::text IS NULL OR r.doc_no ILIKE '%' || $5 || '%'
       OR r.invoice_no ILIKE '%' || $5 || '%')
  AND ($6::date IS NULL OR r.doc_date >= $6)
  AND ($7::date IS NULL OR r.doc_date <= $7)
ORDER BY r.doc_date DESC, r.id DESC
LIMIT $9 OFFSET $8
`

type ListGoodsReceiptsParams struct {
	CompanyID  int64
	DocType    *string
	Status     *string
	SupplierID *int64
	Keyword    *string
	FromDate   *time.Time
	ToDate     *time.Time
	Off        int32
	Lim        int32
}

type ListGoodsReceiptsRow struct {
	ID            int64
	DocType       string
	DocNo         string
	DocDate       time.Time
	Status        string
	Currency      string
	TotalAmount   decimal.Decimal
	InvoiceNo     string
	Note          string
	Version       int32
	UpdatedAt     time.Time
	SupplierCode  string
	SupplierName  string
	WarehouseName string
	CreatedByName *string
}

// ======== 進貨單 / 進貨退出單 ========
func (q *Queries) ListGoodsReceipts(ctx context.Context, arg ListGoodsReceiptsParams) ([]ListGoodsReceiptsRow, error) {
	rows, err := q.db.Query(ctx, listGoodsReceipts,
		arg.CompanyID,
		arg.DocType,
		arg.Status,
		arg.SupplierID,
		arg.Keyword,
		arg.FromDate,
		arg.ToDate,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGoodsReceiptsRow{}
	for rows.Next() {
		var i ListGoodsReceiptsRow
		if err := rows.Scan(
			&i.ID,
			&i.DocType,
			&i.DocNo,
			&i.DocDate,
			&i.Status,
			&i.Currency,
			&i.TotalAmount,
			&i.InvoiceNo,
			&i.Note,
			&i.Version,
			&i.UpdatedAt,
			&i.SupplierCode,
			&i.SupplierName,
			&i.WarehouseName,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayables = `-- name: ListPayables :many
SELECT p.id, p.company_id, p.supplier_id, p.source_type, p.source_id, p.source_no, p.doc_date, p.due_date, p.currency, p.exchange_rate, p.amount, p.base_amount, p.paid_amount, p.created_by, p.created_at, p.updated_at, p.import_batch_id, s.code AS supplier_code, s.name AS supplier_name
FROM accounts_payable p
JOIN suppliers s ON s.id = p.supplier_id
WHERE p.company_id = $1
  AND ($2::bigint IS NULL OR p.supplier_id = $2)
  AND ($3::text IS NULL OR p.source_no ILIKE '%' || $3 || '%')
  AND ($4::date IS NULL OR p.doc_date >= $4)
  AND ($5::date IS NULL OR p.doc_date <= $5)
  AND (NOT $6::boolean OR p.amount <> p.paid_amount)
ORDER BY p.due_date, p.id
LIMIT $8 OFFSET $7
`

type ListPayablesParams struct {
	CompanyID  int64
	SupplierID *int64
	Keyword    *string
	FromDate   *time.Time
	ToDate     *time.Time
	OpenOnly   bool
	Off        int32
	Lim        int32
}

type ListPayablesRow struct {
	ID            int64
	CompanyID     int64
	SupplierID    int64
	SourceType    string
	SourceID      int64
	SourceNo      string
	DocDate       time.Time
	DueDate       time.Time
	Currency      string
	ExchangeRate  decimal.Decimal
	Amount        decimal.Decimal
	BaseAmount    decimal.Decimal
	PaidAmount    decimal.Decimal
	CreatedBy     *int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	ImportBatchID *int64
	SupplierCode  string
	SupplierName  string
}

func (q *Queries) ListPayables(ctx context.Context, arg ListPayablesParams) ([]ListPayablesRow, error) {
	rows, err := q.db.Query(ctx, listPayables,
		arg.CompanyID,
		arg.SupplierID,
		arg.Keyword,
		arg.FromDate,
		arg.ToDate,
		arg.OpenOnly,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPayablesRow{}
	for rows.Next() {
		var i ListPayablesRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.SupplierID,
			&i.SourceType,
			&i.SourceID,
			&i.SourceNo,
			&i.DocDate,
			&i.DueDate,
			&i.Currency,
			&i.ExchangeRate,
			&i.Amount,
			&i.BaseAmount,
			&i.PaidAmount,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImportBatchID,
			&i.SupplierCode,
			&i.SupplierName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchaseOrderLines = `-- name: ListPurchaseOrderLines :many
SELECT l.id, l.order_id, l.line_no, l.item_id, l.unit_id, l.qty, l.factor, l.base_qty, l.unit_price, l.amount, l.note, i.code AS item_code, i.name AS item_name, i.spec AS item_spec, i.item_type,
       u.name AS unit_name, bu.name AS base_unit_name,
       (SELECT COALESCE(SUM(rl.qty), 0) FROM goods_receipt_lines rl
        JOIN goods_receipts r ON r.id = rl.receipt_id
        WHERE rl.po_line_id = l.id AND r.status = 'posted')::numeric AS received_qty
FROM purchase_order_lines l
JOIN items i ON i.id = l.item_id
JOIN units u ON u.id = l.unit_id
JOIN units bu ON bu.id = i.base_unit_id
WHERE l.order_id = $1
ORDER BY l.line_no
`

type ListPurchaseOrderLinesRow struct {
	ID           int64
	OrderID      int64
	LineNo       int32
	ItemID       int64
	UnitID       int64
	Qty          decimal.Decimal
	Factor       decimal.Decimal
	BaseQty      decimal.Decimal
	UnitPrice    decimal.Decimal
	Amount       decimal.Decimal
	Note         string
	ItemCode     string
	ItemName     string
	ItemSpec     string
	ItemType     string
	UnitName     string
	BaseUnitName string
	ReceivedQty  decimal.Decimal
}

func (q *Queries) ListPurchaseOrderLines(ctx context.Context, orderID int64) ([]ListPurchaseOrderLinesRow, error) {
	rows, err := q.db.Query(ctx, listPurchaseOrderLines, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPurchaseOrderLinesRow{}
	for rows.Next() {
		var i ListPurchaseOrderLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.LineNo,
			&i.ItemID,
			&i.UnitID,
			&i.Qty,
			&i.Factor,
			&i.BaseQty,
			&i.UnitPrice,
			&i.Amount,
			&i.Note,
			&i.ItemCode,
			&i.ItemName,
			&i.ItemSpec,
			&i.ItemType,
			&i.UnitName,
			&i.BaseUnitName,
			&i.ReceivedQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchaseOrders = `-- name: ListPurchaseOrders :many

WITH page AS (
    SELECT o.id, o.company_id, o.doc_no, o.doc_date, o.supplier_id, o.warehouse_id, o.expected_date, o.currency, o.exchange_rate, o.tax_type_id, o.tax_rate, o.payment_term_id, o.untaxed_amount, o.tax_amount, o.total_amount, o.status, o.note, o.submitted_by, o.submitted_at, o.approved_by, o.approved_at, o.closed_by, o.closed_at, o.created_by, o.updated_by, o.version, o.created_at, o.updated_at FROM purchase_orders o
    WHERE o.company_id = $1
      AND ($2::text IS NULL OR o.status = $2)
      AND ($3::bigint IS NULL OR o.supplier_id = $3)
      AND ($4::text IS NULL OR o.doc_no ILIKE '%' || $4 || '%')
      AND ($5::date IS NULL OR o.doc_date >= $5)
      AND ($6::date IS NULL OR o.doc_date <= $6)
    ORDER BY o.doc_date DESC, o.id DESC
    LIMIT $8 OFFSET $7
)
SELECT o.id, o.doc_no, o.doc_date, o.expected_date, o.status, o.currency, o.total_amount, o.note,
       o.version, o.updated_at, s.code AS supplier_code, s.name AS supplier_name, cu.name AS created_by_name,
       -- 交貨狀態:依已過帳進貨量判斷(none 未交 / partial 部分 / full 交齊)
       (CASE
            WHEN NOT EXISTS (SELECT 1 FROM purchase_order_lines l WHERE l.order_id = o.id) THEN 'none'
            WHEN NOT EXISTS (
                SELECT 1 FROM purchase_order_lines l
                WHERE l.order_id = o.id AND l.qty > (
                    SELECT COALESCE(SUM(rl.qty), 0) FROM goods_receipt_lines rl
                    JOIN goods_receipts r ON r.id = rl.receipt_id
                    WHERE rl.po_line_id = l.id AND r.status = 'posted')) THEN 'full'
            WHEN EXISTS (
                SELECT 1 FROM goods_receipt_lines rl
                JOIN goods_receipts r ON r.id = rl.receipt_id
                JOIN purchase_order_lines l ON l.id = rl.po_line_id
                WHERE l.order_id = o.id AND r.status = 'posted') THEN 'partial'
            ELSE 'none' END)::text AS receipt_state
FROM page o
JOIN suppliers s ON s.id = o.supplier_id
LEFT JOIN users cu ON cu.id = o.created_by
ORDER BY o.doc_date DESC, o.id DESC
`

type ListPurchaseOrdersParams struct {
	CompanyID  int64
	Status     *string
	SupplierID *int64
	Keyword    *string
	FromDate   *time.Time
	ToDate     *time.Time
	Off        int32
	Lim        int32
}

type ListPurchaseOrdersRow struct {
	ID            int64
	DocNo         string
	DocDate       time.Time
	ExpectedDate  *time.Time
	Status        string
	Currency      string
	TotalAmount   decimal.Decimal
	Note          string
	Version       int32
	UpdatedAt     time.Time
	SupplierCode  string
	SupplierName  string
	CreatedByName *string
	ReceiptState  string
}

// ======== 採購單 ========
// 先依條件排序取出該頁,再對這一頁計算交貨狀態(相關子查詢只算 @lim 次,不是全部單據;壓測 12,000 張單 94 ms → 個位數)
func (q *Queries) ListPurchaseOrders(ctx context.Context, arg ListPurchaseOrdersParams) ([]ListPurchaseOrdersRow, error) {
	rows, err := q.db.Query(ctx, listPurchaseOrders,
		arg.CompanyID,
		arg.Status,
		arg.SupplierID,
		arg.Keyword,
		arg.FromDate,
		arg.ToDate,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPurchaseOrdersRow{}
	for rows.Next() {
		var i ListPurchaseOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.DocNo,
			&i.DocDate,
			&i.ExpectedDate,
			&i.Status,
			&i.Currency,
			&i.TotalAmount,
			&i.Note,
			&i.Version,
			&i.UpdatedAt,
			&i.SupplierCode,
			&i.SupplierName,
			&i.CreatedByName,
			&i.ReceiptState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockGoodsReceipt = `-- name: LockGoodsReceipt :one
SELECT id, company_id, doc_type, doc_no, doc_date, supplier_id, warehouse_id, currency, exchange_rate, tax_type_id, tax_rate, payment_term_id, invoice_no, untaxed_amount, tax_amount, total_amount, base_untaxed, base_tax, base_total, status, note, submitted_by, submitted_at, approved_by, approved_at, posted_by, posted_at, created_by, updated_by, version, created_at, updated_at, invoice_date, invoice_kind FROM goods_receipts WHERE id = $1 AND company_id = $2 FOR UPDATE
`

type LockGoodsReceiptParams struct {
	ID        int64
	CompanyID int64
}

func (q *Queries) LockGoodsReceipt(ctx context.Context, arg LockGoodsReceiptParams) (GoodsReceipt, error) {
	row := q.db.QueryRow(ctx, lockGoodsReceipt, arg.ID, arg.CompanyID)
	var i GoodsReceipt
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocType,
		&i.DocNo,
		&i.DocDate,
		&i.SupplierID,
		&i.WarehouseID,
		&i.Currency,
		&i.ExchangeRate,
		&i.TaxTypeID,
		&i.TaxRate,
		&i.PaymentTermID,
		&i.InvoiceNo,
		&i.UntaxedAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.BaseUntaxed,
		&i.BaseTax,
		&i.BaseTotal,
		&i.Status,
		&i.Note,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.PostedBy,
		&i.PostedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InvoiceDate,
		&i.InvoiceKind,
	)
	return i, err
}

const lockGoodsReceipts = `-- name: LockGoodsReceipts :many
SELECT id, doc_no, doc_type, status FROM goods_receipts
WHERE company_id = $1 AND id = ANY($2::bigint[])
ORDER BY id
FOR UPDATE
`

type LockGoodsReceiptsParams struct {
	CompanyID int64
	Ids       []int64
}

type LockGoodsReceiptsRow struct {
	ID      int64
	DocNo   string
	DocType string
	Status  string
}

// 退出過帳時鎖定來源進貨單(依 id 排序)
func (q *Queries) LockGoodsReceipts(ctx context.Context, arg LockGoodsReceiptsParams) ([]LockGoodsReceiptsRow, error) {
	rows, err := q.db.Query(ctx, lockGoodsReceipts, arg.CompanyID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockGoodsReceiptsRow{}
	for rows.Next() {
		var i LockGoodsReceiptsRow
		if err := rows.Scan(
			&i.ID,
			&i.DocNo,
			&i.DocType,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPayableBySource = `-- name: LockPayableBySource :one
SELECT id, company_id, supplier_id, source_type, source_id, source_no, doc_date, due_date, currency, exchange_rate, amount, base_amount, paid_amount, created_by, created_at, updated_at, import_batch_id FROM accounts_payable WHERE source_type = $1 AND source_id = $2 FOR UPDATE
`

type LockPayableBySourceParams struct {
	SourceType string
	SourceID   int64
}

func (q *Queries) LockPayableBySource(ctx context.Context, arg LockPayableBySourceParams) (AccountsPayable, error) {
	row := q.db.QueryRow(ctx, lockPayableBySource, arg.SourceType, arg.SourceID)
	var i AccountsPayable
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SupplierID,
		&i.SourceType,
		&i.SourceID,
		&i.SourceNo,
		&i.DocDate,
		&i.DueDate,
		&i.Currency,
		&i.ExchangeRate,
		&i.Amount,
		&i.BaseAmount,
		&i.PaidAmount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImportBatchID,
	)
	return i, err
}

const lockPurchaseOrder = `-- name: LockPurchaseOrder :one
SELECT id, company_id, doc_no, doc_date, supplier_id, warehouse_id, expected_date, currency, exchange_rate, tax_type_id, tax_rate, payment_term_id, untaxed_amount, tax_amount, total_amount, status, note, submitted_by, submitted_at, approved_by, approved_at, closed_by, closed_at, created_by, updated_by, version, created_at, updated_at FROM purchase_orders WHERE id = $1 AND company_id = $2 FOR UPDATE
`

type LockPurchaseOrderParams struct {
	ID        int64
	CompanyID int64
}

func (q *Queries) LockPurchaseOrder(ctx context.Context, arg LockPurchaseOrderParams) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, lockPurchaseOrder, arg.ID, arg.CompanyID)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocNo,
		&i.DocDate,
		&i.SupplierID,
		&i.WarehouseID,
		&i.ExpectedDate,
		&i.Currency,
		&i.ExchangeRate,
		&i.TaxTypeID,
		&i.TaxRate,
		&i.PaymentTermID,
		&i.UntaxedAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.Status,
		&i.Note,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockPurchaseOrders = `-- name: LockPurchaseOrders :many
SELECT id, doc_no, status FROM purchase_orders
WHERE company_id = $1 AND id = ANY($2::bigint[])
ORDER BY id
FOR UPDATE
`

type LockPurchaseOrdersParams struct {
	CompanyID int64
	Ids       []int64
}

type LockPurchaseOrdersRow struct {
	ID     int64
	DocNo  string
	Status string
}

// 進貨過帳時鎖定來源採購單(依 id 排序,上鎖順序一致)
func (q *Queries) LockPurchaseOrders(ctx context.Context, arg LockPurchaseOrdersParams) ([]LockPurchaseOrdersRow, error) {
	rows, err := q.db.Query(ctx, lockPurchaseOrders, arg.CompanyID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockPurchaseOrdersRow{}
	for rows.Next() {
		var i LockPurchaseOrdersRow
		if err := rows.Scan(&i.ID, &i.DocNo, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const outstandingPurchaseLines = `-- name: OutstandingPurchaseLines :many
SELECT l.id AS po_line_id, o.id AS order_id, o.doc_no, o.doc_date, o.expected_date, o.supplier_id,
       s.code AS supplier_code, s.name AS supplier_name, o.currency, o.warehouse_id,
       l.line_no, l.item_id, i.code AS item_code, i.name AS item_name, i.spec AS item_spec,
       l.unit_id, u.name AS unit_name, l.qty, l.unit_price, rec.received_qty,
       (l.qty - rec.received_qty)::numeric AS remaining_qty
FROM purchase_order_lines l
JOIN purchase_orders o ON o.id = l.order_id
JOIN suppliers s ON s.id = o.supplier_id
JOIN items i ON i.id = l.item_id
JOIN units u ON u.id = l.unit_id
CROSS JOIN LATERAL (
    SELECT COALESCE(SUM(rl.qty), 0)::numeric AS received_qty FROM goods_receipt_lines rl
    JOIN goods_receipts r ON r.id = rl.receipt_id
    WHERE rl.po_line_id = l.id AND r.status = 'posted'
) rec
WHERE o.company_id = $1 AND o.status = 'approved' AND l.qty > rec.received_qty
  AND ($2::bigint IS NULL OR o.supplier_id = $2)
  AND ($3::text IS NULL OR o.currency = $3)
  AND ($4::text IS NULL
       OR o.doc_no ILIKE '%' || $4 || '%'
       OR i.code ILIKE '%' || $4 || '%'
       OR i.name ILIKE '%' || $4 || '%')
  AND ($5::date IS NULL OR o.expected_date <= $5)
ORDER BY o.expected_date NULLS LAST, o.doc_no, l.line_no
LIMIT $7 OFFSET $6
`

type OutstandingPurchaseLinesParams struct {
	CompanyID  int64
	SupplierID *int64
	Currency   *string
	Keyword    *string
	DueBefore  *time.Time
	Off        int32
	Lim        int32
}

type OutstandingPurchaseLinesRow struct {
	PoLineID     int64
	OrderID      int64
	DocNo        string
	DocDate      time.Time
	ExpectedDate *time.Time
	SupplierID   int64
	SupplierCode string
	SupplierName string
	Currency     string
	WarehouseID  int64
	LineNo       int32
	ItemID       int64
	ItemCode     string
	ItemName     string
	ItemSpec     string
	UnitID       int64
	UnitName     string
	Qty          decimal.Decimal
	UnitPrice    decimal.Decimal
	ReceivedQty  decimal.Decimal
	RemainingQty decimal.Decimal
}

// 未交貨明細:已核准採購單中尚未交齊的明細(未交貨清單、進貨單帶入用)
func (q *Queries) OutstandingPurchaseLines(ctx context.Context, arg OutstandingPurchaseLinesParams) ([]OutstandingPurchaseLinesRow, error) {
	rows, err := q.db.Query(ctx, outstandingPurchaseLines,
		arg.CompanyID,
		arg.SupplierID,
		arg.Currency,
		arg.Keyword,
		arg.DueBefore,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutstandingPurchaseLinesRow{}
	for rows.Next() {
		var i OutstandingPurchaseLinesRow
		if err := rows.Scan(
			&i.PoLineID,
			&i.OrderID,
			&i.DocNo,
			&i.DocDate,
			&i.ExpectedDate,
			&i.SupplierID,
			&i.SupplierCode,
			&i.SupplierName,
			&i.Currency,
			&i.WarehouseID,
			&i.LineNo,
			&i.ItemID,
			&i.ItemCode,
			&i.ItemName,
			&i.ItemSpec,
			&i.UnitID,
			&i.UnitName,
			&i.Qty,
			&i.UnitPrice,
			&i.ReceivedQty,
			&i.RemainingQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const poLineRefs = `-- name: PoLineRefs :many
SELECT l.id, l.order_id, o.doc_no, o.status, o.supplier_id, o.currency, l.item_id, l.unit_id, l.qty,
       (SELECT COALESCE(SUM(rl.qty), 0) FROM goods_receipt_lines rl
        JOIN goods_receipts r ON r.id = rl.receipt_id
        WHERE rl.po_line_id = l.id AND r.status = 'posted' AND r.id <> $1::bigint)::numeric
           AS received_qty
FROM purchase_order_lines l
JOIN purchase_orders o ON o.id = l.order_id
WHERE o.company_id = $2 AND l.id = ANY($3::bigint[])
`

type PoLineRefsParams struct {
	ExcludeReceiptID int64
	CompanyID        int64
	Ids              []int64
}

type PoLineRefsRow struct {
	ID          int64
	OrderID     int64
	DocNo       string
	Status      string
	SupplierID  int64
	Currency    string
	ItemID      int64
	UnitID      int64
	Qty         decimal.Decimal
	ReceivedQty decimal.Decimal
}

// 進貨明細引用的採購明細,以及「其他」已過帳進貨單的已交量
func (q *Queries) PoLineRefs(ctx context.Context, arg PoLineRefsParams) ([]PoLineRefsRow, error) {
	rows, err := q.db.Query(ctx, poLineRefs, arg.ExcludeReceiptID, arg.CompanyID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PoLineRefsRow{}
	for rows.Next() {
		var i PoLineRefsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.DocNo,
			&i.Status,
			&i.SupplierID,
			&i.Currency,
			&i.ItemID,
			&i.UnitID,
			&i.Qty,
			&i.ReceivedQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purchaseOrderReceiptNo = `-- name: PurchaseOrderReceiptNo :one
SELECT r.doc_no FROM goods_receipt_lines rl
JOIN goods_receipts r ON r.id = rl.receipt_id
JOIN purchase_order_lines l ON l.id = rl.po_line_id
WHERE l.order_id = $1 AND r.status <> 'voided'
LIMIT 1
`

// 採購單是否已被未作廢的進貨單引用(取消核准、作廢前檢查)
func (q *Queries) PurchaseOrderReceiptNo(ctx context.Context, orderID int64) (string, error) {
	row := q.db.QueryRow(ctx, purchaseOrderReceiptNo, orderID)
	var doc_no string
	err := row.Scan(&doc_no)
	return doc_no, err
}

const receiptLineLots = `-- name: ReceiptLineLots :many
SELECT id, lot_no, expiry_date FROM goods_receipt_lines WHERE id = ANY($1::bigint[])
`

type ReceiptLineLotsRow struct {
	ID         int64
	LotNo      string
	ExpiryDate *time.Time
}

// 進貨退出預設沿用被退進貨明細的批號
func (q *Queries) ReceiptLineLots(ctx context.Context, ids []int64) ([]ReceiptLineLotsRow, error) {
	rows, err := q.db.Query(ctx, receiptLineLots, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReceiptLineLotsRow{}
	for rows.Next() {
		var i ReceiptLineLotsRow
		if err := rows.Scan(&i.ID, &i.LotNo, &i.ExpiryDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const receiptLineRefs = `-- name: ReceiptLineRefs :many
SELECT l.id, l.receipt_id, r.doc_no, r.doc_type, r.status, r.supplier_id, r.currency, l.item_id, l.unit_id, l.qty,
       (SELECT COALESCE(SUM(xl.qty), 0) FROM goods_receipt_lines xl
        JOIN goods_receipts x ON x.id = xl.receipt_id
        WHERE xl.receipt_line_id = l.id AND x.status = 'posted' AND x.id <> $1::bigint)::numeric
           AS returned_qty
FROM goods_receipt_lines l
JOIN goods_receipts r ON r.id = l.receipt_id
WHERE r.company_id = $2 AND l.id = ANY($3::bigint[])
`

type ReceiptLineRefsParams struct {
	ExcludeReceiptID int64
	CompanyID        int64
	Ids              []int64
}

type ReceiptLineRefsRow struct {
	ID          int64
	ReceiptID   int64
	DocNo       string
	DocType     string
	Status      string
	SupplierID  int64
	Currency    string
	ItemID      int64
	UnitID      int64
	Qty         decimal.Decimal
	ReturnedQty decimal.Decimal
}

// 退出明細引用的進貨明細,以及「其他」已過帳退出單的已退量
func (q *Queries) ReceiptLineRefs(ctx context.Context, arg ReceiptLineRefsParams) ([]ReceiptLineRefsRow, error) {
	rows, err := q.db.Query(ctx, receiptLineRefs, arg.ExcludeReceiptID, arg.CompanyID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReceiptLineRefsRow{}
	for rows.Next() {
		var i ReceiptLineRefsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReceiptID,
			&i.DocNo,
			&i.DocType,
			&i.Status,
			&i.SupplierID,
			&i.Currency,
			&i.ItemID,
			&i.UnitID,
			&i.Qty,
			&i.ReturnedQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const receiptReturnNo = `-- name: ReceiptReturnNo :one
SELECT x.doc_no FROM goods_receipt_lines xl
JOIN goods_receipts x ON x.id = xl.receipt_id
JOIN goods_receipt_lines l ON l.id = xl.receipt_line_id
WHERE l.receipt_id = $1 AND x.status <> 'voided'
LIMIT 1
`

// 進貨單是否已被未作廢的退出單引用(反過帳前檢查)
func (q *Queries) ReceiptReturnNo(ctx context.Context, receiptID int64) (string, error) {
	row := q.db.QueryRow(ctx, receiptReturnNo, receiptID)
	var doc_no string
	err := row.Scan(&doc_no)
	return doc_no, err
}

const returnableReceiptLines = `-- name: ReturnableReceiptLines :many
SELECT l.id AS receipt_line_id, r.id AS receipt_id, r.doc_no, r.doc_date, r.warehouse_id, l.line_no,
       l.item_id, i.code AS item_code, i.name AS item_name, i.spec AS item_spec, l.unit_id, u.name AS unit_name,
       l.qty, l.unit_price, ret.returned_qty, (l.qty - ret.returned_qty)::numeric AS remaining_qty
FROM goods_receipt_lines l
JOIN goods_receipts r ON r.id = l.receipt_id
JOIN items i ON i.id = l.item_id
JOIN units u ON u.id = l.unit_id
CROSS JOIN LATERAL (
    SELECT COALESCE(SUM(xl.qty), 0)::numeric AS returned_qty FROM goods_receipt_lines xl
    JOIN goods_receipts x ON x.id = xl.receipt_id
    WHERE xl.receipt_line_id = l.id AND x.status = 'posted'
) ret
WHERE r.company_id = $1 AND r.doc_type = 'receipt' AND r.status = 'posted'
  AND r.supplier_id = $2 AND r.currency = $3 AND l.qty > ret.returned_qty
  AND ($4::text IS NULL
       OR r.doc_no ILIKE '%' || $4 || '%'
       OR i.code ILIKE '%' || $4 || '%'
       OR i.name ILIKE '%' || $4 || '%')
ORDER BY r.doc_date DESC, r.doc_no DESC, l.line_no
LIMIT 200
`

type ReturnableReceiptLinesParams struct {
	CompanyID  int64
	SupplierID int64
	Currency   string
	Keyword    *string
}

type ReturnableReceiptLinesRow struct {
	ReceiptLineID int64
	ReceiptID     int64
	DocNo         string
	DocDate       time.Time
	WarehouseID   int64
	LineNo        int32
	ItemID        int64
	ItemCode      string
	ItemName      string
	ItemSpec      string
	UnitID        int64
	UnitName      string
	Qty           decimal.Decimal
	UnitPrice     decimal.Decimal
	ReturnedQty   decimal.Decimal
	RemainingQty  decimal.Decimal
}

// 可退貨的進貨明細:已過帳進貨單中尚未退完的明細(退出單帶入用)
func (q *Queries) ReturnableReceiptLines(ctx context.Context, arg ReturnableReceiptLinesParams) ([]ReturnableReceiptLinesRow, error) {
	rows, err := q.db.Query(ctx, returnableReceiptLines,
		arg.CompanyID,
		arg.SupplierID,
		arg.Currency,
		arg.Keyword,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReturnableReceiptLinesRow{}
	for rows.Next() {
		var i ReturnableReceiptLinesRow
		if err := rows.Scan(
			&i.ReceiptLineID,
			&i.ReceiptID,
			&i.DocNo,
			&i.DocDate,
			&i.WarehouseID,
			&i.LineNo,
			&i.ItemID,
			&i.ItemCode,
			&i.ItemName,
			&i.ItemSpec,
			&i.UnitID,
			&i.UnitName,
			&i.Qty,
			&i.UnitPrice,
			&i.ReturnedQty,
			&i.RemainingQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGoodsReceiptStatus = `-- name: SetGoodsReceiptStatus :one
UPDATE goods_receipts
SET status       = $1,
    submitted_by = CASE WHEN $2::text = 'submit' THEN $3::bigint ELSE submitted_by END,
    submitted_at = CASE WHEN $2::text = 'submit' THEN now() ELSE submitted_at END,
    approved_by  = CASE WHEN $2::text = 'approve' THEN $3::bigint
                        WHEN $2::text IN ('reject', 'unapprove') THEN NULL ELSE approved_by END,
    approved_at  = CASE WHEN $2::text = 'approve' THEN now()
                        WHEN $2::text IN ('reject', 'unapprove') THEN NULL ELSE approved_at END,
    posted_by    = CASE WHEN $2::text = 'post' THEN $3::bigint
                        WHEN $2::text = 'unpost' THEN NULL ELSE posted_by END,
    posted_at    = CASE WHEN $2::text = 'post' THEN now()
                        WHEN $2::text = 'unpost' THEN NULL ELSE posted_at END,
    version      = version + 1,
    updated_by   = $3::bigint
WHERE id = $4 AND company_id = $5 AND version = $6
RETURNING id, company_id, doc_type, doc_no, doc_date, supplier_id, warehouse_id, currency, exchange_rate, tax_type_id, tax_rate, payment_term_id, invoice_no, untaxed_amount, tax_amount, total_amount, base_untaxed, base_tax, base_total, status, note, submitted_by, submitted_at, approved_by, approved_at, posted_by, posted_at, created_by, updated_by, version, created_at, updated_at, invoice_date, invoice_kind
`

type SetGoodsReceiptStatusParams struct {
	Status    string
	Action    string
	ActorID   int64
	ID        int64
	CompanyID int64
	Version   int32
}

func (q *Queries) SetGoodsReceiptStatus(ctx context.Context, arg SetGoodsReceiptStatusParams) (GoodsReceipt, error) {
	row := q.db.QueryRow(ctx, setGoodsReceiptStatus,
		arg.Status,
		arg.Action,
		arg.ActorID,
		arg.ID,
		arg.CompanyID,
		arg.Version,
	)
	var i GoodsReceipt
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocType,
		&i.DocNo,
		&i.DocDate,
		&i.SupplierID,
		&i.WarehouseID,
		&i.Currency,
		&i.ExchangeRate,
		&i.TaxTypeID,
		&i.TaxRate,
		&i.PaymentTermID,
		&i.InvoiceNo,
		&i.UntaxedAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.BaseUntaxed,
		&i.BaseTax,
		&i.BaseTotal,
		&i.Status,
		&i.Note,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.PostedBy,
		&i.PostedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InvoiceDate,
		&i.InvoiceKind,
	)
	return i, err
}

const setPurchaseOrderStatus = `-- name: SetPurchaseOrderStatus :one
UPDATE purchase_orders
SET status       = $1,
    submitted_by = CASE WHEN $2::text = 'submit' THEN $3::bigint ELSE submitted_by END,
    submitted_at = CASE WHEN $2::text = 'submit' THEN now() ELSE submitted_at END,
    approved_by  = CASE WHEN $2::text = 'approve' THEN $3::bigint
                        WHEN $2::text IN ('reject', 'unapprove') THEN NULL ELSE approved_by END,
    approved_at  = CASE WHEN $2::text = 'approve' THEN now()
                        WHEN $2::text IN ('reject', 'unapprove') THEN NULL ELSE approved_at END,
    closed_by    = CASE WHEN $2::text = 'close' THEN $3::bigint
                        WHEN $2::text = 'reopen' THEN NULL ELSE closed_by END,
    closed_at    = CASE WHEN $2::text = 'close' THEN now()
                        WHEN $2::text = 'reopen' THEN NULL ELSE closed_at END,
    version      = version + 1,
    updated_by   = $3::bigint
WHERE id = $4 AND company_id = $5 AND version = $6
RETURNING id, company_id, doc_no, doc_date, supplier_id, warehouse_id, expected_date, currency, exchange_rate, tax_type_id, tax_rate, payment_term_id, untaxed_amount, tax_amount, total_amount, status, note, submitted_by, submitted_at, approved_by, approved_at, closed_by, closed_at, created_by, updated_by, version, created_at, updated_at
`

type SetPurchaseOrderStatusParams struct {
	Status    string
	Action    string
	ActorID   int64
	ID        int64
	CompanyID int64
	Version   int32
}

func (q *Queries) SetPurchaseOrderStatus(ctx context.Context, arg SetPurchaseOrderStatusParams) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, setPurchaseOrderStatus,
		arg.Status,
		arg.Action,
		arg.ActorID,
		arg.ID,
		arg.CompanyID,
		arg.Version,
	)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocNo,
		&i.DocDate,
		&i.SupplierID,
		&i.WarehouseID,
		&i.ExpectedDate,
		&i.Currency,
		&i.ExchangeRate,
		&i.TaxTypeID,
		&i.TaxRate,
		&i.PaymentTermID,
		&i.UntaxedAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.Status,
		&i.Note,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const supplierForDoc = `-- name: SupplierForDoc :one
SELECT id, code, name, is_active FROM suppliers WHERE id = $1 AND company_id = $2
`

type SupplierForDocParams struct {
	ID        int64
	CompanyID int64
}

type SupplierForDocRow struct {
	ID       int64
	Code     string
	Name     string
	IsActive bool
}

func (q *Queries) SupplierForDoc(ctx context.Context, arg SupplierForDocParams) (SupplierForDocRow, error) {
	row := q.db.QueryRow(ctx, supplierForDoc, arg.ID, arg.CompanyID)
	var i SupplierForDocRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.IsActive,
	)
	return i, err
}

const supplierOptions = `-- name: SupplierOptions :many
SELECT id, code, name, short_name, currency, tax_type_id, payment_term_id
FROM suppliers
WHERE company_id = $1 AND is_active
  AND ($2::text IS NULL
       OR code ILIKE '%' || $2 || '%'
       OR name ILIKE '%' || $2 || '%'
       OR short_name ILIKE '%' || $2 || '%')
ORDER BY code
LIMIT 20
`

type SupplierOptionsParams struct {
	CompanyID int64
	Keyword   *string
}

type SupplierOptionsRow struct {
	ID            int64
	Code          string
	Name          string
	ShortName     string
	Currency      string
	TaxTypeID     *int64
	PaymentTermID *int64
}

// 開單選供應商:只需登入,只回傳啟用中的精簡欄位
func (q *Queries) SupplierOptions(ctx context.Context, arg SupplierOptionsParams) ([]SupplierOptionsRow, error) {
	rows, err := q.db.Query(ctx, supplierOptions, arg.CompanyID, arg.Keyword)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SupplierOptionsRow{}
	for rows.Next() {
		var i SupplierOptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.ShortName,
			&i.Currency,
			&i.TaxTypeID,
			&i.PaymentTermID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGoodsReceiptHeader = `-- name: UpdateGoodsReceiptHeader :one
UPDATE goods_receipts
SET doc_date = $1, supplier_id = $2, warehouse_id = $3, currency = $4,
    exchange_rate = $5, tax_type_id = $6, tax_rate = $7,
    payment_term_id = $8, invoice_no = $9, invoice_date = $10,
    invoice_kind = $11, untaxed_amount = $12,
    tax_amount = $13, total_amount = $14, base_untaxed = $15, base_tax = $16,
    base_total = $17, note = $18, version = version + 1, updated_by = $19
WHERE id = $20 AND company_id = $21 AND version = $22 AND status = 'draft'
RETURNING id, company_id, doc_type, doc_no, doc_date, supplier_id, warehouse_id, currency, exchange_rate, tax_type_id, tax_rate, payment_term_id, invoice_no, untaxed_amount, tax_amount, total_amount, base_untaxed, base_tax, base_total, status, note, submitted_by, submitted_at, approved_by, approved_at, posted_by, posted_at, created_by, updated_by, version, created_at, updated_at, invoice_date, invoice_kind
`

type UpdateGoodsReceiptHeaderParams struct {
	DocDate       time.Time
	SupplierID    int64
	WarehouseID   int64
	Currency      string
	ExchangeRate  decimal.Decimal
	TaxTypeID     int64
	TaxRate       decimal.Decimal
	PaymentTermID *int64
	InvoiceNo     string
	InvoiceDate   *time.Time
	InvoiceKind   string
	UntaxedAmount decimal.Decimal
	TaxAmount     decimal.Decimal
	TotalAmount   decimal.Decimal
	BaseUntaxed   decimal.Decimal
	BaseTax       decimal.Decimal
	BaseTotal     decimal.Decimal
	Note          string
	UpdatedBy     *int64
	ID            int64
	CompanyID     int64
	Version       int32
}

func (q *Queries) UpdateGoodsReceiptHeader(ctx context.Context, arg UpdateGoodsReceiptHeaderParams) (GoodsReceipt, error) {
	row := q.db.QueryRow(ctx, updateGoodsReceiptHeader,
		arg.DocDate,
		arg.SupplierID,
		arg.WarehouseID,
		arg.Currency,
		arg.ExchangeRate,
		arg.TaxTypeID,
		arg.TaxRate,
		arg.PaymentTermID,
		arg.InvoiceNo,
		arg.InvoiceDate,
		arg.InvoiceKind,
		arg.UntaxedAmount,
		arg.TaxAmount,
		arg.TotalAmount,
		arg.BaseUntaxed,
		arg.BaseTax,
		arg.BaseTotal,
		arg.Note,
		arg.UpdatedBy,
		arg.ID,
		arg.CompanyID,
		arg.Version,
	)
	var i GoodsReceipt
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocType,
		&i.DocNo,
		&i.DocDate,
		&i.SupplierID,
		&i.WarehouseID,
		&i.Currency,
		&i.ExchangeRate,
		&i.TaxTypeID,
		&i.TaxRate,
		&i.PaymentTermID,
		&i.InvoiceNo,
		&i.UntaxedAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.BaseUntaxed,
		&i.BaseTax,
		&i.BaseTotal,
		&i.Status,
		&i.Note,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.PostedBy,
		&i.PostedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InvoiceDate,
		&i.InvoiceKind,
	)
	return i, err
}

const updatePurchaseOrderHeader = `-- name: UpdatePurchaseOrderHeader :one
UPDATE purchase_orders
SET doc_date = $1, supplier_id = $2, warehouse_id = $3,
    expected_date = $4, currency = $5, exchange_rate = $6,
    tax_type_id = $7, tax_rate = $8, payment_term_id = $9,
    untaxed_amount = $10, tax_amount = $11, total_amount = $12, note = $13,
    version = version + 1, updated_by = $14
WHERE id = $15 AND company_id = $16 AND version = $17 AND status = 'draft'
RETURNING id, company_id, doc_no, doc_date, supplier_id, warehouse_id, expected_date, currency, exchange_rate, tax_type_id, tax_rate, payment_term_id, untaxed_amount, tax_amount, total_amount, status, note, submitted_by, submitted_at, approved_by, approved_at, closed_by, closed_at, created_by, updated_by, version, created_at, updated_at
`

type UpdatePurchaseOrderHeaderParams struct {
	DocDate       time.Time
	SupplierID    int64
	WarehouseID   int64
	ExpectedDate  *time.Time
	Currency      string
	ExchangeRate  decimal.Decimal
	TaxTypeID     int64
	TaxRate       decimal.Decimal
	PaymentTermID *int64
	UntaxedAmount decimal.Decimal
	TaxAmount     decimal.Decimal
	TotalAmount   decimal.Decimal
	Note          string
	UpdatedBy     *int64
	ID            int64
	CompanyID     int64
	Version       int32
}

func (q *Queries) UpdatePurchaseOrderHeader(ctx context.Context, arg UpdatePurchaseOrderHeaderParams) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, updatePurchaseOrderHeader,
		arg.DocDate,
		arg.SupplierID,
		arg.WarehouseID,
		arg.ExpectedDate,
		arg.Currency,
		arg.ExchangeRate,
		arg.TaxTypeID,
		arg.TaxRate,
		arg.PaymentTermID,
		arg.UntaxedAmount,
		arg.TaxAmount,
		arg.TotalAmount,
		arg.Note,
		arg.UpdatedBy,
		arg.ID,
		arg.CompanyID,
		arg.Version,
	)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocNo,
		&i.DocDate,
		&i.SupplierID,
		&i.WarehouseID,
		&i.ExpectedDate,
		&i.Currency,
		&i.ExchangeRate,
		&i.TaxTypeID,
		&i.TaxRate,
		&i.PaymentTermID,
		&i.UntaxedAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.Status,
		&i.Note,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
