// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roles.sql

package db

import (
	"context"
	"time"
)

const addRolePermissions = `-- name: AddRolePermissions :exec
INSERT INTO role_permissions (role_id, permission)
SELECT $1, unnest($2::text[])
`

type AddRolePermissionsParams struct {
	RoleID      int64
	Permissions []string
}

func (q *Queries) AddRolePermissions(ctx context.Context, arg AddRolePermissionsParams) error {
	_, err := q.db.Exec(ctx, addRolePermissions, arg.RoleID, arg.Permissions)
	return err
}

const countRolesByIDs = `-- name: CountRolesByIDs :one
SELECT count(*) FROM roles WHERE company_id = $1 AND id = ANY($2::bigint[])
`

type CountRolesByIDsParams struct {
	CompanyID int64
	Ids       []int64
}

func (q *Queries) CountRolesByIDs(ctx context.Context, arg CountRolesByIDsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRolesByIDs, arg.CompanyID, arg.Ids)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRolesUsers = `-- name: CountRolesUsers :one
SELECT count(*) FROM user_roles WHERE role_id = $1
`

func (q *Queries) CountRolesUsers(ctx context.Context, roleID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countRolesUsers, roleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (company_id, code, name, description, data_scope, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $6)
RETURNING id, company_id, code, name, description, data_scope, is_active, version, created_by, updated_by, created_at, updated_at
`

type CreateRoleParams struct {
	CompanyID   int64
	Code        string
	Name        string
	Description string
	DataScope   string
	CreatedBy   *int64
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.CompanyID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.DataScope,
		arg.CreatedBy,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.DataScope,
		&i.IsActive,
		&i.Version,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :execrows
DELETE FROM roles WHERE id = $1 AND company_id = $2
`

type DeleteRoleParams struct {
	ID        int64
	CompanyID int64
}

func (q *Queries) DeleteRole(ctx context.Context, arg DeleteRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRole, arg.ID, arg.CompanyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRolePermissions = `-- name: DeleteRolePermissions :exec
DELETE FROM role_permissions WHERE role_id = $1
`

func (q *Queries) DeleteRolePermissions(ctx context.Context, roleID int64) error {
	_, err := q.db.Exec(ctx, deleteRolePermissions, roleID)
	return err
}

const getRole = `-- name: GetRole :one
SELECT id, company_id, code, name, description, data_scope, is_active, version, created_by, updated_by, created_at, updated_at FROM roles WHERE id = $1 AND company_id = $2
`

type GetRoleParams struct {
	ID        int64
	CompanyID int64
}

func (q *Queries) GetRole(ctx context.Context, arg GetRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRole, arg.ID, arg.CompanyID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.DataScope,
		&i.IsActive,
		&i.Version,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRolePermissions = `-- name: ListRolePermissions :many
SELECT permission FROM role_permissions WHERE role_id = $1 ORDER BY permission
`

func (q *Queries) ListRolePermissions(ctx context.Context, roleID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var permission string
		if err := rows.Scan(&permission); err != nil {
			return nil, err
		}
		items = append(items, permission)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT r.id, r.company_id, r.code, r.name, r.description, r.data_scope, r.is_active, r.version, r.created_by, r.updated_by, r.created_at, r.updated_at, (SELECT count(*) FROM user_roles ur WHERE ur.role_id = r.id) AS user_count
FROM roles r
WHERE r.company_id = $1
ORDER BY r.code
`

type ListRolesRow struct {
	ID          int64
	CompanyID   int64
	Code        string
	Name        string
	Description string
	DataScope   string
	IsActive    bool
	Version     int32
	CreatedBy   *int64
	UpdatedBy   *int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	UserCount   int64
}

func (q *Queries) ListRoles(ctx context.Context, companyID int64) ([]ListRolesRow, error) {
	rows, err := q.db.Query(ctx, listRoles, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolesRow{}
	for rows.Next() {
		var i ListRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.DataScope,
			&i.IsActive,
			&i.Version,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles
SET code        = $1,
    name        = $2,
    description = $3,
    data_scope  = $4,
    is_active   = $5,
    version     = version + 1,
    updated_by  = $6
WHERE id = $7 AND company_id = $8 AND version = $9
RETURNING id, company_id, code, name, description, data_scope, is_active, version, created_by, updated_by, created_at, updated_at
`

type UpdateRoleParams struct {
	Code        string
	Name        string
	Description string
	DataScope   string
	IsActive    bool
	UpdatedBy   *int64
	ID          int64
	CompanyID   int64
	Version     int32
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.DataScope,
		arg.IsActive,
		arg.UpdatedBy,
		arg.ID,
		arg.CompanyID,
		arg.Version,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.DataScope,
		&i.IsActive,
		&i.Version,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
