// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sales.sql

package db

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const addDeliveryLine = `-- name: AddDeliveryLine :exec
INSERT INTO delivery_lines (delivery_id, line_no, item_id, unit_id, qty, factor, base_qty, unit_price, amount,
                            base_amount, so_line_id, delivery_line_id, note, lot_no, expiry_date, bin_code)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
        $11, $12, $13, $14, $15, $16)
`

type AddDeliveryLineParams struct {
	DeliveryID     int64
	LineNo         int32
	ItemID         int64
	UnitID         int64
	Qty            decimal.Decimal
	Factor         decimal.Decimal
	BaseQty        decimal.Decimal
	UnitPrice      decimal.Decimal
	Amount         decimal.Decimal
	BaseAmount     decimal.Decimal
	SoLineID       *int64
	DeliveryLineID *int64
	Note           string
	LotNo          string
	ExpiryDate     *time.Time
	BinCode        string
}

func (q *Queries) AddDeliveryLine(ctx context.Context, arg AddDeliveryLineParams) error {
	_, err := q.db.Exec(ctx, addDeliveryLine,
		arg.DeliveryID,
		arg.LineNo,
		arg.ItemID,
		arg.UnitID,
		arg.Qty,
		arg.Factor,
		arg.BaseQty,
		arg.UnitPrice,
		arg.Amount,
		arg.BaseAmount,
		arg.SoLineID,
		arg.DeliveryLineID,
		arg.Note,
		arg.LotNo,
		arg.ExpiryDate,
		arg.BinCode,
	)
	return err
}

const addSalesOrderLine = `-- name: AddSalesOrderLine :exec
INSERT INTO sales_order_lines (order_id, line_no, item_id, unit_id, qty, factor, base_qty, unit_price, amount, note)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type AddSalesOrderLineParams struct {
	OrderID   int64
	LineNo    int32
	ItemID    int64
	UnitID    int64
	Qty       decimal.Decimal
	Factor    decimal.Decimal
	BaseQty   decimal.Decimal
	UnitPrice decimal.Decimal
	Amount    decimal.Decimal
	Note      string
}

func (q *Queries) AddSalesOrderLine(ctx context.Context, arg AddSalesOrderLineParams) error {
	_, err := q.db.Exec(ctx, addSalesOrderLine,
		arg.OrderID,
		arg.LineNo,
		arg.ItemID,
		arg.UnitID,
		arg.Qty,
		arg.Factor,
		arg.BaseQty,
		arg.UnitPrice,
		arg.Amount,
		arg.Note,
	)
	return err
}

const countDeliveries = `-- name: CountDeliveries :one
SELECT count(*) FROM deliveries d
LEFT JOIN users su ON su.id = d.sales_user_id
WHERE d.company_id = $1
  AND ($2::text IS NULL OR d.doc_type = $2)
  AND ($3::text IS NULL OR d.status = $3)
  AND ($4::bigint IS NULL OR d.customer_id = $4)
  AND ($5::text IS NULL OR d.doc_no ILIKE '%' || $5 || '%'
       OR d.invoice_no ILIKE '%' || $5 || '%')
  AND ($6::date IS NULL OR d.doc_date >= $6)
  AND ($7::date IS NULL OR d.doc_date <= $7)
  AND (NOT $8::boolean OR d.invoice_no = '')
  AND ($9::bigint IS NULL OR d.sales_user_id = $9)
  AND ($10::bigint IS NULL OR su.department_id = $10)
`

type CountDeliveriesParams struct {
	CompanyID   int64
	DocType     *string
	Status      *string
	CustomerID  *int64
	Keyword     *string
	FromDate    *time.Time
	ToDate      *time.Time
	NoInvoice   bool
	ScopeUserID *int64
	ScopeDeptID *int64
}

func (q *Queries) CountDeliveries(ctx context.Context, arg CountDeliveriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDeliveries,
		arg.CompanyID,
		arg.DocType,
		arg.Status,
		arg.CustomerID,
		arg.Keyword,
		arg.FromDate,
		arg.ToDate,
		arg.NoInvoice,
		arg.ScopeUserID,
		arg.ScopeDeptID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReceivables = `-- name: CountReceivables :one
SELECT count(*) AS total,
       COALESCE(SUM(CASE WHEN r.amount = 0 THEN 0 ELSE r.base_amount * (r.amount - r.paid_amount) / r.amount END), 0)::numeric AS base_amount_sum
FROM accounts_receivable r
JOIN customers c ON c.id = r.customer_id
LEFT JOIN users su ON su.id = c.sales_user_id
WHERE r.company_id = $1
  AND ($2::bigint IS NULL OR r.customer_id = $2)
  AND ($3::text IS NULL OR r.source_no ILIKE '%' || $3 || '%')
  AND ($4::date IS NULL OR r.doc_date >= $4)
  AND ($5::date IS NULL OR r.doc_date <= $5)
  AND (NOT $6::boolean OR r.amount <> r.paid_amount)
  AND ($7::bigint IS NULL OR c.sales_user_id = $7)
  AND ($8::bigint IS NULL OR su.department_id = $8)
`

type CountReceivablesParams struct {
	CompanyID   int64
	CustomerID  *int64
	Keyword     *string
	FromDate    *time.Time
	ToDate      *time.Time
	OpenOnly    bool
	ScopeUserID *int64
	ScopeDeptID *int64
}

type CountReceivablesRow struct {
	Total         int64
	BaseAmountSum decimal.Decimal
}

// base_amount_sum:未沖餘額的本位幣合計(依原幣餘額比例換算)
func (q *Queries) CountReceivables(ctx context.Context, arg CountReceivablesParams) (CountReceivablesRow, error) {
	row := q.db.QueryRow(ctx, countReceivables,
		arg.CompanyID,
		arg.CustomerID,
		arg.Keyword,
		arg.FromDate,
		arg.ToDate,
		arg.OpenOnly,
		arg.ScopeUserID,
		arg.ScopeDeptID,
	)
	var i CountReceivablesRow
	err := row.Scan(&i.Total, &i.BaseAmountSum)
	return i, err
}

const countSalesOrders = `-- name: CountSalesOrders :one
SELECT count(*) FROM sales_orders o
LEFT JOIN users su ON su.id = o.sales_user_id
WHERE o.company_id = $1
  AND ($2::text IS NULL OR o.doc_type = $2)
  AND ($3::text IS NULL OR o.status = $3)
  AND ($4::bigint IS NULL OR o.customer_id = $4)
  AND ($5::text IS NULL OR o.doc_no ILIKE '%' || $5 || '%'
       OR o.customer_po_no ILIKE '%' || $5 || '%')
  AND ($6::date IS NULL OR o.doc_date >= $6)
  AND ($7::date IS NULL OR o.doc_date <= $7)
  AND ($8::bigint IS NULL OR o.sales_user_id = $8)
  AND ($9::bigint IS NULL OR su.department_id = $9)
`

type CountSalesOrdersParams struct {
	CompanyID   int64
	DocType     *string
	Status      *string
	CustomerID  *int64
	Keyword     *string
	FromDate    *time.Time
	ToDate      *time.Time
	ScopeUserID *int64
	ScopeDeptID *int64
}

func (q *Queries) CountSalesOrders(ctx context.Context, arg CountSalesOrdersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSalesOrders,
		arg.CompanyID,
		arg.DocType,
		arg.Status,
		arg.CustomerID,
		arg.Keyword,
		arg.FromDate,
		arg.ToDate,
		arg.ScopeUserID,
		arg.ScopeDeptID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnshippedSalesLines = `-- name: CountUnshippedSalesLines :one
SELECT count(*)
FROM sales_order_lines l
JOIN sales_orders o ON o.id = l.order_id
JOIN items i ON i.id = l.item_id
LEFT JOIN users su ON su.id = o.sales_user_id
WHERE o.company_id = $1 AND o.doc_type = 'order' AND o.status = 'approved'
  AND l.qty > (SELECT COALESCE(SUM(dl.qty), 0) FROM delivery_lines dl
               JOIN deliveries d ON d.id = dl.delivery_id
               WHERE dl.so_line_id = l.id AND d.status = 'posted')
  AND ($2::bigint IS NULL OR o.customer_id = $2)
  AND ($3::text IS NULL OR o.currency = $3)
  AND ($4::text IS NULL
       OR o.doc_no ILIKE '%' || $4 || '%'
       OR o.customer_po_no ILIKE '%' || $4 || '%'
       OR i.code ILIKE '%' || $4 || '%'
       OR i.name ILIKE '%' || $4 || '%')
  AND ($5::date IS NULL OR o.delivery_date <= $5)
  AND ($6::bigint IS NULL OR o.sales_user_id = $6)
  AND ($7::bigint IS NULL OR su.department_id = $7)
`

type CountUnshippedSalesLinesParams struct {
	CompanyID   int64
	CustomerID  *int64
	Currency    *string
	Keyword     *string
	DueBefore   *time.Time
	ScopeUserID *int64
	ScopeDeptID *int64
}

func (q *Queries) CountUnshippedSalesLines(ctx context.Context, arg CountUnshippedSalesLinesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnshippedSalesLines,
		arg.CompanyID,
		arg.CustomerID,
		arg.Currency,
		arg.Keyword,
		arg.DueBefore,
		arg.ScopeUserID,
		arg.ScopeDeptID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDelivery = `-- name: CreateDelivery :one
INSERT INTO deliveries (company_id, doc_type, doc_no, doc_date, customer_id, sales_user_id, warehouse_id, currency,
                        exchange_rate, tax_type_id, tax_rate, payment_term_id, untaxed_amount, tax_amount,
                        total_amount, base_untaxed, base_tax, base_total, note, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        $9, $10, $11, $12, $13, $14,
        $15, $16, $17, $18, $19, $20, $20)
RETURNING id, company_id, doc_type, doc_no, doc_date, customer_id, sales_user_id, warehouse_id, currency, exchange_rate, tax_type_id, tax_rate, payment_term_id, invoice_no, invoice_date, untaxed_amount, tax_amount, total_amount, base_untaxed, base_tax, base_total, status, note, submitted_by, submitted_at, approved_by, approved_at, posted_by, posted_at, created_by, updated_by, version, created_at, updated_at
`

type CreateDeliveryParams struct {
	CompanyID     int64
	DocType       string
	DocNo         string
	DocDate       time.Time
	CustomerID    int64
	SalesUserID   *int64
	WarehouseID   int64
	Currency      string
	ExchangeRate  decimal.Decimal
	TaxTypeID     int64
	TaxRate       decimal.Decimal
	PaymentTermID *int64
	UntaxedAmount decimal.Decimal
	TaxAmount     decimal.Decimal
	TotalAmount   decimal.Decimal
	BaseUntaxed   decimal.Decimal
	BaseTax       decimal.Decimal
	BaseTotal     decimal.Decimal
	Note          string
	CreatedBy     *int64
}

func (q *Queries) CreateDelivery(ctx context.Context, arg CreateDeliveryParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, createDelivery,
		arg.CompanyID,
		arg.DocType,
		arg.DocNo,
		arg.DocDate,
		arg.CustomerID,
		arg.SalesUserID,
		arg.WarehouseID,
		arg.Currency,
		arg.ExchangeRate,
		arg.TaxTypeID,
		arg.TaxRate,
		arg.PaymentTermID,
		arg.UntaxedAmount,
		arg.TaxAmount,
		arg.TotalAmount,
		arg.BaseUntaxed,
		arg.BaseTax,
		arg.BaseTotal,
		arg.Note,
		arg.CreatedBy,
	)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocType,
		&i.DocNo,
		&i.DocDate,
		&i.CustomerID,
		&i.SalesUserID,
		&i.WarehouseID,
		&i.Currency,
		&i.ExchangeRate,
		&i.TaxTypeID,
		&i.TaxRate,
		&i.PaymentTermID,
		&i.InvoiceNo,
		&i.InvoiceDate,
		&i.UntaxedAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.BaseUntaxed,
		&i.BaseTax,
		&i.BaseTotal,
		&i.Status,
		&i.Note,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.PostedBy,
		&i.PostedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSalesOrder = `-- name: CreateSalesOrder :one
INSERT INTO sales_orders (company_id, doc_type, doc_no, doc_date, customer_id, sales_user_id, warehouse_id,
                          quotation_id, valid_until, delivery_date, customer_po_no, currency, exchange_rate,
                          tax_type_id, tax_rate, payment_term_id, untaxed_amount, tax_amount, total_amount, note,
                          created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11, $12,
        $13, $14, $15, $16, $17, $18,
        $19, $20, $21, $21)
RETURNING id, company_id, doc_type, doc_no, doc_date, customer_id, sales_user_id, warehouse_id, quotation_id, valid_until, delivery_date, customer_po_no, currency, exchange_rate, tax_type_id, tax_rate, payment_term_id, untaxed_amount, tax_amount, total_amount, status, note, submitted_by, submitted_at, approved_by, approved_at, closed_by, closed_at, created_by, updated_by, version, created_at, updated_at
`

type CreateSalesOrderParams struct {
	CompanyID     int64
	DocType       string
	DocNo         string
	DocDate       time.Time
	CustomerID    int64
	SalesUserID   *int64
	WarehouseID   int64
	QuotationID   *int64
	ValidUntil    *time.Time
	DeliveryDate  *time.Time
	CustomerPoNo  string
	Currency      string
	ExchangeRate  decimal.Decimal
	TaxTypeID     int64
	TaxRate       decimal.Decimal
	PaymentTermID *int64
	UntaxedAmount decimal.Decimal
	TaxAmount     decimal.Decimal
	TotalAmount   decimal.Decimal
	Note          string
	CreatedBy     *int64
}

func (q *Queries) CreateSalesOrder(ctx context.Context, arg CreateSalesOrderParams) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, createSalesOrder,
		arg.CompanyID,
		arg.DocType,
		arg.DocNo,
		arg.DocDate,
		arg.CustomerID,
		arg.SalesUserID,
		arg.WarehouseID,
		arg.QuotationID,
		arg.ValidUntil,
		arg.DeliveryDate,
		arg.CustomerPoNo,
		arg.Currency,
		arg.ExchangeRate,
		arg.TaxTypeID,
		arg.TaxRate,
		arg.PaymentTermID,
		arg.UntaxedAmount,
		arg.TaxAmount,
		arg.TotalAmount,
		arg.Note,
		arg.CreatedBy,
	)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocType,
		&i.DocNo,
		&i.DocDate,
		&i.CustomerID,
		&i.SalesUserID,
		&i.WarehouseID,
		&i.QuotationID,
		&i.ValidUntil,
		&i.DeliveryDate,
		&i.CustomerPoNo,
		&i.Currency,
		&i.ExchangeRate,
		&i.TaxTypeID,
		&i.TaxRate,
		&i.PaymentTermID,
		&i.UntaxedAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.Status,
		&i.Note,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const customerExposure = `-- name: CustomerExposure :one
SELECT
    COALESCE((SELECT SUM(CASE WHEN ar.amount = 0 THEN 0
                              ELSE ar.base_amount * (ar.amount - ar.paid_amount) / ar.amount END)
              FROM accounts_receivable ar WHERE ar.customer_id = $1), 0)::numeric AS ar_open,
    COALESCE((SELECT SUM(GREATEST(l.qty - (
                  SELECT COALESCE(SUM(dl.qty), 0) FROM delivery_lines dl
                  JOIN deliveries d ON d.id = dl.delivery_id
                  WHERE dl.so_line_id = l.id AND d.status = 'posted'), 0)
                  * l.unit_price * (1 + o.tax_rate) * o.exchange_rate)
              FROM sales_order_lines l
              JOIN sales_orders o ON o.id = l.order_id
              WHERE o.customer_id = $1 AND o.doc_type = 'order' AND o.status = 'approved'
                AND o.id <> $2::bigint), 0)::numeric AS open_orders
`

type CustomerExposureParams struct {
	CustomerID     int64
	ExcludeOrderID int64
}

type CustomerExposureRow struct {
	ArOpen     decimal.Decimal
	OpenOrders decimal.Decimal
}

// 信用額度占用(本位幣含稅):未沖應收 + 其他已核准訂單的未出貨金額(D39)
func (q *Queries) CustomerExposure(ctx context.Context, arg CustomerExposureParams) (CustomerExposureRow, error) {
	row := q.db.QueryRow(ctx, customerExposure, arg.CustomerID, arg.ExcludeOrderID)
	var i CustomerExposureRow
	err := row.Scan(&i.ArOpen, &i.OpenOrders)
	return i, err
}

const customerForDoc = `-- name: CustomerForDoc :one

SELECT c.id, c.code, c.name, c.is_active, c.sales_user_id, c.credit_limit, su.department_id AS sales_department_id
FROM customers c
LEFT JOIN users su ON su.id = c.sales_user_id
WHERE c.id = $1 AND c.company_id = $2
`

type CustomerForDocParams struct {
	ID        int64
	CompanyID int64
}

type CustomerForDocRow struct {
	ID                int64
	Code              string
	Name              string
	IsActive          bool
	SalesUserID       *int64
	CreditLimit       decimal.Decimal
	SalesDepartmentID *int64
}

// ======== 客戶 ========
func (q *Queries) CustomerForDoc(ctx context.Context, arg CustomerForDocParams) (CustomerForDocRow, error) {
	row := q.db.QueryRow(ctx, customerForDoc, arg.ID, arg.CompanyID)
	var i CustomerForDocRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.IsActive,
		&i.SalesUserID,
		&i.CreditLimit,
		&i.SalesDepartmentID,
	)
	return i, err
}

const customerOptions = `-- name: CustomerOptions :many
SELECT c.id, c.code, c.name, c.short_name, c.currency, c.tax_type_id, c.payment_term_id, c.sales_user_id,
       su.name AS sales_user_name
FROM customers c
LEFT JOIN users su ON su.id = c.sales_user_id
WHERE c.company_id = $1 AND c.is_active
  AND ($2::text IS NULL
       OR c.code ILIKE '%' || $2 || '%'
       OR c.name ILIKE '%' || $2 || '%'
       OR c.short_name ILIKE '%' || $2 || '%')
  AND ($3::bigint IS NULL OR c.sales_user_id = $3)
  AND ($4::bigint IS NULL OR su.department_id = $4)
ORDER BY c.code
LIMIT 20
`

type CustomerOptionsParams struct {
	CompanyID   int64
	Keyword     *string
	ScopeUserID *int64
	ScopeDeptID *int64
}

type CustomerOptionsRow struct {
	ID            int64
	Code          string
	Name          string
	ShortName     string
	Currency      string
	TaxTypeID     *int64
	PaymentTermID *int64
	SalesUserID   *int64
	SalesUserName *string
}

// 開單選客戶:只需登入,依資料範圍過濾,只回傳啟用中的精簡欄位
func (q *Queries) CustomerOptions(ctx context.Context, arg CustomerOptionsParams) ([]CustomerOptionsRow, error) {
	rows, err := q.db.Query(ctx, customerOptions,
		arg.CompanyID,
		arg.Keyword,
		arg.ScopeUserID,
		arg.ScopeDeptID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomerOptionsRow{}
	for rows.Next() {
		var i CustomerOptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.ShortName,
			&i.Currency,
			&i.TaxTypeID,
			&i.PaymentTermID,
			&i.SalesUserID,
			&i.SalesUserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteDeliveryLines = `-- name: DeleteDeliveryLines :exec
DELETE FROM delivery_lines WHERE delivery_id = $1
`

func (q *Queries) DeleteDeliveryLines(ctx context.Context, deliveryID int64) error {
	_, err := q.db.Exec(ctx, deleteDeliveryLines, deliveryID)
	return err
}

const deleteReceivable = `-- name: DeleteReceivable :exec
DELETE FROM accounts_receivable WHERE id = $1
`

func (q *Queries) DeleteReceivable(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteReceivable, id)
	return err
}

const deleteSalesOrderLines = `-- name: DeleteSalesOrderLines :exec
DELETE FROM sales_order_lines WHERE order_id = $1
`

func (q *Queries) DeleteSalesOrderLines(ctx context.Context, orderID int64) error {
	_, err := q.db.Exec(ctx, deleteSalesOrderLines, orderID)
	return err
}

const deliveryLineRefs = `-- name: DeliveryLineRefs :many
SELECT l.id, l.delivery_id, d.doc_no, d.doc_type, d.status, d.customer_id, d.currency, l.item_id, l.unit_id, l.qty,
       (SELECT COALESCE(SUM(xl.qty), 0) FROM delivery_lines xl
        JOIN deliveries x ON x.id = xl.delivery_id
        WHERE xl.delivery_line_id = l.id AND x.status = 'posted' AND x.id <> $1::bigint)::numeric
           AS returned_qty
FROM delivery_lines l
JOIN deliveries d ON d.id = l.delivery_id
WHERE d.company_id = $2 AND l.id = ANY($3::bigint[])
`

type DeliveryLineRefsParams struct {
	ExcludeDeliveryID int64
	CompanyID         int64
	Ids               []int64
}

type DeliveryLineRefsRow struct {
	ID          int64
	DeliveryID  int64
	DocNo       string
	DocType     string
	Status      string
	CustomerID  int64
	Currency    string
	ItemID      int64
	UnitID      int64
	Qty         decimal.Decimal
	ReturnedQty decimal.Decimal
}

// 退回明細引用的出貨明細,以及「其他」已過帳退回單的已退量
func (q *Queries) DeliveryLineRefs(ctx context.Context, arg DeliveryLineRefsParams) ([]DeliveryLineRefsRow, error) {
	rows, err := q.db.Query(ctx, deliveryLineRefs, arg.ExcludeDeliveryID, arg.CompanyID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeliveryLineRefsRow{}
	for rows.Next() {
		var i DeliveryLineRefsRow
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryID,
			&i.DocNo,
			&i.DocType,
			&i.Status,
			&i.CustomerID,
			&i.Currency,
			&i.ItemID,
			&i.UnitID,
			&i.Qty,
			&i.ReturnedQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deliveryReturnNo = `-- name: DeliveryReturnNo :one
SELECT x.doc_no FROM delivery_lines xl
JOIN deliveries x ON x.id = xl.delivery_id
JOIN delivery_lines l ON l.id = xl.delivery_line_id
WHERE l.delivery_id = $1 AND x.status <> 'voided'
LIMIT 1
`

// 出貨單是否已被未作廢的退回單引用(反過帳前檢查)
func (q *Queries) DeliveryReturnNo(ctx context.Context, deliveryID int64) (string, error) {
	row := q.db.QueryRow(ctx, deliveryReturnNo, deliveryID)
	var doc_no string
	err := row.Scan(&doc_no)
	return doc_no, err
}

const getDelivery = `-- name: GetDelivery :one
SELECT d.id, d.company_id, d.doc_type, d.doc_no, d.doc_date, d.customer_id, d.sales_user_id, d.warehouse_id, d.currency, d.exchange_rate, d.tax_type_id, d.tax_rate, d.payment_term_id, d.invoice_no, d.invoice_date, d.untaxed_amount, d.tax_amount, d.total_amount, d.base_untaxed, d.base_tax, d.base_total, d.status, d.note, d.submitted_by, d.submitted_at, d.approved_by, d.approved_at, d.posted_by, d.posted_at, d.created_by, d.updated_by, d.version, d.created_at, d.updated_at, c.code AS customer_code, c.name AS customer_name, w.name AS warehouse_name,
       t.name AS tax_type_name, pt.name AS payment_term_name,
       su.name AS sales_user_name, su.department_id AS sales_department_id,
       cu.name AS created_by_name, sbu.name AS submitted_by_name, au.name AS approved_by_name,
       pu.name AS posted_by_name
FROM deliveries d
JOIN customers c ON c.id = d.customer_id
JOIN warehouses w ON w.id = d.warehouse_id
JOIN tax_types t ON t.id = d.tax_type_id
LEFT JOIN payment_terms pt ON pt.id = d.payment_term_id
LEFT JOIN users su ON su.id = d.sales_user_id
LEFT JOIN users cu ON cu.id = d.created_by
LEFT JOIN users sbu ON sbu.id = d.submitted_by
LEFT JOIN users au ON au.id = d.approved_by
LEFT JOIN users pu ON pu.id = d.posted_by
WHERE d.id = $1 AND d.company_id = $2
`

type GetDeliveryParams struct {
	ID        int64
	CompanyID int64
}

type GetDeliveryRow struct {
	ID                int64
	CompanyID         int64
	DocType           string
	DocNo             string
	DocDate           time.Time
	CustomerID        int64
	SalesUserID       *int64
	WarehouseID       int64
	Currency          string
	ExchangeRate      decimal.Decimal
	TaxTypeID         int64
	TaxRate           decimal.Decimal
	PaymentTermID     *int64
	InvoiceNo         string
	InvoiceDate       *time.Time
	UntaxedAmount     decimal.Decimal
	TaxAmount         decimal.Decimal
	TotalAmount       decimal.Decimal
	BaseUntaxed       decimal.Decimal
	BaseTax           decimal.Decimal
	BaseTotal         decimal.Decimal
	Status            string
	Note              string
	SubmittedBy       *int64
	SubmittedAt       *time.Time
	ApprovedBy        *int64
	ApprovedAt        *time.Time
	PostedBy          *int64
	PostedAt          *time.Time
	CreatedBy         *int64
	UpdatedBy         *int64
	Version           int32
	CreatedAt         time.Time
	UpdatedAt         time.Time
	CustomerCode      string
	CustomerName      string
	WarehouseName     string
	TaxTypeName       string
	PaymentTermName   *string
	SalesUserName     *string
	SalesDepartmentID *int64
	CreatedByName     *string
	SubmittedByName   *string
	ApprovedByName    *string
	PostedByName      *string
}

func (q *Queries) GetDelivery(ctx context.Context, arg GetDeliveryParams) (GetDeliveryRow, error) {
	row := q.db.QueryRow(ctx, getDelivery, arg.ID, arg.CompanyID)
	var i GetDeliveryRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocType,
		&i.DocNo,
		&i.DocDate,
		&i.CustomerID,
		&i.SalesUserID,
		&i.WarehouseID,
		&i.Currency,
		&i.ExchangeRate,
		&i.TaxTypeID,
		&i.TaxRate,
		&i.PaymentTermID,
		&i.InvoiceNo,
		&i.InvoiceDate,
		&i.UntaxedAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.BaseUntaxed,
		&i.BaseTax,
		&i.BaseTotal,
		&i.Status,
		&i.Note,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.PostedBy,
		&i.PostedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerCode,
		&i.CustomerName,
		&i.WarehouseName,
		&i.TaxTypeName,
		&i.PaymentTermName,
		&i.SalesUserName,
		&i.SalesDepartmentID,
		&i.CreatedByName,
		&i.SubmittedByName,
		&i.ApprovedByName,
		&i.PostedByName,
	)
	return i, err
}

const getSalesOrder = `-- name: GetSalesOrder :one
SELECT o.id, o.company_id, o.doc_type, o.doc_no, o.doc_date, o.customer_id, o.sales_user_id, o.warehouse_id, o.quotation_id, o.valid_until, o.delivery_date, o.customer_po_no, o.currency, o.exchange_rate, o.tax_type_id, o.tax_rate, o.payment_term_id, o.untaxed_amount, o.tax_amount, o.total_amount, o.status, o.note, o.submitted_by, o.submitted_at, o.approved_by, o.approved_at, o.closed_by, o.closed_at, o.created_by, o.updated_by, o.version, o.created_at, o.updated_at, c.code AS customer_code, c.name AS customer_name, w.name AS warehouse_name,
       t.name AS tax_type_name, pt.name AS payment_term_name, q.doc_no AS quotation_no,
       su.name AS sales_user_name, su.department_id AS sales_department_id,
       cu.name AS created_by_name, sbu.name AS submitted_by_name, au.name AS approved_by_name,
       clu.name AS closed_by_name
FROM sales_orders o
JOIN customers c ON c.id = o.customer_id
JOIN warehouses w ON w.id = o.warehouse_id
JOIN tax_types t ON t.id = o.tax_type_id
LEFT JOIN payment_terms pt ON pt.id = o.payment_term_id
LEFT JOIN sales_orders q ON q.id = o.quotation_id
LEFT JOIN users su ON su.id = o.sales_user_id
LEFT JOIN users cu ON cu.id = o.created_by
LEFT JOIN users sbu ON sbu.id = o.submitted_by
LEFT JOIN users au ON au.id = o.approved_by
LEFT JOIN users clu ON clu.id = o.closed_by
WHERE o.id = $1 AND o.company_id = $2
`

type GetSalesOrderParams struct {
	ID        int64
	CompanyID int64
}

type GetSalesOrderRow struct {
	ID                int64
	CompanyID         int64
	DocType           string
	DocNo             string
	DocDate           time.Time
	CustomerID        int64
	SalesUserID       *int64
	WarehouseID       int64
	QuotationID       *int64
	ValidUntil        *time.Time
	DeliveryDate      *time.Time
	CustomerPoNo      string
	Currency          string
	ExchangeRate      decimal.Decimal
	TaxTypeID         int64
	TaxRate           decimal.Decimal
	PaymentTermID     *int64
	UntaxedAmount     decimal.Decimal
	TaxAmount         decimal.Decimal
	TotalAmount       decimal.Decimal
	Status            string
	Note              string
	SubmittedBy       *int64
	SubmittedAt       *time.Time
	ApprovedBy        *int64
	ApprovedAt        *time.Time
	ClosedBy          *int64
	ClosedAt          *time.Time
	CreatedBy         *int64
	UpdatedBy         *int64
	Version           int32
	CreatedAt         time.Time
	UpdatedAt         time.Time
	CustomerCode      string
	CustomerName      string
	WarehouseName     string
	TaxTypeName       string
	PaymentTermName   *string
	QuotationNo       *string
	SalesUserName     *string
	SalesDepartmentID *int64
	CreatedByName     *string
	SubmittedByName   *string
	ApprovedByName    *string
	ClosedByName      *string
}

func (q *Queries) GetSalesOrder(ctx context.Context, arg GetSalesOrderParams) (GetSalesOrderRow, error) {
	row := q.db.QueryRow(ctx, getSalesOrder, arg.ID, arg.CompanyID)
	var i GetSalesOrderRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocType,
		&i.DocNo,
		&i.DocDate,
		&i.CustomerID,
		&i.SalesUserID,
		&i.WarehouseID,
		&i.QuotationID,
		&i.ValidUntil,
		&i.DeliveryDate,
		&i.CustomerPoNo,
		&i.Currency,
		&i.ExchangeRate,
		&i.TaxTypeID,
		&i.TaxRate,
		&i.PaymentTermID,
		&i.UntaxedAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.Status,
		&i.Note,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerCode,
		&i.CustomerName,
		&i.WarehouseName,
		&i.TaxTypeName,
		&i.PaymentTermName,
		&i.QuotationNo,
		&i.SalesUserName,
		&i.SalesDepartmentID,
		&i.CreatedByName,
		&i.SubmittedByName,
		&i.ApprovedByName,
		&i.ClosedByName,
	)
	return i, err
}

const insertReceivable = `-- name: InsertReceivable :exec

INSERT INTO accounts_receivable (company_id, customer_id, source_type, source_id, source_no, doc_date, due_date,
                                 currency, exchange_rate, amount, base_amount, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        $9, $10, $11, $12)
`

type InsertReceivableParams struct {
	CompanyID    int64
	CustomerID   int64
	SourceType   string
	SourceID     int64
	SourceNo     string
	DocDate      time.Time
	DueDate      time.Time
	Currency     string
	ExchangeRate decimal.Decimal
	Amount       decimal.Decimal
	BaseAmount   decimal.Decimal
	CreatedBy    *int64
}

// ======== 應收帳款 ========
func (q *Queries) InsertReceivable(ctx context.Context, arg InsertReceivableParams) error {
	_, err := q.db.Exec(ctx, insertReceivable,
		arg.CompanyID,
		arg.CustomerID,
		arg.SourceType,
		arg.SourceID,
		arg.SourceNo,
		arg.DocDate,
		arg.DueDate,
		arg.Currency,
		arg.ExchangeRate,
		arg.Amount,
		arg.BaseAmount,
		arg.CreatedBy,
	)
	return err
}

const itemAvailability = `-- name: ItemAvailability :many
SELECT i.id AS item_id,
       COALESCE((SELECT b.qty FROM inventory_balances b
                 WHERE b.item_id = i.id AND b.warehouse_id = $1::bigint), 0)::numeric AS on_hand,
       COALESCE((SELECT SUM(GREATEST(l.qty - (
                     SELECT COALESCE(SUM(dl.qty), 0) FROM delivery_lines dl
                     JOIN deliveries d ON d.id = dl.delivery_id
                     WHERE dl.so_line_id = l.id AND d.status = 'posted'), 0) * l.factor)
                 FROM sales_order_lines l
                 JOIN sales_orders o ON o.id = l.order_id
                 WHERE l.item_id = i.id AND o.warehouse_id = $1::bigint AND o.doc_type = 'order'
                   AND o.status = 'approved' AND o.id <> $2::bigint), 0)::numeric AS reserved
FROM items i
WHERE i.company_id = $3 AND i.id = ANY($4::bigint[]) AND i.item_type = 'goods'
`

type ItemAvailabilityParams struct {
	WarehouseID    int64
	ExcludeOrderID int64
	CompanyID      int64
	ItemIds        []int64
}

type ItemAvailabilityRow struct {
	ItemID   int64
	OnHand   decimal.Decimal
	Reserved decimal.Decimal
}

// 可用量 = 現有量 − 保留量(其他已核准訂單的未出貨基本單位數量)(D39)
func (q *Queries) ItemAvailability(ctx context.Context, arg ItemAvailabilityParams) ([]ItemAvailabilityRow, error) {
	rows, err := q.db.Query(ctx, itemAvailability,
		arg.WarehouseID,
		arg.ExcludeOrderID,
		arg.CompanyID,
		arg.ItemIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemAvailabilityRow{}
	for rows.Next() {
		var i ItemAvailabilityRow
		if err := rows.Scan(&i.ItemID, &i.OnHand, &i.Reserved); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveries = `-- name: ListDeliveries :many

SELECT d.id, d.doc_type, d.doc_no, d.doc_date, d.status, d.currency, d.total_amount, d.invoice_no, d.note,
       d.version, d.updated_at, c.code AS customer_code, c.name AS customer_name, w.name AS warehouse_name,
       su.name AS sales_user_name, cu.name AS created_by_name
FROM deliveries d
JOIN customers c ON c.id = d.customer_id
JOIN warehouses w ON w.id = d.warehouse_id
LEFT JOIN users su ON su.id = d.sales_user_id
LEFT JOIN users cu ON cu.id = d.created_by
WHERE d.company_id = $1
  AND ($2::text IS NULL OR d.doc_type = $2)
  AND ($3::text IS NULL OR d.status = $3)
  AND ($4::bigint IS NULL OR d.customer_id = $4)
  AND ($5::text IS NULL OR d.doc_no ILIKE '%' || $5 || '%'
       OR d.invoice_no ILIKE '%' || $5 || '%')
  AND ($6::date IS NULL OR d.doc_date >= $6)
  AND ($7::date IS NULL OR d.doc_date <= $7)
  AND (NOT $8::boolean OR d.invoice_no = '')
  AND ($9::bigint IS NULL OR d.sales_user_id = $9)
  AND ($10::bigint IS NULL OR su.department_id = $10)
ORDER BY d.doc_date DESC, d.id DESC
LIMIT $12 OFFSET $11
`

type ListDeliveriesParams struct {
	CompanyID   int64
	DocType     *string
	Status      *string
	CustomerID  *int64
	Keyword     *string
	FromDate    *time.Time
	ToDate      *time.Time
	NoInvoice   bool
	ScopeUserID *int64
	ScopeDeptID *int64
	Off         int32
	Lim         int32
}

type ListDeliveriesRow struct {
	ID            int64
	DocType       string
	DocNo         string
	DocDate       time.Time
	Status        string
	Currency      string
	TotalAmount   decimal.Decimal
	InvoiceNo     string
	Note          string
	Version       int32
	UpdatedAt     time.Time
	CustomerCode  string
	CustomerName  string
	WarehouseName string
	SalesUserName *string
	CreatedByName *string
}

// ======== 出貨單 / 銷貨退回單 ========
func (q *Queries) ListDeliveries(ctx context.Context, arg ListDeliveriesParams) ([]ListDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, listDeliveries,
		arg.CompanyID,
		arg.DocType,
		arg.Status,
		arg.CustomerID,
		arg.Keyword,
		arg.FromDate,
		arg.ToDate,
		arg.NoInvoice,
		arg.ScopeUserID,
		arg.ScopeDeptID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeliveriesRow{}
	for rows.Next() {
		var i ListDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.DocType,
			&i.DocNo,
			&i.DocDate,
			&i.Status,
			&i.Currency,
			&i.TotalAmount,
			&i.InvoiceNo,
			&i.Note,
			&i.Version,
			&i.UpdatedAt,
			&i.CustomerCode,
			&i.CustomerName,
			&i.WarehouseName,
			&i.SalesUserName,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveryLines = `-- name: ListDeliveryLines :many
SELECT l.id, l.delivery_id, l.line_no, l.item_id, l.unit_id, l.qty, l.factor, l.base_qty, l.unit_price, l.amount, l.base_amount, l.so_line_id, l.delivery_line_id, l.note, l.lot_no, l.expiry_date, l.bin_code, i.code AS item_code, i.name AS item_name, i.spec AS item_spec, i.item_type, i.lot_control AS item_lot_control,
       u.name AS unit_name, bu.name AS base_unit_name,
       so.doc_no AS so_no, src.doc_no AS source_delivery_no
FROM delivery_lines l
JOIN items i ON i.id = l.item_id
JOIN units u ON u.id = l.unit_id
JOIN units bu ON bu.id = i.base_unit_id
LEFT JOIN sales_order_lines sol ON sol.id = l.so_line_id
LEFT JOIN sales_orders so ON so.id = sol.order_id
LEFT JOIN delivery_lines sdl ON sdl.id = l.delivery_line_id
LEFT JOIN deliveries src ON src.id = sdl.delivery_id
WHERE l.delivery_id = $1
ORDER BY l.line_no
`

type ListDeliveryLinesRow struct {
	ID               int64
	DeliveryID       int64
	LineNo           int32
	ItemID           int64
	UnitID           int64
	Qty              decimal.Decimal
	Factor           decimal.Decimal
	BaseQty          decimal.Decimal
	UnitPrice        decimal.Decimal
	Amount           decimal.Decimal
	BaseAmount       decimal.Decimal
	SoLineID         *int64
	DeliveryLineID   *int64
	Note             string
	LotNo            string
	ExpiryDate       *time.Time
	BinCode          string
	ItemCode         string
	ItemName         string
	ItemSpec         string
	ItemType         string
	ItemLotControl   string
	UnitName         string
	BaseUnitName     string
	SoNo             *string
	SourceDeliveryNo *string
}

func (q *Queries) ListDeliveryLines(ctx context.Context, deliveryID int64) ([]ListDeliveryLinesRow, error) {
	rows, err := q.db.Query(ctx, listDeliveryLines, deliveryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeliveryLinesRow{}
	for rows.Next() {
		var i ListDeliveryLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryID,
			&i.LineNo,
			&i.ItemID,
			&i.UnitID,
			&i.Qty,
			&i.Factor,
			&i.BaseQty,
			&i.UnitPrice,
			&i.Amount,
			&i.BaseAmount,
			&i.SoLineID,
			&i.DeliveryLineID,
			&i.Note,
			&i.LotNo,
			&i.ExpiryDate,
			&i.BinCode,
			&i.ItemCode,
			&i.ItemName,
			&i.ItemSpec,
			&i.ItemType,
			&i.ItemLotControl,
			&i.UnitName,
			&i.BaseUnitName,
			&i.SoNo,
			&i.SourceDeliveryNo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceivables = `-- name: ListReceivables :many
SELECT r.id, r.company_id, r.customer_id, r.source_type, r.source_id, r.source_no, r.doc_date, r.due_date, r.currency, r.exchange_rate, r.amount, r.base_amount, r.paid_amount, r.created_by, r.created_at, r.updated_at, r.import_batch_id, c.code AS customer_code, c.name AS customer_name
FROM accounts_receivable r
JOIN customers c ON c.id = r.customer_id
LEFT JOIN users su ON su.id = c.sales_user_id
WHERE r.company_id = $1
  AND ($2::bigint IS NULL OR r.customer_id = $2)
  AND ($3::text IS NULL OR r.source_no ILIKE '%' || $3 || '%')
  AND ($4::date IS NULL OR r.doc_date >= $4)
  AND ($5::date IS NULL OR r.doc_date <= $5)
  AND (NOT $6::boolean OR r.amount <> r.paid_amount)
  AND ($7::bigint IS NULL OR c.sales_user_id = $7)
  AND ($8::bigint IS NULL OR su.department_id = $8)
ORDER BY r.due_date, r.id
LIMIT $10 OFFSET $9
`

type ListReceivablesParams struct {
	CompanyID   int64
	CustomerID  *int64
	Keyword     *string
	FromDate    *time.Time
	ToDate      *time.Time
	OpenOnly    bool
	ScopeUserID *int64
	ScopeDeptID *int64
	Off         int32
	Lim         int32
}

type ListReceivablesRow struct {
	ID            int64
	CompanyID     int64
	CustomerID    int64
	SourceType    string
	SourceID      int64
	SourceNo      string
	DocDate       time.Time
	DueDate       time.Time
	Currency      string
	ExchangeRate  decimal.Decimal
	Amount        decimal.Decimal
	BaseAmount    decimal.Decimal
	PaidAmount    decimal.Decimal
	CreatedBy     *int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	ImportBatchID *int64
	CustomerCode  string
	CustomerName  string
}

// 資料範圍依客戶目前的負責業務
func (q *Queries) ListReceivables(ctx context.Context, arg ListReceivablesParams) ([]ListReceivablesRow, error) {
	rows, err := q.db.Query(ctx, listReceivables,
		arg.CompanyID,
		arg.CustomerID,
		arg.Keyword,
		arg.FromDate,
		arg.ToDate,
		arg.OpenOnly,
		arg.ScopeUserID,
		arg.ScopeDeptID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReceivablesRow{}
	for rows.Next() {
		var i ListReceivablesRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CustomerID,
			&i.SourceType,
			&i.SourceID,
			&i.SourceNo,
			&i.DocDate,
			&i.DueDate,
			&i.Currency,
			&i.ExchangeRate,
			&i.Amount,
			&i.BaseAmount,
			&i.PaidAmount,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImportBatchID,
			&i.CustomerCode,
			&i.CustomerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesOrderLines = `-- name: ListSalesOrderLines :many
SELECT l.id, l.order_id, l.line_no, l.item_id, l.unit_id, l.qty, l.factor, l.base_qty, l.unit_price, l.amount, l.note, i.code AS item_code, i.name AS item_name, i.spec AS item_spec, i.item_type,
       u.name AS unit_name, bu.name AS base_unit_name,
       (SELECT COALESCE(SUM(dl.qty), 0) FROM delivery_lines dl
        JOIN deliveries d ON d.id = dl.delivery_id
        WHERE dl.so_line_id = l.id AND d.status = 'posted')::numeric AS delivered_qty
FROM sales_order_lines l
JOIN items i ON i.id = l.item_id
JOIN units u ON u.id = l.unit_id
JOIN units bu ON bu.id = i.base_unit_id
WHERE l.order_id = $1
ORDER BY l.line_no
`

type ListSalesOrderLinesRow struct {
	ID           int64
	OrderID      int64
	LineNo       int32
	ItemID       int64
	UnitID       int64
	Qty          decimal.Decimal
	Factor       decimal.Decimal
	BaseQty      decimal.Decimal
	UnitPrice    decimal.Decimal
	Amount       decimal.Decimal
	Note         string
	ItemCode     string
	ItemName     string
	ItemSpec     string
	ItemType     string
	UnitName     string
	BaseUnitName string
	DeliveredQty decimal.Decimal
}

func (q *Queries) ListSalesOrderLines(ctx context.Context, orderID int64) ([]ListSalesOrderLinesRow, error) {
	rows, err := q.db.Query(ctx, listSalesOrderLines, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSalesOrderLinesRow{}
	for rows.Next() {
		var i ListSalesOrderLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.LineNo,
			&i.ItemID,
			&i.UnitID,
			&i.Qty,
			&i.Factor,
			&i.BaseQty,
			&i.UnitPrice,
			&i.Amount,
			&i.Note,
			&i.ItemCode,
			&i.ItemName,
			&i.ItemSpec,
			&i.ItemType,
			&i.UnitName,
			&i.BaseUnitName,
			&i.DeliveredQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesOrders = `-- name: ListSalesOrders :many


WITH page AS (
    SELECT o.id, o.company_id, o.doc_type, o.doc_no, o.doc_date, o.customer_id, o.sales_user_id, o.warehouse_id, o.quotation_id, o.valid_until, o.delivery_date, o.customer_po_no, o.currency, o.exchange_rate, o.tax_type_id, o.tax_rate, o.payment_term_id, o.untaxed_amount, o.tax_amount, o.total_amount, o.status, o.note, o.submitted_by, o.submitted_at, o.approved_by, o.approved_at, o.closed_by, o.closed_at, o.created_by, o.updated_by, o.version, o.created_at, o.updated_at FROM sales_orders o
    WHERE o.company_id = $1
      AND ($2::text IS NULL OR o.doc_type = $2)
      AND ($3::text IS NULL OR o.status = $3)
      AND ($4::bigint IS NULL OR o.customer_id = $4)
      AND ($5::text IS NULL OR o.doc_no ILIKE '%' || $5 || '%'
           OR o.customer_po_no ILIKE '%' || $5 || '%')
      AND ($6::date IS NULL OR o.doc_date >= $6)
      AND ($7::date IS NULL OR o.doc_date <= $7)
      AND ($8::bigint IS NULL OR o.sales_user_id = $8)
      AND ($9::bigint IS NULL OR EXISTS (
            SELECT 1 FROM users u WHERE u.id = o.sales_user_id AND u.department_id = $9))
    ORDER BY o.doc_date DESC, o.id DESC
    LIMIT $11 OFFSET $10
)
SELECT o.id, o.doc_type, o.doc_no, o.doc_date, o.valid_until, o.delivery_date, o.customer_po_no, o.status,
       o.currency, o.total_amount, o.note, o.version, o.updated_at,
       c.code AS customer_code, c.name AS customer_name, su.name AS sales_user_name, cu.name AS created_by_name,
       -- 訂單出貨狀態:依已過帳出貨量判斷(none / partial / full);報價單為 none
       (CASE
            WHEN o.doc_type <> 'order' OR NOT EXISTS (SELECT 1 FROM sales_order_lines l WHERE l.order_id = o.id) THEN 'none'
            WHEN NOT EXISTS (
                SELECT 1 FROM sales_order_lines l
                WHERE l.order_id = o.id AND l.qty > (
                    SELECT COALESCE(SUM(dl.qty), 0) FROM delivery_lines dl
                    JOIN deliveries d ON d.id = dl.delivery_id
                    WHERE dl.so_line_id = l.id AND d.status = 'posted')) THEN 'full'
            WHEN EXISTS (
                SELECT 1 FROM delivery_lines dl
                JOIN deliveries d ON d.id = dl.delivery_id
                JOIN sales_order_lines l ON l.id = dl.so_line_id
                WHERE l.order_id = o.id AND d.status = 'posted') THEN 'partial'
            ELSE 'none' END)::text AS ship_state,
       -- 報價單是否已轉訂單(未作廢)
       EXISTS (SELECT 1 FROM sales_orders so WHERE so.quotation_id = o.id AND so.status <> 'voided') AS converted
FROM page o
JOIN customers c ON c.id = o.customer_id
LEFT JOIN users su ON su.id = o.sales_user_id
LEFT JOIN users cu ON cu.id = o.created_by
ORDER BY o.doc_date DESC, o.id DESC
`

type ListSalesOrdersParams struct {
	CompanyID   int64
	DocType     *string
	Status      *string
	CustomerID  *int64
	Keyword     *string
	FromDate    *time.Time
	ToDate      *time.Time
	ScopeUserID *int64
	ScopeDeptID *int64
	Off         int32
	Lim         int32
}

type ListSalesOrdersRow struct {
	ID            int64
	DocType       string
	DocNo         string
	DocDate       time.Time
	ValidUntil    *time.Time
	DeliveryDate  *time.Time
	CustomerPoNo  string
	Status        string
	Currency      string
	TotalAmount   decimal.Decimal
	Note          string
	Version       int32
	UpdatedAt     time.Time
	CustomerCode  string
	CustomerName  string
	SalesUserName *string
	CreatedByName *string
	ShipState     string
	Converted     bool
}

// scope_* 為資料範圍:依單據的負責業務(本人 / 同部門)過濾;未指定負責業務的單據只有「全部」範圍看得到(D38)
// ======== 報價單 / 訂單 ========
// 先依條件排序取出該頁,再對這一頁計算出貨狀態與是否已轉訂單(相關子查詢只算 @lim 次;壓測 30,000 張單 94 ms → 個位數)。
// 資料範圍用 EXISTS 而非 JOIN,避免非必要的 JOIN 影響排序計畫。
func (q *Queries) ListSalesOrders(ctx context.Context, arg ListSalesOrdersParams) ([]ListSalesOrdersRow, error) {
	rows, err := q.db.Query(ctx, listSalesOrders,
		arg.CompanyID,
		arg.DocType,
		arg.Status,
		arg.CustomerID,
		arg.Keyword,
		arg.FromDate,
		arg.ToDate,
		arg.ScopeUserID,
		arg.ScopeDeptID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSalesOrdersRow{}
	for rows.Next() {
		var i ListSalesOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.DocType,
			&i.DocNo,
			&i.DocDate,
			&i.ValidUntil,
			&i.DeliveryDate,
			&i.CustomerPoNo,
			&i.Status,
			&i.Currency,
			&i.TotalAmount,
			&i.Note,
			&i.Version,
			&i.UpdatedAt,
			&i.CustomerCode,
			&i.CustomerName,
			&i.SalesUserName,
			&i.CreatedByName,
			&i.ShipState,
			&i.Converted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCustomer = `-- name: LockCustomer :exec
SELECT id FROM customers WHERE id = $1 AND company_id = $2 FOR UPDATE
`

type LockCustomerParams struct {
	ID        int64
	CompanyID int64
}

// 核准訂單檢查信用額度時鎖定客戶,同一客戶的核准依序進行
func (q *Queries) LockCustomer(ctx context.Context, arg LockCustomerParams) error {
	_, err := q.db.Exec(ctx, lockCustomer, arg.ID, arg.CompanyID)
	return err
}

const lockDeliveries = `-- name: LockDeliveries :many
SELECT id FROM deliveries
WHERE company_id = $1 AND id = ANY($2::bigint[])
ORDER BY id
FOR UPDATE
`

type LockDeliveriesParams struct {
	CompanyID int64
	Ids       []int64
}

// 退回過帳時鎖定來源出貨單(依 id 排序)
func (q *Queries) LockDeliveries(ctx context.Context, arg LockDeliveriesParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, lockDeliveries, arg.CompanyID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDelivery = `-- name: LockDelivery :one
SELECT id, company_id, doc_type, doc_no, doc_date, customer_id, sales_user_id, warehouse_id, currency, exchange_rate, tax_type_id, tax_rate, payment_term_id, invoice_no, invoice_date, untaxed_amount, tax_amount, total_amount, base_untaxed, base_tax, base_total, status, note, submitted_by, submitted_at, approved_by, approved_at, posted_by, posted_at, created_by, updated_by, version, created_at, updated_at FROM deliveries WHERE id = $1 AND company_id = $2 FOR UPDATE
`

type LockDeliveryParams struct {
	ID        int64
	CompanyID int64
}

func (q *Queries) LockDelivery(ctx context.Context, arg LockDeliveryParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, lockDelivery, arg.ID, arg.CompanyID)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocType,
		&i.DocNo,
		&i.DocDate,
		&i.CustomerID,
		&i.SalesUserID,
		&i.WarehouseID,
		&i.Currency,
		&i.ExchangeRate,
		&i.TaxTypeID,
		&i.TaxRate,
		&i.PaymentTermID,
		&i.InvoiceNo,
		&i.InvoiceDate,
		&i.UntaxedAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.BaseUntaxed,
		&i.BaseTax,
		&i.BaseTotal,
		&i.Status,
		&i.Note,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.PostedBy,
		&i.PostedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockReceivableBySource = `-- name: LockReceivableBySource :one
SELECT id, company_id, customer_id, source_type, source_id, source_no, doc_date, due_date, currency, exchange_rate, amount, base_amount, paid_amount, created_by, created_at, updated_at, import_batch_id FROM accounts_receivable WHERE source_type = $1 AND source_id = $2 FOR UPDATE
`

type LockReceivableBySourceParams struct {
	SourceType string
	SourceID   int64
}

func (q *Queries) LockReceivableBySource(ctx context.Context, arg LockReceivableBySourceParams) (AccountsReceivable, error) {
	row := q.db.QueryRow(ctx, lockReceivableBySource, arg.SourceType, arg.SourceID)
	var i AccountsReceivable
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CustomerID,
		&i.SourceType,
		&i.SourceID,
		&i.SourceNo,
		&i.DocDate,
		&i.DueDate,
		&i.Currency,
		&i.ExchangeRate,
		&i.Amount,
		&i.BaseAmount,
		&i.PaidAmount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImportBatchID,
	)
	return i, err
}

const lockSalesOrder = `-- name: LockSalesOrder :one
SELECT id, company_id, doc_type, doc_no, doc_date, customer_id, sales_user_id, warehouse_id, quotation_id, valid_until, delivery_date, customer_po_no, currency, exchange_rate, tax_type_id, tax_rate, payment_term_id, untaxed_amount, tax_amount, total_amount, status, note, submitted_by, submitted_at, approved_by, approved_at, closed_by, closed_at, created_by, updated_by, version, created_at, updated_at FROM sales_orders WHERE id = $1 AND company_id = $2 FOR UPDATE
`

type LockSalesOrderParams struct {
	ID        int64
	CompanyID int64
}

func (q *Queries) LockSalesOrder(ctx context.Context, arg LockSalesOrderParams) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, lockSalesOrder, arg.ID, arg.CompanyID)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocType,
		&i.DocNo,
		&i.DocDate,
		&i.CustomerID,
		&i.SalesUserID,
		&i.WarehouseID,
		&i.QuotationID,
		&i.ValidUntil,
		&i.DeliveryDate,
		&i.CustomerPoNo,
		&i.Currency,
		&i.ExchangeRate,
		&i.TaxTypeID,
		&i.TaxRate,
		&i.PaymentTermID,
		&i.UntaxedAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.Status,
		&i.Note,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockSalesOrders = `-- name: LockSalesOrders :many
SELECT id FROM sales_orders
WHERE company_id = $1 AND id = ANY($2::bigint[])
ORDER BY id
FOR UPDATE
`

type LockSalesOrdersParams struct {
	CompanyID int64
	Ids       []int64
}

// 出貨過帳時鎖定來源訂單(依 id 排序,上鎖順序一致)
func (q *Queries) LockSalesOrders(ctx context.Context, arg LockSalesOrdersParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, lockSalesOrders, arg.CompanyID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const quotationOrderNo = `-- name: QuotationOrderNo :one
SELECT doc_no FROM sales_orders WHERE quotation_id = $1 AND status <> 'voided' LIMIT 1
`

// 報價單是否已轉成未作廢的訂單(取消核准、作廢前檢查)
func (q *Queries) QuotationOrderNo(ctx context.Context, quotationID *int64) (string, error) {
	row := q.db.QueryRow(ctx, quotationOrderNo, quotationID)
	var doc_no string
	err := row.Scan(&doc_no)
	return doc_no, err
}

const returnableDeliveryLines = `-- name: ReturnableDeliveryLines :many
SELECT l.id AS delivery_line_id, d.id AS delivery_id, d.doc_no, d.doc_date, d.warehouse_id, l.line_no,
       l.item_id, i.code AS item_code, i.name AS item_name, i.spec AS item_spec, l.unit_id, u.name AS unit_name,
       l.qty, l.unit_price, ret.returned_qty, (l.qty - ret.returned_qty)::numeric AS remaining_qty
FROM delivery_lines l
JOIN deliveries d ON d.id = l.delivery_id
JOIN items i ON i.id = l.item_id
JOIN units u ON u.id = l.unit_id
CROSS JOIN LATERAL (
    SELECT COALESCE(SUM(xl.qty), 0)::numeric AS returned_qty FROM delivery_lines xl
    JOIN deliveries x ON x.id = xl.delivery_id
    WHERE xl.delivery_line_id = l.id AND x.status = 'posted'
) ret
WHERE d.company_id = $1 AND d.doc_type = 'delivery' AND d.status = 'posted'
  AND d.customer_id = $2 AND d.currency = $3 AND l.qty > ret.returned_qty
  AND ($4::text IS NULL
       OR d.doc_no ILIKE '%' || $4 || '%'
       OR i.code ILIKE '%' || $4 || '%'
       OR i.name ILIKE '%' || $4 || '%')
ORDER BY d.doc_date DESC, d.doc_no DESC, l.line_no
LIMIT 200
`

type ReturnableDeliveryLinesParams struct {
	CompanyID  int64
	CustomerID int64
	Currency   string
	Keyword    *string
}

type ReturnableDeliveryLinesRow struct {
	DeliveryLineID int64
	DeliveryID     int64
	DocNo          string
	DocDate        time.Time
	WarehouseID    int64
	LineNo         int32
	ItemID         int64
	ItemCode       string
	ItemName       string
	ItemSpec       string
	UnitID         int64
	UnitName       string
	Qty            decimal.Decimal
	UnitPrice      decimal.Decimal
	ReturnedQty    decimal.Decimal
	RemainingQty   decimal.Decimal
}

// 可退回的出貨明細:已過帳出貨單中尚未退完的明細(退回單帶入用)
func (q *Queries) ReturnableDeliveryLines(ctx context.Context, arg ReturnableDeliveryLinesParams) ([]ReturnableDeliveryLinesRow, error) {
	rows, err := q.db.Query(ctx, returnableDeliveryLines,
		arg.CompanyID,
		arg.CustomerID,
		arg.Currency,
		arg.Keyword,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReturnableDeliveryLinesRow{}
	for rows.Next() {
		var i ReturnableDeliveryLinesRow
		if err := rows.Scan(
			&i.DeliveryLineID,
			&i.DeliveryID,
			&i.DocNo,
			&i.DocDate,
			&i.WarehouseID,
			&i.LineNo,
			&i.ItemID,
			&i.ItemCode,
			&i.ItemName,
			&i.ItemSpec,
			&i.UnitID,
			&i.UnitName,
			&i.Qty,
			&i.UnitPrice,
			&i.ReturnedQty,
			&i.RemainingQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesOrderDeliveryNo = `-- name: SalesOrderDeliveryNo :one
SELECT d.doc_no FROM delivery_lines dl
JOIN deliveries d ON d.id = dl.delivery_id
JOIN sales_order_lines l ON l.id = dl.so_line_id
WHERE l.order_id = $1 AND d.status <> 'voided'
LIMIT 1
`

// 訂單是否已被未作廢的出貨單引用(取消核准、作廢前檢查)
func (q *Queries) SalesOrderDeliveryNo(ctx context.Context, orderID int64) (string, error) {
	row := q.db.QueryRow(ctx, salesOrderDeliveryNo, orderID)
	var doc_no string
	err := row.Scan(&doc_no)
	return doc_no, err
}

const setDeliveryInvoice = `-- name: SetDeliveryInvoice :one
UPDATE deliveries
SET invoice_no = $1, invoice_date = $2, version = version + 1, updated_by = $3
WHERE id = $4 AND company_id = $5 AND version = $6 AND status <> 'voided'
RETURNING id, company_id, doc_type, doc_no, doc_date, customer_id, sales_user_id, warehouse_id, currency, exchange_rate, tax_type_id, tax_rate, payment_term_id, invoice_no, invoice_date, untaxed_amount, tax_amount, total_amount, base_untaxed, base_tax, base_total, status, note, submitted_by, submitted_at, approved_by, approved_at, posted_by, posted_at, created_by, updated_by, version, created_at, updated_at
`

type SetDeliveryInvoiceParams struct {
	InvoiceNo   string
	InvoiceDate *time.Time
	UpdatedBy   *int64
	ID          int64
	CompanyID   int64
	Version     int32
}

func (q *Queries) SetDeliveryInvoice(ctx context.Context, arg SetDeliveryInvoiceParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, setDeliveryInvoice,
		arg.InvoiceNo,
		arg.InvoiceDate,
		arg.UpdatedBy,
		arg.ID,
		arg.CompanyID,
		arg.Version,
	)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocType,
		&i.DocNo,
		&i.DocDate,
		&i.CustomerID,
		&i.SalesUserID,
		&i.WarehouseID,
		&i.Currency,
		&i.ExchangeRate,
		&i.TaxTypeID,
		&i.TaxRate,
		&i.PaymentTermID,
		&i.InvoiceNo,
		&i.InvoiceDate,
		&i.UntaxedAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.BaseUntaxed,
		&i.BaseTax,
		&i.BaseTotal,
		&i.Status,
		&i.Note,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.PostedBy,
		&i.PostedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setDeliveryStatus = `-- name: SetDeliveryStatus :one
UPDATE deliveries
SET status       = $1,
    submitted_by = CASE WHEN $2::text = 'submit' THEN $3::bigint ELSE submitted_by END,
    submitted_at = CASE WHEN $2::text = 'submit' THEN now() ELSE submitted_at END,
    approved_by  = CASE WHEN $2::text = 'approve' THEN $3::bigint
                        WHEN $2::text IN ('reject', 'unapprove') THEN NULL ELSE approved_by END,
    approved_at  = CASE WHEN $2::text = 'approve' THEN now()
                        WHEN $2::text IN ('reject', 'unapprove') THEN NULL ELSE approved_at END,
    posted_by    = CASE WHEN $2::text = 'post' THEN $3::bigint
                        WHEN $2::text = 'unpost' THEN NULL ELSE posted_by END,
    posted_at    = CASE WHEN $2::text = 'post' THEN now()
                        WHEN $2::text = 'unpost' THEN NULL ELSE posted_at END,
    version      = version + 1,
    updated_by   = $3::bigint
WHERE id = $4 AND company_id = $5 AND version = $6
RETURNING id, company_id, doc_type, doc_no, doc_date, customer_id, sales_user_id, warehouse_id, currency, exchange_rate, tax_type_id, tax_rate, payment_term_id, invoice_no, invoice_date, untaxed_amount, tax_amount, total_amount, base_untaxed, base_tax, base_total, status, note, submitted_by, submitted_at, approved_by, approved_at, posted_by, posted_at, created_by, updated_by, version, created_at, updated_at
`

type SetDeliveryStatusParams struct {
	Status    string
	Action    string
	ActorID   int64
	ID        int64
	CompanyID int64
	Version   int32
}

func (q *Queries) SetDeliveryStatus(ctx context.Context, arg SetDeliveryStatusParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, setDeliveryStatus,
		arg.Status,
		arg.Action,
		arg.ActorID,
		arg.ID,
		arg.CompanyID,
		arg.Version,
	)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocType,
		&i.DocNo,
		&i.DocDate,
		&i.CustomerID,
		&i.SalesUserID,
		&i.WarehouseID,
		&i.Currency,
		&i.ExchangeRate,
		&i.TaxTypeID,
		&i.TaxRate,
		&i.PaymentTermID,
		&i.InvoiceNo,
		&i.InvoiceDate,
		&i.UntaxedAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.BaseUntaxed,
		&i.BaseTax,
		&i.BaseTotal,
		&i.Status,
		&i.Note,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.PostedBy,
		&i.PostedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setSalesOrderStatus = `-- name: SetSalesOrderStatus :one
UPDATE sales_orders
SET status       = $1,
    submitted_by = CASE WHEN $2::text = 'submit' THEN $3::bigint ELSE submitted_by END,
    submitted_at = CASE WHEN $2::text = 'submit' THEN now() ELSE submitted_at END,
    approved_by  = CASE WHEN $2::text = 'approve' THEN $3::bigint
                        WHEN $2::text IN ('reject', 'unapprove') THEN NULL ELSE approved_by END,
    approved_at  = CASE WHEN $2::text = 'approve' THEN now()
                        WHEN $2::text IN ('reject', 'unapprove') THEN NULL ELSE approved_at END,
    closed_by    = CASE WHEN $2::text = 'close' THEN $3::bigint
                        WHEN $2::text = 'reopen' THEN NULL ELSE closed_by END,
    closed_at    = CASE WHEN $2::text = 'close' THEN now()
                        WHEN $2::text = 'reopen' THEN NULL ELSE closed_at END,
    version      = version + 1,
    updated_by   = $3::bigint
WHERE id = $4 AND company_id = $5 AND version = $6
RETURNING id, company_id, doc_type, doc_no, doc_date, customer_id, sales_user_id, warehouse_id, quotation_id, valid_until, delivery_date, customer_po_no, currency, exchange_rate, tax_type_id, tax_rate, payment_term_id, untaxed_amount, tax_amount, total_amount, status, note, submitted_by, submitted_at, approved_by, approved_at, closed_by, closed_at, created_by, updated_by, version, created_at, updated_at
`

type SetSalesOrderStatusParams struct {
	Status    string
	Action    string
	ActorID   int64
	ID        int64
	CompanyID int64
	Version   int32
}

func (q *Queries) SetSalesOrderStatus(ctx context.Context, arg SetSalesOrderStatusParams) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, setSalesOrderStatus,
		arg.Status,
		arg.Action,
		arg.ActorID,
		arg.ID,
		arg.CompanyID,
		arg.Version,
	)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocType,
		&i.DocNo,
		&i.DocDate,
		&i.CustomerID,
		&i.SalesUserID,
		&i.WarehouseID,
		&i.QuotationID,
		&i.ValidUntil,
		&i.DeliveryDate,
		&i.CustomerPoNo,
		&i.Currency,
		&i.ExchangeRate,
		&i.TaxTypeID,
		&i.TaxRate,
		&i.PaymentTermID,
		&i.UntaxedAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.Status,
		&i.Note,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const soLineRefs = `-- name: SoLineRefs :many
SELECT l.id, l.order_id, o.doc_no, o.doc_type, o.status, o.customer_id, o.currency, l.item_id, l.unit_id, l.qty,
       (SELECT COALESCE(SUM(dl.qty), 0) FROM delivery_lines dl
        JOIN deliveries d ON d.id = dl.delivery_id
        WHERE dl.so_line_id = l.id AND d.status = 'posted' AND d.id <> $1::bigint)::numeric
           AS delivered_qty
FROM sales_order_lines l
JOIN sales_orders o ON o.id = l.order_id
WHERE o.company_id = $2 AND l.id = ANY($3::bigint[])
`

type SoLineRefsParams struct {
	ExcludeDeliveryID int64
	CompanyID         int64
	Ids               []int64
}

type SoLineRefsRow struct {
	ID           int64
	OrderID      int64
	DocNo        string
	DocType      string
	Status       string
	CustomerID   int64
	Currency     string
	ItemID       int64
	UnitID       int64
	Qty          decimal.Decimal
	DeliveredQty decimal.Decimal
}

// 出貨明細引用的訂單明細,以及「其他」已過帳出貨單的已出貨量
func (q *Queries) SoLineRefs(ctx context.Context, arg SoLineRefsParams) ([]SoLineRefsRow, error) {
	rows, err := q.db.Query(ctx, soLineRefs, arg.ExcludeDeliveryID, arg.CompanyID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SoLineRefsRow{}
	for rows.Next() {
		var i SoLineRefsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.DocNo,
			&i.DocType,
			&i.Status,
			&i.CustomerID,
			&i.Currency,
			&i.ItemID,
			&i.UnitID,
			&i.Qty,
			&i.DeliveredQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unshippedSalesLines = `-- name: UnshippedSalesLines :many
SELECT l.id AS so_line_id, o.id AS order_id, o.doc_no, o.doc_date, o.delivery_date, o.customer_id,
       c.code AS customer_code, c.name AS customer_name, o.currency, o.warehouse_id, o.customer_po_no,
       l.line_no, l.item_id, i.code AS item_code, i.name AS item_name, i.spec AS item_spec,
       l.unit_id, u.name AS unit_name, l.qty, l.unit_price, dlv.delivered_qty,
       (l.qty - dlv.delivered_qty)::numeric AS remaining_qty
FROM sales_order_lines l
JOIN sales_orders o ON o.id = l.order_id
JOIN customers c ON c.id = o.customer_id
JOIN items i ON i.id = l.item_id
JOIN units u ON u.id = l.unit_id
LEFT JOIN users su ON su.id = o.sales_user_id
CROSS JOIN LATERAL (
    SELECT COALESCE(SUM(dl.qty), 0)::numeric AS delivered_qty FROM delivery_lines dl
    JOIN deliveries d ON d.id = dl.delivery_id
    WHERE dl.so_line_id = l.id AND d.status = 'posted'
) dlv
WHERE o.company_id = $1 AND o.doc_type = 'order' AND o.status = 'approved' AND l.qty > dlv.delivered_qty
  AND ($2::bigint IS NULL OR o.customer_id = $2)
  AND ($3::text IS NULL OR o.currency = $3)
  AND ($4::text IS NULL
       OR o.doc_no ILIKE '%' || $4 || '%'
       OR o.customer_po_no ILIKE '%' || $4 || '%'
       OR i.code ILIKE '%' || $4 || '%'
       OR i.name ILIKE '%' || $4 || '%')
  AND ($5::date IS NULL OR o.delivery_date <= $5)
  AND ($6::bigint IS NULL OR o.sales_user_id = $6)
  AND ($7::bigint IS NULL OR su.department_id = $7)
ORDER BY o.delivery_date NULLS LAST, o.doc_no, l.line_no
LIMIT $9 OFFSET $8
`

type UnshippedSalesLinesParams struct {
	CompanyID   int64
	CustomerID  *int64
	Currency    *string
	Keyword     *string
	DueBefore   *time.Time
	ScopeUserID *int64
	ScopeDeptID *int64
	Off         int32
	Lim         int32
}

type UnshippedSalesLinesRow struct {
	SoLineID     int64
	OrderID      int64
	DocNo        string
	DocDate      time.Time
	DeliveryDate *time.Time
	CustomerID   int64
	CustomerCode string
	CustomerName string
	Currency     string
	WarehouseID  int64
	CustomerPoNo string
	LineNo       int32
	ItemID       int64
	ItemCode     string
	ItemName     string
	ItemSpec     string
	UnitID       int64
	UnitName     string
	Qty          decimal.Decimal
	UnitPrice    decimal.Decimal
	DeliveredQty decimal.Decimal
	RemainingQty decimal.Decimal
}

// 未出貨明細:已核准訂單中尚未出齊的明細(未出貨清單、出貨單帶入用)
func (q *Queries) UnshippedSalesLines(ctx context.Context, arg UnshippedSalesLinesParams) ([]UnshippedSalesLinesRow, error) {
	rows, err := q.db.Query(ctx, unshippedSalesLines,
		arg.CompanyID,
		arg.CustomerID,
		arg.Currency,
		arg.Keyword,
		arg.DueBefore,
		arg.ScopeUserID,
		arg.ScopeDeptID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnshippedSalesLinesRow{}
	for rows.Next() {
		var i UnshippedSalesLinesRow
		if err := rows.Scan(
			&i.SoLineID,
			&i.OrderID,
			&i.DocNo,
			&i.DocDate,
			&i.DeliveryDate,
			&i.CustomerID,
			&i.CustomerCode,
			&i.CustomerName,
			&i.Currency,
			&i.WarehouseID,
			&i.CustomerPoNo,
			&i.LineNo,
			&i.ItemID,
			&i.ItemCode,
			&i.ItemName,
			&i.ItemSpec,
			&i.UnitID,
			&i.UnitName,
			&i.Qty,
			&i.UnitPrice,
			&i.DeliveredQty,
			&i.RemainingQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeliveryHeader = `-- name: UpdateDeliveryHeader :one
UPDATE deliveries
SET doc_date = $1, customer_id = $2, sales_user_id = $3,
    warehouse_id = $4, currency = $5, exchange_rate = $6, tax_type_id = $7,
    tax_rate = $8, payment_term_id = $9, untaxed_amount = $10,
    tax_amount = $11, total_amount = $12, base_untaxed = $13, base_tax = $14,
    base_total = $15, note = $16, version = version + 1, updated_by = $17
WHERE id = $18 AND company_id = $19 AND version = $20 AND status = 'draft'
RETURNING id, company_id, doc_type, doc_no, doc_date, customer_id, sales_user_id, warehouse_id, currency, exchange_rate, tax_type_id, tax_rate, payment_term_id, invoice_no, invoice_date, untaxed_amount, tax_amount, total_amount, base_untaxed, base_tax, base_total, status, note, submitted_by, submitted_at, approved_by, approved_at, posted_by, posted_at, created_by, updated_by, version, created_at, updated_at
`

type UpdateDeliveryHeaderParams struct {
	DocDate       time.Time
	CustomerID    int64
	SalesUserID   *int64
	WarehouseID   int64
	Currency      string
	ExchangeRate  decimal.Decimal
	TaxTypeID     int64
	TaxRate       decimal.Decimal
	PaymentTermID *int64
	UntaxedAmount decimal.Decimal
	TaxAmount     decimal.Decimal
	TotalAmount   decimal.Decimal
	BaseUntaxed   decimal.Decimal
	BaseTax       decimal.Decimal
	BaseTotal     decimal.Decimal
	Note          string
	UpdatedBy     *int64
	ID            int64
	CompanyID     int64
	Version       int32
}

func (q *Queries) UpdateDeliveryHeader(ctx context.Context, arg UpdateDeliveryHeaderParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, updateDeliveryHeader,
		arg.DocDate,
		arg.CustomerID,
		arg.SalesUserID,
		arg.WarehouseID,
		arg.Currency,
		arg.ExchangeRate,
		arg.TaxTypeID,
		arg.TaxRate,
		arg.PaymentTermID,
		arg.UntaxedAmount,
		arg.TaxAmount,
		arg.TotalAmount,
		arg.BaseUntaxed,
		arg.BaseTax,
		arg.BaseTotal,
		arg.Note,
		arg.UpdatedBy,
		arg.ID,
		arg.CompanyID,
		arg.Version,
	)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocType,
		&i.DocNo,
		&i.DocDate,
		&i.CustomerID,
		&i.SalesUserID,
		&i.WarehouseID,
		&i.Currency,
		&i.ExchangeRate,
		&i.TaxTypeID,
		&i.TaxRate,
		&i.PaymentTermID,
		&i.InvoiceNo,
		&i.InvoiceDate,
		&i.UntaxedAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.BaseUntaxed,
		&i.BaseTax,
		&i.BaseTotal,
		&i.Status,
		&i.Note,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.PostedBy,
		&i.PostedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSalesOrderHeader = `-- name: UpdateSalesOrderHeader :one
UPDATE sales_orders
SET doc_date = $1, customer_id = $2, sales_user_id = $3,
    warehouse_id = $4, quotation_id = $5, valid_until = $6,
    delivery_date = $7, customer_po_no = $8, currency = $9,
    exchange_rate = $10, tax_type_id = $11, tax_rate = $12,
    payment_term_id = $13, untaxed_amount = $14, tax_amount = $15,
    total_amount = $16, note = $17, version = version + 1, updated_by = $18
WHERE id = $19 AND company_id = $20 AND version = $21 AND status = 'draft'
RETURNING id, company_id, doc_type, doc_no, doc_date, customer_id, sales_user_id, warehouse_id, quotation_id, valid_until, delivery_date, customer_po_no, currency, exchange_rate, tax_type_id, tax_rate, payment_term_id, untaxed_amount, tax_amount, total_amount, status, note, submitted_by, submitted_at, approved_by, approved_at, closed_by, closed_at, created_by, updated_by, version, created_at, updated_at
`

type UpdateSalesOrderHeaderParams struct {
	DocDate       time.Time
	CustomerID    int64
	SalesUserID   *int64
	WarehouseID   int64
	QuotationID   *int64
	ValidUntil    *time.Time
	DeliveryDate  *time.Time
	CustomerPoNo  string
	Currency      string
	ExchangeRate  decimal.Decimal
	TaxTypeID     int64
	TaxRate       decimal.Decimal
	PaymentTermID *int64
	UntaxedAmount decimal.Decimal
	TaxAmount     decimal.Decimal
	TotalAmount   decimal.Decimal
	Note          string
	UpdatedBy     *int64
	ID            int64
	CompanyID     int64
	Version       int32
}

func (q *Queries) UpdateSalesOrderHeader(ctx context.Context, arg UpdateSalesOrderHeaderParams) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, updateSalesOrderHeader,
		arg.DocDate,
		arg.CustomerID,
		arg.SalesUserID,
		arg.WarehouseID,
		arg.QuotationID,
		arg.ValidUntil,
		arg.DeliveryDate,
		arg.CustomerPoNo,
		arg.Currency,
		arg.ExchangeRate,
		arg.TaxTypeID,
		arg.TaxRate,
		arg.PaymentTermID,
		arg.UntaxedAmount,
		arg.TaxAmount,
		arg.TotalAmount,
		arg.Note,
		arg.UpdatedBy,
		arg.ID,
		arg.CompanyID,
		arg.Version,
	)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocType,
		&i.DocNo,
		&i.DocDate,
		&i.CustomerID,
		&i.SalesUserID,
		&i.WarehouseID,
		&i.QuotationID,
		&i.ValidUntil,
		&i.DeliveryDate,
		&i.CustomerPoNo,
		&i.Currency,
		&i.ExchangeRate,
		&i.TaxTypeID,
		&i.TaxRate,
		&i.PaymentTermID,
		&i.UntaxedAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.Status,
		&i.Note,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
