// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settlement.sql

package db

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const addPayablePaid = `-- name: AddPayablePaid :exec
UPDATE accounts_payable SET paid_amount = paid_amount + $1 WHERE id = $2
`

type AddPayablePaidParams struct {
	Delta decimal.Decimal
	ID    int64
}

func (q *Queries) AddPayablePaid(ctx context.Context, arg AddPayablePaidParams) error {
	_, err := q.db.Exec(ctx, addPayablePaid, arg.Delta, arg.ID)
	return err
}

const addReceivablePaid = `-- name: AddReceivablePaid :exec
UPDATE accounts_receivable SET paid_amount = paid_amount + $1 WHERE id = $2
`

type AddReceivablePaidParams struct {
	Delta decimal.Decimal
	ID    int64
}

func (q *Queries) AddReceivablePaid(ctx context.Context, arg AddReceivablePaidParams) error {
	_, err := q.db.Exec(ctx, addReceivablePaid, arg.Delta, arg.ID)
	return err
}

const addSettlementLine = `-- name: AddSettlementLine :exec
INSERT INTO settlement_lines (settlement_id, line_no, receivable_id, payable_id, amount)
VALUES ($1, $2, $3, $4, $5)
`

type AddSettlementLineParams struct {
	SettlementID int64
	LineNo       int32
	ReceivableID *int64
	PayableID    *int64
	Amount       decimal.Decimal
}

func (q *Queries) AddSettlementLine(ctx context.Context, arg AddSettlementLineParams) error {
	_, err := q.db.Exec(ctx, addSettlementLine,
		arg.SettlementID,
		arg.LineNo,
		arg.ReceivableID,
		arg.PayableID,
		arg.Amount,
	)
	return err
}

const countSettlements = `-- name: CountSettlements :one
SELECT count(*) FROM settlements s
LEFT JOIN users su ON su.id = s.sales_user_id
WHERE s.company_id = $1 AND s.side = $2::text
  AND ($3::text IS NULL OR s.status = $3)
  AND ($4::bigint IS NULL OR s.customer_id = $4 OR s.supplier_id = $4)
  AND ($5::text IS NULL OR s.doc_no ILIKE '%' || $5 || '%'
       OR s.reference ILIKE '%' || $5 || '%')
  AND ($6::date IS NULL OR s.doc_date >= $6)
  AND ($7::date IS NULL OR s.doc_date <= $7)
  AND ($8::bigint IS NULL OR s.sales_user_id = $8)
  AND ($9::bigint IS NULL OR su.department_id = $9)
`

type CountSettlementsParams struct {
	CompanyID   int64
	Side        string
	Status      *string
	PartnerID   *int64
	Keyword     *string
	FromDate    *time.Time
	ToDate      *time.Time
	ScopeUserID *int64
	ScopeDeptID *int64
}

func (q *Queries) CountSettlements(ctx context.Context, arg CountSettlementsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSettlements,
		arg.CompanyID,
		arg.Side,
		arg.Status,
		arg.PartnerID,
		arg.Keyword,
		arg.FromDate,
		arg.ToDate,
		arg.ScopeUserID,
		arg.ScopeDeptID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSettlement = `-- name: CreateSettlement :one
INSERT INTO settlements (company_id, side, doc_no, doc_date, customer_id, supplier_id, sales_user_id, currency,
                         method, reference, amount, note, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, $10, $11, $12, $13, $13)
RETURNING id, company_id, side, doc_no, doc_date, customer_id, supplier_id, sales_user_id, currency, method, reference, amount, status, note, submitted_by, submitted_at, approved_by, approved_at, posted_by, posted_at, created_by, updated_by, version, created_at, updated_at
`

type CreateSettlementParams struct {
	CompanyID   int64
	Side        string
	DocNo       string
	DocDate     time.Time
	CustomerID  *int64
	SupplierID  *int64
	SalesUserID *int64
	Currency    string
	Method      string
	Reference   string
	Amount      decimal.Decimal
	Note        string
	CreatedBy   *int64
}

func (q *Queries) CreateSettlement(ctx context.Context, arg CreateSettlementParams) (Settlement, error) {
	row := q.db.QueryRow(ctx, createSettlement,
		arg.CompanyID,
		arg.Side,
		arg.DocNo,
		arg.DocDate,
		arg.CustomerID,
		arg.SupplierID,
		arg.SalesUserID,
		arg.Currency,
		arg.Method,
		arg.Reference,
		arg.Amount,
		arg.Note,
		arg.CreatedBy,
	)
	var i Settlement
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Side,
		&i.DocNo,
		&i.DocDate,
		&i.CustomerID,
		&i.SupplierID,
		&i.SalesUserID,
		&i.Currency,
		&i.Method,
		&i.Reference,
		&i.Amount,
		&i.Status,
		&i.Note,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.PostedBy,
		&i.PostedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSettlementLines = `-- name: DeleteSettlementLines :exec
DELETE FROM settlement_lines WHERE settlement_id = $1
`

func (q *Queries) DeleteSettlementLines(ctx context.Context, settlementID int64) error {
	_, err := q.db.Exec(ctx, deleteSettlementLines, settlementID)
	return err
}

const deleteSettlementLinesByPayable = `-- name: DeleteSettlementLinesByPayable :exec
DELETE FROM settlement_lines WHERE payable_id = $1
`

func (q *Queries) DeleteSettlementLinesByPayable(ctx context.Context, payableID *int64) error {
	_, err := q.db.Exec(ctx, deleteSettlementLinesByPayable, payableID)
	return err
}

const deleteSettlementLinesByReceivable = `-- name: DeleteSettlementLinesByReceivable :exec
DELETE FROM settlement_lines WHERE receivable_id = $1
`

// 移除應收前清掉已作廢收款單的明細(未作廢者已在呼叫端擋下)
func (q *Queries) DeleteSettlementLinesByReceivable(ctx context.Context, receivableID *int64) error {
	_, err := q.db.Exec(ctx, deleteSettlementLinesByReceivable, receivableID)
	return err
}

const getSettlement = `-- name: GetSettlement :one
SELECT s.id, s.company_id, s.side, s.doc_no, s.doc_date, s.customer_id, s.supplier_id, s.sales_user_id, s.currency, s.method, s.reference, s.amount, s.status, s.note, s.submitted_by, s.submitted_at, s.approved_by, s.approved_at, s.posted_by, s.posted_at, s.created_by, s.updated_by, s.version, s.created_at, s.updated_at, COALESCE(c.code, sp.code) AS partner_code, COALESCE(c.name, sp.name) AS partner_name,
       su.name AS sales_user_name, su.department_id AS sales_department_id,
       cu.name AS created_by_name, sbu.name AS submitted_by_name, au.name AS approved_by_name,
       pu.name AS posted_by_name
FROM settlements s
LEFT JOIN customers c ON c.id = s.customer_id
LEFT JOIN suppliers sp ON sp.id = s.supplier_id
LEFT JOIN users su ON su.id = s.sales_user_id
LEFT JOIN users cu ON cu.id = s.created_by
LEFT JOIN users sbu ON sbu.id = s.submitted_by
LEFT JOIN users au ON au.id = s.approved_by
LEFT JOIN users pu ON pu.id = s.posted_by
WHERE s.id = $1 AND s.company_id = $2
`

type GetSettlementParams struct {
	ID        int64
	CompanyID int64
}

type GetSettlementRow struct {
	ID                int64
	CompanyID         int64
	Side              string
	DocNo             string
	DocDate           time.Time
	CustomerID        *int64
	SupplierID        *int64
	SalesUserID       *int64
	Currency          string
	Method            string
	Reference         string
	Amount            decimal.Decimal
	Status            string
	Note              string
	SubmittedBy       *int64
	SubmittedAt       *time.Time
	ApprovedBy        *int64
	ApprovedAt        *time.Time
	PostedBy          *int64
	PostedAt          *time.Time
	CreatedBy         *int64
	UpdatedBy         *int64
	Version           int32
	CreatedAt         time.Time
	UpdatedAt         time.Time
	PartnerCode       string
	PartnerName       string
	SalesUserName     *string
	SalesDepartmentID *int64
	CreatedByName     *string
	SubmittedByName   *string
	ApprovedByName    *string
	PostedByName      *string
}

func (q *Queries) GetSettlement(ctx context.Context, arg GetSettlementParams) (GetSettlementRow, error) {
	row := q.db.QueryRow(ctx, getSettlement, arg.ID, arg.CompanyID)
	var i GetSettlementRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Side,
		&i.DocNo,
		&i.DocDate,
		&i.CustomerID,
		&i.SupplierID,
		&i.SalesUserID,
		&i.Currency,
		&i.Method,
		&i.Reference,
		&i.Amount,
		&i.Status,
		&i.Note,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.PostedBy,
		&i.PostedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PartnerCode,
		&i.PartnerName,
		&i.SalesUserName,
		&i.SalesDepartmentID,
		&i.CreatedByName,
		&i.SubmittedByName,
		&i.ApprovedByName,
		&i.PostedByName,
	)
	return i, err
}

const listSettlementLines = `-- name: ListSettlementLines :many
SELECT l.id, l.line_no, l.receivable_id, l.payable_id, l.amount,
       COALESCE(r.source_no, p.source_no) AS source_no, COALESCE(r.source_type, p.source_type) AS source_type,
       COALESCE(r.doc_date, p.doc_date) AS source_date, COALESCE(r.due_date, p.due_date) AS due_date,
       COALESCE(r.amount, p.amount) AS source_amount, COALESCE(r.paid_amount, p.paid_amount) AS source_paid
FROM settlement_lines l
LEFT JOIN accounts_receivable r ON r.id = l.receivable_id
LEFT JOIN accounts_payable p ON p.id = l.payable_id
WHERE l.settlement_id = $1
ORDER BY l.line_no
`

type ListSettlementLinesRow struct {
	ID           int64
	LineNo       int32
	ReceivableID *int64
	PayableID    *int64
	Amount       decimal.Decimal
	SourceNo     string
	SourceType   string
	SourceDate   time.Time
	DueDate      time.Time
	SourceAmount decimal.Decimal
	SourcePaid   decimal.Decimal
}

func (q *Queries) ListSettlementLines(ctx context.Context, settlementID int64) ([]ListSettlementLinesRow, error) {
	rows, err := q.db.Query(ctx, listSettlementLines, settlementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSettlementLinesRow{}
	for rows.Next() {
		var i ListSettlementLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.LineNo,
			&i.ReceivableID,
			&i.PayableID,
			&i.Amount,
			&i.SourceNo,
			&i.SourceType,
			&i.SourceDate,
			&i.DueDate,
			&i.SourceAmount,
			&i.SourcePaid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettlements = `-- name: ListSettlements :many

SELECT s.id, s.side, s.doc_no, s.doc_date, s.currency, s.method, s.reference, s.amount, s.status, s.note,
       s.version, s.updated_at,
       COALESCE(c.code, sp.code) AS partner_code, COALESCE(c.name, sp.name) AS partner_name,
       su.name AS sales_user_name, cu.name AS created_by_name
FROM settlements s
LEFT JOIN customers c ON c.id = s.customer_id
LEFT JOIN suppliers sp ON sp.id = s.supplier_id
LEFT JOIN users su ON su.id = s.sales_user_id
LEFT JOIN users cu ON cu.id = s.created_by
WHERE s.company_id = $1 AND s.side = $2::text
  AND ($3::text IS NULL OR s.status = $3)
  AND ($4::bigint IS NULL OR s.customer_id = $4 OR s.supplier_id = $4)
  AND ($5::text IS NULL OR s.doc_no ILIKE '%' || $5 || '%'
       OR s.reference ILIKE '%' || $5 || '%')
  AND ($6::date IS NULL OR s.doc_date >= $6)
  AND ($7::date IS NULL OR s.doc_date <= $7)
  AND ($8::bigint IS NULL OR s.sales_user_id = $8)
  AND ($9::bigint IS NULL OR su.department_id = $9)
ORDER BY s.doc_date DESC, s.id DESC
LIMIT $11 OFFSET $10
`

type ListSettlementsParams struct {
	CompanyID   int64
	Side        string
	Status      *string
	PartnerID   *int64
	Keyword     *string
	FromDate    *time.Time
	ToDate      *time.Time
	ScopeUserID *int64
	ScopeDeptID *int64
	Off         int32
	Lim         int32
}

type ListSettlementsRow struct {
	ID            int64
	Side          string
	DocNo         string
	DocDate       time.Time
	Currency      string
	Method        string
	Reference     string
	Amount        decimal.Decimal
	Status        string
	Note          string
	Version       int32
	UpdatedAt     time.Time
	PartnerCode   string
	PartnerName   string
	SalesUserName *string
	CreatedByName *string
}

// ======== 收款單 / 付款單 ========
// scope_* 為資料範圍:收款單依負責業務快照過濾(D38);付款單無資料範圍
func (q *Queries) ListSettlements(ctx context.Context, arg ListSettlementsParams) ([]ListSettlementsRow, error) {
	rows, err := q.db.Query(ctx, listSettlements,
		arg.CompanyID,
		arg.Side,
		arg.Status,
		arg.PartnerID,
		arg.Keyword,
		arg.FromDate,
		arg.ToDate,
		arg.ScopeUserID,
		arg.ScopeDeptID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSettlementsRow{}
	for rows.Next() {
		var i ListSettlementsRow
		if err := rows.Scan(
			&i.ID,
			&i.Side,
			&i.DocNo,
			&i.DocDate,
			&i.Currency,
			&i.Method,
			&i.Reference,
			&i.Amount,
			&i.Status,
			&i.Note,
			&i.Version,
			&i.UpdatedAt,
			&i.PartnerCode,
			&i.PartnerName,
			&i.SalesUserName,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPayables = `-- name: LockPayables :many
SELECT id, supplier_id, currency, amount, base_amount, paid_amount, source_no FROM accounts_payable
WHERE company_id = $1 AND id = ANY($2::bigint[])
ORDER BY id
FOR UPDATE
`

type LockPayablesParams struct {
	CompanyID int64
	Ids       []int64
}

type LockPayablesRow struct {
	ID         int64
	SupplierID int64
	Currency   string
	Amount     decimal.Decimal
	BaseAmount decimal.Decimal
	PaidAmount decimal.Decimal
	SourceNo   string
}

func (q *Queries) LockPayables(ctx context.Context, arg LockPayablesParams) ([]LockPayablesRow, error) {
	rows, err := q.db.Query(ctx, lockPayables, arg.CompanyID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockPayablesRow{}
	for rows.Next() {
		var i LockPayablesRow
		if err := rows.Scan(
			&i.ID,
			&i.SupplierID,
			&i.Currency,
			&i.Amount,
			&i.BaseAmount,
			&i.PaidAmount,
			&i.SourceNo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockReceivables = `-- name: LockReceivables :many
SELECT id, customer_id, currency, amount, base_amount, paid_amount, source_no FROM accounts_receivable
WHERE company_id = $1 AND id = ANY($2::bigint[])
ORDER BY id
FOR UPDATE
`

type LockReceivablesParams struct {
	CompanyID int64
	Ids       []int64
}

type LockReceivablesRow struct {
	ID         int64
	CustomerID int64
	Currency   string
	Amount     decimal.Decimal
	BaseAmount decimal.Decimal
	PaidAmount decimal.Decimal
	SourceNo   string
}

// 過帳 / 反過帳時依 id 順序鎖定要沖的應收;同時用於開單驗證(不鎖也可讀)
func (q *Queries) LockReceivables(ctx context.Context, arg LockReceivablesParams) ([]LockReceivablesRow, error) {
	rows, err := q.db.Query(ctx, lockReceivables, arg.CompanyID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockReceivablesRow{}
	for rows.Next() {
		var i LockReceivablesRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Currency,
			&i.Amount,
			&i.BaseAmount,
			&i.PaidAmount,
			&i.SourceNo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSettlement = `-- name: LockSettlement :one
SELECT id, company_id, side, doc_no, doc_date, customer_id, supplier_id, sales_user_id, currency, method, reference, amount, status, note, submitted_by, submitted_at, approved_by, approved_at, posted_by, posted_at, created_by, updated_by, version, created_at, updated_at FROM settlements WHERE id = $1 AND company_id = $2 FOR UPDATE
`

type LockSettlementParams struct {
	ID        int64
	CompanyID int64
}

func (q *Queries) LockSettlement(ctx context.Context, arg LockSettlementParams) (Settlement, error) {
	row := q.db.QueryRow(ctx, lockSettlement, arg.ID, arg.CompanyID)
	var i Settlement
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Side,
		&i.DocNo,
		&i.DocDate,
		&i.CustomerID,
		&i.SupplierID,
		&i.SalesUserID,
		&i.Currency,
		&i.Method,
		&i.Reference,
		&i.Amount,
		&i.Status,
		&i.Note,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.PostedBy,
		&i.PostedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const payableAging = `-- name: PayableAging :many
WITH items AS (
    SELECT p.supplier_id AS partner_id, ($1::date - p.due_date)::int AS days,
           (CASE WHEN p.amount = 0 THEN 0 ELSE p.base_amount * (p.amount - p.paid_amount) / p.amount END)::numeric AS bal
    FROM accounts_payable p
    WHERE p.company_id = $2 AND p.amount <> p.paid_amount AND p.doc_date <= $1::date
)
SELECT sp.id AS partner_id, sp.code AS partner_code, sp.name AS partner_name,
       COALESCE(SUM(i.bal) FILTER (WHERE i.days <= 0), 0)::numeric AS not_due,
       COALESCE(SUM(i.bal) FILTER (WHERE i.days BETWEEN 1 AND 30), 0)::numeric AS d1_30,
       COALESCE(SUM(i.bal) FILTER (WHERE i.days BETWEEN 31 AND 60), 0)::numeric AS d31_60,
       COALESCE(SUM(i.bal) FILTER (WHERE i.days BETWEEN 61 AND 90), 0)::numeric AS d61_90,
       COALESCE(SUM(i.bal) FILTER (WHERE i.days > 90), 0)::numeric AS d90_plus,
       COALESCE(SUM(i.bal), 0)::numeric AS total
FROM items i
JOIN suppliers sp ON sp.id = i.partner_id
GROUP BY sp.id
ORDER BY sp.code
`

type PayableAgingParams struct {
	AsOf      time.Time
	CompanyID int64
}

type PayableAgingRow struct {
	PartnerID   int64
	PartnerCode string
	PartnerName string
	NotDue      decimal.Decimal
	D130        decimal.Decimal
	D3160       decimal.Decimal
	D6190       decimal.Decimal
	D90Plus     decimal.Decimal
	Total       decimal.Decimal
}

func (q *Queries) PayableAging(ctx context.Context, arg PayableAgingParams) ([]PayableAgingRow, error) {
	rows, err := q.db.Query(ctx, payableAging, arg.AsOf, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PayableAgingRow{}
	for rows.Next() {
		var i PayableAgingRow
		if err := rows.Scan(
			&i.PartnerID,
			&i.PartnerCode,
			&i.PartnerName,
			&i.NotDue,
			&i.D130,
			&i.D3160,
			&i.D6190,
			&i.D90Plus,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const payableSettlementNo = `-- name: PayableSettlementNo :one
SELECT s.doc_no FROM settlement_lines l JOIN settlements s ON s.id = l.settlement_id
WHERE l.payable_id = $1 AND s.status <> 'voided' LIMIT 1
`

func (q *Queries) PayableSettlementNo(ctx context.Context, payableID *int64) (string, error) {
	row := q.db.QueryRow(ctx, payableSettlementNo, payableID)
	var doc_no string
	err := row.Scan(&doc_no)
	return doc_no, err
}

const payableStatement = `-- name: PayableStatement :many
SELECT txn_date, kind, doc_no, delta, ref_id FROM (
    SELECT p.doc_date AS txn_date, p.source_type::text AS kind, p.source_no AS doc_no, p.amount AS delta,
           p.source_id AS ref_id, 0 AS ord
    FROM accounts_payable p
    WHERE p.company_id = $1 AND p.supplier_id = $2 AND p.currency = $3::text
      AND p.doc_date BETWEEN $4::date AND $5::date
    UNION ALL
    SELECT s.doc_date, 'payment'::text, s.doc_no, -SUM(l.amount), s.id, 1
    FROM settlements s JOIN settlement_lines l ON l.settlement_id = s.id
    WHERE s.company_id = $1 AND s.supplier_id = $2 AND s.currency = $3::text
      AND s.status = 'posted' AND s.doc_date BETWEEN $4::date AND $5::date
    GROUP BY s.id
) t ORDER BY txn_date, ord, doc_no
`

type PayableStatementParams struct {
	CompanyID int64
	PartnerID int64
	Currency  string
	FromDate  time.Time
	ToDate    time.Time
}

type PayableStatementRow struct {
	TxnDate time.Time
	Kind    string
	DocNo   string
	Delta   decimal.Decimal
	RefID   int64
}

func (q *Queries) PayableStatement(ctx context.Context, arg PayableStatementParams) ([]PayableStatementRow, error) {
	rows, err := q.db.Query(ctx, payableStatement,
		arg.CompanyID,
		arg.PartnerID,
		arg.Currency,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PayableStatementRow{}
	for rows.Next() {
		var i PayableStatementRow
		if err := rows.Scan(
			&i.TxnDate,
			&i.Kind,
			&i.DocNo,
			&i.Delta,
			&i.RefID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const payableStatementOpening = `-- name: PayableStatementOpening :one
SELECT (COALESCE((SELECT SUM(p.amount) FROM accounts_payable p
                  WHERE p.company_id = $1 AND p.supplier_id = $2 AND p.currency = $3::text
                    AND p.doc_date < $4::date), 0)
      - COALESCE((SELECT SUM(l.amount) FROM settlement_lines l JOIN settlements s ON s.id = l.settlement_id
                  WHERE s.company_id = $1 AND s.supplier_id = $2 AND s.currency = $3::text
                    AND s.status = 'posted' AND s.doc_date < $4::date), 0))::numeric AS opening
`

type PayableStatementOpeningParams struct {
	CompanyID int64
	PartnerID int64
	Currency  string
	FromDate  time.Time
}

func (q *Queries) PayableStatementOpening(ctx context.Context, arg PayableStatementOpeningParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, payableStatementOpening,
		arg.CompanyID,
		arg.PartnerID,
		arg.Currency,
		arg.FromDate,
	)
	var opening decimal.Decimal
	err := row.Scan(&opening)
	return opening, err
}

const receivableAging = `-- name: ReceivableAging :many

WITH items AS (
    SELECT r.customer_id AS partner_id, ($3::date - r.due_date)::int AS days,
           (CASE WHEN r.amount = 0 THEN 0 ELSE r.base_amount * (r.amount - r.paid_amount) / r.amount END)::numeric AS bal
    FROM accounts_receivable r
    WHERE r.company_id = $4 AND r.amount <> r.paid_amount AND r.doc_date <= $3::date
)
SELECT c.id AS partner_id, c.code AS partner_code, c.name AS partner_name,
       COALESCE(SUM(i.bal) FILTER (WHERE i.days <= 0), 0)::numeric AS not_due,
       COALESCE(SUM(i.bal) FILTER (WHERE i.days BETWEEN 1 AND 30), 0)::numeric AS d1_30,
       COALESCE(SUM(i.bal) FILTER (WHERE i.days BETWEEN 31 AND 60), 0)::numeric AS d31_60,
       COALESCE(SUM(i.bal) FILTER (WHERE i.days BETWEEN 61 AND 90), 0)::numeric AS d61_90,
       COALESCE(SUM(i.bal) FILTER (WHERE i.days > 90), 0)::numeric AS d90_plus,
       COALESCE(SUM(i.bal), 0)::numeric AS total
FROM items i
JOIN customers c ON c.id = i.partner_id
LEFT JOIN users su ON su.id = c.sales_user_id
WHERE ($1::bigint IS NULL OR c.sales_user_id = $1)
  AND ($2::bigint IS NULL OR su.department_id = $2)
GROUP BY c.id
ORDER BY c.code
`

type ReceivableAgingParams struct {
	ScopeUserID *int64
	ScopeDeptID *int64
	AsOf        time.Time
	CompanyID   int64
}

type ReceivableAgingRow struct {
	PartnerID   int64
	PartnerCode string
	PartnerName string
	NotDue      decimal.Decimal
	D130        decimal.Decimal
	D3160       decimal.Decimal
	D6190       decimal.Decimal
	D90Plus     decimal.Decimal
	Total       decimal.Decimal
}

// ======== 帳齡分析 ========
// 以目前未沖餘額(本位幣,依原幣餘額比例換算)按到期日分組;as_of 之後的單據不計
func (q *Queries) ReceivableAging(ctx context.Context, arg ReceivableAgingParams) ([]ReceivableAgingRow, error) {
	rows, err := q.db.Query(ctx, receivableAging,
		arg.ScopeUserID,
		arg.ScopeDeptID,
		arg.AsOf,
		arg.CompanyID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReceivableAgingRow{}
	for rows.Next() {
		var i ReceivableAgingRow
		if err := rows.Scan(
			&i.PartnerID,
			&i.PartnerCode,
			&i.PartnerName,
			&i.NotDue,
			&i.D130,
			&i.D3160,
			&i.D6190,
			&i.D90Plus,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const receivableSettlementNo = `-- name: ReceivableSettlementNo :one
SELECT s.doc_no FROM settlement_lines l JOIN settlements s ON s.id = l.settlement_id
WHERE l.receivable_id = $1 AND s.status <> 'voided' LIMIT 1
`

// 應收是否已被未作廢的收款單引用(來源單據反過帳前檢查)
func (q *Queries) ReceivableSettlementNo(ctx context.Context, receivableID *int64) (string, error) {
	row := q.db.QueryRow(ctx, receivableSettlementNo, receivableID)
	var doc_no string
	err := row.Scan(&doc_no)
	return doc_no, err
}

const receivableStatement = `-- name: ReceivableStatement :many
SELECT txn_date, kind, doc_no, delta, ref_id FROM (
    SELECT r.doc_date AS txn_date, r.source_type::text AS kind, r.source_no AS doc_no, r.amount AS delta,
           r.source_id AS ref_id, 0 AS ord
    FROM accounts_receivable r
    WHERE r.company_id = $1 AND r.customer_id = $2 AND r.currency = $3::text
      AND r.doc_date BETWEEN $4::date AND $5::date
    UNION ALL
    SELECT s.doc_date, 'receipt'::text, s.doc_no, -SUM(l.amount), s.id, 1
    FROM settlements s JOIN settlement_lines l ON l.settlement_id = s.id
    WHERE s.company_id = $1 AND s.customer_id = $2 AND s.currency = $3::text
      AND s.status = 'posted' AND s.doc_date BETWEEN $4::date AND $5::date
    GROUP BY s.id
) t ORDER BY txn_date, ord, doc_no
`

type ReceivableStatementParams struct {
	CompanyID int64
	PartnerID int64
	Currency  string
	FromDate  time.Time
	ToDate    time.Time
}

type ReceivableStatementRow struct {
	TxnDate time.Time
	Kind    string
	DocNo   string
	Delta   decimal.Decimal
	RefID   int64
}

func (q *Queries) ReceivableStatement(ctx context.Context, arg ReceivableStatementParams) ([]ReceivableStatementRow, error) {
	rows, err := q.db.Query(ctx, receivableStatement,
		arg.CompanyID,
		arg.PartnerID,
		arg.Currency,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReceivableStatementRow{}
	for rows.Next() {
		var i ReceivableStatementRow
		if err := rows.Scan(
			&i.TxnDate,
			&i.Kind,
			&i.DocNo,
			&i.Delta,
			&i.RefID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const receivableStatementOpening = `-- name: ReceivableStatementOpening :one

SELECT (COALESCE((SELECT SUM(r.amount) FROM accounts_receivable r
                  WHERE r.company_id = $1 AND r.customer_id = $2 AND r.currency = $3::text
                    AND r.doc_date < $4::date), 0)
      - COALESCE((SELECT SUM(l.amount) FROM settlement_lines l JOIN settlements s ON s.id = l.settlement_id
                  WHERE s.company_id = $1 AND s.customer_id = $2 AND s.currency = $3::text
                    AND s.status = 'posted' AND s.doc_date < $4::date), 0))::numeric AS opening
`

type ReceivableStatementOpeningParams struct {
	CompanyID int64
	PartnerID int64
	Currency  string
	FromDate  time.Time
}

// ======== 對帳單 ========
// 以單一幣別計算;應收 / 應付的異動 = 帳款金額(退回 / 退出為負),已過帳的收付款為反向
func (q *Queries) ReceivableStatementOpening(ctx context.Context, arg ReceivableStatementOpeningParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, receivableStatementOpening,
		arg.CompanyID,
		arg.PartnerID,
		arg.Currency,
		arg.FromDate,
	)
	var opening decimal.Decimal
	err := row.Scan(&opening)
	return opening, err
}

const setSettlementStatus = `-- name: SetSettlementStatus :one
UPDATE settlements
SET status       = $1,
    submitted_by = CASE WHEN $2::text = 'submit' THEN $3::bigint ELSE submitted_by END,
    submitted_at = CASE WHEN $2::text = 'submit' THEN now() ELSE submitted_at END,
    approved_by  = CASE WHEN $2::text = 'approve' THEN $3::bigint
                        WHEN $2::text IN ('reject', 'unapprove') THEN NULL ELSE approved_by END,
    approved_at  = CASE WHEN $2::text = 'approve' THEN now()
                        WHEN $2::text IN ('reject', 'unapprove') THEN NULL ELSE approved_at END,
    posted_by    = CASE WHEN $2::text = 'post' THEN $3::bigint
                        WHEN $2::text = 'unpost' THEN NULL ELSE posted_by END,
    posted_at    = CASE WHEN $2::text = 'post' THEN now()
                        WHEN $2::text = 'unpost' THEN NULL ELSE posted_at END,
    version      = version + 1,
    updated_by   = $3::bigint
WHERE id = $4 AND company_id = $5 AND version = $6
RETURNING id, company_id, side, doc_no, doc_date, customer_id, supplier_id, sales_user_id, currency, method, reference, amount, status, note, submitted_by, submitted_at, approved_by, approved_at, posted_by, posted_at, created_by, updated_by, version, created_at, updated_at
`

type SetSettlementStatusParams struct {
	Status    string
	Action    string
	ActorID   int64
	ID        int64
	CompanyID int64
	Version   int32
}

func (q *Queries) SetSettlementStatus(ctx context.Context, arg SetSettlementStatusParams) (Settlement, error) {
	row := q.db.QueryRow(ctx, setSettlementStatus,
		arg.Status,
		arg.Action,
		arg.ActorID,
		arg.ID,
		arg.CompanyID,
		arg.Version,
	)
	var i Settlement
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Side,
		&i.DocNo,
		&i.DocDate,
		&i.CustomerID,
		&i.SupplierID,
		&i.SalesUserID,
		&i.Currency,
		&i.Method,
		&i.Reference,
		&i.Amount,
		&i.Status,
		&i.Note,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.PostedBy,
		&i.PostedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSettlementHeader = `-- name: UpdateSettlementHeader :one
UPDATE settlements
SET doc_date = $1, customer_id = $2, supplier_id = $3,
    sales_user_id = $4, currency = $5, method = $6, reference = $7,
    amount = $8, note = $9, version = version + 1, updated_by = $10
WHERE id = $11 AND company_id = $12 AND version = $13 AND status = 'draft'
RETURNING id, company_id, side, doc_no, doc_date, customer_id, supplier_id, sales_user_id, currency, method, reference, amount, status, note, submitted_by, submitted_at, approved_by, approved_at, posted_by, posted_at, created_by, updated_by, version, created_at, updated_at
`

type UpdateSettlementHeaderParams struct {
	DocDate     time.Time
	CustomerID  *int64
	SupplierID  *int64
	SalesUserID *int64
	Currency    string
	Method      string
	Reference   string
	Amount      decimal.Decimal
	Note        string
	UpdatedBy   *int64
	ID          int64
	CompanyID   int64
	Version     int32
}

func (q *Queries) UpdateSettlementHeader(ctx context.Context, arg UpdateSettlementHeaderParams) (Settlement, error) {
	row := q.db.QueryRow(ctx, updateSettlementHeader,
		arg.DocDate,
		arg.CustomerID,
		arg.SupplierID,
		arg.SalesUserID,
		arg.Currency,
		arg.Method,
		arg.Reference,
		arg.Amount,
		arg.Note,
		arg.UpdatedBy,
		arg.ID,
		arg.CompanyID,
		arg.Version,
	)
	var i Settlement
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Side,
		&i.DocNo,
		&i.DocDate,
		&i.CustomerID,
		&i.SupplierID,
		&i.SalesUserID,
		&i.Currency,
		&i.Method,
		&i.Reference,
		&i.Amount,
		&i.Status,
		&i.Note,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.PostedBy,
		&i.PostedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
