// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stock_documents.sql

package db

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const addStockDocumentLine = `-- name: AddStockDocumentLine :exec
INSERT INTO stock_document_lines (document_id, line_no, item_id, unit_id, qty, factor, base_qty, system_qty, note,
                                  lot_no, expiry_date, bin_code, to_bin_code)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11, $12, $13)
`

type AddStockDocumentLineParams struct {
	DocumentID int64
	LineNo     int32
	ItemID     int64
	UnitID     int64
	Qty        *decimal.Decimal
	Factor     decimal.Decimal
	BaseQty    *decimal.Decimal
	SystemQty  *decimal.Decimal
	Note       string
	LotNo      string
	ExpiryDate *time.Time
	BinCode    string
	ToBinCode  string
}

func (q *Queries) AddStockDocumentLine(ctx context.Context, arg AddStockDocumentLineParams) error {
	_, err := q.db.Exec(ctx, addStockDocumentLine,
		arg.DocumentID,
		arg.LineNo,
		arg.ItemID,
		arg.UnitID,
		arg.Qty,
		arg.Factor,
		arg.BaseQty,
		arg.SystemQty,
		arg.Note,
		arg.LotNo,
		arg.ExpiryDate,
		arg.BinCode,
		arg.ToBinCode,
	)
	return err
}

const countLotSnapshot = `-- name: CountLotSnapshot :many
SELECT b.item_id, l.lot_no, l.expiry_date, b.qty
FROM inventory_lot_balances b JOIN item_lots l ON l.id = b.lot_id
WHERE b.company_id = $1 AND b.warehouse_id = $2 AND b.item_id = ANY($3::bigint[]) AND b.qty > 0
ORDER BY b.item_id, l.expiry_date NULLS LAST, l.id
`

type CountLotSnapshotParams struct {
	CompanyID   int64
	WarehouseID int64
	ItemIds     []int64
}

type CountLotSnapshotRow struct {
	ItemID     int64
	LotNo      string
	ExpiryDate *time.Time
	Qty        decimal.Decimal
}

// 盤點建立時批號管理料品的帳面數量快照:依批號逐筆(有庫存的批號)
func (q *Queries) CountLotSnapshot(ctx context.Context, arg CountLotSnapshotParams) ([]CountLotSnapshotRow, error) {
	rows, err := q.db.Query(ctx, countLotSnapshot, arg.CompanyID, arg.WarehouseID, arg.ItemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountLotSnapshotRow{}
	for rows.Next() {
		var i CountLotSnapshotRow
		if err := rows.Scan(
			&i.ItemID,
			&i.LotNo,
			&i.ExpiryDate,
			&i.Qty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSnapshot = `-- name: CountSnapshot :many
WITH RECURSIVE cats (cat_id) AS (
    SELECT item_categories.id FROM item_categories WHERE item_categories.id = $3::bigint
    UNION ALL
    SELECT item_categories.id FROM item_categories, cats WHERE item_categories.parent_id = cats.cat_id
)
SELECT b.item_id, i.base_unit_id, b.qty, i.lot_control
FROM inventory_balances b
JOIN items i ON i.id = b.item_id
WHERE b.company_id = $1 AND b.warehouse_id = $2 AND i.item_type = 'goods'
  AND ($3::bigint IS NULL OR i.category_id IN (SELECT cat_id FROM cats))
ORDER BY i.code
`

type CountSnapshotParams struct {
	CompanyID   int64
	WarehouseID int64
	CategoryID  *int64
}

type CountSnapshotRow struct {
	ItemID     int64
	BaseUnitID int64
	Qty        decimal.Decimal
	LotControl string
}

// 盤點建立時的帳面數量快照:該倉庫有現有量紀錄的商品(可限分類,含下層)
func (q *Queries) CountSnapshot(ctx context.Context, arg CountSnapshotParams) ([]CountSnapshotRow, error) {
	rows, err := q.db.Query(ctx, countSnapshot, arg.CompanyID, arg.WarehouseID, arg.CategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountSnapshotRow{}
	for rows.Next() {
		var i CountSnapshotRow
		if err := rows.Scan(
			&i.ItemID,
			&i.BaseUnitID,
			&i.Qty,
			&i.LotControl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countStockDocuments = `-- name: CountStockDocuments :one
SELECT count(*) FROM stock_documents d
WHERE d.company_id = $1
  AND ($2::text IS NULL OR d.doc_type = $2)
  AND ($3::text IS NULL OR d.status = $3)
  AND ($4::bigint IS NULL
       OR d.warehouse_id = $4 OR d.to_warehouse_id = $4)
  AND ($5::text IS NULL OR d.doc_no ILIKE '%' || $5 || '%')
  AND ($6::date IS NULL OR d.doc_date >= $6)
  AND ($7::date IS NULL OR d.doc_date <= $7)
`

type CountStockDocumentsParams struct {
	CompanyID   int64
	DocType     *string
	Status      *string
	WarehouseID *int64
	Keyword     *string
	FromDate    *time.Time
	ToDate      *time.Time
}

func (q *Queries) CountStockDocuments(ctx context.Context, arg CountStockDocumentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStockDocuments,
		arg.CompanyID,
		arg.DocType,
		arg.Status,
		arg.WarehouseID,
		arg.Keyword,
		arg.FromDate,
		arg.ToDate,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStockDocument = `-- name: CreateStockDocument :one
INSERT INTO stock_documents (company_id, doc_type, doc_no, doc_date, warehouse_id, to_warehouse_id, category_id,
                             note, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, $9)
RETURNING id, company_id, doc_type, doc_no, doc_date, warehouse_id, to_warehouse_id, category_id, status, note, submitted_by, submitted_at, approved_by, approved_at, posted_by, posted_at, created_by, updated_by, version, created_at, updated_at
`

type CreateStockDocumentParams struct {
	CompanyID     int64
	DocType       string
	DocNo         string
	DocDate       time.Time
	WarehouseID   int64
	ToWarehouseID *int64
	CategoryID    *int64
	Note          string
	CreatedBy     *int64
}

func (q *Queries) CreateStockDocument(ctx context.Context, arg CreateStockDocumentParams) (StockDocument, error) {
	row := q.db.QueryRow(ctx, createStockDocument,
		arg.CompanyID,
		arg.DocType,
		arg.DocNo,
		arg.DocDate,
		arg.WarehouseID,
		arg.ToWarehouseID,
		arg.CategoryID,
		arg.Note,
		arg.CreatedBy,
	)
	var i StockDocument
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocType,
		&i.DocNo,
		&i.DocDate,
		&i.WarehouseID,
		&i.ToWarehouseID,
		&i.CategoryID,
		&i.Status,
		&i.Note,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.PostedBy,
		&i.PostedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStockDocumentLines = `-- name: DeleteStockDocumentLines :exec
DELETE FROM stock_document_lines WHERE document_id = $1
`

func (q *Queries) DeleteStockDocumentLines(ctx context.Context, documentID int64) error {
	_, err := q.db.Exec(ctx, deleteStockDocumentLines, documentID)
	return err
}

const getBalanceQty = `-- name: GetBalanceQty :one
SELECT COALESCE((SELECT qty FROM inventory_balances WHERE item_id = $1 AND warehouse_id = $2), 0)::numeric
`

type GetBalanceQtyParams struct {
	ItemID      int64
	WarehouseID int64
}

func (q *Queries) GetBalanceQty(ctx context.Context, arg GetBalanceQtyParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, getBalanceQty, arg.ItemID, arg.WarehouseID)
	var column_1 decimal.Decimal
	err := row.Scan(&column_1)
	return column_1, err
}

const getLotBalanceQtyByNo = `-- name: GetLotBalanceQtyByNo :one
SELECT COALESCE((SELECT b.qty FROM inventory_lot_balances b JOIN item_lots l ON l.id = b.lot_id
                 WHERE l.company_id = $1 AND l.item_id = $2 AND l.lot_no = $3
                   AND b.warehouse_id = $4), 0)::numeric
`

type GetLotBalanceQtyByNoParams struct {
	CompanyID   int64
	ItemID      int64
	LotNo       string
	WarehouseID int64
}

// 某批號在某倉庫的現有量(批號不存在為 0)
func (q *Queries) GetLotBalanceQtyByNo(ctx context.Context, arg GetLotBalanceQtyByNoParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, getLotBalanceQtyByNo,
		arg.CompanyID,
		arg.ItemID,
		arg.LotNo,
		arg.WarehouseID,
	)
	var column_1 decimal.Decimal
	err := row.Scan(&column_1)
	return column_1, err
}

const getStockDocument = `-- name: GetStockDocument :one
SELECT d.id, d.company_id, d.doc_type, d.doc_no, d.doc_date, d.warehouse_id, d.to_warehouse_id, d.category_id, d.status, d.note, d.submitted_by, d.submitted_at, d.approved_by, d.approved_at, d.posted_by, d.posted_at, d.created_by, d.updated_by, d.version, d.created_at, d.updated_at, w.name AS warehouse_name, tw.name AS to_warehouse_name, c.name AS category_name,
       cu.name AS created_by_name, su.name AS submitted_by_name, au.name AS approved_by_name,
       pu.name AS posted_by_name
FROM stock_documents d
JOIN warehouses w ON w.id = d.warehouse_id
LEFT JOIN warehouses tw ON tw.id = d.to_warehouse_id
LEFT JOIN item_categories c ON c.id = d.category_id
LEFT JOIN users cu ON cu.id = d.created_by
LEFT JOIN users su ON su.id = d.submitted_by
LEFT JOIN users au ON au.id = d.approved_by
LEFT JOIN users pu ON pu.id = d.posted_by
WHERE d.id = $1 AND d.company_id = $2
`

type GetStockDocumentParams struct {
	ID        int64
	CompanyID int64
}

type GetStockDocumentRow struct {
	ID              int64
	CompanyID       int64
	DocType         string
	DocNo           string
	DocDate         time.Time
	WarehouseID     int64
	ToWarehouseID   *int64
	CategoryID      *int64
	Status          string
	Note            string
	SubmittedBy     *int64
	SubmittedAt     *time.Time
	ApprovedBy      *int64
	ApprovedAt      *time.Time
	PostedBy        *int64
	PostedAt        *time.Time
	CreatedBy       *int64
	UpdatedBy       *int64
	Version         int32
	CreatedAt       time.Time
	UpdatedAt       time.Time
	WarehouseName   string
	ToWarehouseName *string
	CategoryName    *string
	CreatedByName   *string
	SubmittedByName *string
	ApprovedByName  *string
	PostedByName    *string
}

func (q *Queries) GetStockDocument(ctx context.Context, arg GetStockDocumentParams) (GetStockDocumentRow, error) {
	row := q.db.QueryRow(ctx, getStockDocument, arg.ID, arg.CompanyID)
	var i GetStockDocumentRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocType,
		&i.DocNo,
		&i.DocDate,
		&i.WarehouseID,
		&i.ToWarehouseID,
		&i.CategoryID,
		&i.Status,
		&i.Note,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.PostedBy,
		&i.PostedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WarehouseName,
		&i.ToWarehouseName,
		&i.CategoryName,
		&i.CreatedByName,
		&i.SubmittedByName,
		&i.ApprovedByName,
		&i.PostedByName,
	)
	return i, err
}

const listStockDocumentLines = `-- name: ListStockDocumentLines :many
SELECT l.id, l.document_id, l.line_no, l.item_id, l.unit_id, l.qty, l.factor, l.base_qty, l.system_qty, l.note, l.lot_no, l.expiry_date, l.bin_code, l.to_bin_code, i.code AS item_code, i.name AS item_name, i.spec AS item_spec, i.lot_control AS item_lot_control,
       u.name AS unit_name, bu.name AS base_unit_name
FROM stock_document_lines l
JOIN items i ON i.id = l.item_id
JOIN units u ON u.id = l.unit_id
JOIN units bu ON bu.id = i.base_unit_id
WHERE l.document_id = $1
ORDER BY l.line_no
`

type ListStockDocumentLinesRow struct {
	ID             int64
	DocumentID     int64
	LineNo         int32
	ItemID         int64
	UnitID         int64
	Qty            *decimal.Decimal
	Factor         decimal.Decimal
	BaseQty        *decimal.Decimal
	SystemQty      *decimal.Decimal
	Note           string
	LotNo          string
	ExpiryDate     *time.Time
	BinCode        string
	ToBinCode      string
	ItemCode       string
	ItemName       string
	ItemSpec       string
	ItemLotControl string
	UnitName       string
	BaseUnitName   string
}

func (q *Queries) ListStockDocumentLines(ctx context.Context, documentID int64) ([]ListStockDocumentLinesRow, error) {
	rows, err := q.db.Query(ctx, listStockDocumentLines, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStockDocumentLinesRow{}
	for rows.Next() {
		var i ListStockDocumentLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.LineNo,
			&i.ItemID,
			&i.UnitID,
			&i.Qty,
			&i.Factor,
			&i.BaseQty,
			&i.SystemQty,
			&i.Note,
			&i.LotNo,
			&i.ExpiryDate,
			&i.BinCode,
			&i.ToBinCode,
			&i.ItemCode,
			&i.ItemName,
			&i.ItemSpec,
			&i.ItemLotControl,
			&i.UnitName,
			&i.BaseUnitName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockDocuments = `-- name: ListStockDocuments :many
SELECT d.id, d.doc_type, d.doc_no, d.doc_date, d.warehouse_id, d.to_warehouse_id, d.status, d.note,
       d.version, d.updated_at, w.name AS warehouse_name, tw.name AS to_warehouse_name,
       cu.name AS created_by_name,
       (SELECT count(*) FROM stock_document_lines l WHERE l.document_id = d.id) AS line_count
FROM stock_documents d
JOIN warehouses w ON w.id = d.warehouse_id
LEFT JOIN warehouses tw ON tw.id = d.to_warehouse_id
LEFT JOIN users cu ON cu.id = d.created_by
WHERE d.company_id = $1
  AND ($2::text IS NULL OR d.doc_type = $2)
  AND ($3::text IS NULL OR d.status = $3)
  AND ($4::bigint IS NULL
       OR d.warehouse_id = $4 OR d.to_warehouse_id = $4)
  AND ($5::text IS NULL OR d.doc_no ILIKE '%' || $5 || '%')
  AND ($6::date IS NULL OR d.doc_date >= $6)
  AND ($7::date IS NULL OR d.doc_date <= $7)
ORDER BY d.doc_date DESC, d.id DESC
LIMIT $9 OFFSET $8
`

type ListStockDocumentsParams struct {
	CompanyID   int64
	DocType     *string
	Status      *string
	WarehouseID *int64
	Keyword     *string
	FromDate    *time.Time
	ToDate      *time.Time
	Off         int32
	Lim         int32
}

type ListStockDocumentsRow struct {
	ID              int64
	DocType         string
	DocNo           string
	DocDate         time.Time
	WarehouseID     int64
	ToWarehouseID   *int64
	Status          string
	Note            string
	Version         int32
	UpdatedAt       time.Time
	WarehouseName   string
	ToWarehouseName *string
	CreatedByName   *string
	LineCount       int64
}

func (q *Queries) ListStockDocuments(ctx context.Context, arg ListStockDocumentsParams) ([]ListStockDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listStockDocuments,
		arg.CompanyID,
		arg.DocType,
		arg.Status,
		arg.WarehouseID,
		arg.Keyword,
		arg.FromDate,
		arg.ToDate,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStockDocumentsRow{}
	for rows.Next() {
		var i ListStockDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.DocType,
			&i.DocNo,
			&i.DocDate,
			&i.WarehouseID,
			&i.ToWarehouseID,
			&i.Status,
			&i.Note,
			&i.Version,
			&i.UpdatedAt,
			&i.WarehouseName,
			&i.ToWarehouseName,
			&i.CreatedByName,
			&i.LineCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockStockDocument = `-- name: LockStockDocument :one
SELECT id, company_id, doc_type, doc_no, doc_date, warehouse_id, to_warehouse_id, category_id, status, note, submitted_by, submitted_at, approved_by, approved_at, posted_by, posted_at, created_by, updated_by, version, created_at, updated_at FROM stock_documents WHERE id = $1 AND company_id = $2 FOR UPDATE
`

type LockStockDocumentParams struct {
	ID        int64
	CompanyID int64
}

func (q *Queries) LockStockDocument(ctx context.Context, arg LockStockDocumentParams) (StockDocument, error) {
	row := q.db.QueryRow(ctx, lockStockDocument, arg.ID, arg.CompanyID)
	var i StockDocument
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocType,
		&i.DocNo,
		&i.DocDate,
		&i.WarehouseID,
		&i.ToWarehouseID,
		&i.CategoryID,
		&i.Status,
		&i.Note,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.PostedBy,
		&i.PostedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setStockDocumentStatus = `-- name: SetStockDocumentStatus :one
UPDATE stock_documents
SET status       = $1,
    submitted_by = CASE WHEN $2::text = 'submit' THEN $3::bigint ELSE submitted_by END,
    submitted_at = CASE WHEN $2::text = 'submit' THEN now() ELSE submitted_at END,
    approved_by  = CASE WHEN $2::text = 'approve' THEN $3::bigint
                        WHEN $2::text IN ('reject', 'unapprove') THEN NULL ELSE approved_by END,
    approved_at  = CASE WHEN $2::text = 'approve' THEN now()
                        WHEN $2::text IN ('reject', 'unapprove') THEN NULL ELSE approved_at END,
    posted_by    = CASE WHEN $2::text = 'post' THEN $3::bigint
                        WHEN $2::text = 'unpost' THEN NULL ELSE posted_by END,
    posted_at    = CASE WHEN $2::text = 'post' THEN now()
                        WHEN $2::text = 'unpost' THEN NULL ELSE posted_at END,
    version      = version + 1,
    updated_by   = $3::bigint
WHERE id = $4 AND company_id = $5 AND version = $6
RETURNING id, company_id, doc_type, doc_no, doc_date, warehouse_id, to_warehouse_id, category_id, status, note, submitted_by, submitted_at, approved_by, approved_at, posted_by, posted_at, created_by, updated_by, version, created_at, updated_at
`

type SetStockDocumentStatusParams struct {
	Status    string
	Action    string
	ActorID   int64
	ID        int64
	CompanyID int64
	Version   int32
}

func (q *Queries) SetStockDocumentStatus(ctx context.Context, arg SetStockDocumentStatusParams) (StockDocument, error) {
	row := q.db.QueryRow(ctx, setStockDocumentStatus,
		arg.Status,
		arg.Action,
		arg.ActorID,
		arg.ID,
		arg.CompanyID,
		arg.Version,
	)
	var i StockDocument
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocType,
		&i.DocNo,
		&i.DocDate,
		&i.WarehouseID,
		&i.ToWarehouseID,
		&i.CategoryID,
		&i.Status,
		&i.Note,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.PostedBy,
		&i.PostedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStockDocumentHeader = `-- name: UpdateStockDocumentHeader :one
UPDATE stock_documents
SET doc_date = $1, to_warehouse_id = $2, note = $3,
    version = version + 1, updated_by = $4
WHERE id = $5 AND company_id = $6 AND version = $7 AND status = 'draft'
RETURNING id, company_id, doc_type, doc_no, doc_date, warehouse_id, to_warehouse_id, category_id, status, note, submitted_by, submitted_at, approved_by, approved_at, posted_by, posted_at, created_by, updated_by, version, created_at, updated_at
`

type UpdateStockDocumentHeaderParams struct {
	DocDate       time.Time
	ToWarehouseID *int64
	Note          string
	UpdatedBy     *int64
	ID            int64
	CompanyID     int64
	Version       int32
}

// 只有草稿可修改;倉庫在建立後不可變更(盤點快照、調撥方向皆依此)
func (q *Queries) UpdateStockDocumentHeader(ctx context.Context, arg UpdateStockDocumentHeaderParams) (StockDocument, error) {
	row := q.db.QueryRow(ctx, updateStockDocumentHeader,
		arg.DocDate,
		arg.ToWarehouseID,
		arg.Note,
		arg.UpdatedBy,
		arg.ID,
		arg.CompanyID,
		arg.Version,
	)
	var i StockDocument
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DocType,
		&i.DocNo,
		&i.DocDate,
		&i.WarehouseID,
		&i.ToWarehouseID,
		&i.CategoryID,
		&i.Status,
		&i.Note,
		&i.SubmittedBy,
		&i.SubmittedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.PostedBy,
		&i.PostedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
