// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: two_factor.sql

package db

import (
	"context"
)

const advanceTOTPStep = `-- name: AdvanceTOTPStep :execrows
UPDATE users SET totp_last_step = $1 WHERE id = $2 AND totp_last_step < $1
`

type AdvanceTOTPStepParams struct {
	Step int64
	ID   int64
}

// 只有時間步比上次大才接受(同一個驗證碼不可重複使用);回傳 0 表示重放
func (q *Queries) AdvanceTOTPStep(ctx context.Context, arg AdvanceTOTPStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceTOTPStep, arg.Step, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bumpTokenVersion = `-- name: BumpTokenVersion :exec
UPDATE users SET token_version = token_version + 1 WHERE id = $1
`

func (q *Queries) BumpTokenVersion(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, bumpTokenVersion, id)
	return err
}

const companyRequires2FA = `-- name: CompanyRequires2FA :one
SELECT require_2fa FROM companies WHERE id = $1
`

func (q *Queries) CompanyRequires2FA(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, companyRequires2FA, id)
	var require_2fa bool
	err := row.Scan(&require_2fa)
	return require_2fa, err
}

const countUnusedRecoveryCodes = `-- name: CountUnusedRecoveryCodes :one
SELECT count(*) FROM user_recovery_codes WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) CountUnusedRecoveryCodes(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUnusedRecoveryCodes, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRecoveryCodes = `-- name: DeleteRecoveryCodes :exec
DELETE FROM user_recovery_codes WHERE user_id = $1
`

func (q *Queries) DeleteRecoveryCodes(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteRecoveryCodes, userID)
	return err
}

const disableTOTP = `-- name: DisableTOTP :exec
UPDATE users SET totp_secret_enc = NULL, totp_enabled = FALSE, totp_enabled_at = NULL, totp_last_step = 0 WHERE id = $1
`

func (q *Queries) DisableTOTP(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, disableTOTP, id)
	return err
}

const enableTOTP = `-- name: EnableTOTP :exec
UPDATE users SET totp_enabled = TRUE, totp_enabled_at = now(), totp_last_step = $1 WHERE id = $2
`

type EnableTOTPParams struct {
	LastStep int64
	ID       int64
}

func (q *Queries) EnableTOTP(ctx context.Context, arg EnableTOTPParams) error {
	_, err := q.db.Exec(ctx, enableTOTP, arg.LastStep, arg.ID)
	return err
}

const insertRecoveryCode = `-- name: InsertRecoveryCode :exec
INSERT INTO user_recovery_codes (user_id, code_hash) VALUES ($1, $2)
`

type InsertRecoveryCodeParams struct {
	UserID   int64
	CodeHash []byte
}

func (q *Queries) InsertRecoveryCode(ctx context.Context, arg InsertRecoveryCodeParams) error {
	_, err := q.db.Exec(ctx, insertRecoveryCode, arg.UserID, arg.CodeHash)
	return err
}

const setCompanyRequire2FA = `-- name: SetCompanyRequire2FA :exec
UPDATE companies SET require_2fa = $1 WHERE id = $2
`

type SetCompanyRequire2FAParams struct {
	Require bool
	ID      int64
}

func (q *Queries) SetCompanyRequire2FA(ctx context.Context, arg SetCompanyRequire2FAParams) error {
	_, err := q.db.Exec(ctx, setCompanyRequire2FA, arg.Require, arg.ID)
	return err
}

const setTOTPPending = `-- name: SetTOTPPending :exec

UPDATE users SET totp_secret_enc = $1, totp_enabled = FALSE, totp_enabled_at = NULL, totp_last_step = 0
WHERE id = $2
`

type SetTOTPPendingParams struct {
	SecretEnc []byte
	ID        int64
}

// ======== 雙因素驗證(D66) ========
// 產生新的待驗證密鑰(覆蓋舊的暫存值;已啟用者不可呼叫,程式先檢查)
func (q *Queries) SetTOTPPending(ctx context.Context, arg SetTOTPPendingParams) error {
	_, err := q.db.Exec(ctx, setTOTPPending, arg.SecretEnc, arg.ID)
	return err
}

const useRecoveryCode = `-- name: UseRecoveryCode :execrows
UPDATE user_recovery_codes SET used_at = now() WHERE user_id = $1 AND code_hash = $2 AND used_at IS NULL
`

type UseRecoveryCodeParams struct {
	UserID   int64
	CodeHash []byte
}

func (q *Queries) UseRecoveryCode(ctx context.Context, arg UseRecoveryCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, useRecoveryCode, arg.UserID, arg.CodeHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
