// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"time"
)

const addUserRoles = `-- name: AddUserRoles :exec
INSERT INTO user_roles (user_id, role_id)
SELECT $1, unnest($2::bigint[])
`

type AddUserRolesParams struct {
	UserID  int64
	RoleIds []int64
}

func (q *Queries) AddUserRoles(ctx context.Context, arg AddUserRolesParams) error {
	_, err := q.db.Exec(ctx, addUserRoles, arg.UserID, arg.RoleIds)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*)
FROM users u
WHERE u.company_id = $1
  AND ($2::text IS NULL
       OR u.username ILIKE '%' || $2 || '%'
       OR u.name ILIKE '%' || $2 || '%')
  AND ($3::bigint IS NULL OR u.department_id = $3)
  AND ($4::boolean IS NULL OR u.is_active = $4)
`

type CountUsersParams struct {
	CompanyID    int64
	Keyword      *string
	DepartmentID *int64
	IsActive     *bool
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers,
		arg.CompanyID,
		arg.Keyword,
		arg.DepartmentID,
		arg.IsActive,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (company_id, department_id, username, name, email, password_hash,
                   is_superadmin, must_change_password, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, $9)
RETURNING id, company_id, department_id, username, name, email, password_hash, is_superadmin, is_active, must_change_password, failed_login_count, locked_until, last_login_at, password_changed_at, token_version, version, created_by, updated_by, created_at, updated_at
`

type CreateUserParams struct {
	CompanyID          int64
	DepartmentID       *int64
	Username           string
	Name               string
	Email              *string
	PasswordHash       string
	IsSuperadmin       bool
	MustChangePassword bool
	CreatedBy          *int64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.CompanyID,
		arg.DepartmentID,
		arg.Username,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.IsSuperadmin,
		arg.MustChangePassword,
		arg.CreatedBy,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DepartmentID,
		&i.Username,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsSuperadmin,
		&i.IsActive,
		&i.MustChangePassword,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.PasswordChangedAt,
		&i.TokenVersion,
		&i.Version,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserRoles = `-- name: DeleteUserRoles :exec
DELETE FROM user_roles WHERE user_id = $1
`

func (q *Queries) DeleteUserRoles(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserRoles, userID)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, company_id, department_id, username, name, email, password_hash, is_superadmin, is_active, must_change_password, failed_login_count, locked_until, last_login_at, password_changed_at, token_version, version, created_by, updated_by, created_at, updated_at FROM users WHERE id = $1 AND company_id = $2
`

type GetUserParams struct {
	ID        int64
	CompanyID int64
}

func (q *Queries) GetUser(ctx context.Context, arg GetUserParams) (User, error) {
	row := q.db.QueryRow(ctx, getUser, arg.ID, arg.CompanyID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DepartmentID,
		&i.Username,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsSuperadmin,
		&i.IsActive,
		&i.MustChangePassword,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.PasswordChangedAt,
		&i.TokenVersion,
		&i.Version,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, company_id, department_id, username, name, email, password_hash, is_superadmin, is_active, must_change_password, failed_login_count, locked_until, last_login_at, password_changed_at, token_version, version, created_by, updated_by, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DepartmentID,
		&i.Username,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsSuperadmin,
		&i.IsActive,
		&i.MustChangePassword,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.PasswordChangedAt,
		&i.TokenVersion,
		&i.Version,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, company_id, department_id, username, name, email, password_hash, is_superadmin, is_active, must_change_password, failed_login_count, locked_until, last_login_at, password_changed_at, token_version, version, created_by, updated_by, created_at, updated_at FROM users WHERE lower(username) = lower($1)
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DepartmentID,
		&i.Username,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsSuperadmin,
		&i.IsActive,
		&i.MustChangePassword,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.PasswordChangedAt,
		&i.TokenVersion,
		&i.Version,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRolesForUsers = `-- name: ListRolesForUsers :many
SELECT ur.user_id, r.id, r.name
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
WHERE ur.user_id = ANY($1::bigint[])
ORDER BY r.id
`

type ListRolesForUsersRow struct {
	UserID int64
	ID     int64
	Name   string
}

func (q *Queries) ListRolesForUsers(ctx context.Context, userIds []int64) ([]ListRolesForUsersRow, error) {
	rows, err := q.db.Query(ctx, listRolesForUsers, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolesForUsersRow{}
	for rows.Next() {
		var i ListRolesForUsersRow
		if err := rows.Scan(&i.UserID, &i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAccess = `-- name: ListUserAccess :many
SELECT r.data_scope, rp.permission
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id AND r.is_active
LEFT JOIN role_permissions rp ON rp.role_id = r.id
WHERE ur.user_id = $1
`

type ListUserAccessRow struct {
	DataScope  string
	Permission *string
}

// 登入者的有效角色(啟用中)與其權限;沒有權限的角色 permission 為 NULL
func (q *Queries) ListUserAccess(ctx context.Context, userID int64) ([]ListUserAccessRow, error) {
	rows, err := q.db.Query(ctx, listUserAccess, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserAccessRow{}
	for rows.Next() {
		var i ListUserAccessRow
		if err := rows.Scan(&i.DataScope, &i.Permission); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserOptions = `-- name: ListUserOptions :many
SELECT u.id, u.username, u.name, u.department_id
FROM users u
WHERE u.company_id = $1 AND u.is_active
ORDER BY u.name
`

type ListUserOptionsRow struct {
	ID           int64
	Username     string
	Name         string
	DepartmentID *int64
}

// 下拉選單用:只回傳啟用中使用者的最少欄位
func (q *Queries) ListUserOptions(ctx context.Context, companyID int64) ([]ListUserOptionsRow, error) {
	rows, err := q.db.Query(ctx, listUserOptions, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserOptionsRow{}
	for rows.Next() {
		var i ListUserOptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Name,
			&i.DepartmentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoleIDs = `-- name: ListUserRoleIDs :many
SELECT role_id FROM user_roles WHERE user_id = $1 ORDER BY role_id
`

func (q *Queries) ListUserRoleIDs(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listUserRoleIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var role_id int64
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT u.id, u.company_id, u.department_id, u.username, u.name, u.email, u.password_hash, u.is_superadmin, u.is_active, u.must_change_password, u.failed_login_count, u.locked_until, u.last_login_at, u.password_changed_at, u.token_version, u.version, u.created_by, u.updated_by, u.created_at, u.updated_at, d.name AS department_name
FROM users u
LEFT JOIN departments d ON d.id = u.department_id
WHERE u.company_id = $1
  AND ($2::text IS NULL
       OR u.username ILIKE '%' || $2 || '%'
       OR u.name ILIKE '%' || $2 || '%')
  AND ($3::bigint IS NULL OR u.department_id = $3)
  AND ($4::boolean IS NULL OR u.is_active = $4)
ORDER BY u.id
LIMIT $6 OFFSET $5
`

type ListUsersParams struct {
	CompanyID    int64
	Keyword      *string
	DepartmentID *int64
	IsActive     *bool
	Off          int32
	Lim          int32
}

type ListUsersRow struct {
	ID                 int64
	CompanyID          int64
	DepartmentID       *int64
	Username           string
	Name               string
	Email              *string
	PasswordHash       string
	IsSuperadmin       bool
	IsActive           bool
	MustChangePassword bool
	FailedLoginCount   int32
	LockedUntil        *time.Time
	LastLoginAt        *time.Time
	PasswordChangedAt  time.Time
	TokenVersion       int32
	Version            int32
	CreatedBy          *int64
	UpdatedBy          *int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DepartmentName     *string
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.CompanyID,
		arg.Keyword,
		arg.DepartmentID,
		arg.IsActive,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.DepartmentID,
			&i.Username,
			&i.Name,
			&i.Email,
			&i.PasswordHash,
			&i.IsSuperadmin,
			&i.IsActive,
			&i.MustChangePassword,
			&i.FailedLoginCount,
			&i.LockedUntil,
			&i.LastLoginAt,
			&i.PasswordChangedAt,
			&i.TokenVersion,
			&i.Version,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DepartmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordLoginFailure = `-- name: RecordLoginFailure :one
UPDATE users
SET failed_login_count = CASE WHEN failed_login_count + 1 >= $1::int THEN 0
                              ELSE failed_login_count + 1 END,
    locked_until       = CASE WHEN failed_login_count + 1 >= $1::int
                              THEN now() + make_interval(secs => $2::int)
                              ELSE locked_until END
WHERE id = $3
RETURNING failed_login_count, locked_until
`

type RecordLoginFailureParams struct {
	MaxAttempts int32
	LockSeconds int32
	ID          int64
}

type RecordLoginFailureRow struct {
	FailedLoginCount int32
	LockedUntil      *time.Time
}

// 失敗次數達上限即鎖定,並將計數歸零
func (q *Queries) RecordLoginFailure(ctx context.Context, arg RecordLoginFailureParams) (RecordLoginFailureRow, error) {
	row := q.db.QueryRow(ctx, recordLoginFailure, arg.MaxAttempts, arg.LockSeconds, arg.ID)
	var i RecordLoginFailureRow
	err := row.Scan(&i.FailedLoginCount, &i.LockedUntil)
	return i, err
}

const recordLoginSuccess = `-- name: RecordLoginSuccess :exec
UPDATE users
SET failed_login_count = 0, locked_until = NULL, last_login_at = now()
WHERE id = $1
`

func (q *Queries) RecordLoginSuccess(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, recordLoginSuccess, id)
	return err
}

const setPassword = `-- name: SetPassword :one
UPDATE users
SET password_hash        = $1,
    password_changed_at  = now(),
    must_change_password = $2,
    token_version        = token_version + 1,
    failed_login_count   = 0,
    locked_until         = NULL,
    version              = version + 1,
    updated_by           = $3
WHERE id = $4
RETURNING id, company_id, department_id, username, name, email, password_hash, is_superadmin, is_active, must_change_password, failed_login_count, locked_until, last_login_at, password_changed_at, token_version, version, created_by, updated_by, created_at, updated_at
`

type SetPasswordParams struct {
	PasswordHash       string
	MustChangePassword bool
	UpdatedBy          *int64
	ID                 int64
}

func (q *Queries) SetPassword(ctx context.Context, arg SetPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, setPassword,
		arg.PasswordHash,
		arg.MustChangePassword,
		arg.UpdatedBy,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DepartmentID,
		&i.Username,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsSuperadmin,
		&i.IsActive,
		&i.MustChangePassword,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.PasswordChangedAt,
		&i.TokenVersion,
		&i.Version,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unlockUser = `-- name: UnlockUser :exec
UPDATE users
SET failed_login_count = 0, locked_until = NULL, version = version + 1, updated_by = $1
WHERE id = $2 AND company_id = $3
`

type UnlockUserParams struct {
	UpdatedBy *int64
	ID        int64
	CompanyID int64
}

func (q *Queries) UnlockUser(ctx context.Context, arg UnlockUserParams) error {
	_, err := q.db.Exec(ctx, unlockUser, arg.UpdatedBy, arg.ID, arg.CompanyID)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET department_id = $1,
    name          = $2,
    email         = $3,
    is_active     = $4,
    -- 停用時讓既有 token 立即失效
    token_version = CASE WHEN is_active AND NOT $4 THEN token_version + 1 ELSE token_version END,
    version       = version + 1,
    updated_by    = $5
WHERE id = $6 AND company_id = $7 AND version = $8
RETURNING id, company_id, department_id, username, name, email, password_hash, is_superadmin, is_active, must_change_password, failed_login_count, locked_until, last_login_at, password_changed_at, token_version, version, created_by, updated_by, created_at, updated_at
`

type UpdateUserParams struct {
	DepartmentID *int64
	Name         string
	Email        *string
	IsActive     bool
	UpdatedBy    *int64
	ID           int64
	CompanyID    int64
	Version      int32
}

// 樂觀鎖:version 不符時不會更新任何列
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.DepartmentID,
		arg.Name,
		arg.Email,
		arg.IsActive,
		arg.UpdatedBy,
		arg.ID,
		arg.CompanyID,
		arg.Version,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.DepartmentID,
		&i.Username,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsSuperadmin,
		&i.IsActive,
		&i.MustChangePassword,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.PasswordChangedAt,
		&i.TokenVersion,
		&i.Version,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
