// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vat.sql

package db

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const vatPurchaseDocs = `-- name: VatPurchaseDocs :many
SELECT r.id, r.doc_no, r.doc_type, r.doc_date, r.invoice_no, r.base_untaxed, r.base_tax, t.kind AS tax_kind,
       s.code AS partner_code, s.name AS partner_name, COALESCE(s.tax_id, '')::text AS partner_tax_id,
       COALESCE(SUM(l.base_amount) FILTER (WHERE i.item_type = 'goods'), 0)::numeric AS goods_amount,
       COALESCE(SUM(l.base_amount) FILTER (WHERE i.item_type <> 'goods'), 0)::numeric AS expense_amount
FROM goods_receipts r
JOIN suppliers s ON s.id = r.supplier_id
JOIN tax_types t ON t.id = r.tax_type_id
LEFT JOIN goods_receipt_lines l ON l.receipt_id = r.id
LEFT JOIN items i ON i.id = l.item_id
WHERE r.company_id = $1 AND r.status = 'posted'
  AND r.doc_date BETWEEN $2::date AND $3::date
GROUP BY r.id, t.kind, s.id
ORDER BY r.doc_date, r.doc_no
`

type VatPurchaseDocsParams struct {
	CompanyID int64
	FromDate  time.Time
	ToDate    time.Time
}

type VatPurchaseDocsRow struct {
	ID            int64
	DocNo         string
	DocType       string
	DocDate       time.Time
	InvoiceNo     string
	BaseUntaxed   decimal.Decimal
	BaseTax       decimal.Decimal
	TaxKind       string
	PartnerCode   string
	PartnerName   string
	PartnerTaxID  string
	GoodsAmount   decimal.Decimal
	ExpenseAmount decimal.Decimal
}

// 期間內已過帳的進貨 / 進貨退出;進貨(商品)與費用(服務)依料品類型拆分
func (q *Queries) VatPurchaseDocs(ctx context.Context, arg VatPurchaseDocsParams) ([]VatPurchaseDocsRow, error) {
	rows, err := q.db.Query(ctx, vatPurchaseDocs, arg.CompanyID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VatPurchaseDocsRow{}
	for rows.Next() {
		var i VatPurchaseDocsRow
		if err := rows.Scan(
			&i.ID,
			&i.DocNo,
			&i.DocType,
			&i.DocDate,
			&i.InvoiceNo,
			&i.BaseUntaxed,
			&i.BaseTax,
			&i.TaxKind,
			&i.PartnerCode,
			&i.PartnerName,
			&i.PartnerTaxID,
			&i.GoodsAmount,
			&i.ExpenseAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const vatSalesDocs = `-- name: VatSalesDocs :many

SELECT d.id, d.doc_no, d.doc_type, d.doc_date, COALESCE(d.invoice_date, d.doc_date)::date AS eff_date,
       d.invoice_no, d.base_untaxed, d.base_tax, t.kind AS tax_kind,
       c.code AS partner_code, c.name AS partner_name, COALESCE(c.tax_id, '')::text AS partner_tax_id
FROM deliveries d
JOIN customers c ON c.id = d.customer_id
JOIN tax_types t ON t.id = d.tax_type_id
WHERE d.company_id = $1 AND d.status = 'posted'
  AND COALESCE(d.invoice_date, d.doc_date) BETWEEN $2::date AND $3::date
ORDER BY eff_date, d.doc_no
`

type VatSalesDocsParams struct {
	CompanyID int64
	FromDate  time.Time
	ToDate    time.Time
}

type VatSalesDocsRow struct {
	ID           int64
	DocNo        string
	DocType      string
	DocDate      time.Time
	EffDate      time.Time
	InvoiceNo    string
	BaseUntaxed  decimal.Decimal
	BaseTax      decimal.Decimal
	TaxKind      string
	PartnerCode  string
	PartnerName  string
	PartnerTaxID string
}

// ======== 營業稅 401 申報資料(D60) ========
// 期間內已過帳的出貨 / 銷貨退回;日期以發票日期為準,未登錄發票者以單據日期列為待處理
func (q *Queries) VatSalesDocs(ctx context.Context, arg VatSalesDocsParams) ([]VatSalesDocsRow, error) {
	rows, err := q.db.Query(ctx, vatSalesDocs, arg.CompanyID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VatSalesDocsRow{}
	for rows.Next() {
		var i VatSalesDocsRow
		if err := rows.Scan(
			&i.ID,
			&i.DocNo,
			&i.DocType,
			&i.DocDate,
			&i.EffDate,
			&i.InvoiceNo,
			&i.BaseUntaxed,
			&i.BaseTax,
			&i.TaxKind,
			&i.PartnerCode,
			&i.PartnerName,
			&i.PartnerTaxID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
